#pragma once

#include "radio.hpp"
#include "core/vector.hpp"
#include "fundamentals.hpp"

namespace ra2 {
namespace game {

using ::gamemd::DynamicVectorClass;
using ::gamemd::ProgressTimer;

enum class CloakState : int;
enum class FireError : int;
enum class Rank : int;
enum class TargetFlags : unsigned int;
enum class ZGradient : int;
enum class Ability : int;
enum class AIDifficulty : unsigned int;
enum class NetworkEvents : unsigned char;
struct WeaponStruct;
class AirstrikeClass;
class AnimClass;
class BulletClass;
class BuildingClass;
class CaptureManagerClass;
class CellClass;
class FootClass;
class HouseClass;
class InfantryTypeClass;
class LaserDrawClass;
class ObjectTypeClass;
class ParticleSystemClass;
class PlanningTokenClass;
class RadBeam;
class SlaveManagerClass;
class SpawnManagerClass;
class TeamClass;
class TemporalClass;
class WaveClass;

struct FlashData {
    int32_t DurationRemaining;
    bool    FlashingNow;
    uint8_t padding[3];
};

class PassengersClass {
public:
    int32_t     NumPassengers;
    FootClass*  FirstPassenger;
};

struct VeterancyStruct {
    float Veterancy;
};

struct TurretControl {
    uint32_t data[4];
};

struct RecoilData {
    TurretControl   Turret;
    float           TravelPerFrame;
    float           TravelSoFar;
    uint32_t        State;
    int32_t         TravelFramesLeft;
};

struct TransitionTimer {
    uint32_t data[3];
};

template <typename T>
struct IndexBitfield {
    T* Items;
};

struct OwnedTiberiumStruct {
    float Amount1;
    float Amount2;
    float Amount3;
    float Amount4;
};

class TechnoClass : public RadioClass {
public:
    static constexpr AbstractType kObjectDeriveId = static_cast<AbstractType>(0x1);

    virtual HRESULT __stdcall Load(IStream* stream) override;
    virtual HRESULT __stdcall Save(IStream* stream, int clear_dirty) override;

    virtual ~TechnoClass() = default;

    virtual bool isUnitfactory() const;
    virtual bool isCloakable() const;
    virtual bool canScatter() const;
    virtual bool belongsToATeam() const;
    virtual bool shouldSelfHealOneStep() const;  // 0x70be80
    virtual bool isVoxel() const;
    virtual bool canSelfRepair();  // 0x70fb50
    virtual bool shouldBeCloaked() const;  // 0x6fbdc0
    virtual bool shouldNotBeCloaked() const;  // 0x6fbc90
    virtual DirStruct* getFacing(DirStruct* buffer) const;
    virtual bool isArmed() const;
    virtual void onSpawnComplete() const;
    virtual double getStoragePercentage() const;
    virtual int getPipFillLevel() const;
    virtual int getRefund() const;
    virtual int getThreatValue() const;  // 0x4ded70
    virtual bool canBeAttacked(uint32_t a);
    virtual uint32_t getSpecialValue(uint32_t a, uint32_t b);
    virtual bool canCrush(uint32_t a);
    virtual int getCrewCount() const;  // 0x6f3950
    virtual int getAntiAirValue() const;
    virtual int getAntiArmorValue() const;
    virtual int getAntiInfantryValue() const;
    virtual void gotHijacked();
    virtual int selectNavalTargeting(AbstractClass* target) const;
    virtual int getZAdjustment() const;
    virtual ZGradient GetZGradient() const;
    virtual CellStruct* GetSomeCellStruct() const;
    virtual void SetSomeCellStruct(CellStruct* buffer);
    virtual CellStruct* getOccupiedCell(CellStruct* buffer, uint32_t a, uint32_t b) const;
    virtual CoordStruct* getTurretCoords(CoordStruct* buffer, uint32_t a) const;
    virtual uint32_t getWeaponRangeValue(uint32_t a, uint32_t b) const;
    virtual DirStruct* GetRealFacing(DirStruct* buffer) const;
    virtual InfantryTypeClass* GetCrew() const;  // 0x707d20
    virtual bool isInAirAlt() const;
    virtual bool CanDeploySlashUnload() const;
    virtual int GetROF(int weapon) const;
    virtual int GetGuardRange(int unknown) const;
    virtual bool canEnterTransport() const;
    virtual bool IsRadarVisible(int* out_detection) const;
    virtual bool IsSensorVisibleToPlayer() const;
    virtual bool IsSensorVisibleToHouse(HouseClass* house) const;
    virtual bool IsEngineer() const;
    virtual void ProceedToNextPlanningWaypoint();
    virtual uint32_t ScanForTiberium(uint32_t a, uint32_t b, uint32_t c) const;
    virtual bool EnterGrinder();
    virtual bool EnterBioReactor();
    virtual bool EnterTankBunker();
    virtual bool EnterBattleBunker();
    virtual bool GarrisonStructure();
    virtual bool isPowerOnline() const;
    virtual void QueueVoice(int idx_voc);
    virtual int VoiceEnter();
    virtual int VoiceHarvest();
    virtual int VoiceSelect();
    virtual int VoiceCapture();
    virtual int VoiceMove();
    virtual int VoiceDeploy();
    virtual int VoiceAttack(ObjectClass* target);  // 0x7090a0
    virtual bool ClickedEvent(NetworkEvents event);
    virtual bool ClickedMission(Mission mission, ObjectClass* target, CellClass* target_cell, CellClass* nearest_target_cell);
    virtual bool isUnderEmp() const;
    virtual bool isParalyzed() const;
    virtual bool canCheer() const;
    virtual void Cheer(bool force);
    virtual int GetDefaultSpeed() const;
    virtual void DecreaseAmmo();
    virtual void AddPassenger(FootClass* passenger);
    virtual bool CanDisguiseAs(AbstractClass* target) const;
    virtual bool TargetAndEstimateDamage(uint32_t a, uint32_t b);
    virtual uint32_t getDamageReduction();
    virtual bool TriggersCellInset(AbstractClass* target);
    virtual bool IsCloseEnough(AbstractClass* target, int weapon_idx) const;
    virtual bool IsCloseEnoughToAttack(AbstractClass* target) const;
    virtual bool IsCloseEnoughToAttackCoords(const CoordStruct& coords) const;
    virtual uint32_t getSightRange(uint32_t a) const;  // 0x717800
    virtual void Destroyed(ObjectClass* killer) = 0;
    virtual FireError GetFireErrorWithoutRange(AbstractClass* target, int weapon_index) const;
    virtual FireError GetFireError(AbstractClass* target, int weapon_index, bool ignore_range) const;
    virtual CellClass* SelectAutoTarget(TargetFlags flags, int current_threat, bool only_target_house_enemy);
    virtual void SetTarget(AbstractClass* target);
    virtual BulletClass* Fire(AbstractClass* target, int weapon_index);  // 0x70ece0
    virtual void Guard();
    virtual bool SetOwningHouse(HouseClass* house, bool announce = true);
    virtual void onHouseChange(uint32_t a, uint32_t b, uint32_t c);
    virtual bool Crash(ObjectClass* killer);
    virtual bool isAreaFire() const;
    virtual int isNotSprayAttack() const;
    virtual int canAct();
    virtual int isNotSprayAttack2() const;
    virtual WeaponStruct* GetDeployWeapon() const;
    virtual WeaponStruct* GetTurretWeapon() const;
    virtual WeaponStruct* GetWeapon(int weapon_index) const;
    virtual bool hasTurret() const;
    virtual bool canOccupyFire() const;
    virtual int getOccupyRangeBonus() const;
    virtual int getOccupantCount() const;
    virtual void OnFinishRepair();

    virtual void UpdateCloak(bool unknown = true);
    virtual void CreateGap();
    virtual void DestroyGap();
    virtual void onBridgeRepair();
    virtual void Sensed();
    virtual void Reload();
    virtual void onReloadComplete();
    virtual CoordStruct* GetTargetCoords(CoordStruct* pCrd) const;  // 0x70bcb0
    virtual bool IsNotWarpingIn() const;
    virtual bool canChronoShift(uint32_t dwUnk) const;
    virtual void DrawActionLines(bool force, uint32_t dwUnk2);
    virtual uint32_t GetDisguiseFlags(uint32_t existingFlags) const;
    virtual bool isClearlyVisibleTo(HouseClass* house) const;
    virtual void drawSelectionBox(uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5,
        uint32_t a6, uint32_t a7, uint32_t a8, uint32_t a9, uint32_t a10) {}
    virtual void onSelect(uint32_t a, uint32_t b);
    virtual void DrawHealthBar(Point2D* pLocation, RectangleStruct* pBounds, bool bUnk3) const;
    virtual void DrawPipScalePips(Point2D* pLocation, Point2D* pOriginalLocation, RectangleStruct* pBounds) const;
    virtual void DrawVeterancyPips(Point2D* pLocation, RectangleStruct* pBounds) const;
    virtual void DrawExtraInfo(Point2D const& location, Point2D const& originalLocation, RectangleStruct const& bounds) const;
    virtual void Uncloak(bool play_sound);
    virtual void Cloak(bool play_sound);
    virtual uint32_t getSight(uint32_t dwUnk) const;
    virtual void UpdateRefinerySmokeSystems();
    virtual uint32_t DisguiseAs(AbstractClass* pTarget);
    virtual void ClearDisguise();
    virtual bool IsItTimeForIdleActionYet() const;
    virtual bool UpdateIdleAction();
    virtual void onDamage(uint32_t dwUnk);
    virtual void SetDestination(AbstractClass* dest, bool unknown);
    virtual bool canRecruit(uint32_t dwUnk, uint32_t dwUnk2);
    virtual void UpdateSight(uint32_t a, uint32_t b, uint32_t c, uint32_t d, uint32_t e);
    virtual void onPlacement(uint32_t a, uint32_t b, uint32_t c, uint32_t d);
    virtual void onBuildingPlacement(uint32_t a, uint32_t b) = 0;
    virtual void RadarTrackingStart();
    virtual void RadarTrackingStop();
    virtual void RadarTrackingFlash();
    virtual void RadarTrackingUpdate(bool unknown);
    virtual void onRadarEvent(uint32_t a);
    virtual void onSpawn();
    virtual bool canSpawn() const;
    virtual bool isSpawning() const;
    virtual int getSpawnCount() const;
    virtual CoordStruct* getSpawnCoords(CoordStruct* out);
    virtual uint32_t processSpawn();
    virtual bool canAttackOnTheMove() const;
    virtual bool canTarget() const;
    virtual bool selectTarget();
    virtual void onTargetChange();
    virtual bool canFire();

    // === Phase 3 generated declarations (IDA functions.json) ===
    virtual int ApplyIronCurtain();
    virtual int ReturnToBase();
    virtual int ReturnToBaseAndReload();
    virtual int ScatterFromThreat();
    virtual int ExecuteMissionCommand();
    virtual int FindNearbyBuildCell();
    virtual int FindClosestPlacementCell();
    virtual int GetTurretFacing() const;
    virtual void ComputeTeamAttackPriority();
    virtual int GetAutoFireDirection() const;
    virtual int sub_41B7D0();
    virtual bool HasOnlyOneGarrisonSlot() const;
    virtual int sub_41B840();
    virtual int sub_41B860();
    virtual int sub_41B9E0();
    virtual bool CreateWarheadDamageEffect();
    virtual void sub_41BEF0();
    virtual void vt_entry_428();
    virtual int vt_entry_434();
    virtual int GetBodyFacing() const;
    virtual int sub_41C640();
    virtual int sub_41C650();
    virtual int sub_41C660();
    virtual int sub_41C670();
    virtual int sub_41C680();
    virtual int sub_41C690();
    virtual int ApplyDamageEffects();
    virtual int sub_5439080();
    virtual int RemoveFromDynamicVector();
    virtual void ComputeTargetAngle();
    virtual int StartOrResumeProduction();
    virtual int GetTurretScreenPos() const;
    virtual void ProcessMissionDeploy();
    virtual int EvacuateFootprintCells();
    virtual int MissionStubReturnZero4();
    virtual bool StubReturnFalse2();
    virtual int sub_546B270();
    virtual int sub_54722D0();
    virtual int IndexOf();
    virtual int CalcFacingFromMatrix() const;
    virtual void CreateTrailParticle();
    virtual int sub_4C2BD0();
    virtual int UpdateThunk();
    virtual int GetData() const;
    virtual int sub_54A50F0();
    virtual int CreatePlanningNode();
    virtual int GetBuildCost() const;
    virtual int CheckState1() const;
    virtual int CheckState2() const;
    virtual int StubReturn450();
    virtual void vt_entry_448();
    virtual int sub_54D28C0();
    virtual int GetTypeFlag() const;
    virtual int sub_5505180();
    virtual int FindClosestBuilding();
    virtual int FindBestMatch();
    virtual int FindClosestInfantry();
    virtual int FindClosestUnit();
    virtual int FindBestMovementDirection();
    virtual int vt_entry_4A8();
    virtual int vt_entry_4AC();
    virtual int vt_entry_4B0();
    virtual int vt_entry_4B4();
    virtual int vt_entry_4B8();
    virtual int vt_entry_4C4();
    virtual int vt_entry_4C8();
    virtual int vt_entry_4D0();
    virtual int GetAnimationValue() const;
    virtual int FindDeployDestination();
    virtual int sub_550D9C0();
    virtual int sub_550D9D0();
    virtual int MapHouseRelationIndex();
    virtual int GetDamageMultiplier() const;
    virtual int ProcessTarget();
    virtual int sub_55224F0();
    virtual int GetDeployCoords();
    virtual int CanBePermaMC() const;
    virtual int GarrisonBuilding();
    virtual int IsMission27to30() const;
    virtual int HandleSpecialAction();
    virtual int IsEnteringOrCapturingStructure() const;
    virtual void CreateDestructionEffect();
    virtual int FindMatchingUnit();
    virtual int ClearArrays();
    virtual int ComputeScanRange() const;
    virtual int sub_659470();
    virtual int sub_659490();
    virtual int sub_6594A0();
    virtual int sub_6594C0();
    virtual int sub_6594E0();
    virtual int sub_6594F0();
    virtual int sub_659540();
    virtual int sub_659550();
    virtual int ClearScriptPlanningData();
    virtual int GetTileAnimationData() const;
    virtual int MutateAll();
    virtual int RefreshDeployOccupierState();
    virtual int CountPassengers() const;
    virtual int GetValue() const;
    virtual int ComputeTransform();
    virtual int CanMoveToCell() const;
    virtual int CanInitiateSell() const;
    virtual int IsNotAircraftOrBuilding() const;
    virtual int SelectWeapon();
    virtual int CanTargetHouse() const;
    virtual int CanSelfRepair();
    virtual int Mission_RepairDispatch();
    virtual int PushNearbyUnits();
    virtual int SetFocus();  // 0x7c8674
    virtual int SetHouseFlag();
    virtual int ProcessAIDecision();
    virtual int CheckPlayerOwned() const;
    virtual int UpdateProdWithSound();
    virtual int HasActiveParam() const;
    virtual int HasOnlyOneGarrisonSlot2() const;
    virtual int FindLowestDamage();
    virtual int ProcessCapture();
    virtual int GetRangeModifier() const;
    virtual int ShouldScanArea() const;
    virtual int IsCloseEnoughToBuilding() const;
    virtual int IsCellPassableFor() const;
    virtual int IsPlayerCellPassable() const;
    virtual int SetMoveDestination();
    virtual int GetPrimaryTargetOrFallback() const;
    virtual int PickAlternateTarget();
    virtual int SelectRandomTarget();
    virtual int GetSecondaryTargetOrFallback() const;
    virtual int SetPositionAnimated();
    virtual int GetTargetCellCenter();
    virtual int ComputeSpeedFactor();
    virtual int ComputeSpeedFactorEx();
    virtual int CleanupDirection();
    virtual int GetDeployProgressValue() const;
    virtual int ComputeAverageValue() const;
    virtual int GetGlobalValue() const;
    virtual int SetIdleState();
    virtual int ComputeAimVector();
    virtual int RevealAreaConditional();
    virtual int GetCellCoordsV2() const;
    virtual int Vt46Thunk();
    virtual int RevealAreaSmall();
    virtual int ScanForEnemies();
    virtual int GetTargetCoords();
    virtual int CalcOffsetFacing() const;
    virtual int ShouldSelfHealOneStep() const;
    virtual int ComputeThreatLevel();
    virtual int CanBeTargeted() const;
    virtual int GetCommandTooltip() const;
    virtual int ShouldBeCloaked() const;
    virtual int ShouldNotBeCloaked() const;
    virtual int SetTargetIfAllowed();
    virtual int CanReceivePassengers() const;
    virtual int GetTarget() const;
    virtual int GetID() const;
    virtual int GetSightRange() const;
    virtual int CheckAndFireAtTarget();
    virtual int GattlingRateUp_GattlingRateDownReset();
    virtual int GattlingValueRateDown_GattlingRateDownDelay();
    virtual int SetMember81();
    virtual int Deactivate();
    virtual int Activate();
    virtual int ActivateEffect();
    virtual int IronCurtain();
    virtual int InvulnerabilityIntensity_SetContext();
    virtual int ResetTimer();
    virtual int CalcAnimDelay() const;
    virtual int StepAnimFrame();
    virtual int BeginFiringSequence();
    virtual int CompleteFactoryProduction();
    virtual int IsTimerExpired() const;
    virtual int GetAudioEntry() const;
    virtual int GetTertiaryTargetOrFallback() const;
    virtual int VoiceAttack();
    virtual int ResponseMove_Pickup();
    virtual int Vt170();
    virtual int CanAttack() const;
    virtual int IsDeadOrInactive() const;
    virtual int CalculateROF();
    virtual int GetAmmoCount() const;
    virtual int GetAmmoCount_0() const;
    virtual int SelectAttackWeapon();
    virtual int GetAverageDamageScore() const;
    virtual int ProcessSpecialUnitDeployCrush();
    virtual int FireWeaponBurst();
    virtual int GetWeaponRange(int weapon_index) const;
    virtual int FireWeapon();
    virtual int CreateFireEffect();
    virtual int CreateFireBeamEffect();
    virtual int CreateFiringRadarBlip();
    virtual int CreateRadarBlip();
    virtual int GetFiringAngle() const;
    virtual int AssignTarget_SyncLog();
    virtual int ProcessDeploymentState();
    virtual int ComputeAudioFalloffDamage();
    virtual int ComputeCombatDamage();
    virtual int CheckFireCooldown() const;
    virtual int CanDamageTarget() const;
    virtual int COMStub_Return0_298();
    virtual int HasPassengers() const;
    virtual int COMStub_Return0_307();
    virtual int sub_70F040();
    virtual int ProcessCellClearance();
    virtual int GetTypeVt40() const;
    virtual int GetMaxSpeed() const;
    virtual int DrainAmmo();
    virtual int EjectPassengers();
    virtual int RadarUpdateOn();
    virtual int RadarUpdateOff();
    virtual int RevealOwnCell();
    virtual int ComputeDamage();
    virtual int GetCostMultiplier() const;
    virtual int IsInRange() const;
    virtual int GetCrew();
    virtual int GetCrew_0();
    virtual int GetCrewCount();
    virtual int CheckCellPassable() const;
    virtual int CheckCellPassable2() const;
    virtual int CheckCellPassable3() const;
    virtual int ValidateTarget() const;
    virtual int GetBridgeDamageMult() const;
    virtual int CheckAndFireAtTarget2();
    virtual int EvaluateTarget();
    virtual int SelectAutoTarget_Start_AU();
    virtual int CheckTargetLOS() const;
    virtual int CheckTargetCell() const;
    virtual int CheckPlacementTileMatch() const;
    virtual int ComputeScanDistance() const;
    virtual int ComputeTotalPowerDrain();
    virtual int EvaluateBuildingTarget();
    virtual int GetBuildAnim() const;
    virtual int IsNotBusy() const;
    virtual int EvaluateMission();
    virtual int GetThreatValue() const;
    virtual int GetThreatValue_0() const;
    virtual int ProcessBorderTower();
    virtual int HandleCursor();
    virtual int HandleCursorClick();
    virtual int ScanAdjacentCells2();
    virtual int ScanNeighborCells();
    virtual int IsValidBuildingPlacement();
    virtual int StartEffectAudio();
    virtual int TransitionEffectState();
    virtual int Vt279Thunk0();
    virtual int UpdatePowerDrain();
    virtual int UpdatePowered();
    virtual int UpdateState();
    virtual int UpdateUnitAnimation();
    virtual int GetInfantryCursorAction() const;
    virtual int GetThreatValueEx() const;
    virtual int ComputeSlopeDifference();
    virtual int ComputeSlopePenalty();
    virtual int IsOwnedByHuman() const;
    virtual int IsCapturableByPlayer() const;
    virtual int IsC4AnimationActive() const;
    virtual int CreateDeathAnim();
    virtual int DispatchPlayerInput();
    virtual int Deploy();
    virtual int DeployIntoBuilding();
    virtual int SpawnInfantryFromBuilding();
    virtual int CleanupDeploy();
    virtual int ClearAllTargets();
    virtual int SelectAITarget();
    virtual int ReturnCapturedFlag();
    virtual int AreBuildingFlagsClear() const;
    virtual int MarkCellImpassable();
    virtual int ClearCellImpassable();
    virtual int CaptureTurret();
    virtual int TransferSlavedUnit();
    virtual int TransferTurret();
    virtual int ApplyObjectEffect();
    virtual int IsGuardingTarget() const;
    virtual int ProcessUnitSelfDestruct();
    virtual int NotifyTeamOnDestruction();
    virtual int RespondToDestruction();
    virtual int GetWaypointCoords() const;
    virtual int Create();
    virtual int CopyStateFrom();
    virtual int ScalarDtor();
    virtual int EnteredOpenTopped();
    virtual int MarkPassengersAsExited();
    virtual int ExitedOpenTopped();
    virtual int GetMember388() const;
    virtual int GetBuildCost2() const;
    virtual int FindBestMatch2();
    virtual int IsWaypointHidden() const;
    virtual int LinkToBridge();
    virtual int ResetDamageAccumulator();
    virtual int UpdateBodyTilt();
    virtual int CheckCliffTransition() const;
    virtual int OnEnterCell();
    virtual int sub_570DC50();
    virtual int OwnerHasPower() const;
    virtual int sub_570DCE0();
    virtual int sub_570DCF0();
    virtual int GetPoweredWeaponIndex() const;
    virtual int GetVt252Byte() const;
    virtual int vt_entry_3E8();
    virtual int SetSpread();
    virtual int DecCounter();
    virtual int PlaceAtCell();
    virtual int SelectVocOrSfx();
    virtual int Update2();
    virtual int GetAnimationFlags() const;
    virtual int GetTargetSpeedMultiplier() const;
    virtual int ProcessEnterTransport();
    virtual int IsCloseEnoughToBuilding2() const;
    virtual int IsDeployed() const;
    virtual int CheckAdjacencyFlags() const;
    virtual int IsProductionChainActive() const;
    virtual int HasDeployFlags() const;
    virtual int RemoveBuildingFromScripts();
    virtual int FinishDeploy();
    virtual int ValidateMoveType();
    virtual int ComputeSlopePenalty2();
    virtual int sub_740B10();
    virtual int CheckRepairNeeded() const;
    virtual int EnterRepairBuilding();
    virtual int CheckUnitFireConstraints() const;
    virtual int sub_741490();
    virtual int sub_7441B0();
    virtual int sub_744180();
    virtual int sub_744210();
    virtual int sub_744270();
    virtual int sub_744720();
    virtual int sub_7440B0();
    virtual int sub_744100();
    virtual int sub_743190();
    virtual int sub_746400();
    virtual int sub_746420();
    virtual int sub_7464E0();
    virtual int sub_7465B0();
    virtual int sub_7465F0();
    virtual int sub_7463A0();
    virtual int sub_746670();
    virtual int sub_746720();
    virtual int sub_746750();
    virtual int sub_746B20();
    virtual int sub_746C90();
    virtual int sub_746CD0();
    virtual int sub_746D00();
    virtual int sub_746D60();
    virtual int sub_746DB0();
    virtual int sub_746E30();
    virtual int sub_746EA0();
    virtual int sub_746100();
    virtual int sub_746F80();
    virtual int sub_70F850();
    virtual int sub_70FB50();
    virtual int sub_70FC90();
    virtual int sub_70FD70();
    virtual int sub_70FEE0();
    virtual int sub_710000();
    virtual int sub_710470();
    virtual int sub_7104A0();
    virtual int sub_7104C0();
    virtual int sub_7106E0();
    virtual int sub_710F70();
    virtual int sub_711E00();
    virtual int sub_711EB0();
    virtual int sub_73EFC0();
    virtual int sub_7393C0();
    virtual int sub_737BA0();
    virtual int sub_738910();
    virtual int sub_732050();
    virtual int sub_732580();
    virtual int sub_731CF0();
    virtual int sub_729AA0();
    virtual int sub_729480();
    virtual int sub_71F010();
    virtual int sub_71A130();
    virtual int CalculateDamage();
    virtual int UpdateBodyTilt2();
    virtual int GattlingRateUp_GattlingRateDownReset2();
    virtual int ApplySplashDamageToNeighbors();
    virtual int ReceiveDamage_Shield();
    virtual int sub_70B1D0();
    virtual int sub_70B280();
    virtual int sub_70B570();
    virtual int sub_70BCB0();
    virtual int sub_70BE80();
    virtual int sub_70D1D0();
    virtual int sub_70D990();
    virtual int sub_70DE70();
    virtual int sub_70DE00();
    virtual int sub_70DD20();
    virtual int sub_70DD50();
    virtual int sub_70DDD0();
    virtual int sub_70DE40();
    virtual int sub_70E120();
    virtual int sub_70E140();
    virtual int sub_70E1A0();
    virtual int sub_70E280();
    virtual int sub_70E2B0();
    virtual int sub_70E300();
    virtual int sub_70E380();
    virtual int sub_70E4B0();
    virtual int sub_70EC0A();
    virtual int sub_70ED10();
    virtual int sub_70ED80();
    virtual int sub_70EE30();
    virtual int sub_70EFD0();
    virtual int sub_70EF00();
    virtual int sub_70F010();
    virtual int sub_70F000();
    virtual int sub_70ECE0();
    virtual int sub_70CCC0();
    virtual int sub_70CC90();
    virtual int sub_70CD10();
    virtual int sub_70D190();
    virtual int sub_70D460();
    virtual int sub_70D590();
    virtual int sub_70D670();
    virtual int sub_70D690();
    virtual int sub_70D8F0();
    virtual int sub_70DD90();
    virtual int sub_70BE50();
    virtual int sub_70C620();
    virtual int sub_70C610();

    virtual int SelectWeapon(AbstractClass* target) const;
    void SmokeupdateLogic();
    bool CreateUnit();

    int GetIonCannonValue(AIDifficulty difficulty) const;

    DirStruct getFacing() const;
    DirStruct GetRealFacing() const;

    // ---- member variables ----

    FlashData               flashing;
    ProgressTimer           animation;
    PassengersClass         passengers;
    TechnoClass*            transporter;
    int32_t                 turretChargeTimer;
    int32_t                 currentTurretNumber;
    int32_t                 secondaryTurretIndex;
    AnimClass*              behindAnim;
    AnimClass*              deployAnim;
    bool                    inAirFlag;
    uint8_t                 alignmentPadding139[3];
    int32_t                 currentWeaponSlot;
    int32_t                 currentRank;          // Rank enum
    int32_t                 gattlingStage;
    int32_t                 gattlingValue;
    uint32_t                ammoReloadTimer;
    HouseClass*             initialOwner;
    VeterancyStruct         veterancy;
    uint32_t                alignmentPadding154;
    double                  armorMultiplier;
    double                  firepowerMultiplier;
    TimerStruct             idleActionTimer;
    TimerStruct             radarFlashTimer;
    TimerStruct             targetingTimer;
    TimerStruct             ironCurtainTimer;
    TimerStruct             ironTintTimer;
    int32_t                 ironTintStage;
    TimerStruct             airstrikeTimer;
    TimerStruct             airstrikeTintTimer;
    uint32_t                airstrikeTintStage;
    int32_t                 forceShielded;
    bool                    isDeactivated;
    uint8_t                 alignmentPadding1BD[3];
    TechnoClass*            drainTarget;
    TechnoClass*            drainingMe;
    AnimClass*              drainAnim;
    bool                    isDisguisedFlag;
    uint8_t                 alignmentPadding1CE[3];
    uint32_t                disguiseCreationFrame;
    TimerStruct             infantryBlinkTimer;
    TimerStruct             disguiseBlinkTimer;
    bool                    isTargetedByChrono;
    uint8_t                 alignmentPadding1F9[3];
    TimerStruct             reloadTimer;
    uint32_t                currentBurstCount;
    uint32_t                currentBarrelIndex;
    IndexBitfield<HouseClass*> displayProductionTo;
    int32_t                 group;
    AbstractClass*          focus;
    HouseClass*             owner;
    uint32_t                cloakState;              // CloakState enum
    ProgressTimer           cloakProgress;
    TimerStruct             cloakDelayTimer;
    float                   warpFactor;
    bool                    isChronosphereImmune;
    uint8_t                 alignmentPadding251[3];
    CoordStruct             lastSightCoords;
    int32_t                 lastSightRange;
    int32_t                 lastSightHeight;
    bool                    gapSuperCharged;
    bool                    isGeneratingGap;
    uint8_t                 alignmentPadding27E[2];
    int32_t                 gapRadius;
    bool                    isBeingWarpedOut;
    bool                    isWarpingOut;
    bool                    isWarpEffectActive;
    uint8_t                 unusedField273;
    TemporalClass*          temporalUsing;
    TemporalClass*          temporalTargetingMe;
    bool                    isImmobilized;
    uint8_t                 alignmentPadding27D[3];
    uint32_t                owningHouseIndex0;
    int32_t                 chronoLockRemaining;
    CoordStruct             chronoDestCoords;
    AirstrikeClass*         airstrike;
    bool                    isBerserk;
    uint8_t                 alignmentPadding29D[3];
    uint32_t                isBerserk_duration_left;
    uint32_t                sprayOffsetIndex;
    bool                    isUncrushable;
    uint8_t                 alignmentPadding2A9[3];
    FootClass*              rockerLinkedUnit;
    FootClass*              locomotorTarget;
    FootClass*              locomotorSource;
    AbstractClass*          target;
    AbstractClass*          lastTarget;
    CaptureManagerClass*    captureManager;
    TechnoClass*            mindControlledBy;
    bool                    mindControlledBy_a_unit;
    uint8_t                 alignmentPadding2C2[3];
    AnimClass*              mindControlRingAnim;
    HouseClass*             mindControlledBy_house;
    SpawnManagerClass*      spawnManager;
    TechnoClass*            spawnOwner;
    SlaveManagerClass*      slaveManager;
    TechnoClass*            slaveOwner;
    HouseClass*             originalOwnerHouse;
    TechnoClass*            bunkerLinkedUnit;
    float                   pitchAngle;
    TimerStruct             diskLaserTimer;
    uint32_t                diskLaserChargeState;
    int32_t                 ammo;
    int32_t                 unitValue;
    ParticleSystemClass*    fireParticles;
    ParticleSystemClass*    sparkParticles;
    ParticleSystemClass*    ambientParticles;
    ParticleSystemClass*    damageParticles;
    ParticleSystemClass*    railgunParticles;
    ParticleSystemClass*    auxParticles1;
    ParticleSystemClass*    auxParticles2;
    ParticleSystemClass*    firingParticles;
    WaveClass*              waveEffect;
    float                   tiltSidewaysAngle;
    float                   tiltForwardsAngle;
    float                   tiltSidewaysRate;
    float                   tiltForwardsRate;
    int32_t                 hijackerInfantryType;
    OwnedTiberiumStruct     storedTiberium;
    uint32_t                tiberiumCollectionState;
    TransitionTimer         unloadTimer;
    FacingStruct            barrelFacing;
    FacingStruct            facing;
    FacingStruct            turretFacing;
    int32_t                 currentBurstIndex;
    TimerStruct             target_laser_timer;
    int16_t                 targetLaserOpacity;
    uint16_t                targetLaserFlags;
    bool                    isCountedAsOwned;
    bool                    isSinking;
    bool                    wasAlreadySinking;
    bool                    isReceivingDamageEffect;
    bool                    isPlayingDamageSound;
    bool                    hasBeenAttacked;
    bool                    isCloakableFlag;
    bool                    isPrimaryFactory;
    bool                    isSpawned;
    bool                    isInPlayfield;
    RecoilData              turretRecoil;
    RecoilData              barrelRecoil;
    bool                    isTurretLocked;
    bool                    isBarrelLocked;
    bool                    isHumanControlled;
    bool                    isDiscoveredByPlayer;
    bool                    isDiscoveredByComputer;
    bool                    isSelectedByPlayer;
    bool                    isUnderCursor;
    bool                    isCommandLineTarget;
    char                    sightRangeBonus;
    bool                    isRecruitableByAlly;
    bool                    isRecruitableByEnemy;
    bool                    isRadarTracked;
    bool                    isOnCarryall;
    bool                    isCrashing;
    bool                    wasAlreadyCrashing;
    bool                    isBeingManipulated;
    TechnoClass*            manipulatedByUnit;
    HouseClass*             chronoWarpedByHouse;
    bool                    isChronoImmuneFlag;
    bool                    isEMPImmune;
    bool                    isRadiationImmune;
    uint8_t                 alignmentPadding433;
    TeamClass*              previousTeam;
    bool                    isCountedAsOwned_special;
    bool                    isAbsorbed;
    bool                    isGrindingInProgress;
    uint8_t                 alignmentPadding43B;
    uint32_t                grindingAnimHandle;
    DynamicVectorClass<int32_t> currentTargetThreatValues;
    DynamicVectorClass<AbstractClass*> currentTargets;
    DynamicVectorClass<AbstractClass*> attackedTargets;
    AudioController         audioController3;
    uint32_t                audioLoopIndex3;
    uint32_t                audioVolume3;
    AudioController         audioController4;
    bool                    isAudio4Active;
    uint8_t                 alignmentPadding4B9[3];
    uint32_t                audioHandle4;
    AudioController         audioController5;
    bool                    isAudio5Active;
    uint8_t                 alignmentPadding4D5[3];
    uint32_t                audioHandle5;
    AudioController         audioController6;
    uint32_t                queuedVoiceIndex;
    uint32_t                voiceFlags;
    bool                    isVoiceOverride;
    uint8_t                 alignmentPadding4F9[3];
    uint32_t                voiceHandle;
    uint32_t                voiceVolumeModifier;
    uint32_t                empLockRemaining;
    uint32_t                threatPosed;
    uint32_t                shouldLoseTarget;
    RadBeam*                firingRadBeam;
    PlanningTokenClass*     planningToken;
    ObjectTypeClass*        disguiseAsType;
    HouseClass*             isDisguisedFlag_as_house;

protected:
    TechnoClass() noexcept;
};

} // namespace game
} // namespace ra2
