// Auto-generated by tools/task17_generate.py
// Module: system | Functions: 300
// Regenerate: python tools/task17_generate.py

#include <cstdint>
#include <cstddef>

// IDA-named globals referenced (extern stubs)
extern double dbl_ABF130;
extern double dbl_ABF150;
extern double dbl_ABF158;
extern double dbl_ABF1B8;
extern double dbl_ABF210;
extern double dbl_ABF248;
extern double dbl_ABF270;
extern double dbl_ABF278;
extern double dbl_ABF2B0;
extern double dbl_ABF2D0;
extern double dbl_ABF2E0;
extern double dbl_ABF300;
extern double dbl_ABF308;
extern double dbl_ABF330;
extern double dbl_ABF350;
extern double dbl_ABF360;
extern double dbl_ABF380;
extern double dbl_ABF388;
extern double dbl_ABF3C8;
extern double dbl_ABF3E8;
extern double dbl_ABF400;
extern double dbl_ABF420;
extern double dbl_ABF428;
extern double dbl_ABF450;
extern double dbl_ABF490;
extern double dbl_ABF4A0;
extern double dbl_ABF4C0;
extern double dbl_ABF4C8;
extern double dbl_ABF4F0;
extern double dbl_ABF510;
extern double dbl_ABF520;
extern double dbl_ABF540;
extern double dbl_ABF548;
extern double dbl_ABF570;
extern double dbl_ABF590;
extern double dbl_ABF8D8;
extern double dbl_ABF8F8;
extern double dbl_ABF900;
extern double dbl_ABF928;
extern double dbl_ABF948;
extern double dbl_ABF978;
extern double dbl_ABF998;
extern double dbl_ABF9A0;
extern double dbl_ABF9C8;
extern double dbl_ABF9E8;
extern double dbl_ABFA00;
extern double dbl_ABFA20;
extern double dbl_ABFA28;
extern double dbl_ABFA50;
extern double dbl_ABFA70;
extern double dbl_ABFA80;
extern double dbl_ABFAA0;
extern double dbl_ABFAA8;
extern double dbl_ABFAD0;
extern double dbl_ABFAF0;
extern double dbl_ABFB08;
extern double dbl_ABFC10;
extern double dbl_ABFC38;
extern double dbl_ABFC60;
extern double dbl_ABFD38;
extern double dbl_ABFD60;
extern double dbl_ABFDD8;
extern double dbl_ABFDF8;
extern double dbl_ABFE00;
extern double dbl_ABFE28;
extern double dbl_ABFE48;
extern double dbl_ABFE58;
extern double dbl_ABFE78;
extern double dbl_ABFE80;
extern double dbl_ABFEA8;
extern double dbl_ABFEE0;
extern double dbl_ABFEF0;
extern double dbl_ABFF10;
extern double dbl_ABFF18;
extern double dbl_ABFF40;
extern double dbl_ABFF60;
extern double dbl_AC0198;
extern double dbl_AC01C0;
extern double dbl_AC01C8;
extern double dbl_AC0210;
extern double dbl_AC0250;
extern double dbl_AC0AC0;
extern double dbl_AC0CE8;
extern double dbl_AC0D28;
extern double dbl_AC10D8;
extern double dbl_AC1160;
extern double dbl_AC11D0;
extern double dbl_AC1210;
extern double dbl_AC1218;
extern double dbl_AC1240;
extern double dbl_AC1260;
extern double dbl_AC1270;
extern double dbl_AC12E0;
extern double dbl_AC12F0;
extern double dbl_AC1318;
extern double dbl_AC1338;
extern double dbl_AC1348;
extern double dbl_AC1368;
extern double dbl_AC1370;
extern double dbl_AC13A0;
extern double dbl_AC13C0;
extern double dbl_AC13D0;
extern double dbl_AC13F0;
extern double dbl_AC13F8;
extern double dbl_AC1440;
extern double dbl_AC1468;
extern double dbl_AC1490;
extern double dbl_AC14B0;
extern double dbl_AC14B8;
extern double dbl_AC14E0;
extern double dbl_AC1500;
extern double dbl_AC1510;
extern double dbl_AC1530;
extern double dbl_AC1538;
extern double dbl_AC15B8;
extern double dbl_AC15D8;
extern double dbl_AC15F0;
extern double dbl_AC1610;
extern double dbl_AC1618;
extern double dbl_AC1648;
extern double dbl_AC1668;
extern double dbl_AC1690;
extern double dbl_AC17D8;
extern double dbl_AC17E0;
extern double dbl_AC1808;
extern double dbl_AC1828;
extern double dbl_AC1898;
extern double dbl_AC1B40;
extern double dbl_AC1B88;
extern double dbl_AC4830;
extern double dbl_AC48A0;
extern double dbl_AC48F8;
extern double dbl_AC4930;
extern double dbl_AC4938;
extern double dbl_AC4960;
extern double dbl_AC4980;
extern double dbl_AC4990;
extern double dbl_AC49B8;
extern double dbl_AC49C0;
extern double dbl_AC49F0;
extern double dbl_AC4A10;
extern double dbl_AC4A20;
extern double dbl_AC4A40;
extern double dbl_AC4A48;
extern double dbl_AC4A70;
extern double dbl_AC4A90;
extern double dbl_AC4AB0;
extern double dbl_AC4AD0;
extern double dbl_AC4AD8;
extern double dbl_AC4B00;
extern double dbl_AC4B20;
extern double dbl_AC4B68;
extern double dbl_AC4BE8;
extern double dbl_AC4C10;
extern double dbl_AC4CB8;
extern double dbl_AC4CE8;
extern double dbl_AC4CF8;
extern double dbl_AC4D18;
extern double dbl_AC4D20;
extern double dbl_AC4E48;
extern double dbl_AC4E68;
extern double dbl_AC4E88;
extern double dbl_AC4EB0;
extern double dbl_AC4EB8;
extern double dbl_AC4EE0;
extern double dbl_AC4F00;
extern double dbl_AC4F10;
extern double dbl_AC4F30;
extern double dbl_AC4F38;
extern double dbl_AC4FE8;
extern double dbl_AC5008;
extern double dbl_AC5018;
extern double dbl_AC5028;
extern double dbl_AC5030;
extern double dbl_AC5058;
extern double dbl_AC5078;
extern double dbl_AC5088;
extern double dbl_AC5098;
extern double dbl_AC50A0;
extern double dbl_AC50C8;
extern double dbl_AC50E8;
extern double dbl_AC5208;
extern double dbl_AC6650;
extern double dbl_AFA260;
extern double dbl_AFA408;
extern double dbl_AFA460;
extern double dbl_B048A0;
extern double dbl_B048D8;
extern double dbl_B048E8;
extern double dbl_B049D8;
extern double dbl_B049F8;
extern double dbl_B04A40;
extern double dbl_B04A78;
extern double dbl_B04A80;
extern double dbl_B04AA8;
extern double dbl_B04AC8;
extern double dbl_B04AD8;
extern double dbl_B04AF8;
extern double dbl_B04B00;
extern double dbl_B04B28;
extern double dbl_B04B48;
extern double dbl_B04B58;
extern double dbl_B04B78;
extern double dbl_B04B80;
extern double dbl_B04BA8;
extern double dbl_B04BC8;
extern double dbl_B04C20;
extern double dbl_B04C40;
extern double dbl_B04C48;
extern double dbl_B04C70;
extern double dbl_B04C90;
extern double dbl_B04CA8;
extern double dbl_B04CC8;
extern double dbl_B04CD0;
extern double dbl_B04CF8;
extern double dbl_B04D18;
extern double dbl_B04D30;
extern double dbl_B04D70;
extern double dbl_B04D80;
extern double dbl_B04DC8;
extern double dbl_B04DF0;
extern double dbl_B04E00;
extern double dbl_B04E20;
extern double dbl_B04E28;
extern double dbl_B04E50;
extern double dbl_B04E70;
extern double dbl_B04E80;
extern double dbl_B052A0;
extern double dbl_B052B0;
extern double dbl_B05308;
extern double dbl_B05328;
extern double dbl_B05338;
extern double dbl_B05358;
extern double dbl_B05360;
extern double dbl_B05388;
extern double dbl_B053A8;
extern double dbl_B053C0;
extern double dbl_B053E0;
extern double dbl_B053E8;
extern double dbl_B05410;
extern double dbl_B05430;
extern double dbl_B05440;
extern double dbl_B05460;
extern double dbl_B05468;
extern double dbl_B054A0;
extern double dbl_B054C0;
extern double dbl_B054E8;
extern double dbl_B05510;
extern double dbl_B05518;
extern double dbl_B05550;
extern double dbl_B05578;
extern double dbl_B055A8;
extern double dbl_B055C8;
extern double dbl_B055D0;
extern double dbl_B055F8;
extern double dbl_B05618;
extern double dbl_B05630;
extern double dbl_B05660;
extern double dbl_B05668;
extern double dbl_B05698;
extern double dbl_B056B8;
extern double dbl_B056C8;
extern double dbl_B056E8;
extern double dbl_B056F0;
extern double dbl_B05718;
extern double dbl_B05738;
extern double dbl_B05748;
extern double dbl_B05768;
extern double dbl_B05770;
extern double dbl_B05798;
extern double dbl_B057B8;
extern double dbl_B057C8;
extern double dbl_B057E8;
extern double dbl_B057F0;
extern double dbl_B07758;
extern double dbl_B07778;
extern double dbl_B077C0;
extern double dbl_B077E0;
extern double dbl_B077E8;
extern double dbl_B07810;
extern double dbl_B07830;
extern double dbl_B07840;
extern double dbl_B07850;
extern double dbl_B07858;
extern double dbl_B07880;
extern double dbl_B078A0;
extern double dbl_B07BB8;
extern double dbl_B07DE0;
extern double dbl_B07DE8;
extern double dbl_B0B318;
extern double dbl_B0B398;
extern double dbl_B0B520;
extern double dbl_B0B540;
extern double dbl_B0B548;
extern double dbl_B0B570;
extern double dbl_B0B590;
extern double dbl_B0B5C0;
extern double dbl_B0B628;
extern int dword_ABF200;
extern int dword_ABF204;
extern int dword_ABF208;
extern int dword_ABF23C;
extern int dword_ABF2C0;
extern int dword_ABF2C4;
extern int dword_ABF2C8;
extern int dword_ABF340;
extern int dword_ABF344;
extern int dword_ABF348;
extern int dword_ABF3D8;
extern int dword_ABF3DC;
extern int dword_ABF3E0;
extern int dword_ABF480;
extern int dword_ABF484;
extern int dword_ABF488;
extern int dword_ABF500;
extern int dword_ABF504;
extern int dword_ABF508;
extern int dword_ABF580;
extern int dword_ABF584;
extern int dword_ABF588;
extern int dword_ABF938;
extern int dword_ABF93C;
extern int dword_ABF940;
extern int dword_ABF9D8;
extern int dword_ABF9DC;
extern int dword_ABF9E0;
extern int dword_ABFA60;
extern int dword_ABFA64;
extern int dword_ABFA68;
extern int dword_ABFB68;
extern int dword_ABFB6C;
extern int dword_ABFB70;
extern int dword_ABFDB8;
extern int dword_ABFDBC;
extern int dword_ABFDC0;
extern int dword_ABFE38;
extern int dword_ABFE3C;
extern int dword_ABFE40;
extern int dword_ABFEB8;
extern int dword_ABFEBC;
extern int dword_ABFEC0;
extern int dword_ABFF50;
extern int dword_ABFF54;
extern int dword_ABFF58;
extern int dword_AC0240;
extern int dword_AC0244;
extern int dword_AC0248;
extern int dword_AC1148;
extern int dword_AC114C;
extern int dword_AC1150;
extern int dword_AC1250;
extern int dword_AC1254;
extern int dword_AC1258;
extern int dword_AC1328;
extern int dword_AC132C;
extern int dword_AC1330;
extern int dword_AC13B0;
extern int dword_AC13B4;
extern int dword_AC13B8;
extern int dword_AC1450;
extern int dword_AC1454;
extern int dword_AC1458;
extern int dword_AC14F0;
extern int dword_AC14F4;
extern int dword_AC14F8;
extern int dword_AC15C8;
extern int dword_AC15CC;
extern int dword_AC15D0;
extern int dword_AC1658;
extern int dword_AC165C;
extern int dword_AC1660;
extern int dword_AC1818;
extern int dword_AC181C;
extern int dword_AC1820;
extern int dword_AC1DE8;
extern int dword_AC4888;
extern int dword_AC488C;
extern int dword_AC4890;
extern int dword_AC4970;
extern int dword_AC4974;
extern int dword_AC4978;
extern int dword_AC4A00;
extern int dword_AC4A04;
extern int dword_AC4A08;
extern int dword_AC4A80;
extern int dword_AC4A84;
extern int dword_AC4A88;
extern int dword_AC4B10;
extern int dword_AC4B14;
extern int dword_AC4B18;
extern int dword_AC4CD8;
extern int dword_AC4CDC;
extern int dword_AC4CE0;
extern int dword_AC4E58;
extern int dword_AC4E5C;
extern int dword_AC4E60;
extern int dword_AC4EF0;
extern int dword_AC4EF4;
extern int dword_AC4EF8;
extern int dword_AC4FF8;
extern int dword_AC4FFC;
extern int dword_AC5000;
extern int dword_AC5068;
extern int dword_AC506C;
extern int dword_AC5070;
extern int dword_AC50D8;
extern int dword_AC50DC;
extern int dword_AC50E0;
extern int dword_AFA420;
extern int dword_AFA424;
extern int dword_AFA428;
extern int dword_B049E8;
extern int dword_B049EC;
extern int dword_B049F0;
extern int dword_B04AB8;
extern int dword_B04ABC;
extern int dword_B04AC0;
extern int dword_B04B38;
extern int dword_B04B3C;
extern int dword_B04B40;
extern int dword_B04BB8;
extern int dword_B04BBC;
extern int dword_B04BC0;
extern int dword_B04C80;
extern int dword_B04C84;
extern int dword_B04C88;
extern int dword_B04D08;
extern int dword_B04D0C;
extern int dword_B04D10;
extern int dword_B04DE0;
extern int dword_B04DE4;
extern int dword_B04DE8;
extern int dword_B04E60;
extern int dword_B04E64;
extern int dword_B04E68;
extern int dword_B05318;
extern int dword_B0531C;
extern int dword_B05320;
extern int dword_B05398;
extern int dword_B0539C;
extern int dword_B053A0;
extern int dword_B05420;
extern int dword_B05424;
extern int dword_B05428;
extern int dword_B054B0;
extern int dword_B054B4;
extern int dword_B054B8;
extern int dword_B05568;
extern int dword_B0556C;
extern int dword_B05570;
extern int dword_B05608;
extern int dword_B0560C;
extern int dword_B05610;
extern int dword_B056A8;
extern int dword_B056AC;
extern int dword_B056B0;
extern int dword_B05728;
extern int dword_B0572C;
extern int dword_B05730;
extern int dword_B057A8;
extern int dword_B057AC;
extern int dword_B057B0;
extern int dword_B07768;
extern int dword_B0776C;
extern int dword_B07770;
extern int dword_B07820;
extern int dword_B07824;
extern int dword_B07828;
extern int dword_B07890;
extern int dword_B07894;
extern int dword_B07898;
extern int dword_B0B388;
extern int dword_B0B38C;
extern int dword_B0B390;
extern int dword_B0B580;
extern int dword_B0B584;
extern int dword_B0B588;

namespace gamemd {

// IDA: 0x5BBFC0  proposal: InitGlobal5BBFC0
// IDA: void sub_5BBFC0()
//   dbl_ABF210 = dbl_ABF150 / 60.0;
void InitGlobal5BBFC0()
{
}

// IDA: 0x5BC000  proposal: InitDegToRad5BC000
// IDA: void sub_5BC000()
//   dbl_ABF1B8 = 0.0174532925199433 * 45.0;
void InitDegToRad5BC000()
{
}

// IDA: 0x5BC020  proposal: InitScale605BC020
// IDA: void sub_5BC020()
//   dbl_ABF158 = 0.0174532925199433 * 60.0;
void InitScale605BC020()
{
}

// IDA: 0x5BC040  proposal: InitDegToRad5BC040
// IDA: void sub_5BC040()
//   dbl_ABF130 = 0.0174532925199433 * 90.0;
void InitDegToRad5BC040()
{
}

// IDA: 0x5BC160  proposal: InitZero5BC160
// IDA: int sub_5BC160()
//   dword_ABF208 = 0;
//   dword_ABF200 = 128;
//   dword_ABF204 = 128;
//   return 128;
int InitZero5BC160()
{
  return 128;
}

// IDA: 0x5BC440  proposal: InitGlobal5BC440
// IDA: int sub_5BC440()
//   return dword_ABF23C;
int InitGlobal5BC440()
{
  return 0;
}

// IDA: 0x5BD810  proposal: InitGlobal5BD810
// IDA: void sub_5BD810()
//   dbl_ABF2D0 = dbl_ABF270 / 60.0;
void InitGlobal5BD810()
{
}

// IDA: 0x5BD850  proposal: InitDegToRad5BD850
// IDA: void sub_5BD850()
//   dbl_ABF2B0 = 0.0174532925199433 * 45.0;
void InitDegToRad5BD850()
{
}

// IDA: 0x5BD870  proposal: InitScale605BD870
// IDA: void sub_5BD870()
//   dbl_ABF278 = 0.0174532925199433 * 60.0;
void InitScale605BD870()
{
}

// IDA: 0x5BD890  proposal: InitDegToRad5BD890
// IDA: void sub_5BD890()
//   dbl_ABF248 = 0.0174532925199433 * 90.0;
void InitDegToRad5BD890()
{
}

// IDA: 0x5BD9B0  proposal: InitZero5BD9B0
// IDA: int sub_5BD9B0()
//   dword_ABF2C8 = 0;
//   dword_ABF2C0 = 128;
//   dword_ABF2C4 = 128;
//   return 128;
int InitZero5BD9B0()
{
  return 128;
}

// IDA: 0x5BEB00  proposal: InitGlobal5BEB00
// IDA: void sub_5BEB00()
//   dbl_ABF350 = dbl_ABF300 / 60.0;
void InitGlobal5BEB00()
{
}

// IDA: 0x5BEB40  proposal: InitDegToRad5BEB40
// IDA: void sub_5BEB40()
//   dbl_ABF330 = 0.0174532925199433 * 45.0;
void InitDegToRad5BEB40()
{
}

// IDA: 0x5BEB60  proposal: InitScale605BEB60
// IDA: void sub_5BEB60()
//   dbl_ABF308 = 0.0174532925199433 * 60.0;
void InitScale605BEB60()
{
}

// IDA: 0x5BEB80  proposal: InitDegToRad5BEB80
// IDA: void sub_5BEB80()
//   dbl_ABF2E0 = 0.0174532925199433 * 90.0;
void InitDegToRad5BEB80()
{
}

// IDA: 0x5BECA0  proposal: InitZero5BECA0
// IDA: int sub_5BECA0()
//   dword_ABF348 = 0;
//   dword_ABF340 = 128;
//   dword_ABF344 = 128;
//   return 128;
int InitZero5BECA0()
{
  return 128;
}

// IDA: 0x5BF610  proposal: InitGlobal5BF610
// IDA: void sub_5BF610()
//   dbl_ABF3E8 = dbl_ABF380 / 60.0;
void InitGlobal5BF610()
{
}

// IDA: 0x5BF650  proposal: InitDegToRad5BF650
// IDA: void sub_5BF650()
//   dbl_ABF3C8 = 0.0174532925199433 * 45.0;
void InitDegToRad5BF650()
{
}

// IDA: 0x5BF670  proposal: InitScale605BF670
// IDA: void sub_5BF670()
//   dbl_ABF388 = 0.0174532925199433 * 60.0;
void InitScale605BF670()
{
}

// IDA: 0x5BF690  proposal: InitDegToRad5BF690
// IDA: void sub_5BF690()
//   dbl_ABF360 = 0.0174532925199433 * 90.0;
void InitDegToRad5BF690()
{
}

// IDA: 0x5BF7B0  proposal: InitZero5BF7B0
// IDA: int sub_5BF7B0()
//   dword_ABF3E0 = 0;
//   dword_ABF3D8 = 128;
//   dword_ABF3DC = 128;
//   return 128;
int InitZero5BF7B0()
{
  return 128;
}

// IDA: 0x5C1120  proposal: InitGlobal5C1120
// IDA: void sub_5C1120()
//   dbl_ABF490 = dbl_ABF420 / 60.0;
void InitGlobal5C1120()
{
}

// IDA: 0x5C1160  proposal: InitDegToRad5C1160
// IDA: void sub_5C1160()
//   dbl_ABF450 = 0.0174532925199433 * 45.0;
void InitDegToRad5C1160()
{
}

// IDA: 0x5C1180  proposal: InitScale605C1180
// IDA: void sub_5C1180()
//   dbl_ABF428 = 0.0174532925199433 * 60.0;
void InitScale605C1180()
{
}

// IDA: 0x5C11A0  proposal: InitDegToRad5C11A0
// IDA: void sub_5C11A0()
//   dbl_ABF400 = 0.0174532925199433 * 90.0;
void InitDegToRad5C11A0()
{
}

// IDA: 0x5C12C0  proposal: InitZero5C12C0
// IDA: int sub_5C12C0()
//   dword_ABF488 = 0;
//   dword_ABF480 = 128;
//   dword_ABF484 = 128;
//   return 128;
int InitZero5C12C0()
{
  return 128;
}

// IDA: 0x5C5B20  proposal: InitGlobal5C5B20
// IDA: void sub_5C5B20()
//   dbl_ABF510 = dbl_ABF4C0 / 60.0;
void InitGlobal5C5B20()
{
}

// IDA: 0x5C5B60  proposal: InitDegToRad5C5B60
// IDA: void sub_5C5B60()
//   dbl_ABF4F0 = 0.0174532925199433 * 45.0;
void InitDegToRad5C5B60()
{
}

// IDA: 0x5C5B80  proposal: InitScale605C5B80
// IDA: void sub_5C5B80()
//   dbl_ABF4C8 = 0.0174532925199433 * 60.0;
void InitScale605C5B80()
{
}

// IDA: 0x5C5BA0  proposal: InitDegToRad5C5BA0
// IDA: void sub_5C5BA0()
//   dbl_ABF4A0 = 0.0174532925199433 * 90.0;
void InitDegToRad5C5BA0()
{
}

// IDA: 0x5C5CC0  proposal: InitZero5C5CC0
// IDA: int sub_5C5CC0()
//   dword_ABF508 = 0;
//   dword_ABF500 = 128;
//   dword_ABF504 = 128;
//   return 128;
int InitZero5C5CC0()
{
  return 128;
}

// IDA: 0x5C5EC0  proposal: InitGlobal5C5EC0
// IDA: void sub_5C5EC0()
//   dbl_ABF590 = dbl_ABF540 / 60.0;
void InitGlobal5C5EC0()
{
}

// IDA: 0x5C5F00  proposal: InitDegToRad5C5F00
// IDA: void sub_5C5F00()
//   dbl_ABF570 = 0.0174532925199433 * 45.0;
void InitDegToRad5C5F00()
{
}

// IDA: 0x5C5F20  proposal: InitScale605C5F20
// IDA: void sub_5C5F20()
//   dbl_ABF548 = 0.0174532925199433 * 60.0;
void InitScale605C5F20()
{
}

// IDA: 0x5C5F40  proposal: InitDegToRad5C5F40
// IDA: void sub_5C5F40()
//   dbl_ABF520 = 0.0174532925199433 * 90.0;
void InitDegToRad5C5F40()
{
}

// IDA: 0x5C6060  proposal: InitZero5C6060
// IDA: int sub_5C6060()
//   dword_ABF588 = 0;
//   dword_ABF580 = 128;
//   dword_ABF584 = 128;
//   return 128;
int InitZero5C6060()
{
  return 128;
}

// IDA: 0x5C9220  proposal: InitGlobal5C9220
// IDA: void sub_5C9220()
//   dbl_ABF948 = dbl_ABF8F8 / 60.0;
void InitGlobal5C9220()
{
}

// IDA: 0x5C9260  proposal: InitDegToRad5C9260
// IDA: void sub_5C9260()
//   dbl_ABF928 = 0.0174532925199433 * 45.0;
void InitDegToRad5C9260()
{
}

// IDA: 0x5C9280  proposal: InitScale605C9280
// IDA: void sub_5C9280()
//   dbl_ABF900 = 0.0174532925199433 * 60.0;
void InitScale605C9280()
{
}

// IDA: 0x5C92A0  proposal: InitDegToRad5C92A0
// IDA: void sub_5C92A0()
//   dbl_ABF8D8 = 0.0174532925199433 * 90.0;
void InitDegToRad5C92A0()
{
}

// IDA: 0x5C93C0  proposal: InitZero5C93C0
// IDA: int sub_5C93C0()
//   dword_ABF940 = 0;
//   dword_ABF938 = 128;
//   dword_ABF93C = 128;
//   return 128;
int InitZero5C93C0()
{
  return 128;
}

// IDA: 0x5C9540  proposal: InitGlobal5C9540
// IDA: void sub_5C9540()
//   dbl_ABF9E8 = dbl_ABF998 / 60.0;
void InitGlobal5C9540()
{
}

// IDA: 0x5C9580  proposal: InitDegToRad5C9580
// IDA: void sub_5C9580()
//   dbl_ABF9C8 = 0.0174532925199433 * 45.0;
void InitDegToRad5C9580()
{
}

// IDA: 0x5C95A0  proposal: InitScale605C95A0
// IDA: void sub_5C95A0()
//   dbl_ABF9A0 = 0.0174532925199433 * 60.0;
void InitScale605C95A0()
{
}

// IDA: 0x5C95C0  proposal: InitDegToRad5C95C0
// IDA: void sub_5C95C0()
//   dbl_ABF978 = 0.0174532925199433 * 90.0;
void InitDegToRad5C95C0()
{
}

// IDA: 0x5C96E0  proposal: InitZero5C96E0
// IDA: int sub_5C96E0()
//   dword_ABF9E0 = 0;
//   dword_ABF9D8 = 128;
//   dword_ABF9DC = 128;
//   return 128;
int InitZero5C96E0()
{
  return 128;
}

// IDA: 0x5CA450  proposal: InitGlobal5CA450
// IDA: void sub_5CA450()
//   dbl_ABFA70 = dbl_ABFA20 / 60.0;
void InitGlobal5CA450()
{
}

// IDA: 0x5CA490  proposal: InitDegToRad5CA490
// IDA: void sub_5CA490()
//   dbl_ABFA50 = 0.0174532925199433 * 45.0;
void InitDegToRad5CA490()
{
}

// IDA: 0x5CA4B0  proposal: InitScale605CA4B0
// IDA: void sub_5CA4B0()
//   dbl_ABFA28 = 0.0174532925199433 * 60.0;
void InitScale605CA4B0()
{
}

// IDA: 0x5CA4D0  proposal: InitDegToRad5CA4D0
// IDA: void sub_5CA4D0()
//   dbl_ABFA00 = 0.0174532925199433 * 90.0;
void InitDegToRad5CA4D0()
{
}

// IDA: 0x5CA5F0  proposal: InitZero5CA5F0
// IDA: int sub_5CA5F0()
//   dword_ABFA68 = 0;
//   dword_ABFA60 = 128;
//   dword_ABFA64 = 128;
//   return 128;
int InitZero5CA5F0()
{
  return 128;
}

// IDA: 0x5CAC50  proposal: InitGlobal5CAC50
// IDA: void sub_5CAC50()
//   dbl_ABFAF0 = dbl_ABFAA0 / 60.0;
void InitGlobal5CAC50()
{
}

// IDA: 0x5CAC90  proposal: InitDegToRad5CAC90
// IDA: void sub_5CAC90()
//   dbl_ABFAD0 = 0.0174532925199433 * 45.0;
void InitDegToRad5CAC90()
{
}

// IDA: 0x5CACB0  proposal: InitScale605CACB0
// IDA: void sub_5CACB0()
//   dbl_ABFAA8 = 0.0174532925199433 * 60.0;
void InitScale605CACB0()
{
}

// IDA: 0x5CACD0  proposal: InitDegToRad5CACD0
// IDA: void sub_5CACD0()
//   dbl_ABFA80 = 0.0174532925199433 * 90.0;
void InitDegToRad5CACD0()
{
}

// IDA: 0x5CB240  proposal: InitDegToRad5CB240
// IDA: void sub_5CB240()
//   dbl_ABFB08 = 0.0174532925199433 * 90.0;
void InitDegToRad5CB240()
{
}

// IDA: 0x5CB360  proposal: InitZero5CB360
// IDA: int sub_5CB360()
//   dword_ABFB70 = 0;
//   dword_ABFB68 = 128;
//   dword_ABFB6C = 128;
//   return 128;
int InitZero5CB360()
{
  return 128;
}

// IDA: 0x5D3850  proposal: InitDegToRad5D3850
// IDA: void sub_5D3850()
//   dbl_ABFC60 = 0.0174532925199433 * 45.0;
void InitDegToRad5D3850()
{
}

// IDA: 0x5D3870  proposal: InitScale605D3870
// IDA: void sub_5D3870()
//   dbl_ABFC38 = 0.0174532925199433 * 60.0;
void InitScale605D3870()
{
}

// IDA: 0x5D3890  proposal: InitDegToRad5D3890
// IDA: void sub_5D3890()
//   dbl_ABFC10 = 0.0174532925199433 * 90.0;
void InitDegToRad5D3890()
{
}

// IDA: 0x5D5940  proposal: InitScale605D5940
// IDA: void sub_5D5940()
//   dbl_ABFD60 = 0.0174532925199433 * 60.0;
void InitScale605D5940()
{
}

// IDA: 0x5D5960  proposal: InitDegToRad5D5960
// IDA: void sub_5D5960()
//   dbl_ABFD38 = 0.0174532925199433 * 90.0;
void InitDegToRad5D5960()
{
}

// IDA: 0x5D5A80  proposal: InitZero5D5A80
// IDA: int sub_5D5A80()
//   dword_ABFDC0 = 0;
//   dword_ABFDB8 = 128;
//   dword_ABFDBC = 128;
//   return 128;
int InitZero5D5A80()
{
  return 128;
}

// IDA: 0x5D8A90  proposal: InitGlobal5D8A90
// IDA: void sub_5D8A90()
//   dbl_ABFE48 = dbl_ABFDF8 / 60.0;
void InitGlobal5D8A90()
{
}

// IDA: 0x5D8AD0  proposal: InitDegToRad5D8AD0
// IDA: void sub_5D8AD0()
//   dbl_ABFE28 = 0.0174532925199433 * 45.0;
void InitDegToRad5D8AD0()
{
}

// IDA: 0x5D8AF0  proposal: InitScale605D8AF0
// IDA: void sub_5D8AF0()
//   dbl_ABFE00 = 0.0174532925199433 * 60.0;
void InitScale605D8AF0()
{
}

// IDA: 0x5D8B10  proposal: InitDegToRad5D8B10
// IDA: void sub_5D8B10()
//   dbl_ABFDD8 = 0.0174532925199433 * 90.0;
void InitDegToRad5D8B10()
{
}

// IDA: 0x5D8C30  proposal: InitZero5D8C30
// IDA: int sub_5D8C30()
//   dword_ABFE40 = 0;
//   dword_ABFE38 = 128;
//   dword_ABFE3C = 128;
//   return 128;
int InitZero5D8C30()
{
  return 128;
}

// IDA: 0x5D8DB0  proposal: InitGlobal5D8DB0
// IDA: void sub_5D8DB0()
//   dbl_ABFEE0 = dbl_ABFE78 / 60.0;
void InitGlobal5D8DB0()
{
}

// IDA: 0x5D8DF0  proposal: InitDegToRad5D8DF0
// IDA: void sub_5D8DF0()
//   dbl_ABFEA8 = 0.0174532925199433 * 45.0;
void InitDegToRad5D8DF0()
{
}

// IDA: 0x5D8E10  proposal: InitScale605D8E10
// IDA: void sub_5D8E10()
//   dbl_ABFE80 = 0.0174532925199433 * 60.0;
void InitScale605D8E10()
{
}

// IDA: 0x5D8E30  proposal: InitDegToRad5D8E30
// IDA: void sub_5D8E30()
//   dbl_ABFE58 = 0.0174532925199433 * 90.0;
void InitDegToRad5D8E30()
{
}

// IDA: 0x5D8F50  proposal: InitZero5D8F50
// IDA: int sub_5D8F50()
//   dword_ABFEC0 = 0;
//   dword_ABFEB8 = 128;
//   dword_ABFEBC = 128;
//   return 128;
int InitZero5D8F50()
{
  return 128;
}

// IDA: 0x5DA500  proposal: InitGlobal5DA500
// IDA: void sub_5DA500()
//   dbl_ABFF60 = dbl_ABFF10 / 60.0;
void InitGlobal5DA500()
{
}

// IDA: 0x5DA540  proposal: InitDegToRad5DA540
// IDA: void sub_5DA540()
//   dbl_ABFF40 = 0.0174532925199433 * 45.0;
void InitDegToRad5DA540()
{
}

// IDA: 0x5DA560  proposal: InitScale605DA560
// IDA: void sub_5DA560()
//   dbl_ABFF18 = 0.0174532925199433 * 60.0;
void InitScale605DA560()
{
}

// IDA: 0x5DA580  proposal: InitDegToRad5DA580
// IDA: void sub_5DA580()
//   dbl_ABFEF0 = 0.0174532925199433 * 90.0;
void InitDegToRad5DA580()
{
}

// IDA: 0x5DA6A0  proposal: InitZero5DA6A0
// IDA: int sub_5DA6A0()
//   dword_ABFF58 = 0;
//   dword_ABFF50 = 128;
//   dword_ABFF54 = 128;
//   return 128;
int InitZero5DA6A0()
{
  return 128;
}

// IDA: 0x5DAD20  proposal: InitGlobal5DAD20
// IDA: void sub_5DAD20()
//   dbl_AC0250 = dbl_AC01C0 / 60.0;
void InitGlobal5DAD20()
{
}

// IDA: 0x5DAD60  proposal: InitDegToRad5DAD60
// IDA: void sub_5DAD60()
//   dbl_AC0210 = 0.0174532925199433 * 45.0;
void InitDegToRad5DAD60()
{
}

// IDA: 0x5DAD80  proposal: InitScale605DAD80
// IDA: void sub_5DAD80()
//   dbl_AC01C8 = 0.0174532925199433 * 60.0;
void InitScale605DAD80()
{
}

// IDA: 0x5DADA0  proposal: InitDegToRad5DADA0
// IDA: void sub_5DADA0()
//   dbl_AC0198 = 0.0174532925199433 * 90.0;
void InitDegToRad5DADA0()
{
}

// IDA: 0x5DAEC0  proposal: InitZero5DAEC0
// IDA: int sub_5DAEC0()
//   dword_AC0248 = 0;
//   dword_AC0240 = 128;
//   dword_AC0244 = 128;
//   return 128;
int InitZero5DAEC0()
{
  return 128;
}

// IDA: 0x5E2460  proposal: InitGlobal5E2460
// IDA: void sub_5E2460()
//   dbl_AC1160 = dbl_AC0CE8 / 60.0;
void InitGlobal5E2460()
{
}

// IDA: 0x5E24A0  proposal: InitDegToRad5E24A0
// IDA: void sub_5E24A0()
//   dbl_AC10D8 = 0.0174532925199433 * 45.0;
void InitDegToRad5E24A0()
{
}

// IDA: 0x5E24C0  proposal: InitScale605E24C0
// IDA: void sub_5E24C0()
//   dbl_AC0D28 = 0.0174532925199433 * 60.0;
void InitScale605E24C0()
{
}

// IDA: 0x5E24E0  proposal: InitDegToRad5E24E0
// IDA: void sub_5E24E0()
//   dbl_AC0AC0 = 0.0174532925199433 * 90.0;
void InitDegToRad5E24E0()
{
}

// IDA: 0x5E2600  proposal: InitZero5E2600
// IDA: int sub_5E2600()
//   dword_AC1150 = 0;
//   dword_AC1148 = 128;
//   dword_AC114C = 128;
//   return 128;
int InitZero5E2600()
{
  return 128;
}

// IDA: 0x5EF320  proposal: InitGlobal5EF320
// IDA: void sub_5EF320()
//   dbl_AC1260 = dbl_AC1210 / 60.0;
void InitGlobal5EF320()
{
}

// IDA: 0x5EF360  proposal: InitDegToRad5EF360
// IDA: void sub_5EF360()
//   dbl_AC1240 = 0.0174532925199433 * 45.0;
void InitDegToRad5EF360()
{
}

// IDA: 0x5EF380  proposal: InitScale605EF380
// IDA: void sub_5EF380()
//   dbl_AC1218 = 0.0174532925199433 * 60.0;
void InitScale605EF380()
{
}

// IDA: 0x5EF3A0  proposal: InitDegToRad5EF3A0
// IDA: void sub_5EF3A0()
//   dbl_AC11D0 = 0.0174532925199433 * 90.0;
void InitDegToRad5EF3A0()
{
}

// IDA: 0x5EF4C0  proposal: InitZero5EF4C0
// IDA: int sub_5EF4C0()
//   dword_AC1258 = 0;
//   dword_AC1250 = 128;
//   dword_AC1254 = 128;
//   return 128;
int InitZero5EF4C0()
{
  return 128;
}

// IDA: 0x5F1400  proposal: InitGlobal5F1400
// IDA: void sub_5F1400()
//   dbl_AC1338 = dbl_AC12E0 / 60.0;
void InitGlobal5F1400()
{
}

// IDA: 0x5F1440  proposal: InitDegToRad5F1440
// IDA: void sub_5F1440()
//   dbl_AC1318 = 0.0174532925199433 * 45.0;
void InitDegToRad5F1440()
{
}

// IDA: 0x5F1460  proposal: InitScale605F1460
// IDA: void sub_5F1460()
//   dbl_AC12F0 = 0.0174532925199433 * 60.0;
void InitScale605F1460()
{
}

// IDA: 0x5F1480  proposal: InitDegToRad5F1480
// IDA: void sub_5F1480()
//   dbl_AC1270 = 0.0174532925199433 * 90.0;
void InitDegToRad5F1480()
{
}

// IDA: 0x5F15A0  proposal: InitZero5F15A0
// IDA: int sub_5F15A0()
//   dword_AC1330 = 0;
//   dword_AC1328 = 128;
//   dword_AC132C = 128;
//   return 128;
int InitZero5F15A0()
{
  return 128;
}

// IDA: 0x5F3720  proposal: InitGlobal5F3720
// IDA: void sub_5F3720()
//   dbl_AC13C0 = dbl_AC1368 / 60.0;
void InitGlobal5F3720()
{
}

// IDA: 0x5F3760  proposal: InitDegToRad5F3760
// IDA: void sub_5F3760()
//   dbl_AC13A0 = 0.0174532925199433 * 45.0;
void InitDegToRad5F3760()
{
}

// IDA: 0x5F3780  proposal: InitScale605F3780
// IDA: void sub_5F3780()
//   dbl_AC1370 = 0.0174532925199433 * 60.0;
void InitScale605F3780()
{
}

// IDA: 0x5F37A0  proposal: InitDegToRad5F37A0
// IDA: void sub_5F37A0()
//   dbl_AC1348 = 0.0174532925199433 * 90.0;
void InitDegToRad5F37A0()
{
}

// IDA: 0x5F38C0  proposal: InitZero5F38C0
// IDA: int sub_5F38C0()
//   dword_AC13B8 = 0;
//   dword_AC13B0 = 128;
//   dword_AC13B4 = 128;
//   return 128;
int InitZero5F38C0()
{
  return 128;
}

// IDA: 0x5F6E10  proposal: InitGlobal5F6E10
// IDA: void sub_5F6E10()
//   dbl_AC1468 = dbl_AC13F0 / 60.0;
void InitGlobal5F6E10()
{
}

// IDA: 0x5F6E50  proposal: InitDegToRad5F6E50
// IDA: void sub_5F6E50()
//   dbl_AC1440 = 0.0174532925199433 * 45.0;
void InitDegToRad5F6E50()
{
}

// IDA: 0x5F6E70  proposal: InitScale605F6E70
// IDA: void sub_5F6E70()
//   dbl_AC13F8 = 0.0174532925199433 * 60.0;
void InitScale605F6E70()
{
}

// IDA: 0x5F6E90  proposal: InitDegToRad5F6E90
// IDA: void sub_5F6E90()
//   dbl_AC13D0 = 0.0174532925199433 * 90.0;
void InitDegToRad5F6E90()
{
}

// IDA: 0x5F6FB0  proposal: InitZero5F6FB0
// IDA: int sub_5F6FB0()
//   dword_AC1458 = 0;
//   dword_AC1450 = 128;
//   dword_AC1454 = 128;
//   return 128;
int InitZero5F6FB0()
{
  return 128;
}

// IDA: 0x5FA100  proposal: InitGlobal5FA100
// IDA: void sub_5FA100()
//   dbl_AC1500 = dbl_AC14B0 / 60.0;
void InitGlobal5FA100()
{
}

// IDA: 0x5FA140  proposal: InitDegToRad5FA140
// IDA: void sub_5FA140()
//   dbl_AC14E0 = 0.0174532925199433 * 45.0;
void InitDegToRad5FA140()
{
}

// IDA: 0x5FA160  proposal: InitScale605FA160
// IDA: void sub_5FA160()
//   dbl_AC14B8 = 0.0174532925199433 * 60.0;
void InitScale605FA160()
{
}

// IDA: 0x5FA180  proposal: InitDegToRad5FA180
// IDA: void sub_5FA180()
//   dbl_AC1490 = 0.0174532925199433 * 90.0;
void InitDegToRad5FA180()
{
}

// IDA: 0x5FA2A0  proposal: InitZero5FA2A0
// IDA: int sub_5FA2A0()
//   dword_AC14F8 = 0;
//   dword_AC14F0 = 128;
//   dword_AC14F4 = 128;
//   return 128;
int InitZero5FA2A0()
{
  return 128;
}

// IDA: 0x5FC1A0  proposal: InitGlobal5FC1A0
// IDA: void sub_5FC1A0()
//   dbl_AC15D8 = dbl_AC1530 / 60.0;
void InitGlobal5FC1A0()
{
}

// IDA: 0x5FC1E0  proposal: InitDegToRad5FC1E0
// IDA: void sub_5FC1E0()
//   dbl_AC15B8 = 0.0174532925199433 * 45.0;
void InitDegToRad5FC1E0()
{
}

// IDA: 0x5FC200  proposal: InitScale605FC200
// IDA: void sub_5FC200()
//   dbl_AC1538 = 0.0174532925199433 * 60.0;
void InitScale605FC200()
{
}

// IDA: 0x5FC220  proposal: InitDegToRad5FC220
// IDA: void sub_5FC220()
//   dbl_AC1510 = 0.0174532925199433 * 90.0;
void InitDegToRad5FC220()
{
}

// IDA: 0x5FC340  proposal: InitZero5FC340
// IDA: int sub_5FC340()
//   dword_AC15D0 = 0;
//   dword_AC15C8 = 128;
//   dword_AC15CC = 128;
//   return 128;
int InitZero5FC340()
{
  return 128;
}

// IDA: 0x5FE090  proposal: InitGlobal5FE090
// IDA: void sub_5FE090()
//   dbl_AC1668 = dbl_AC1610 / 60.0;
void InitGlobal5FE090()
{
}

// IDA: 0x5FE0D0  proposal: InitDegToRad5FE0D0
// IDA: void sub_5FE0D0()
//   dbl_AC1648 = 0.0174532925199433 * 45.0;
void InitDegToRad5FE0D0()
{
}

// IDA: 0x5FE0F0  proposal: InitScale605FE0F0
// IDA: void sub_5FE0F0()
//   dbl_AC1618 = 0.0174532925199433 * 60.0;
void InitScale605FE0F0()
{
}

// IDA: 0x5FE110  proposal: InitDegToRad5FE110
// IDA: void sub_5FE110()
//   dbl_AC15F0 = 0.0174532925199433 * 90.0;
void InitDegToRad5FE110()
{
}

// IDA: 0x5FE230  proposal: InitZero5FE230
// IDA: int sub_5FE230()
//   dword_AC1660 = 0;
//   dword_AC1658 = 128;
//   dword_AC165C = 128;
//   return 128;
int InitZero5FE230()
{
  return 128;
}

// IDA: 0x5FEFF0  proposal: InitGlobal5FEFF0
// IDA: void sub_5FEFF0()
//   dbl_AC1828 = dbl_AC17D8 / 60.0;
void InitGlobal5FEFF0()
{
}

// IDA: 0x5FF030  proposal: InitDegToRad5FF030
// IDA: void sub_5FF030()
//   dbl_AC1808 = 0.0174532925199433 * 45.0;
void InitDegToRad5FF030()
{
}

// IDA: 0x5FF050  proposal: InitScale605FF050
// IDA: void sub_5FF050()
//   dbl_AC17E0 = 0.0174532925199433 * 60.0;
void InitScale605FF050()
{
}

// IDA: 0x5FF070  proposal: InitDegToRad5FF070
// IDA: void sub_5FF070()
//   dbl_AC1690 = 0.0174532925199433 * 90.0;
void InitDegToRad5FF070()
{
}

// IDA: 0x5FF190  proposal: InitZero5FF190
// IDA: int sub_5FF190()
//   dword_AC1820 = 0;
//   dword_AC1818 = 128;
//   dword_AC181C = 128;
//   return 128;
int InitZero5FF190()
{
  return 128;
}

// IDA: 0x600370  proposal: InitGlobal600370
// IDA: void sub_600370()
//   dbl_AC48A0 = dbl_AC1B40 / 60.0;
void InitGlobal600370()
{
}

// IDA: 0x6003B0  proposal: InitDegToRad6003B0
// IDA: void sub_6003B0()
//   dbl_AC4830 = 0.0174532925199433 * 45.0;
void InitDegToRad6003B0()
{
}

// IDA: 0x6003D0  proposal: InitScale606003D0
// IDA: void sub_6003D0()
//   dbl_AC1B88 = 0.0174532925199433 * 60.0;
void InitScale606003D0()
{
}

// IDA: 0x6003F0  proposal: InitDegToRad6003F0
// IDA: void sub_6003F0()
//   dbl_AC1898 = 0.0174532925199433 * 90.0;
void InitDegToRad6003F0()
{
}

// IDA: 0x600510  proposal: InitZero600510
// IDA: int sub_600510()
//   dword_AC4890 = 0;
//   dword_AC4888 = 128;
//   dword_AC488C = 128;
//   return 128;
int InitZero600510()
{
  return 128;
}

// IDA: 0x612910  proposal: InitGlobal612910
// IDA: void __cdecl sub_612910()
//   g_ComboBoxState = 0;
//   __3_YAXPAX_Z(dword_AC1DE8);
void InitGlobal612910()
{
}

// IDA: 0x628FB0  proposal: InitGlobal628FB0
// IDA: void sub_628FB0()
//   dbl_AC4980 = dbl_AC4930 / 60.0;
void InitGlobal628FB0()
{
}

// IDA: 0x628FF0  proposal: InitDegToRad628FF0
// IDA: void sub_628FF0()
//   dbl_AC4960 = 0.0174532925199433 * 45.0;
void InitDegToRad628FF0()
{
}

// IDA: 0x629010  proposal: InitScale60629010
// IDA: void sub_629010()
//   dbl_AC4938 = 0.0174532925199433 * 60.0;
void InitScale60629010()
{
}

// IDA: 0x629030  proposal: InitDegToRad629030
// IDA: void sub_629030()
//   dbl_AC48F8 = 0.0174532925199433 * 90.0;
void InitDegToRad629030()
{
}

// IDA: 0x629150  proposal: InitZero629150
// IDA: int sub_629150()
//   dword_AC4978 = 0;
//   dword_AC4970 = 128;
//   dword_AC4974 = 128;
//   return 128;
int InitZero629150()
{
  return 128;
}

// IDA: 0x62B400  proposal: InitGlobal62B400
// IDA: void sub_62B400()
//   dbl_AC4A10 = dbl_AC49B8 / 60.0;
void InitGlobal62B400()
{
}

// IDA: 0x62B440  proposal: InitDegToRad62B440
// IDA: void sub_62B440()
//   dbl_AC49F0 = 0.0174532925199433 * 45.0;
void InitDegToRad62B440()
{
}

// IDA: 0x62B460  proposal: InitScale6062B460
// IDA: void sub_62B460()
//   dbl_AC49C0 = 0.0174532925199433 * 60.0;
void InitScale6062B460()
{
}

// IDA: 0x62B480  proposal: InitDegToRad62B480
// IDA: void sub_62B480()
//   dbl_AC4990 = 0.0174532925199433 * 90.0;
void InitDegToRad62B480()
{
}

// IDA: 0x62B5A0  proposal: InitZero62B5A0
// IDA: int sub_62B5A0()
//   dword_AC4A08 = 0;
//   dword_AC4A00 = 128;
//   dword_AC4A04 = 128;
//   return 128;
int InitZero62B5A0()
{
  return 128;
}

// IDA: 0x62DA70  proposal: InitGlobal62DA70
// IDA: void sub_62DA70()
//   dbl_AC4A90 = dbl_AC4A40 / 60.0;
void InitGlobal62DA70()
{
}

// IDA: 0x62DAB0  proposal: InitDegToRad62DAB0
// IDA: void sub_62DAB0()
//   dbl_AC4A70 = 0.0174532925199433 * 45.0;
void InitDegToRad62DAB0()
{
}

// IDA: 0x62DAD0  proposal: InitScale6062DAD0
// IDA: void sub_62DAD0()
//   dbl_AC4A48 = 0.0174532925199433 * 60.0;
void InitScale6062DAD0()
{
}

// IDA: 0x62DAF0  proposal: InitDegToRad62DAF0
// IDA: void sub_62DAF0()
//   dbl_AC4A20 = 0.0174532925199433 * 90.0;
void InitDegToRad62DAF0()
{
}

// IDA: 0x62DC10  proposal: InitZero62DC10
// IDA: int sub_62DC10()
//   dword_AC4A88 = 0;
//   dword_AC4A80 = 128;
//   dword_AC4A84 = 128;
//   return 128;
int InitZero62DC10()
{
  return 128;
}

// IDA: 0x6309D0  proposal: InitGlobal6309D0
// IDA: void sub_6309D0()
//   dbl_AC4B20 = dbl_AC4AD0 / 60.0;
void InitGlobal6309D0()
{
}

// IDA: 0x630A10  proposal: InitDegToRad630A10
// IDA: void sub_630A10()
//   dbl_AC4B00 = 0.0174532925199433 * 45.0;
void InitDegToRad630A10()
{
}

// IDA: 0x630A30  proposal: InitScale60630A30
// IDA: void sub_630A30()
//   dbl_AC4AD8 = 0.0174532925199433 * 60.0;
void InitScale60630A30()
{
}

// IDA: 0x630A50  proposal: InitDegToRad630A50
// IDA: void sub_630A50()
//   dbl_AC4AB0 = 0.0174532925199433 * 90.0;
void InitDegToRad630A50()
{
}

// IDA: 0x630B70  proposal: InitZero630B70
// IDA: int sub_630B70()
//   dword_AC4B18 = 0;
//   dword_AC4B10 = 128;
//   dword_AC4B14 = 128;
//   return 128;
int InitZero630B70()
{
  return 128;
}

// IDA: 0x633400  proposal: InitGlobal633400
// IDA: void sub_633400()
//   dbl_AC4CE8 = dbl_AC4BE8 / 60.0;
void InitGlobal633400()
{
}

// IDA: 0x633440  proposal: InitDegToRad633440
// IDA: void sub_633440()
//   dbl_AC4CB8 = 0.0174532925199433 * 45.0;
void InitDegToRad633440()
{
}

// IDA: 0x633460  proposal: InitScale60633460
// IDA: void sub_633460()
//   dbl_AC4C10 = 0.0174532925199433 * 60.0;
void InitScale60633460()
{
}

// IDA: 0x633480  proposal: InitDegToRad633480
// IDA: void sub_633480()
//   dbl_AC4B68 = 0.0174532925199433 * 90.0;
void InitDegToRad633480()
{
}

// IDA: 0x6335A0  proposal: InitZero6335A0
// IDA: int sub_6335A0()
//   dword_AC4CE0 = 0;
//   dword_AC4CD8 = 128;
//   dword_AC4CDC = 128;
//   return 128;
int InitZero6335A0()
{
  return 128;
}

// IDA: 0x63F4F0  proposal: InitGlobal63F4F0
// IDA: void sub_63F4F0()
//   dbl_AC4E68 = dbl_AC4D18 / 60.0;
void InitGlobal63F4F0()
{
}

// IDA: 0x63F530  proposal: InitDegToRad63F530
// IDA: void sub_63F530()
//   dbl_AC4E48 = 0.0174532925199433 * 45.0;
void InitDegToRad63F530()
{
}

// IDA: 0x63F550  proposal: InitScale6063F550
// IDA: void sub_63F550()
//   dbl_AC4D20 = 0.0174532925199433 * 60.0;
void InitScale6063F550()
{
}

// IDA: 0x63F570  proposal: InitDegToRad63F570
// IDA: void sub_63F570()
//   dbl_AC4CF8 = 0.0174532925199433 * 90.0;
void InitDegToRad63F570()
{
}

// IDA: 0x63F690  proposal: InitZero63F690
// IDA: int sub_63F690()
//   dword_AC4E60 = 0;
//   dword_AC4E58 = 128;
//   dword_AC4E5C = 128;
//   return 128;
int InitZero63F690()
{
  return 128;
}

// IDA: 0x640520  proposal: InitGlobal640520
// IDA: void sub_640520()
//   dbl_AC4F00 = dbl_AC4EB0 / 60.0;
void InitGlobal640520()
{
}

// IDA: 0x640560  proposal: InitDegToRad640560
// IDA: void sub_640560()
//   dbl_AC4EE0 = 0.0174532925199433 * 45.0;
void InitDegToRad640560()
{
}

// IDA: 0x640580  proposal: InitScale60640580
// IDA: void sub_640580()
//   dbl_AC4EB8 = 0.0174532925199433 * 60.0;
void InitScale60640580()
{
}

// IDA: 0x6405A0  proposal: InitDegToRad6405A0
// IDA: void sub_6405A0()
//   dbl_AC4E88 = 0.0174532925199433 * 90.0;
void InitDegToRad6405A0()
{
}

// IDA: 0x6406C0  proposal: InitZero6406C0
// IDA: int sub_6406C0()
//   dword_AC4EF8 = 0;
//   dword_AC4EF0 = 128;
//   dword_AC4EF4 = 128;
//   return 128;
int InitZero6406C0()
{
  return 128;
}

// IDA: 0x6427C0  proposal: InitGlobal6427C0
// IDA: void sub_6427C0()
//   dbl_AC5008 = dbl_AC4F30 / 60.0;
void InitGlobal6427C0()
{
}

// IDA: 0x642800  proposal: InitDegToRad642800
// IDA: void sub_642800()
//   dbl_AC4FE8 = 0.0174532925199433 * 45.0;
void InitDegToRad642800()
{
}

// IDA: 0x642820  proposal: InitScale60642820
// IDA: void sub_642820()
//   dbl_AC4F38 = 0.0174532925199433 * 60.0;
void InitScale60642820()
{
}

// IDA: 0x642840  proposal: InitDegToRad642840
// IDA: void sub_642840()
//   dbl_AC4F10 = 0.0174532925199433 * 90.0;
void InitDegToRad642840()
{
}

// IDA: 0x642960  proposal: InitZero642960
// IDA: int sub_642960()
//   dword_AC5000 = 0;
//   dword_AC4FF8 = 128;
//   dword_AC4FFC = 128;
//   return 128;
int InitZero642960()
{
  return 128;
}

// IDA: 0x643EE0  proposal: InitGlobal643EE0
// IDA: void sub_643EE0()
//   dbl_AC5078 = dbl_AC5028 / 60.0;
void InitGlobal643EE0()
{
}

// IDA: 0x643F20  proposal: InitDegToRad643F20
// IDA: void sub_643F20()
//   dbl_AC5058 = 0.0174532925199433 * 45.0;
void InitDegToRad643F20()
{
}

// IDA: 0x643F40  proposal: InitScale60643F40
// IDA: void sub_643F40()
//   dbl_AC5030 = 0.0174532925199433 * 60.0;
void InitScale60643F40()
{
}

// IDA: 0x643F60  proposal: InitDegToRad643F60
// IDA: void sub_643F60()
//   dbl_AC5018 = 0.0174532925199433 * 90.0;
void InitDegToRad643F60()
{
}

// IDA: 0x644080  proposal: InitZero644080
// IDA: int sub_644080()
//   dword_AC5070 = 0;
//   dword_AC5068 = 128;
//   dword_AC506C = 128;
//   return 128;
int InitZero644080()
{
  return 128;
}

// IDA: 0x644A20  proposal: InitGlobal644A20
// IDA: void sub_644A20()
//   dbl_AC50E8 = dbl_AC5098 / 60.0;
void InitGlobal644A20()
{
}

// IDA: 0x644A60  proposal: InitDegToRad644A60
// IDA: void sub_644A60()
//   dbl_AC50C8 = 0.0174532925199433 * 45.0;
void InitDegToRad644A60()
{
}

// IDA: 0x644A80  proposal: InitScale60644A80
// IDA: void sub_644A80()
//   dbl_AC50A0 = 0.0174532925199433 * 60.0;
void InitScale60644A80()
{
}

// IDA: 0x644AA0  proposal: InitDegToRad644AA0
// IDA: void sub_644AA0()
//   dbl_AC5088 = 0.0174532925199433 * 90.0;
void InitDegToRad644AA0()
{
}

// IDA: 0x644BC0  proposal: InitZero644BC0
// IDA: int sub_644BC0()
//   dword_AC50E0 = 0;
//   dword_AC50D8 = 128;
//   dword_AC50DC = 128;
//   return 128;
int InitZero644BC0()
{
  return 128;
}

// IDA: 0x646AB0  proposal: InitGlobal646AB0
// IDA: void sub_646AB0()
//   dbl_AFA460 = dbl_AC6650 / 60.0;
void InitGlobal646AB0()
{
}

// IDA: 0x646AF0  proposal: InitDegToRad646AF0
// IDA: void sub_646AF0()
//   dbl_AFA408 = 0.0174532925199433 * 45.0;
void InitDegToRad646AF0()
{
}

// IDA: 0x646B10  proposal: InitScale60646B10
// IDA: void sub_646B10()
//   dbl_AFA260 = 0.0174532925199433 * 60.0;
void InitScale60646B10()
{
}

// IDA: 0x646B30  proposal: InitDegToRad646B30
// IDA: void sub_646B30()
//   dbl_AC5208 = 0.0174532925199433 * 90.0;
void InitDegToRad646B30()
{
}

// IDA: 0x646C50  proposal: InitZero646C50
// IDA: int sub_646C50()
//   dword_AFA428 = 0;
//   dword_AFA420 = 128;
//   dword_AFA424 = 128;
//   return 128;
int InitZero646C50()
{
  return 128;
}

// IDA: 0x6526B0  proposal: InitGlobal6526B0
// IDA: void sub_6526B0()
//   dbl_B049F8 = dbl_B048D8 / 60.0;
void InitGlobal6526B0()
{
}

// IDA: 0x6526F0  proposal: InitDegToRad6526F0
// IDA: void sub_6526F0()
//   dbl_B049D8 = 0.0174532925199433 * 45.0;
void InitDegToRad6526F0()
{
}

// IDA: 0x652710  proposal: InitScale60652710
// IDA: void sub_652710()
//   dbl_B048E8 = 0.0174532925199433 * 60.0;
void InitScale60652710()
{
}

// IDA: 0x652730  proposal: InitDegToRad652730
// IDA: void sub_652730()
//   dbl_B048A0 = 0.0174532925199433 * 90.0;
void InitDegToRad652730()
{
}

// IDA: 0x652850  proposal: InitZero652850
// IDA: int sub_652850()
//   dword_B049F0 = 0;
//   dword_B049E8 = 128;
//   dword_B049EC = 128;
//   return 128;
int InitZero652850()
{
  return 128;
}

// IDA: 0x658EB0  proposal: InitGlobal658EB0
// IDA: void sub_658EB0()
//   dbl_B04AC8 = dbl_B04A78 / 60.0;
void InitGlobal658EB0()
{
}

// IDA: 0x658EF0  proposal: InitDegToRad658EF0
// IDA: void sub_658EF0()
//   dbl_B04AA8 = 0.0174532925199433 * 45.0;
void InitDegToRad658EF0()
{
}

// IDA: 0x658F10  proposal: InitScale60658F10
// IDA: void sub_658F10()
//   dbl_B04A80 = 0.0174532925199433 * 60.0;
void InitScale60658F10()
{
}

// IDA: 0x658F30  proposal: InitDegToRad658F30
// IDA: void sub_658F30()
//   dbl_B04A40 = 0.0174532925199433 * 90.0;
void InitDegToRad658F30()
{
}

// IDA: 0x659050  proposal: InitZero659050
// IDA: int sub_659050()
//   dword_B04AC0 = 0;
//   dword_B04AB8 = 128;
//   dword_B04ABC = 128;
//   return 128;
int InitZero659050()
{
  return 128;
}

// IDA: 0x65A570  proposal: InitGlobal65A570
// IDA: void sub_65A570()
//   dbl_B04B48 = dbl_B04AF8 / 60.0;
void InitGlobal65A570()
{
}

// IDA: 0x65A5B0  proposal: InitDegToRad65A5B0
// IDA: void sub_65A5B0()
//   dbl_B04B28 = 0.0174532925199433 * 45.0;
void InitDegToRad65A5B0()
{
}

// IDA: 0x65A5D0  proposal: InitScale6065A5D0
// IDA: void sub_65A5D0()
//   dbl_B04B00 = 0.0174532925199433 * 60.0;
void InitScale6065A5D0()
{
}

// IDA: 0x65A5F0  proposal: InitDegToRad65A5F0
// IDA: void sub_65A5F0()
//   dbl_B04AD8 = 0.0174532925199433 * 90.0;
void InitDegToRad65A5F0()
{
}

// IDA: 0x65A710  proposal: InitZero65A710
// IDA: int sub_65A710()
//   dword_B04B40 = 0;
//   dword_B04B38 = 128;
//   dword_B04B3C = 128;
//   return 128;
int InitZero65A710()
{
  return 128;
}

// IDA: 0x65AF80  proposal: InitGlobal65AF80
// IDA: void sub_65AF80()
//   dbl_B04BC8 = dbl_B04B78 / 60.0;
void InitGlobal65AF80()
{
}

// IDA: 0x65AFC0  proposal: InitDegToRad65AFC0
// IDA: void sub_65AFC0()
//   dbl_B04BA8 = 0.0174532925199433 * 45.0;
void InitDegToRad65AFC0()
{
}

// IDA: 0x65AFE0  proposal: InitScale6065AFE0
// IDA: void sub_65AFE0()
//   dbl_B04B80 = 0.0174532925199433 * 60.0;
void InitScale6065AFE0()
{
}

// IDA: 0x65B000  proposal: InitDegToRad65B000
// IDA: void sub_65B000()
//   dbl_B04B58 = 0.0174532925199433 * 90.0;
void InitDegToRad65B000()
{
}

// IDA: 0x65B120  proposal: InitZero65B120
// IDA: int sub_65B120()
//   dword_B04BC0 = 0;
//   dword_B04BB8 = 128;
//   dword_B04BBC = 128;
//   return 128;
int InitZero65B120()
{
  return 128;
}

// IDA: 0x65D6F0  proposal: InitGlobal65D6F0
// IDA: void sub_65D6F0()
//   dbl_B04C90 = dbl_B04C40 / 60.0;
void InitGlobal65D6F0()
{
}

// IDA: 0x65D730  proposal: InitDegToRad65D730
// IDA: void sub_65D730()
//   dbl_B04C70 = 0.0174532925199433 * 45.0;
void InitDegToRad65D730()
{
}

// IDA: 0x65D750  proposal: InitScale6065D750
// IDA: void sub_65D750()
//   dbl_B04C48 = 0.0174532925199433 * 60.0;
void InitScale6065D750()
{
}

// IDA: 0x65D770  proposal: InitDegToRad65D770
// IDA: void sub_65D770()
//   dbl_B04C20 = 0.0174532925199433 * 90.0;
void InitDegToRad65D770()
{
}

// IDA: 0x65D890  proposal: InitZero65D890
// IDA: int sub_65D890()
//   dword_B04C88 = 0;
//   dword_B04C80 = 128;
//   dword_B04C84 = 128;
//   return 128;
int InitZero65D890()
{
  return 128;
}

// IDA: 0x65F360  proposal: InitGlobal65F360
// IDA: void sub_65F360()
//   dbl_B04D18 = dbl_B04CC8 / 60.0;
void InitGlobal65F360()
{
}

// IDA: 0x65F3A0  proposal: InitDegToRad65F3A0
// IDA: void sub_65F3A0()
//   dbl_B04CF8 = 0.0174532925199433 * 45.0;
void InitDegToRad65F3A0()
{
}

// IDA: 0x65F3C0  proposal: InitScale6065F3C0
// IDA: void sub_65F3C0()
//   dbl_B04CD0 = 0.0174532925199433 * 60.0;
void InitScale6065F3C0()
{
}

// IDA: 0x65F3E0  proposal: InitDegToRad65F3E0
// IDA: void sub_65F3E0()
//   dbl_B04CA8 = 0.0174532925199433 * 90.0;
void InitDegToRad65F3E0()
{
}

// IDA: 0x65F500  proposal: InitZero65F500
// IDA: int sub_65F500()
//   dword_B04D10 = 0;
//   dword_B04D08 = 128;
//   dword_B04D0C = 128;
//   return 128;
int InitZero65F500()
{
  return 128;
}

// IDA: 0x65F7D0  proposal: InitGlobal65F7D0
// IDA: void sub_65F7D0()
//   dbl_B04DF0 = dbl_B04D70 / 60.0;
void InitGlobal65F7D0()
{
}

// IDA: 0x65F810  proposal: InitDegToRad65F810
// IDA: void sub_65F810()
//   dbl_B04DC8 = 0.0174532925199433 * 45.0;
void InitDegToRad65F810()
{
}

// IDA: 0x65F830  proposal: InitScale6065F830
// IDA: void sub_65F830()
//   dbl_B04D80 = 0.0174532925199433 * 60.0;
void InitScale6065F830()
{
}

// IDA: 0x65F850  proposal: InitDegToRad65F850
// IDA: void sub_65F850()
//   dbl_B04D30 = 0.0174532925199433 * 90.0;
void InitDegToRad65F850()
{
}

// IDA: 0x65F970  proposal: InitZero65F970
// IDA: int sub_65F970()
//   dword_B04DE8 = 0;
//   dword_B04DE0 = 128;
//   dword_B04DE4 = 128;
//   return 128;
int InitZero65F970()
{
  return 128;
}

// IDA: 0x661CE0  proposal: InitGlobal661CE0
// IDA: void sub_661CE0()
//   dbl_B04E70 = dbl_B04E20 / 60.0;
void InitGlobal661CE0()
{
}

// IDA: 0x661D20  proposal: InitDegToRad661D20
// IDA: void sub_661D20()
//   dbl_B04E50 = 0.0174532925199433 * 45.0;
void InitDegToRad661D20()
{
}

// IDA: 0x661D40  proposal: InitScale60661D40
// IDA: void sub_661D40()
//   dbl_B04E28 = 0.0174532925199433 * 60.0;
void InitScale60661D40()
{
}

// IDA: 0x661D60  proposal: InitDegToRad661D60
// IDA: void sub_661D60()
//   dbl_B04E00 = 0.0174532925199433 * 90.0;
void InitDegToRad661D60()
{
}

// IDA: 0x661E80  proposal: InitZero661E80
// IDA: int sub_661E80()
//   dword_B04E68 = 0;
//   dword_B04E60 = 128;
//   dword_B04E64 = 128;
//   return 128;
int InitZero661E80()
{
  return 128;
}

// IDA: 0x663620  proposal: InitGlobal663620
// IDA: void sub_663620()
//   dbl_B05328 = dbl_B052A0 / 60.0;
void InitGlobal663620()
{
}

// IDA: 0x663660  proposal: InitDegToRad663660
// IDA: void sub_663660()
//   dbl_B05308 = 0.0174532925199433 * 45.0;
void InitDegToRad663660()
{
}

// IDA: 0x663680  proposal: InitScale60663680
// IDA: void sub_663680()
//   dbl_B052B0 = 0.0174532925199433 * 60.0;
void InitScale60663680()
{
}

// IDA: 0x6636A0  proposal: InitDegToRad6636A0
// IDA: void sub_6636A0()
//   dbl_B04E80 = 0.0174532925199433 * 90.0;
void InitDegToRad6636A0()
{
}

// IDA: 0x6637C0  proposal: InitZero6637C0
// IDA: int sub_6637C0()
//   dword_B05320 = 0;
//   dword_B05318 = 128;
//   dword_B0531C = 128;
//   return 128;
int InitZero6637C0()
{
  return 128;
}

// IDA: 0x664B40  proposal: InitGlobal664B40
// IDA: void sub_664B40()
//   dbl_B053A8 = dbl_B05358 / 60.0;
void InitGlobal664B40()
{
}

// IDA: 0x664B80  proposal: InitDegToRad664B80
// IDA: void sub_664B80()
//   dbl_B05388 = 0.0174532925199433 * 45.0;
void InitDegToRad664B80()
{
}

// IDA: 0x664BA0  proposal: InitScale60664BA0
// IDA: void sub_664BA0()
//   dbl_B05360 = 0.0174532925199433 * 60.0;
void InitScale60664BA0()
{
}

// IDA: 0x664BC0  proposal: InitDegToRad664BC0
// IDA: void sub_664BC0()
//   dbl_B05338 = 0.0174532925199433 * 90.0;
void InitDegToRad664BC0()
{
}

// IDA: 0x664CE0  proposal: InitZero664CE0
// IDA: int sub_664CE0()
//   dword_B053A0 = 0;
//   dword_B05398 = 128;
//   dword_B0539C = 128;
//   return 128;
int InitZero664CE0()
{
  return 128;
}

// IDA: 0x67C4D0  proposal: InitGlobal67C4D0
// IDA: void sub_67C4D0()
//   dbl_B05430 = dbl_B053E0 / 60.0;
void InitGlobal67C4D0()
{
}

// IDA: 0x67C510  proposal: InitDegToRad67C510
// IDA: void sub_67C510()
//   dbl_B05410 = 0.0174532925199433 * 45.0;
void InitDegToRad67C510()
{
}

// IDA: 0x67C530  proposal: InitScale6067C530
// IDA: void sub_67C530()
//   dbl_B053E8 = 0.0174532925199433 * 60.0;
void InitScale6067C530()
{
}

// IDA: 0x67C550  proposal: InitDegToRad67C550
// IDA: void sub_67C550()
//   dbl_B053C0 = 0.0174532925199433 * 90.0;
void InitDegToRad67C550()
{
}

// IDA: 0x67C670  proposal: InitZero67C670
// IDA: int sub_67C670()
//   dword_B05428 = 0;
//   dword_B05420 = 128;
//   dword_B05424 = 128;
//   return 128;
int InitZero67C670()
{
  return 128;
}

// IDA: 0x6830A0  proposal: InitGlobal6830A0
// IDA: void sub_6830A0()
//   dbl_B054C0 = dbl_B05460 / 60.0;
void InitGlobal6830A0()
{
}

// IDA: 0x6830E0  proposal: InitDegToRad6830E0
// IDA: void sub_6830E0()
//   dbl_B054A0 = 0.0174532925199433 * 45.0;
void InitDegToRad6830E0()
{
}

// IDA: 0x683100  proposal: InitScale60683100
// IDA: void sub_683100()
//   dbl_B05468 = 0.0174532925199433 * 60.0;
void InitScale60683100()
{
}

// IDA: 0x683120  proposal: InitDegToRad683120
// IDA: void sub_683120()
//   dbl_B05440 = 0.0174532925199433 * 90.0;
void InitDegToRad683120()
{
}

// IDA: 0x683240  proposal: InitZero683240
// IDA: int sub_683240()
//   dword_B054B8 = 0;
//   dword_B054B0 = 128;
//   dword_B054B4 = 128;
//   return 128;
int InitZero683240()
{
  return 128;
}

// IDA: 0x68CB60  proposal: InitGlobal68CB60
// IDA: void sub_68CB60()
//   dbl_B05578 = dbl_B05510 / 60.0;
void InitGlobal68CB60()
{
}

// IDA: 0x68CBA0  proposal: InitDegToRad68CBA0
// IDA: void sub_68CBA0()
//   dbl_B05550 = 0.0174532925199433 * 45.0;
void InitDegToRad68CBA0()
{
}

// IDA: 0x68CBC0  proposal: InitScale6068CBC0
// IDA: void sub_68CBC0()
//   dbl_B05518 = 0.0174532925199433 * 60.0;
void InitScale6068CBC0()
{
}

// IDA: 0x68CBE0  proposal: InitDegToRad68CBE0
// IDA: void sub_68CBE0()
//   dbl_B054E8 = 0.0174532925199433 * 90.0;
void InitDegToRad68CBE0()
{
}

// IDA: 0x68CD00  proposal: InitZero68CD00
// IDA: int sub_68CD00()
//   dword_B05570 = 0;
//   dword_B05568 = 128;
//   dword_B0556C = 128;
//   return 128;
int InitZero68CD00()
{
  return 128;
}

// IDA: 0x6911E0  proposal: InitGlobal6911E0
// IDA: void sub_6911E0()
//   dbl_B05618 = dbl_B055C8 / 60.0;
void InitGlobal6911E0()
{
}

// IDA: 0x691220  proposal: InitDegToRad691220
// IDA: void sub_691220()
//   dbl_B055F8 = 0.0174532925199433 * 45.0;
void InitDegToRad691220()
{
}

// IDA: 0x691240  proposal: InitScale60691240
// IDA: void sub_691240()
//   dbl_B055D0 = 0.0174532925199433 * 60.0;
void InitScale60691240()
{
}

// IDA: 0x691260  proposal: InitDegToRad691260
// IDA: void sub_691260()
//   dbl_B055A8 = 0.0174532925199433 * 90.0;
void InitDegToRad691260()
{
}

// IDA: 0x691380  proposal: InitZero691380
// IDA: int sub_691380()
//   dword_B05610 = 0;
//   dword_B05608 = 128;
//   dword_B0560C = 128;
//   return 128;
int InitZero691380()
{
  return 128;
}

// IDA: 0x692080  proposal: InitGlobal692080
// IDA: void sub_692080()
//   dbl_B056B8 = dbl_B05660 / 60.0;
void InitGlobal692080()
{
}

// IDA: 0x6920C0  proposal: InitDegToRad6920C0
// IDA: void sub_6920C0()
//   dbl_B05698 = 0.0174532925199433 * 45.0;
void InitDegToRad6920C0()
{
}

// IDA: 0x6920E0  proposal: InitScale606920E0
// IDA: void sub_6920E0()
//   dbl_B05668 = 0.0174532925199433 * 60.0;
void InitScale606920E0()
{
}

// IDA: 0x692100  proposal: InitDegToRad692100
// IDA: void sub_692100()
//   dbl_B05630 = 0.0174532925199433 * 90.0;
void InitDegToRad692100()
{
}

// IDA: 0x692220  proposal: InitZero692220
// IDA: int sub_692220()
//   dword_B056B0 = 0;
//   dword_B056A8 = 128;
//   dword_B056AC = 128;
//   return 128;
int InitZero692220()
{
  return 128;
}

// IDA: 0x693990  proposal: InitGlobal693990
// IDA: void sub_693990()
//   dbl_B05738 = dbl_B056E8 / 60.0;
void InitGlobal693990()
{
}

// IDA: 0x6939D0  proposal: InitDegToRad6939D0
// IDA: void sub_6939D0()
//   dbl_B05718 = 0.0174532925199433 * 45.0;
void InitDegToRad6939D0()
{
}

// IDA: 0x6939F0  proposal: InitScale606939F0
// IDA: void sub_6939F0()
//   dbl_B056F0 = 0.0174532925199433 * 60.0;
void InitScale606939F0()
{
}

// IDA: 0x693A10  proposal: InitDegToRad693A10
// IDA: void sub_693A10()
//   dbl_B056C8 = 0.0174532925199433 * 90.0;
void InitDegToRad693A10()
{
}

// IDA: 0x693B30  proposal: InitZero693B30
// IDA: int sub_693B30()
//   dword_B05730 = 0;
//   dword_B05728 = 128;
//   dword_B0572C = 128;
//   return 128;
int InitZero693B30()
{
  return 128;
}

// IDA: 0x695510  proposal: InitGlobal695510
// IDA: void sub_695510()
//   dbl_B057B8 = dbl_B05768 / 60.0;
void InitGlobal695510()
{
}

// IDA: 0x695550  proposal: InitDegToRad695550
// IDA: void sub_695550()
//   dbl_B05798 = 0.0174532925199433 * 45.0;
void InitDegToRad695550()
{
}

// IDA: 0x695570  proposal: InitScale60695570
// IDA: void sub_695570()
//   dbl_B05770 = 0.0174532925199433 * 60.0;
void InitScale60695570()
{
}

// IDA: 0x695590  proposal: InitDegToRad695590
// IDA: void sub_695590()
//   dbl_B05748 = 0.0174532925199433 * 90.0;
void InitDegToRad695590()
{
}

// IDA: 0x6956B0  proposal: InitZero6956B0
// IDA: int sub_6956B0()
//   dword_B057B0 = 0;
//   dword_B057A8 = 128;
//   dword_B057AC = 128;
//   return 128;
int InitZero6956B0()
{
  return 128;
}

// IDA: 0x696D50  proposal: InitGlobal696D50
// IDA: void sub_696D50()
//   dbl_B07778 = dbl_B057E8 / 60.0;
void InitGlobal696D50()
{
}

// IDA: 0x696D90  proposal: InitDegToRad696D90
// IDA: void sub_696D90()
//   dbl_B07758 = 0.0174532925199433 * 45.0;
void InitDegToRad696D90()
{
}

// IDA: 0x696DB0  proposal: InitScale60696DB0
// IDA: void sub_696DB0()
//   dbl_B057F0 = 0.0174532925199433 * 60.0;
void InitScale60696DB0()
{
}

// IDA: 0x696DD0  proposal: InitDegToRad696DD0
// IDA: void sub_696DD0()
//   dbl_B057C8 = 0.0174532925199433 * 90.0;
void InitDegToRad696DD0()
{
}

// IDA: 0x696EF0  proposal: InitZero696EF0
// IDA: int sub_696EF0()
//   dword_B07770 = 0;
//   dword_B07768 = 128;
//   dword_B0776C = 128;
//   return 128;
int InitZero696EF0()
{
  return 128;
}

// IDA: 0x69EA70  proposal: InitGlobal69EA70
// IDA: void sub_69EA70()
//   dbl_B07830 = dbl_B077E0 / 60.0;
void InitGlobal69EA70()
{
}

// IDA: 0x69EAB0  proposal: InitDegToRad69EAB0
// IDA: void sub_69EAB0()
//   dbl_B07810 = 0.0174532925199433 * 45.0;
void InitDegToRad69EAB0()
{
}

// IDA: 0x69EAD0  proposal: InitScale6069EAD0
// IDA: void sub_69EAD0()
//   dbl_B077E8 = 0.0174532925199433 * 60.0;
void InitScale6069EAD0()
{
}

// IDA: 0x69EAF0  proposal: InitDegToRad69EAF0
// IDA: void sub_69EAF0()
//   dbl_B077C0 = 0.0174532925199433 * 90.0;
void InitDegToRad69EAF0()
{
}

// IDA: 0x69EC10  proposal: InitZero69EC10
// IDA: int sub_69EC10()
//   dword_B07828 = 0;
//   dword_B07820 = 128;
//   dword_B07824 = 128;
//   return 128;
int InitZero69EC10()
{
  return 128;
}

// IDA: 0x6A4390  proposal: InitGlobal6A4390
// IDA: void sub_6A4390()
//   dbl_B078A0 = dbl_B07850 / 60.0;
void InitGlobal6A4390()
{
}

// IDA: 0x6A43D0  proposal: InitDegToRad6A43D0
// IDA: void sub_6A43D0()
//   dbl_B07880 = 0.0174532925199433 * 45.0;
void InitDegToRad6A43D0()
{
}

// IDA: 0x6A43F0  proposal: InitScale606A43F0
// IDA: void sub_6A43F0()
//   dbl_B07858 = 0.0174532925199433 * 60.0;
void InitScale606A43F0()
{
}

// IDA: 0x6A4410  proposal: InitDegToRad6A4410
// IDA: void sub_6A4410()
//   dbl_B07840 = 0.0174532925199433 * 90.0;
void InitDegToRad6A4410()
{
}

// IDA: 0x6A4530  proposal: InitZero6A4530
// IDA: int sub_6A4530()
//   dword_B07898 = 0;
//   dword_B07890 = 128;
//   dword_B07894 = 128;
//   return 128;
int InitZero6A4530()
{
  return 128;
}

// IDA: 0x6A4A50  proposal: InitGlobal6A4A50
// IDA: void sub_6A4A50()
//   dbl_B0B398 = dbl_B07DE0 / 60.0;
void InitGlobal6A4A50()
{
}

// IDA: 0x6A4A90  proposal: InitDegToRad6A4A90
// IDA: void sub_6A4A90()
//   dbl_B0B318 = 0.0174532925199433 * 45.0;
void InitDegToRad6A4A90()
{
}

// IDA: 0x6A4AB0  proposal: InitScale606A4AB0
// IDA: void sub_6A4AB0()
//   dbl_B07DE8 = 0.0174532925199433 * 60.0;
void InitScale606A4AB0()
{
}

// IDA: 0x6A4AD0  proposal: InitDegToRad6A4AD0
// IDA: void sub_6A4AD0()
//   dbl_B07BB8 = 0.0174532925199433 * 90.0;
void InitDegToRad6A4AD0()
{
}

// IDA: 0x6A4BF0  proposal: InitZero6A4BF0
// IDA: int sub_6A4BF0()
//   dword_B0B390 = 0;
//   dword_B0B388 = 128;
//   dword_B0B38C = 128;
//   return 128;
int InitZero6A4BF0()
{
  return 128;
}

// IDA: 0x6AC9A0  proposal: InitGlobal6AC9A0
// IDA: void sub_6AC9A0()
//   dbl_B0B590 = dbl_B0B540 / 60.0;
void InitGlobal6AC9A0()
{
}

// IDA: 0x6AC9E0  proposal: InitDegToRad6AC9E0
// IDA: void sub_6AC9E0()
//   dbl_B0B570 = 0.0174532925199433 * 45.0;
void InitDegToRad6AC9E0()
{
}

// IDA: 0x6ACA00  proposal: InitScale606ACA00
// IDA: void sub_6ACA00()
//   dbl_B0B548 = 0.0174532925199433 * 60.0;
void InitScale606ACA00()
{
}

// IDA: 0x6ACA20  proposal: InitDegToRad6ACA20
// IDA: void sub_6ACA20()
//   dbl_B0B520 = 0.0174532925199433 * 90.0;
void InitDegToRad6ACA20()
{
}

// IDA: 0x6ACB40  proposal: InitZero6ACB40
// IDA: int sub_6ACB40()
//   dword_B0B588 = 0;
//   dword_B0B580 = 128;
//   dword_B0B584 = 128;
//   return 128;
int InitZero6ACB40()
{
  return 128;
}

// IDA: 0x6AEF40  proposal: InitGlobal6AEF40
// IDA: void sub_6AEF40()
//   dbl_B0B628 = dbl_B0B5C0 / 60.0;
void InitGlobal6AEF40()
{
}

} // namespace gamemd
