#include "named_free_decls.hpp"

// Auto-generated by gen_missing_stubs.py
// 5 stubs
// DO NOT EDIT MANUALLY

#pragma warning(disable: 4100 4189)

char __fastcall ClipLine(int*, int*, int*)
{
    return 0;
}

int __cdecl GameFrameCheck(void)
{
    return 0;
}

bool __cdecl GameFrameLoop(void)
{
    return 0;
}

int __cdecl MainGameFrame(void)
{
    return 0;
}

int __fastcall SearchMIXFile(char*, char)
{
    return 0;
}

