// Auto-generated by tools/task17_generate.py
// Module: misc | Functions: 22
// Regenerate: python tools/task17_generate.py

#include <cstdint>
#include <cstddef>

// IDA-named globals referenced (extern stubs)
extern int dword_B1D4D8;

namespace gamemd {

// IDA: 0x403470  proposal: EndMixer
// IDA: int __fastcall sub_403470(int a1, int a2)
//   return EndBufferMixer((int *)(a1 + 104), a2);
int EndMixer(int a0, int a1) // fastcall
{
  return 0;
}

// IDA: 0x403480  proposal: RequestMixer
// IDA: int __fastcall sub_403480(int a1, int a2)
//   return RequestBufferMixer((unsigned int *)(a1 + 104), a2);
int RequestMixer(int a0, int a1) // fastcall
{
  return 0;
}

// IDA: 0x4035B0  proposal: GetAudio
// IDA: int __fastcall sub_4035B0(int a1, int *a2)
//   int result; // eax
//   result = AudioQueue::GetNext((int *)(a1 + 248));
//   *a2 = result;
//   return result;
int GetAudio(int a0, int a1) // fastcall
{
  return 0;
}

// IDA: 0x4036C0  proposal: FindAudio
// IDA: int __fastcall sub_4036C0(int a1, int a2)
//   int v3; // eax
//   int v4; // esi
//   v3 = AudioQueue::FindBestChannel(a1, 1);
//   v4 = v3;
//   if ( v3 )
//   sub_402440(v3, a2);
//   return v4;
int FindAudio(int a0, int a1) // fastcall
{
  return 0;
}

// IDA: 0x406520  proposal: LoadVocFromINIHelper
// IDA: void __fastcall sub_406520(int a1, int a2)
//   *(_DWORD *)(a1 + 312) = a2;
void LoadVocFromINIHelper(int a0, int a1) // fastcall
{
}

// IDA: 0x406530  proposal: LoadVocFromINIHelper406530
// IDA: void __fastcall sub_406530(int a1, int a2)
//   *(_DWORD *)(a1 + 316) = a2;
void LoadVocFromINIHelper406530(int a0, int a1) // fastcall
{
}

// IDA: 0x406540  proposal: LoadVocFromINIHelper406540
// IDA: void __fastcall sub_406540(int a1, int a2)
//   *(_DWORD *)(a1 + 64) = a2;
void LoadVocFromINIHelper406540(int a0, int a1) // fastcall
{
}

// IDA: 0x406550  proposal: EndAudio
// IDA: int __fastcall sub_406550(int a1, int a2)
//   _DWORD *v2; // esi
//   v2 = (_DWORD *)(a1 + 24);
//   EndBufferMixer((int *)(a1 + 24), a2);
//   return AudioMixer::PlaySample(v2);
int EndAudio(int a0, int a1) // fastcall
{
  return 0;
}

// IDA: 0x4065C0  proposal: LoadVocFromINIHelper4065C0
// IDA: void __fastcall sub_4065C0(int a1, int a2)
//   *(_DWORD *)(a1 + 20) = a2;
void LoadVocFromINIHelper4065C0(int a0, int a1) // fastcall
{
}

// IDA: 0x4065D0  proposal: LoadVocFromINIHelper4065D0
// IDA: void __fastcall sub_4065D0(int a1, int a2)
//   *(_DWORD *)(a1 + 72) = a2;
void LoadVocFromINIHelper4065D0(int a0, int a1) // fastcall
{
}

// IDA: 0x4065E0  proposal: LoadVocFromINIHelper4065E0
// IDA: void __fastcall sub_4065E0(int a1, int a2)
//   *(_DWORD *)(a1 + 80) = a2;
void LoadVocFromINIHelper4065E0(int a0, int a1) // fastcall
{
}

// IDA: 0x406620  proposal: LoadVocFromINIHelper406620
// IDA: int __fastcall sub_406620(int a1, int a2)
//   int result; // eax
//   if ( a2 <= 100 )
//   {
//   if ( a2 >= 0 )
//   {
//   *(_DWORD *)(a1 + 104) = a2;
//   }
//   else
//   {
//   *(_DWORD *)(a1 + 104) = 0;
//   return 0;
//   }
//   }
//   else
//   {
//   *(_DWORD *)(a1 + 104) = 100;
//   return 100;
//   }
//   return result;
int LoadVocFromINIHelper406620(int a0, int a1) // fastcall
{
  return 0;
}

// IDA: 0x406640  proposal: LoadVocFromINIHelper406640
// IDA: void __fastcall sub_406640(int a1, int a2)
//   *(_DWORD *)(a1 + 76) = a2;
void LoadVocFromINIHelper406640(int a0, int a1) // fastcall
{
}

// IDA: 0x406EA0  proposal: UpdateAudio
// IDA: int sub_406EA0()
//   if ( g_Audio_Enabled )
//   AudioQueue::DeactivateAllMatching((int)g_Audio_Enabled, 1);
//   AudioStream::UpdateTimers();
//   return sub_751040();
int UpdateAudio()
{
  return 0;
}

// IDA: 0x406EC0  proposal: UpdateAudio406EC0
// IDA: int sub_406EC0()
//   int i; // esi
//   int result; // eax
//   sub_751080();
//   result = AudioStream::UpdateCountdowners();
//   if ( g_Audio_Enabled )
//   {
//   result = AudioQueue::GetNext((int *)g_Audio_Enabled + 62);
//   for ( i = result; result; i = result )
//   {
//   if ( (*(_BYTE *)(i + 164) & 4) = 0 && *(_DWORD *)(i + 12) == 1 )
//   result = AudioChannel::ActivatePlay((_DWORD *)i);
//   if ( i )
//   break;
//   result = AudioQueue::GetNextAlt((int *)i);
//   }
//   }
//   return result;
int UpdateAudio406EC0()
{
  return 0;
}

// IDA: 0x406EE0  proposal: StopAudio406EE0
// IDA: int sub_406EE0()
//   if ( g_Audio_Enabled )
//   AudioQueue::StopAllVoices((int)g_Audio_Enabled, 1);
//   AudioStream::CleanupChannels();
//   return AudioQueue::HaltVoices();
int StopAudio406EE0()
{
  return 0;
}

// IDA: 0x406F00  proposal: UpdateAudio406F00
// IDA: int sub_406F00()
//   int result; // eax
//   if ( !ChronoScreen::IsActive() )
//   {
//   if ( g_Audio_Enabled )
//   AudioQueue::DeactivateAllMatching((int)g_Audio_Enabled, 1);
//   AudioStream::UpdateTimers();
//   sub_751040();
//   }
//   result = AudioFrame::CounterInc();
//   if ( dword_B1D4D8 )
//   return AudioFrame::ProcessAudioFrame((int)dword_B1D4D8);
//   return result;
int UpdateAudio406F00()
{
  return 0;
}

// IDA: 0x406F40  proposal: UpdateAudio406F40
// IDA: int sub_406F40()
//   int i; // esi
//   int result; // eax
//   ____F_m_badAllocExceptionPtr___ExceptionPtr__0V__shared_ptr___ExceptionPtr___tr1_std__A__YAXXZ_1();
//   AudioMixer::Pump();
//   sub_751080();
//   result = AudioStream::UpdateCountdowners();
//   if ( g_Audio_Enabled )
//   {
//   result = AudioQueue::GetNext((int *)g_Audio_Enabled + 62);
//   for ( i = result; result; i = result )
//   {
//   if ( (*(_BYTE *)(i + 164) & 4) = 0 && *(_DWORD *)(i + 12) == 1 )
//   result = AudioChannel::ActivatePlay((_DWORD *)i);
//   if ( i )
//   break;
//   result = AudioQueue::GetNextAlt((int *)i);
//   }
//   }
//   return result;
int UpdateAudio406F40()
{
  return 0;
}

// IDA: 0x4CCA70  proposal: LocomotionClass::SetMember1
// IDA: void __thiscall sub_4CCA70(_DWORD *this)
//   *this = &FlyLocomotionClass::`vftable';
//   *(this + 1) = &FlyLocomotionClass::`vftable';
//   LocomotionClass::Construct(this);
void LocomotionClass_SetMember1(void* _this) // thiscall
{
}

// IDA: 0x513D00  proposal: LocomotionClass::SetMember1513D00
// IDA: void __thiscall sub_513D00(_DWORD *this)
//   *this = &HoverLocomotionClass::`vftable';
//   *(this + 1) = &HoverLocomotionClass::`vftable';
//   LocomotionClass::Construct(this);
void LocomotionClass_SetMember1513D00(void* _this) // thiscall
{
}

// IDA: 0x5AFF50  proposal: LocomotionClass::SetMember15AFF50
// IDA: void __thiscall sub_5AFF50(_DWORD *this)
//   *this = &MechLocomotionClass::`vftable';
//   *(this + 1) = &MechLocomotionClass::`vftable';
//   LocomotionClass::Construct(this);
void LocomotionClass_SetMember15AFF50(void* _this) // thiscall
{
}

// IDA: 0x661F30  proposal: LocomotionClass::SetMember1661F30
// IDA: void __thiscall sub_661F30(_DWORD *this)
//   *this = &RocketLocomotionClass::`vftable';
//   *(this + 1) = &RocketLocomotionClass::`vftable';
//   LocomotionClass::Construct(this);
void LocomotionClass_SetMember1661F30(void* _this) // thiscall
{
}

} // namespace gamemd
