#!/usr/bin/env python3
"""ida_export_c.py — 按类从 IDA 导出反编译 .c 文件（路线图 ④ LLM 命名轮输入）。

当前质量分层（2026-09-03，T14+struct 重建后）：
  T1 已定型核心 — 82 类 1,062 函数 this 已定型 + 69 类 struct 布局正确，
     成员以语义名渲染（GetTarget → this->focus）——可直接用于 LLM 命名
  T2 已定型但含 gap 成员 — struct 存在但部分区域是 __pad/gapN
  T3 未定型 — 其余 ~18K 函数（裸 int this / 纯 v1 v2 局部变量）

本工具只导出 T1/T2（--class 指定类），保证导出物有类上下文。

用法:
  python tools/type_infer/ida_export_c.py --class TechnoClass
  python tools/type_infer/ida_export_c.py --all          # 全部 82 个已定型类
输出: decompile-results/exports/<Class>.c
"""
import argparse
import json
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(os.path.dirname(_HERE))
sys.path.insert(0, _HERE)

from ida_apply_t14 import call  # noqa: E402
from t14_rollout import _norm_addr, _RE_CLASS  # noqa: E402

OUT_DIR = os.path.join(PROJ, "decompile-results", "exports")
STRUCT_CLASSES = os.path.join(PROJ, ".omo", "t14_struct_classes.json")


def export_class(cls: str) -> str:
    """导出一个类的全部 `Class::`/`Class_` 函数, 返回输出路径。"""
    r = call("func_query", {"queries": [
        {"name_regex": f"^{re.escape(cls)}(_|::)", "count": 0, "sort_by": "addr"}]})
    d = r[0] if isinstance(r, list) else r
    fns = d.get("data", [])
    if not fns:
        return ""
    # 原型+代码经 export_funcs 批量取（每响应 10 条上限）
    protos = {}
    addrs = [f["addr"] for f in fns]
    for i in range(0, len(addrs), 10):
        p = call("export_funcs", {"addrs": addrs[i:i + 10], "format": "json"})
        for f in p.get("functions", []):
            na = _norm_addr(f["addr"])
            if na:
                protos[na] = f
    parts = [f"// {cls} — IDA decompiled export ({len(fns)} functions)",
             "// generated by tools/type_infer/ida_export_c.py; T14-typed this",
             ""]
    typed = untyped = 0
    for f in fns:
        na = _norm_addr(f["addr"])
        e = protos.get(na) or {}
        code = (e.get("code") or "").strip()
        if not code:
            continue
        if f"{cls} *this" in code.split("\n")[0]:
            typed += 1
        else:
            untyped += 1
        parts.append("// " + "-" * 70)
        parts.append(f"// {e.get('addr', f['addr'])} {e.get('name', f.get('name',''))}")
        parts.append(code)
        parts.append("")
    os.makedirs(OUT_DIR, exist_ok=True)
    out = os.path.join(OUT_DIR, f"{cls}.c")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts))
    return f"{out} ({typed} typed / {untyped} untyped / {len(fns)} total)"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--class", dest="cls", default="")
    ap.add_argument("--all", action="store_true")
    args = ap.parse_args()

    if args.cls:
        r = export_class(args.cls)
        print(r or f"{args.cls}: 无匹配函数")
        return
    classes = json.load(open(STRUCT_CLASSES, encoding="utf-8"))
    ok = 0
    for c in classes:
        r = export_class(c)
        if r:
            ok += 1
            print(r, flush=True)
    print(f"导出完成: {ok}/{len(classes)} 类 → {OUT_DIR}")


if __name__ == "__main__":
    main()
