// Auto-generated sub_* function stubs
// 1 stubs from IDA decompiled pseudocode
// Generated by tools/gen_sub_stubs.py

#include <cstdint>

namespace gamemd {

// 0x00664750 (96 bytes)
char Debug_Send_664750() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/00664750.json)
    // Size: 96 bytes, calling convention: thiscall
    // IDA pseudocode:
//   char __thiscall sub_664750 ( unsigned __int8 *this, char a2 ) { int v2 ; // eax _BYTE v4[340] ; // [esp+4h] [ebp-154h] BYREF memset ( v4 , 0 , 338 ) ; v2 = * ( this + 24 ) ; if ( ( _BYTE ) v2 ) { v4 [ 0 ] = 6 ; v4 [ 1 ] = a2 ; Debug::Log ( ) ; LOBYTE ( v2 ) = Network::SendPacket ( ( int ) g_NetworkManager , ( int ) v4 , 338 , 1u ) ; } return v2 ; }
    return 0;
}

} // namespace gamemd