#!/usr/bin/env python3
"""C++ code generator for hook DLL — reads functions.json, generates per-function shadow stubs.

Generates:
  - gen/hooks_gen.cpp: per-function DEFINE_HOOK shadow stubs
  - gen/hook_exports.def: exported function names for Syringe (when no .syhks00)
"""
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
JSON_PATH  = os.path.join(SCRIPT_DIR, "functions.json")
OUT_DIR    = os.path.join(SCRIPT_DIR, "gen")

def sanitize_name(name):
    """Convert ClassName::Method to a valid C identifier for export."""
    return name.replace('::', '_').replace('@', '_').replace('<', '_').replace('>', '_')

def load_json():
    with open(JSON_PATH, 'r') as f:
        return json.load(f)

def generate_hooks_cpp(functions, only_completed=False):
    """Generate DEFINE_HOOK stubs for shadow execution."""
    lines = [
        '// Auto-generated by codegen.py — DO NOT EDIT',
        '#include <windows.h>',
        '#include "YRpp/Syringe.h"',
        '#include "tls_storage.h"',
        '#include "shadow_txn.h"',
        '',
        '// PostProcStub — reached via stack hijack after original function RETurns',
        'extern "C" void PostProcStub();',
        '',
    ]

    count = 0
    for fn in functions:
        if only_completed and not fn.get('hook', {}).get('completed', False):
            continue
        if not fn.get('hook', {}).get('is_hookable', False):
            continue

        addr = fn['address']  # e.g., "0x52BA60"
        addr_hex = addr.lstrip('0x').upper()  # "52BA60"
        name = fn['name']
        safe = sanitize_name(name)
        conv = fn['call']['convention']
        is_member = fn['call']['is_member']
        class_name = fn['call']['class_name'] or ''

        # DEFINE_HOOK expands to: extern "C" DWORD __cdecl Name(REGISTERS *R)
        # The { after the macro opens the function body
        lines.append(f'// {name} @ {addr} ({conv})')
        lines.append(f'DEFINE_HOOK({addr_hex}, {safe}_shadow, 5)')
        lines.append(f'{{')
        lines.append(f'    GET(REGISTERS*, pRegs, ESP); // for debug: R is already available')
        lines.append(f'    auto* slot = shadow::GetSlot();')
        lines.append(f'')
        lines.append(f'    shadow::ShadowTransaction txn;')
        lines.append(f'    txn.Begin();')
        lines.append(f'')
        lines.append(f'    // TODO: extract params and call RE version')
        if is_member and class_name:
            lines.append(f'    // auto* pThis = ({class_name}*)R->ECX;')
            lines.append(f'    // auto re_result = pThis->Method(...);')
        else:
            lines.append(f'    // auto re_result = RE_{safe}(...);')
        lines.append(f'    int re_result = 0; // placeholder')
        lines.append(f'')
        lines.append(f'    txn.End();')
        lines.append(f'')
        lines.append(f'    // Store RE result + hijack return address for post-process comparison')
        lines.append(f'    slot->re_result_eax = static_cast<uint32_t>(re_result);')
        lines.append(f'    slot->re_result_edx = 0;')
        lines.append(f'    slot->original_ret_addr = *(uint32_t*)(R->ESP);')
        lines.append(f'    *(uint32_t*)(R->ESP) = (uint32_t)&PostProcStub;')
        lines.append(f'')
        lines.append(f'    return 0; // let original function run')
        lines.append(f'}}')
        lines.append(f'')
        count += 1

    lines.append(f'// Total shadow hooks: {count}')
    return '\n'.join(lines), count

def main():
    if not os.path.exists(JSON_PATH):
        print(f"ERROR: {JSON_PATH} not found. Run ida_extract.py first in IDA.")
        sys.exit(1)

    os.makedirs(OUT_DIR, exist_ok=True)

    data = load_json()
    functions = data['functions']
    print(f"Loaded {len(functions)} functions")

    # Generate hooks.cpp
    hooks_cpp, count = generate_hooks_cpp(functions, only_completed=False)
    hooks_path = os.path.join(OUT_DIR, 'hooks_gen.cpp')
    with open(hooks_path, 'w') as f:
        f.write(hooks_cpp)
    print(f"Generated {hooks_path} ({count} stubs)")

if __name__ == '__main__':
    main()
