// AUTO-GENERATED by tools/gen_gap2_stubs.py -- DO NOT EDIT MANUALLY.
// Gap 2 stub registry: IDA-confirmed no_cpp_body functions (annotation-only).
// Documents address<->symbol mapping for tools/audit_consistency.py.
// Wrapped in `#if 0` so this header is a no-op if ever #included (NEVER compiled).
#ifndef GAMEMD_UI_STUB_DECLS_HPP
#define GAMEMD_UI_STUB_DECLS_HPP
#if 0  // annotation-only; never compiled
// 0x433F50 [stub]
int MessageListClass::CountCharsInWidth(uint16_t* p0, int p1, int p2, int p3);
// 0x4884A0 [stub]
int CheckListClass::GetItem(int p0, int* p1, int p2);
// 0x4886C0 [stub]
char CheckListClass::SelectItem(int p0);
// 0x4886D0 [stub]
int CheckListClass::SetFocus(unsigned int p0);
// 0x4886E0 [stub]
unsigned int * CheckListClass::QueryInterface(char p0);
// 0x4B4FB0 [stub]
int DropListClass::SetFocus(int* p0);
// 0x4B4FF0 [stub]
int DropListClass::KillFocus();
// 0x4B5010 [stub]
int DropListClass::GetItemData();
// 0x4B50A0 [stub]
char DropListClass::AddItem();
// 0x4B50C0 [stub]
__int16 DropListClass::Open(char p0, int* p1, char* p2);
// 0x4B54E0 [stub]
int DropListClass::RemoveItem(int p0, int p1);
// 0x4B5530 [stub]
void DropListClass::OnKeyDown(int* p0);
// 0x4B55B0 [stub]
int DropListClass::ScrollUp();
// 0x4B55D0 [stub]
int DropListClass::ScrollDown(int p0);
// 0x4B55F0 [stub]
_DWORD * DropListClass::QueryInterface(char p0);
// 0x4C30B0 [stub]
int DropListClass::Constructor();
// 0x4C30E0 [stub]
int DropListClass::SelectItem(int* p0, int p1);
// 0x4C3110 [stub]
int DropListClass::GetItem(int p0);
// 0x4C3190 [stub]
int DropListClass::GetCount(unsigned int p0, int* p1, int p2);
// 0x4C32A0 [stub]
int DropListClass::GetSelected();
// 0x4C32E0 [stub]
_DWORD * DropListClass::GetItemText(int* p0);
// 0x4C3420 [stub]
char DropListClass::SetItemText(int p0);
// 0x4C3570 [stub]
__int16 DropListClass::Close();
// 0x4C93D0 [stub]
_DWORD * ProgressTimer::GetValue(int* p0);
// 0x536050 [stub]
wchar_t * SelectTeamCommand::Read();
// 0x536080 [stub]
int SelectTeamCommand::Do(int p0);
// 0x536140 [stub]
wchar_t * AddTeamCommand::Read();
// 0x536170 [stub]
int AddTeamCommand::Do(int p0);
// 0x536230 [stub]
wchar_t * CenterTeamCommand::Read();
// 0x536260 [stub]
int CenterTeamCommand::Do(int p0);
// 0x536320 [stub]
wchar_t * TauntCommandClass::Read();
// 0x536350 [stub]
char TauntCommandClass::Do(int p0);
// 0x556EB0 [stub]
void CheckListClass::initList();
// 0x556EE0 [stub]
unsigned int CheckListClass::addItem(int p0);
// 0x557090 [stub]
char CheckListClass::removeItem(int p0, int* p1);
// 0x557140 [stub]
int CheckListClass::checkItem(int* p0);
// 0x5571C0 [stub]
_DWORD * CheckListClass::toggleItem(char p0);
// 0x557570 [stub]
int CheckListClass::RemoveItem(int p0, int p1);
// 0x557800 [stub]
int ListClass::Destru_vt43(int p0);
// 0x557A20 [stub]
char CheckListClass::SetItemState(int p0);
// 0x557A70 [stub]
char CheckListClass::OnKeyUp(int p0);
// 0x557B00 [stub]
int CheckListClass::GetItemCount();
// 0x557B10 [stub]
char CheckListClass::vt[19](char p0, int p1, int* p2);
// 0x557B70 [stub]
int CheckListClass::OnKeyDown(int p0);
// 0x557CB0 [stub]
int CheckListClass::GetItemData();
// 0x557D10 [stub]
int CheckListClass::KillFocus(int p0);
// 0x557D20 [stub]
_DWORD * ListClass::Destru_vt50(int p0, int p1, int p2, int p3, int p4);
// 0x557E60 [stub]
_DWORD * CheckListClass::HitTest(int p0);
// 0x557EB0 [stub]
int CheckListClass::Draw(int p0);
// 0x557F00 [stub]
int CheckListClass::OnDblClick();
// 0x557FB0 [stub]
int CheckListClass::ScrollDown(int p0);
// 0x557FD0 [stub]
void CheckListClass::AddItem();
// 0x558060 [stub]
_BYTE * ListClass::Destru_vt00(char p0);
// 0x558130 [stub]
_DWORD * CheckListClass::drawList(char p0);
// 0x5581E0 [stub]
void CheckListClass::scrollList();
// 0x558210 [stub]
unsigned int CheckListClass::selectItem(int p0);
// 0x5583C0 [stub]
char CheckListClass::clearList(int p0, int* p1);
// 0x558470 [stub]
int CheckListClass::getItemCount(int* p0);
// 0x5D3A60 [stub]
void MessageListClass::Init(int p0, int p1, int p2, int p3, int p4, int p5, int p6, char p7, int p8, int p9, int p10);
// 0x5D3BA0 [stub]
int MessageListClass::AddMessage(int* p0, int p1, int* p2, int p3, int p4, int p5, char p6);
// 0x60CF00 [stub]
_DWORD * Control::CreateControlDialog();
// 0x623840 [stub]
int ListBox::Clear();
// 0x68C710 [stub]
char * FontClass::InitMetrics(char* p0, int p1, int p2, int p3, int p4, char p5);
// 0x6969C0 [stub]
HWND ListBox::SetCustomEntry();
// 0x6B1DC0 [stub]
__int64 SliderClass::OnClick(int p0);
// 0x6B1E50 [stub]
int SliderClass::Draw(int p0);
// 0x6B1F50 [stub]
int SliderClass::SetValue(unsigned int p0, int* p1, int p2);
// 0x6B2000 [stub]
int SliderClass::OnTrack(int p0);
// 0x6B2040 [stub]
int SliderClass::OnRelease(int p0);
// 0x6B2070 [stub]
int SliderClass::HitTest();
// 0x6B20F0 [stub]
int SliderClass::GetRange(int p0);
// 0x6B2160 [stub]
char SliderClass::SetRange(char p0, int p1, int p2);
// 0x724C80 [stub]
int ToolTipClass::seek(int p0);
// 0x724C90 [stub]
char ToolTipClass::addRef(int p0);
// 0x724CD0 [stub]
char ToolTipClass::readString(int p0, int* p1);
// 0x724D80 [stub]
void ToolTipClass::writeString();
// 0x724DB0 [stub]
int ToolTipClass::seekString(int* p0);
// 0x724DF0 [stub]
unsigned int ToolTipClass::setString(int p0);
// 0x724E10 [stub]
char ToolTipClass::release(int p0, int* p1);
// 0x724EC0 [stub]
int ToolTipClass::read(int* p0);
// 0x724EF0 [stub]
_DWORD * ToolTipClass::compareString(char p0);
// 0x724FA0 [stub]
bool CommandClass::executeAction(int* p0);
// 0x724FC0 [stub]
size_t CommandClass::BinarySearchAction();
// 0x72A440 [stub]
int MessageListClass::clearMessages(int p0, int p1, int p2, int p3, int p4);
#endif  // 0
#endif  // GAMEMD_UI_STUB_DECLS_HPP
