// Auto-generated sub_* function stubs
// 1 stubs from IDA decompiled pseudocode
// Generated by tools/gen_sub_stubs.py

#include <cstdint>

namespace gamemd {

// 0x004E2A50 (147 bytes)
int ControlClass_Construct_4E2A50() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/004E2A50.json)
    // Size: 147 bytes, calling convention: thiscall
    // IDA pseudocode:
//   int __thiscall sub_4E2A50 ( int this, int a2, int a3, int a4, int a5, int a6 ) { int v7 ; // ecx int v8 ; // eax ControlClass::Construct ( ( _DWORD * ) this , a2 , a3 , a4 , a5 , a6 , 7 , 1 ) ; v7 = * ( _DWORD * ) ( this + 48 ) ; * ( _DWORD * ) this = & GaugeClass::vftable' ; if ( v7 != 255 ) { * ( _DWORD * ) ( this + 48 ) = 255 ; VectorClass_ptr_ConvertClass::MarkDirty ( ( _BYTE * ) this ) ; } v8 = 0 ; if ( * ( int * ) ( this + 48 ) < 0 ) v8 = * ( _DWORD * ) ( this + 48 ) ; if ( v8 != * ( _DWORD * ) ( this + 52 ) ) { * ( _DWORD * ) ( this + 52 ) = v8 ; ( * ( void (__thiscall **)(int) ) ( * ( _DWORD * ) this + 72 ) ) ( this ) ; } * ( _BYTE * ) ( this + 45 ) = 1 ; * ( _BYTE * ) ( this + 46 ) = a5 > a6 ; * ( _BYTE * ) ( this + 44 ) = 1 ; * ( _DWORD * ) ( this + 56 ) = 0 ; * ( _DWORD * ) ( this + 60 ) = 0 ; * ( _DWORD * ) ( this + 64 ) = 0 ; * ( _DWORD * ) this = & TriColorGaugeClass::vftable' ; return this ; }
    return 0;
}

} // namespace gamemd