// Auto-generated sub_* function stubs
// 10 stubs from IDA decompiled pseudocode
// Generated by tools/gen_sub_stubs.py

#include <cstdint>

namespace gamemd {

// 0x004E3690 (305 bytes)
int BuildingType_FindBuilding_4E3690() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/004E3690.json)
    // Size: 305 bytes, calling convention: thiscall
    // IDA pseudocode:
//   HWND *__fastcall sub_4E3690 ( HWND hDlg, int a2 ) { !int v4 ! ; // eax !HWND DlgItem ! ; // ebp !int v6 ! ; // esi !LRESULT v7 ! ; // eax !LRESULT v8 ! ; // eax !HWND Default ! ; // eax if ( a2 ) { switch ( a2 ) { case 1 : v4 = 1755 ; break ; case 2 : v4 = 1756 ; break ; case 3 : v4 = 1757 ; break ; case 4 : v4 = 1758 ; break ; case 5 : v4 = 1759 ; break ; case 6 : v4 = 1760 ; break ; default : v4 = a2 != 7 ? -1 : 1761 ; break ; } } else { v4 = 1754 ; } DlgItem = "GetDlgItem " ( hDlg , v4 ) ; if ( a2 ) { switch ( a2 ) { case 1 : v6 = 1296 ; break ; case 2 : v6 = 1299 ; break ; case 3 : v6 = 1310 ; break ; case 4 : v6 = 1300 ; break ; case 5 : v6 = 1311 ; break ; case 6 : v6 = 1312 ; break ; default : v6 = a2 != 7 ? -1 : 1313 ; break ; } } else { v6 = 1697 ; } v7 = "SendDlgItemMessageA " ( hDlg , v6 , 0x147u , 0 , 0 ) ; v8 = "SendDlgItemMessageA " ( hDlg , v6 , 0x150u , v7 , 0 ) ; if ( v8 < -3 || v8 > 9 ) { if ( g_GameStateFlags ) v8 = ( * ( int (__thiscall **)(int) ) ( * ( _DWORD * ) g_GameStateFlags + 40 ) ) ( g_GameStateFlags ) ; else v8 = -2 ; } Default = ( HWND ) BuildingType::FindDefault ( ( void * ) v8 ) ; return CacheDialogInvalidate ( DlgItem , Default ) ; }
    return 0;
}

// 0x006435B0 (184 bytes)
char BuildingType_FindBuilding_6435B0() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/006435B0.json)
    // Size: 184 bytes, calling convention: thiscall
    // IDA pseudocode:
//   char __stdcall sub_6435B0 ( int a1, int a2, int a3 ) { !int Default ! ; // eax !int v4 ! ; // esi !int v5 ! ; // edi !char result ! ; // al !int v7 ! ; // esi int v8[4] ; // [esp+8h] [ebp-10h] BYREF Default = BuildingType::FindDefault ( 0 ) ; v4 = Default ; if ( Default ) { v5 = ( * ( int (__thiscall **)(int) ) ( * ( _DWORD * ) Default + 124 ) ) ( Default ) ; Default = ( * ( int (__thiscall **)(int) ) ( * ( _DWORD * ) v4 + 128 ) ) ( v4 ) ; } else { v5 = 0 ; } v8 [ 0 ] = a1 ; v8 [ 3 ] = Default ; v8 [ 1 ] = a2 ; v8 [ 2 ] = v5 ; result = 0 ; v7 = ( 255 >> g_BitShift_Green_0 << g_BitShift_Red ) | ( 255 >> g_BitMask_Red << g_BitShift_Blue ) ; if ( DSurface_Hidden ) { result = sub_4BAFE0 ( ( _DWORD * ) DSurface_Hidden ) ; if ( ! result ) return Surface::BlitTransparent ( v8 , DSurface_Hidden , a3 , v7 ) ; } return result ; }
    return 0;
}

// 0x00642FF0 (201 bytes)
char BuildingType_GetBuilding_642FF0() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/00642FF0.json)
    // Size: 201 bytes, calling convention: thiscall
    // IDA pseudocode:
//   int __stdcall sub_642FF0 ( int a1, int a2, char a3 ) { !int v3 ! ; // ebx !int Default ! ; // eax !int v5 ! ; // esi !int Instance ! ; // ebp _WORD *v7 ; // esi !int v8 ! ; // edi !int v9 ! ; // ebp !int v11 ! ; // [esp+Ch] [ebp-34h] _DWORD v12[7] ; // [esp+20h] [ebp-20h] BYREF __int16 v13 ; // [esp+3Eh] [ebp-2h] v3 = 0 ; v11 = Building::GetFoundationSize ( v12 , 0 ) [ 3 ] + 6 ; if ( a3 ) { Default = BuildingType::FindDefault ( 0 ) ; v5 = Default ; if ( Default ) { ( * ( void (__thiscall **)(int) ) ( * ( _DWORD * ) Default + 124 ) ) ( Default ) ; v3 = ( * ( int (__thiscall **)(int) ) ( * ( _DWORD * ) v5 + 128 ) ) ( v5 ) ; } } Instance = TextRenderer::GetInstance ( ) ; v7 = v12 ; v8 = 15 ; do { * v7 ++ = * ( _WORD * ) CharToWideString ( g_Str_W ) ; -- v8 ; } while ( v8 ) ; v13 = 0 ; Text::MeasureWidth ( ( int ) v12 , 0 ) ; v9 = * ( _DWORD * ) ( Instance + 28 ) ; if ( v11 > v3 ) v3 = v11 ; if ( v3 <= v9 ) v3 = v9 ; return a1 + a2 * ( v3 + 4 ) ; }
    return 0;
}

// 0x006430C0 (245 bytes)
char BuildingType_GetBuilding_6430C0() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/006430C0.json)
    // Size: 245 bytes, calling convention: thiscall
    // IDA pseudocode:
//   int __stdcall sub_6430C0 ( char a1 ) { !int v1 ! ; // ebx !int Default ! ; // eax !int v3 ! ; // esi !int Instance ! ; // ebp _WORD *v5 ; // esi !int v6 ! ; // edi !int v7 ! ; // esi !int v8 ! ; // ebp !int v10 ! ; // [esp+Ch] [ebp-38h] _DWORD v11[7] ; // [esp+24h] [ebp-20h] BYREF __int16 v12 ; // [esp+42h] [ebp-2h] v1 = 0 ; v10 = Building::GetFoundationSize ( v11 , 0 ) [ 3 ] + 6 ; if ( a1 ) { Default = BuildingType::FindDefault ( 0 ) ; v3 = Default ; if ( Default ) { ( * ( void (__thiscall **)(int) ) ( * ( _DWORD * ) Default + 124 ) ) ( Default ) ; v1 = ( * ( int (__thiscall **)(int) ) ( * ( _DWORD * ) v3 + 128 ) ) ( v3 ) ; } } Instance = TextRenderer::GetInstance ( ) ; v5 = v11 ; v6 = 15 ; do { * v5 ++ = * ( _WORD * ) CharToWideString ( g_Str_W ) ; -- v6 ; } while ( v6 ) ; v12 = 0 ; Text::MeasureWidth ( ( int ) v11 , 0 ) ; v7 = v10 ; v8 = * ( _DWORD * ) ( Instance + 28 ) ; if ( v10 <= v1 ) v7 = v1 ; if ( v7 <= v8 ) v7 = v8 ; return ( v7 - Building::GetFoundationSize ( v11 , 0 ) [ 3 ] - 2 ) / 2 ; }
    return 0;
}

// 0x006431C0 (250 bytes)
char BuildingType_GetBuilding_6431C0() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/006431C0.json)
    // Size: 250 bytes, calling convention: thiscall
    // IDA pseudocode:
//   int __stdcall sub_6431C0 ( char a1 ) { !int v1 ! ; // edi !int Default ! ; // eax !int v3 ! ; // esi !int Instance ! ; // ebp _WORD *v5 ; // esi !int v6 ! ; // ebx !int v7 ! ; // ebp !int v8 ! ; // edi !int v9 ! ; // esi !int v11 ! ; // [esp+8h] [ebp-34h] _DWORD v12[7] ; // [esp+1Ch] [ebp-20h] BYREF __int16 v13 ; // [esp+3Ah] [ebp-2h] v1 = 0 ; v11 = Building::GetFoundationSize ( v12 , 0 ) [ 3 ] + 6 ; if ( a1 ) { Default = BuildingType::FindDefault ( 0 ) ; v3 = Default ; if ( Default ) { ( * ( void (__thiscall **)(int) ) ( * ( _DWORD * ) Default + 124 ) ) ( Default ) ; v1 = ( * ( int (__thiscall **)(int) ) ( * ( _DWORD * ) v3 + 128 ) ) ( v3 ) ; } } Instance = TextRenderer::GetInstance ( ) ; v5 = v12 ; v6 = 15 ; do { * v5 ++ = * ( _WORD * ) CharToWideString ( g_Str_W ) ; -- v6 ; } while ( v6 ) ; v13 = 0 ; Text::MeasureWidth ( ( int ) v12 , 0 ) ; v7 = * ( _DWORD * ) ( Instance + 28 ) ; if ( v11 > v1 ) v1 = v11 ; if ( v1 <= v7 ) v1 = v7 ; v8 = v1 + 4 ; v9 = BuildingType::FindDefault ( 0 ) ; if ( ! v9 ) return v8 / 2 ; ( * ( void (__thiscall **)(int) ) ( * ( _DWORD * ) v9 + 124 ) ) ( v9 ) ; return ( v8 - ( * ( int (__thiscall **)(int) ) ( * ( _DWORD * ) v9 + 128 ) ) ( v9 ) ) / 2 ; }
    return 0;
}

// 0x006432C0 (266 bytes)
char BuildingType_GetBuilding_6432C0() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/006432C0.json)
    // Size: 266 bytes, calling convention: thiscall
    // IDA pseudocode:
//   int __stdcall sub_6432C0 ( char a1 ) { !int v1 ! ; // ebx !int Default ! ; // eax !int v3 ! ; // esi !int Instance ! ; // ebp _WORD *v5 ; // esi !int v6 ! ; // edi !int v7 ! ; // eax !int v8 ! ; // ebp !int v9 ! ; // ebp !int v10 ! ; // ebx _WORD *v11 ; // esi !int v12 ! ; // edi !int v14 ! ; // [esp+10h] [ebp-34h] _DWORD v15[7] ; // [esp+24h] [ebp-20h] BYREF __int16 v16 ; // [esp+42h] [ebp-2h] v1 = 0 ; v14 = Building::GetFoundationSize ( v15 , 0 ) [ 3 ] + 6 ; if ( a1 ) { Default = BuildingType::FindDefault ( 0 ) ; v3 = Default ; if ( Default ) { ( * ( void (__thiscall **)(int) ) ( * ( _DWORD * ) Default + 124 ) ) ( Default ) ; v1 = ( * ( int (__thiscall **)(int) ) ( * ( _DWORD * ) v3 + 128 ) ) ( v3 ) ; } } Instance = TextRenderer::GetInstance ( ) ; v5 = v15 ; v6 = 15 ; do { * v5 ++ = * ( _WORD * ) CharToWideString ( g_Str_W ) ; -- v6 ; } while ( v6 ) ; v16 = 0 ; Text::MeasureWidth ( ( int ) v15 , 0 ) ; v7 = * ( _DWORD * ) ( Instance + 28 ) ; v8 = v14 ; if ( v14 <= v1 ) v8 = v1 ; if ( v8 <= v7 ) v8 = v7 ; v9 = v8 + 4 ; v10 = TextRenderer::GetInstance ( ) ; v11 = v15 ; v12 = 15 ; do { * v11 ++ = * ( _WORD * ) CharToWideString ( g_Str_W ) ; -- v12 ; } while ( v12 ) ; v16 = 0 ; Text::MeasureWidth ( ( int ) v15 , 0 ) ; return ( v9 - * ( _DWORD * ) ( v10 + 28 ) ) / 2 ; }
    return 0;
}

// 0x0063F8F0 (73 bytes)
int PowerBar_Calc_63F8F0() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/0063F8F0.json)
    // Size: 73 bytes, calling convention: thiscall
    // IDA pseudocode:
//   __int64 __thiscall sub_63F8F0 ( _DWORD *this ) { !int v2 ! ; // eax !int v4 ! ; // [esp+0h] [ebp-8h] v2 = PowerBar::CalcFill ( ) ; v4 = * ( this + 1355 ) + * ( this + 1356 ) + * ( this + 1357 ) ; if ( v4 > v2 ) v4 = v2 ; return Math::RoundToInt ( ( double ) v4 / ( double ) v2 * 5.0 ) ; }
    return 0;
}

// 0x0063FDC0 (106 bytes)
int PowerBar_SetMember1356_63FDC0() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/0063FDC0.json)
    // Size: 106 bytes, calling convention: thiscall
    // IDA pseudocode:
//   int __thiscall sub_63FDC0 ( _DWORD *this ) { int v2 ; // eax int result ; // eax int v4 ; // eax int v5 ; // [esp+4h] [ebp-Ch] BYREF int v6 ; // [esp+8h] [ebp-8h] BYREF int v7 ; // [esp+Ch] [ebp-4h] BYREF PowerBar::ComputeFill ( & v5 , & v7 , & v6 ) ; v2 = * ( this + 1355 ) ; if ( v2 <= v5 ) { v4 = * ( this + 1357 ) ; if ( v4 <= v6 ) { result = * ( this + 1356 ) ; if ( result > v7 ) * ( this + 1356 ) = -- result ; } else { result = v4 - 1 ; * ( this + 1357 ) = result ; } } else { result = v2 - 1 ; * ( this + 1355 ) = result ; } return result ; }
    return 0;
}

// 0x0063FE30 (106 bytes)
int PowerBar_SetMember_63FE30() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/0063FE30.json)
    // Size: 106 bytes, calling convention: thiscall
    // IDA pseudocode:
//   int __thiscall sub_63FE30 ( _DWORD *this ) { int v2 ; // eax int result ; // eax int v4 ; // eax int v5 ; // [esp+4h] [ebp-Ch] BYREF int v6 ; // [esp+8h] [ebp-8h] BYREF int v7 ; // [esp+Ch] [ebp-4h] BYREF PowerBar::ComputeFill ( & v6 , & v7 , & v5 ) ; v2 = * ( this + 1357 ) ; if ( v2 >= v5 ) { v4 = * ( this + 1355 ) ; if ( v4 >= v6 ) { result = * ( this + 1356 ) ; if ( result < v7 ) * ( this + 1356 ) = ++ result ; } else { result = v4 + 1 ; * ( this + 1355 ) = result ; } } else { result = v2 + 1 ; * ( this + 1357 ) = result ; } return result ; }
    return 0;
}

// 0x004C4FC0 (64 bytes)
int Power_TimerProcess_4C4FC0() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/004C4FC0.json)
    // Size: 64 bytes, calling convention: thiscall
    // IDA pseudocode:
//   int __thiscall sub_4C4FC0 ( int *this, int a2 ) { !int result ! ; // eax int v4 ; // ecx !int v5 ! ; // eax !int v6 ! ; // eax result = Power::TimerProcess ( * this ) ; v4 = * ( this + 1 ) ; if ( v4 ) { v5 = ( * ( int (__thiscall **)(int) ) ( * ( _DWORD * ) v4 + 44 ) ) ( v4 ) ; Power::TimerProcess ( v5 ) ; v6 = ( * ( int (__stdcall **)(int) ) ( * ( _DWORD * ) ( * ( this + 1 ) + 4 ) + 16 ) ) ( * ( this + 1 ) + 4 ) ; return Power::TimerProcess ( v6 ) ; } return result ; }
    return 0;
}

} // namespace gamemd