// Auto-generated sub_* function stubs
// 2 stubs from IDA decompiled pseudocode
// Generated by tools/gen_sub_stubs.py

#include <cstdint>

namespace gamemd {

// 0x00517110 (169 bytes)
int MovementAI_MainFootClass_517110() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/00517110.json)
    // Size: 169 bytes, calling convention: thiscall
    // IDA pseudocode:
//   int __thiscall sub_517110 ( int this ) { !int v2 ! ; // edi !int v3 ! ; // ebx _WORD *v4 ; // eax !bool v5 ! ; // bl int v6 ; // ecx !int result ! ; // eax _BYTE v8[4] ; // [esp+8h] [ebp-4h] BYREF v5 = 1 ; if ( * ( _DWORD * ) ( this + 36 ) != g_ScoreDisplayState1 || * ( _DWORD * ) ( this + 40 ) != g_ScoreDisplayState2 || * ( _DWORD * ) ( this + 44 ) != g_ScoreDisplayState3 ) { v2 = * ( _DWORD * ) ( this + 36 ) / 256 ; v3 = * ( _DWORD * ) ( this + 40 ) / 256 ; v4 = ( _WORD * ) ( * ( int (__thiscall **)(_DWORD, _BYTE *) ) ( * * ( _DWORD ** ) ( this + 12 ) + 440 ) ) ( * ( _DWORD * ) ( this + 12 ) , v8 ) ; if ( * v4 != ( _WORD ) v2 || v4 [ 1 ] != ( _WORD ) v3 ) v5 = 0 ; } v6 = * ( _DWORD * ) ( this + 12 ) ; * ( _DWORD * ) ( this + 72 ) = 0 ; * ( _DWORD * ) ( this + 76 ) = 1072693248 ; ( * ( void (__thiscall **)(int, _DWORD, int) ) ( * ( _DWORD * ) v6 + 1348 ) ) ( v6 , 0 , 1072693248 ) ; result = MovementAI::StepFootClass ( ( int * ) this , 0 ) ; if ( v5 ) return MovementAI::MainFootClass ( ( int * ) this , 1 ) ; return result ; }
    return 0;
}

// 0x00600AF0 (369 bytes)
void RemoveLinked_600AF0() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/00600AF0.json)
    // Size: 369 bytes, calling convention: cdecl
    // IDA pseudocode:
//   void __cdecl sub_600AF0 ( ) { !unsigned int v0 ! ; // eax !unsigned int v1 ! ; // ecx int j ; // ebp int v3 ; // edi _DWORD *k ; // eax !void **v5 ! ; // ecx !unsigned int v6 ! ; // ecx !int *v7 ! ; // ebp !int v8 ! ; // esi !int *v9 ! ; // edi !int v10 ! ; // ebx int v11 ; // esi !int v12 ! ; // edx int v13 ; // ecx int v14 ; // eax !unsigned int i ! ; // [esp+10h] [ebp-4h] v0 = dword_AC1B08 ; v1 = 0 ; for ( i = 0 ; v1 < dword_AC1B08 ; v0 = dword_AC1B08 ) { for ( j = * ( ( _DWORD * ) g_DialogHashMap_Base + v1 ) ; j ; v1 = i ) { v3 = j ; j = * ( _DWORD * ) ( j + 516 ) ; if ( * ( _DWORD * ) ( v3 + 44 ) ) { __3_YAXPAX_Z ( * ( void ** ) ( v3 + 44 ) ) ; * ( _DWORD * ) ( v3 + 44 ) = 0 ; } for ( k = * ( _DWORD ** ) ( v3 + 56 ) ; k ; k = * ( _DWORD ** ) ( v3 + 56 ) ) LinkedList::Remove ( ( _DWORD * ) ( v3 + 4 ) , k ) ; v5 = * ( void *** ) ( v3 + 64 ) ; if ( v5 ) DeleteAndZero::OrFree ( v5 , 1 ) ; __3_YAXPAX_Z ( ( void * ) v3 ) ; } i = ++ v1 ; * ( ( _DWORD * ) g_DialogHashMap_Base + v1 - 1 ) = 0 ; } v6 = dword_AC1B30 ; g_DialogHashMap_Count = 0 ; if ( v0 > dword_AC1B30 ) { do { if ( byte_AC1B14 || v0 <= v6 ) break ; v7 = ( int * ) g_DialogHashMap_Base ; v8 = v0 ; dword_AC1B08 = v0 >> 1 ; -- g_DialogHashMap_Buckets ; g_DialogHashMap_Base = __2_YAPAXI_Z ( 4 * ( v0 >> 1 ) ) ; memset ( g_DialogHashMap_Base , 0 , 4 * dword_AC1B08 ) ; if ( v8 > 0 ) { v9 = v7 ; v10 = v8 ; do { v11 = * v9 ; if ( * v9 ) { do { v12 = g_DialogHashMap_Hasher ( v11 ) & ( ( 1 << g_DialogHashMap_Buckets ) - 1 ) ; v13 = * ( ( _DWORD * ) g_DialogHashMap_Base + v12 ) ; * ( ( _DWORD * ) g_DialogHashMap_Base + v12 ) = v11 ; v14 = * ( _DWORD * ) ( v11 + 516 ) ; * ( _DWORD * ) ( v11 + 516 ) = v13 ; v11 = v14 ; } while ( v14 ) ; } ++ v9 ; -- v10 ; } while ( v10 ) ; } __3_YAXPAX_Z ( v7 ) ; v6 = dword_AC1B30 ; v0 = dword_AC1B08 ; } while ( dword_AC1B08 > ( unsigned int ) dword_AC1B30 ) ; } __3_YAXPAX_Z ( g_DialogHashMap_Base ) ; }
    
}

} // namespace gamemd