// AUTO-GENERATED by tools/gen_gap2_defs.py -- DO NOT EDIT MANUALLY.
// Gap 2: REAL definitions for global functions / LNK2019 globals & data.
#include <cstdint>
#include "_gap2/gap2_global_decls.hpp"

// forward declarations for data-global pointer types
namespace gamemd { class HouseTypeClass; }

// LNK2019 data global (reference)
namespace ra2 { namespace game { int _gap2_CurrentFrame_store = {}; int& CurrentFrame = _gap2_CurrentFrame_store; } }
// LNK2019 data global
namespace gamemd { unsigned int g_ObjectTypeList = {}; }
// LNK2019 data global
namespace gamemd { gamemd::HouseTypeClass * * g_HouseTypeArray = nullptr; }
// LNK2019 data global
gamemd::HouseTypeClass * * g_HouseTypeArray = nullptr;
// LNK2019 data global
namespace gamemd { int g_ScrollOffsetX = {}; }
// LNK2019 data global
namespace gamemd { int g_ScrollOffsetY = {}; }
extern "C" int BlitterCopySimpleSHP() { return 0; }  // LNK2019 cdecl
// LNK2019 data global
void * g_ZBufferDescriptor = nullptr;
// 0x70E240
namespace gamemd { int IsNonNullPtr(int) { return 0; } }
// 0x402F60
namespace gamemd { int ProcessAudioMixerFrame() { return 0; } }
// 0x403A80
namespace gamemd { int DumpAudioDeviceDebug(void* a1, int a2) { return 0; } }
// 0x4048B0
namespace gamemd { int PrefetchAudioSamples() { return 0; } }
// 0x4055C0
namespace gamemd { int UpdateVoicePlayback() { return 0; } }
// 0x40AA70
namespace gamemd { bool ProcessAudioChannelMovement() { return false; } }
// 0x415C60
namespace gamemd { int ProcessTechnoMovementAction() { return 0; } }
// 0x4197C0
namespace gamemd { void* FindSpiralMoveTarget(int a1) { return nullptr; } }
// 0x41AF80
namespace gamemd { int SaveAircraftToINI() { return 0; } }
// 0x41C250
namespace gamemd { int CreateInstanceCOM() { return 0; } }
// 0x421350
namespace gamemd { int RenderAlphaShapes() { return 0; } }
// 0x429830
namespace gamemd { double ComputeMovementWeight(void* a1, void* a2, int a3, int a4, int a5) { return 0.0; } }
// 0x42B210
namespace gamemd { int ParsePathDirections(int a1, void* a2) { return 0; } }
// 0x42B7F0
namespace gamemd { void* SimplifyPathFilter(void* a1, int a2) { return nullptr; } }
// 0x42E1C0
namespace gamemd { int RenderTooltipBorder() { return 0; } }
// 0x430250
namespace gamemd { int RenderBuildingTag(int a1, int a2, int a3, int a4, int a5) { return 0; } }
// 0x430AC0
namespace gamemd { int RenderAlliedBuildingTags(int a1, int a2, int a3, int a4, int a5) { return 0; } }
// 0x430BA0
namespace gamemd { void PlacePlayerBeacon(int a1, int a2, int a3, int a4, int a5) { } }
// 0x432C10
namespace gamemd { int COMStub_432C10(int a1) { return 0; } }
// 0x438BF0
namespace gamemd { int DispatchBuildingAudioEvents() { return 0; } }
// 0x43B150
namespace gamemd { bool DetectNearbyAlliedThreat() { return false; } }
// 0x43C0D0
namespace gamemd { void* CreateDominatorDestructionEffects() { return nullptr; } }
// 0x4500F0
namespace gamemd { void ProcessAutoProduction() { } }
// 0x455F10
namespace gamemd { int MarkBuildingFoundationCells(int a1) { return 0; } }
// 0x4561F0
namespace gamemd { int RecalculateBuildingFoundation() { return 0; } }
// 0x458330
namespace gamemd { void* PlayHealthDependentBuildingAnim() { return nullptr; } }
// 0x459CA0
namespace gamemd { int ProcessDataCellClass() { return 0; } }
// 0x45A160
namespace gamemd { int Release2COM() { return 0; } }
// 0x465570
namespace gamemd { void* CalculateBuildingFoundationBounds(void* a1) { return nullptr; } }
// 0x471890
namespace gamemd { int SmallFunc_471890() { return 0; } }
// 0x47BDB0
namespace gamemd { int GetBridgeCellColor(void* a1, int a2) { return 0; } }
// 0x47C060
namespace gamemd { int GetCellRadarColors(int a1, int a2) { return 0; } }
// 0x4838E0
namespace gamemd { int IsCoordValidMap(int a1) { return 0; } }
// 0x486E30
namespace gamemd { int Helper_486E30() { return 0; } }
// 0x48DEB0
namespace gamemd { int COMStub_48DEB0() { return 0; } }
// 0x48DF30
namespace gamemd { int LookupNameIndex() { return 0; } }
// 0x49B930
namespace gamemd { int UpdateScoreScreenStatistics() { return 0; } }
// 0x49E740
namespace gamemd { int SmallFunc_49E740(void* a1) { return 0; } }
// 0x4A3660
namespace gamemd { int RenderTactical3DScene(int a1) { return 0; } }
// 0x4A42F0
namespace gamemd { int InitializeDDraw() { return 0; } }
// 0x4B5AB0
namespace gamemd { int SmallFunc_4B5AB0() { return 0; } }
// 0x4C5370
namespace gamemd { int Helper_4C5370() { return 0; } }
// 0x4C54E0
namespace gamemd { int ApplyEMPPulseEffect(int a1) { return 0; } }
// 0x4CB760
namespace gamemd { void* TerrainInitMap(void* a1, int a2) { return nullptr; } }
// 0x4CB7C0
namespace gamemd { void* BuildResultPacket(void* a1, void* a2) { return nullptr; } }
// 0x4CBC40
namespace gamemd { void* WalkPathfindingLine(void* a1, int a2, void* a3, int a4, int a5) { return nullptr; } }
// 0x4CE4B0
namespace gamemd { int ProcessDataHelper(void* a1, int a2) { return 0; } }
// 0x4D0430
namespace gamemd { int Release3COM() { return 0; } }
// 0x4DC340
namespace gamemd { int DrawFootTargetLine() { return 0; } }
// 0x4E3320
namespace gamemd { int GetResourceIDHardcodedCSF() { return 0; } }
// 0x4E37D0
namespace gamemd { int GetResourceID2CSF() { return 0; } }
// 0x4E41D0
namespace gamemd { int GetResourceIDCSF() { return 0; } }
// 0x4E4E60
namespace gamemd { int GetResourceID3CSF() { return 0; } }
// 0x4E5940
namespace gamemd { int GetResourceID4CSF() { return 0; } }
// 0x4F9F70
namespace gamemd { int COMStub_4F9F70(int a1, int a2) { return 0; } }
// 0x4FD9A0
namespace gamemd { int ValidateAIBuildAffordability() { return 0; } }
// 0x504860
namespace gamemd { int Team_Helper(int a1) { return 0; } }
// 0x507B80
namespace gamemd { int CollectSuperWeaponBuildingTypes(int a1, int a2) { return 0; } }
// 0x50BA00
namespace gamemd { int ComputeSessionColorVector() { return 0; } }
// 0x50D6D0
namespace gamemd { int SelectSimilarBuildingTypes(int a1) { return 0; } }
// 0x50DA10
namespace gamemd { int GlobalHelper_0E4440_Helper() { return 0; } }
// 0x50DA50
namespace gamemd { int GlobalHelper_0E44C0_Helper() { return 0; } }
// 0x50DFF0
namespace gamemd { int GlobalHelper_0E4540_Helper() { return 0; } }
// 0x515ED0
namespace gamemd { void UpdateFootFacing() { } }
// 0x5175F0
namespace gamemd { int ReadRegistryOptionsWOL() { return 0; } }
// 0x5176C0
namespace gamemd { bool WinMain_Helper() { return false; } }
// 0x518D80
namespace gamemd { int CalculateLocomotionFrameIndex() { return 0; } }
// 0x51FB00
namespace gamemd { int PlaceScenarioInfantry() { return 0; } }
// 0x5202F0
namespace gamemd { int ProcessTechnoSquadResponse() { return 0; } }
// 0x5206B0
namespace gamemd { void FireTechnoAtTarget() { } }
// 0x5272B0
namespace gamemd { void* LookupCSFString(void* a1, void* a2, int a3) { return nullptr; } }
// 0x52A670
namespace gamemd { void* WinMain_Init(void* a1, int a2) { return nullptr; } }
// 0x53B780
namespace gamemd { int ApplyChronoScreenColorShift() { return 0; } }
// 0x53E4F0
namespace gamemd { bool WinMain_Helper_53E4F0() { return false; } }
// 0x53E550
namespace gamemd { bool WinMain_Write() { return false; } }
// 0x53FA90
namespace gamemd { void* Network_Init_53FA90(int a1, int a2, int a3, int a4, int a5) { return nullptr; } }
// 0x5402B0
namespace gamemd { int Network_Init_5402B0(int a1) { return 0; } }
// 0x540A80
namespace gamemd { int Network_Init() { return 0; } }
// 0x542FC0
namespace gamemd { int Network_Init_542FC0(int a1) { return 0; } }
// 0x5430C0
namespace gamemd { int StartGameWOL_Start(int a1) { return 0; } }
// 0x544CE0
namespace gamemd { int Entity_Read() { return 0; } }
// 0x544E00
namespace gamemd { void* Map_Get(int a1) { return nullptr; } }
// 0x549E50
namespace gamemd { int Map_Get_549E50(int a1, int a2) { return 0; } }
// 0x54BD30
namespace gamemd { int UpdateFootMoveToState() { return 0; } }
// 0x54F530
namespace gamemd { int Event_Process(int a1) { return 0; } }
// 0x551A30
namespace gamemd { int ProcessAutoSave() { return 0; } }
// 0x556B70
namespace gamemd { int Render_Render_556B70() { return 0; } }
// 0x556C00
namespace gamemd { void* Render_Render_556C00() { return nullptr; } }
// 0x55AF50
namespace gamemd { void Map_Init() { } }
// 0x55F690
namespace gamemd { int CheckNetworkSync(int a1, int a2) { return 0; } }
// 0x569760
namespace gamemd { void DestroyCliffMap(int a1, int a2, void* a3) { } }
// 0x56A080
namespace gamemd { int PlaceTerrainCliffsRegion() { return 0; } }
// 0x56A4C0
namespace gamemd { void FlattenCliffMap(void* a1) { } }
// 0x56A980
namespace gamemd { void RepairMapCliff(void* a1) { } }
// 0x56D3F0
namespace gamemd { int CellToTileIndexMap(void* a1) { return 0; } }
// 0x56DA10
namespace gamemd { int GetRegionMap(void* a1, int a2, int a3) { return 0; } }
// 0x56DB70
namespace gamemd { int InvalidateTileRegionMap(void* a1) { return 0; } }
// 0x56E890
namespace gamemd { int ProcessDataHouseClass(void* a1, void* a2, void* a3) { return 0; } }
// 0x5785F0
namespace gamemd { bool IsCoordVisibleMap(void* a1) { return false; } }
// 0x578640
namespace gamemd { bool Math_Helper(void* a1, void* a2, int a3) { return false; } }
// 0x57B870
namespace gamemd { int Map_Create() { return 0; } }
// 0x57B990
namespace gamemd { int Map_Create_57B990() { return 0; } }
// 0x57CAB0
namespace gamemd { int Map_Create_57CAB0() { return 0; } }
// 0x57CBE0
namespace gamemd { int Map_Create_57CBE0() { return 0; } }
// 0x580BC0
namespace gamemd { void* FindMapSpawnCell(int a1) { return nullptr; } }
// 0x581090
namespace gamemd { int CleanupMapSystems() { return 0; } }
// 0x582D30
namespace gamemd { int SmallFunc_582D30(int a1) { return 0; } }
// 0x583C60
namespace gamemd { int CollectMatchingTileCells(void* a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8) { return 0; } }
// 0x5840C0
namespace gamemd { int CheckMapReachability(int a1, int a2, int a3, int a4) { return 0; } }
// 0x584E50
namespace gamemd { int UpdateCellConnectivityGraph(void* a1) { return 0; } }
// 0x5851B0
namespace gamemd { int BuildTileAdjacencyTable(void* a1) { return 0; } }
// 0x585930
namespace gamemd { void FloodFillConnectedCells(int a1, int a2) { } }
// 0x5866C0
namespace gamemd { int SmallFunc_5866C0() { return 0; } }
// 0x5868A0
namespace gamemd { void UpdateAreaConnectivityMap(void* a1) { } }
// 0x587C50
namespace gamemd { int DiagnoseMapCheck() { return 0; } }
// 0x588960
namespace gamemd { int Object_Create(int a1) { return 0; } }
// 0x591740
namespace gamemd { int PlaceMapSeedCityArea(void* a1, void* a2, void* a3) { return 0; } }
// 0x592AF0
namespace gamemd { int PlaceMapSeedCityBlockVariant(void* a1, void* a2, void* a3) { return 0; } }
// 0x593030
namespace gamemd { int PlaceMapSeedCityBlockDiagonal(void* a1, void* a2, void* a3) { return 0; } }
// 0x593AF0
namespace gamemd { int PlaceMapSeedCityBlockVariant2(void* a1, void* a2, void* a3) { return 0; } }
// 0x594870
namespace gamemd { void PlaceRandomWaypoints(int a1) { } }
// 0x595400
namespace gamemd { int PlaceNeutralBuilding() { return 0; } }
// 0x597430
namespace gamemd { void* Team_Start_597430() { return nullptr; } }
// 0x5A1FB0
namespace gamemd { int SpreadMapSeedTerrainFromWaypoints() { return 0; } }
// 0x5A2F50
namespace gamemd { void SmoothTerrainMap() { } }
// 0x5A35F0
namespace gamemd { int GenerateTerrainHeightMap() { return 0; } }
// 0x5A82E0
namespace gamemd { void ScatterMapSeedBuildings(void* a1) { } }
// 0x5A95B0
namespace gamemd { void* PlaceRandomAIBuildings() { return nullptr; } }
// 0x5A99B0
namespace gamemd { void* Object_Helper_5A99B0() { return nullptr; } }
// 0x5AD930
namespace gamemd { int Map_Helper_5AD930(int a1) { return 0; } }
// 0x5AD9F0
namespace gamemd { void* Map_Cleanup(int a1, int a2) { return nullptr; } }
// 0x5B3910
namespace gamemd { int LookupWaypointName() { return 0; } }
// 0x5B6CD0
namespace gamemd { int Surface_Lock() { return 0; } }
// 0x5B6EB0
namespace gamemd { void UI_Setup(void* a1, int a2, int a3) { } }
// 0x5C1300
namespace gamemd { int ReadMPMapsINI() { return 0; } }
// 0x5C80A0
namespace gamemd { int ComputeModularInverse(void* a1, int a2) { return 0; } }
// 0x5CB790
namespace gamemd { int TerritoryUpdateDisplayWOL(int a1) { return 0; } }
// 0x5CC690
namespace gamemd { void Map_Process_5CC690() { } }
// 0x5CE4A0
namespace gamemd { void* UI_Load(void* a1, int a2, int a3) { return nullptr; } }
// 0x5CEDD0
namespace gamemd { void* Map_Delete_5CEDD0() { return nullptr; } }
// 0x5CF830
namespace gamemd { int Network_Load(int a1) { return 0; } }
// 0x5D1C90
namespace gamemd { int UI_Load_5D1C90(void* a1, void* a2) { return 0; } }
// 0x5D4430
namespace gamemd { int SyncFrameCounter() { return 0; } }
// 0x5D6D80
namespace gamemd { int ComputeMultiEngineerAdjustment() { return 0; } }
// 0x5D9360
namespace gamemd { void SmallFunc_5D9360() { } }
// 0x5DB600
namespace gamemd { int PlayerSkirmishSlotHandler_Handle_5DB600() { return 0; } }
// 0x5DBEC0
namespace gamemd { int SendMultiplayerStartSignal_Start() { return 0; } }
// 0x5E23D0
namespace gamemd { int Network_Check(int a1) { return 0; } }
// 0x5E9340
namespace gamemd { int Audio_Helper() { return 0; } }
// 0x5E93F0
namespace gamemd { bool IsKnownPointer() { return false; } }
// 0x5EAAD0
namespace gamemd { int RefreshLobbyAll_Helper_5EAAD0() { return 0; } }
// 0x5EAB30
namespace gamemd { int RefreshLobbyAll_Play_5EAB30() { return 0; } }
// 0x5EAC00
namespace gamemd { int RefreshLobbyAll_Get_5EAC00() { return 0; } }
// 0x5EACD0
namespace gamemd { int RefreshLobbyAll_Get_5EACD0() { return 0; } }
// 0x5EADA0
namespace gamemd { int RefreshLobbyAll_Get_5EADA0() { return 0; } }
// 0x5EAE40
namespace gamemd { bool RefreshLobbyAll_Setup() { return false; } }
// 0x5EAEE0
namespace gamemd { void* RefreshLobbyAll_Play_5EAEE0() { return nullptr; } }
// 0x5EE100
namespace gamemd { bool Network_Send() { return false; } }
// 0x5EEF60
namespace gamemd { void String_Process() { } }
// 0x5EF010
namespace gamemd { void Map_Helper_5EF010() { } }
// 0x5FD2E0
namespace gamemd { int ReadOverlayINI() { return 0; } }
// 0x60B350
namespace gamemd { bool UI_Get_60B350() { return false; } }
// 0x60B420
namespace gamemd { bool UI_Get_60B420() { return false; } }
// 0x60B550
namespace gamemd { bool UI_Get_60B550() { return false; } }
// 0x60B610
namespace gamemd { bool UI_Get_60B610() { return false; } }
// 0x60B7A0
namespace gamemd { int UI_Get_60B7A0() { return 0; } }
// 0x60C7D0
namespace gamemd { int UI_Helper_60C7D0() { return 0; } }
// 0x60C930
namespace gamemd { int UI_Helper_60C930() { return 0; } }
// 0x60CAF0
namespace gamemd { int UI_Helper_60CAF0() { return 0; } }
// 0x60CCC0
namespace gamemd { int UI_Helper_60CCC0() { return 0; } }
// 0x60CDB0
namespace gamemd { int UI_Helper_60CDB0() { return 0; } }
// 0x623E00
namespace gamemd { int Memory_Pop() { return 0; } }
// 0x625C00
namespace gamemd { void* Event_Process_625C00(void* a1) { return nullptr; } }
// 0x626120
namespace gamemd { int Render_Helper(int a1, int a2) { return 0; } }
// 0x62C6E0
namespace gamemd { void UpdateParticleSystem() { } }
// 0x62CB10
namespace gamemd { void UpdateAreaDamageEffect() { } }
// 0x62E430
namespace gamemd { int CreateFireAtSW(int a1, int a2) { return 0; } }
// 0x62E840
namespace gamemd { int UpdateProductionParticleSystem() { return 0; } }
// 0x62ED40
namespace gamemd { void UpdateBuildingParticleSystem() { } }
// 0x62F9A0
namespace gamemd { int UpdateBuildingDamageParticles() { return 0; } }
// 0x630EA0
namespace gamemd { int UI_Get_630EA0() { return 0; } }
// 0x631380
namespace gamemd { void* UI_Pop() { return nullptr; } }
// 0x631500
namespace gamemd { void UI_Pop_631500() { } }
// 0x6316E0
namespace gamemd { bool UI_Pop_631500_Pop() { return false; } }
// 0x6319C0
namespace gamemd { void Network_Set() { } }
// 0x631B20
namespace gamemd { int UI_Pop_631500_Pop_Pop() { return 0; } }
// 0x632000
namespace gamemd { int System_Init_632000(void* a1) { return 0; } }
// 0x632030
namespace gamemd { int System_Init_632030(void* a1) { return 0; } }
// 0x633AC0
namespace gamemd { void* ExecuteActionPlanManager_Helper() { return nullptr; } }
// 0x6342E0
namespace gamemd { int Team_Helper_6342E0(int a1, int a2) { return 0; } }
// 0x6345A0
namespace gamemd { void* Render_Render_6345A0(void* a1) { return nullptr; } }
// 0x634770
namespace gamemd { int Render_Render_634770() { return 0; } }
// 0x634970
namespace gamemd { int Helper_634970() { return 0; } }
// 0x635490
namespace gamemd { int Render_Render_635490(int a1) { return 0; } }
// 0x636EB0
namespace gamemd { int ExecuteActionPlanManager_Helper_636EB0() { return 0; } }
// 0x637D00
namespace gamemd { int UI_Delete_Delete() { return 0; } }
// 0x638C40
namespace gamemd { bool ExecuteActionPlanManager_Helper_638C40(int a1, int a2) { return false; } }
// 0x63B050
namespace gamemd { void* Team_Load_63B050() { return nullptr; } }
// 0x63C690
namespace gamemd { int RenderScenarioActionLines() { return 0; } }
// 0x63CAE0
namespace gamemd { int RenderScenarioActionLines2() { return 0; } }
// 0x63D0F0
namespace gamemd { int Render_Render_63D0F0() { return 0; } }
// 0x63D480
namespace gamemd { int DrawActionLineSegment(int a1, int a2) { return 0; } }
// 0x63DAD0
namespace gamemd { int PackRGBFromBytes() { return 0; } }
// 0x63DB20
namespace gamemd { bool HandlePlanningModeClick_Handle() { return false; } }
// 0x63DEC0
namespace gamemd { void* ExecuteActionPlanManager_Helper_63DEC0(int a1, int a2) { return nullptr; } }
// 0x63E1D0
namespace gamemd { void* ExecuteActionPlanManager_Helper_63E1D0(int a1, int a2) { return nullptr; } }
// 0x63E5D0
namespace gamemd { int Team_Destroy(int a1) { return 0; } }
// 0x63EFB0
namespace gamemd { void* Object_Set(int a1, int a2) { return nullptr; } }
// 0x641B00
namespace gamemd { int LoadMapPreviewImage(void* a1) { return 0; } }
// 0x643720
namespace gamemd { int RenderBuildingProductionButton(int a1, int a2, void* a3, int a4, int a5) { return 0; } }
// 0x645BB0
namespace gamemd { int GetSuperWeaponTypeFlag() { return 0; } }
// 0x64A7B0
namespace gamemd { int RenderPlayerLatencyBars() { return 0; } }
// 0x652540
namespace gamemd { int Network_Process_652540() { return 0; } }
// 0x652560
namespace gamemd { int Network_Process_652560(int a1) { return 0; } }
// 0x6525A0
namespace gamemd { int Network_Process_6525A0(int a1) { return 0; } }
// 0x6547C0
namespace gamemd { void* GenerateImageThumbnail(void* a1, void* a2, void* a3, int a4) { return nullptr; } }
// 0x6550C0
namespace gamemd { void* Team_Load_6550C0(void* a1, void* a2) { return nullptr; } }
// 0x659510
namespace gamemd { int SpreadRadiationAreaEffect_Helper(int a1, int a2) { return 0; } }
// 0x659530
namespace gamemd { int SpreadRadiationAreaEffect_Helper_659530(int a1) { return 0; } }
// 0x659650
namespace gamemd { bool RenderProjectileTrail() { return false; } }
// 0x659E30
namespace gamemd { int Weapon_Update_Update() { return 0; } }
// 0x659EE0
namespace gamemd { int Weapon_Update_Update_659EE0() { return 0; } }
// 0x659FF0
namespace gamemd { int Weapon_Update_Update_659FF0() { return 0; } }
// 0x65A1B0
namespace gamemd { void* Render_Render_65A1B0(int a1) { return nullptr; } }
// 0x65A7E0
namespace gamemd { void* Helper_65A7E0(int a1) { return nullptr; } }
// 0x65C250
namespace gamemd { void* WinMain_Helper_65C250(int a1, int a2) { return nullptr; } }
// 0x65C2A0
namespace gamemd { void WinMain_Helper_65C2A0() { } }
// 0x65C6D0
namespace gamemd { void* SeedInitRNG(int a1) { return nullptr; } }
// 0x65DD30
namespace gamemd { void* ConstructTeamMembers() { return nullptr; } }
// 0x65FB80
namespace gamemd { void* Team_Load_65FB80(int a1, int a2) { return nullptr; } }
// 0x65FE00
namespace gamemd { void Map_Helper_65FE00() { } }
// 0x660050
namespace gamemd { int RenderGradientTrapezoid() { return 0; } }
// 0x660540
namespace gamemd { int Map_Helper_660540() { return 0; } }
// 0x660730
namespace gamemd { int Render_Render_660730(void* a1) { return 0; } }
// 0x660BB0
namespace gamemd { void* UI_Create_734120_Create() { return nullptr; } }
// 0x660BE0
namespace gamemd { void* UI_Create_734120_Create_660BE0() { return nullptr; } }
// 0x661770
namespace gamemd { void* SHA1TickRNG(int a1) { return nullptr; } }
// 0x6686C0
namespace gamemd { int ResetRules() { return 0; } }
// 0x66B900
namespace gamemd { int ReadCrateRulesINI() { return 0; } }
// 0x672230
namespace gamemd { int ReadMaximumPlayersINI() { return 0; } }
// 0x672840
namespace gamemd { int ReadBuildingTypesBuildingTypeClass() { return 0; } }
// 0x678850
namespace gamemd { int InitInterfaceStubsCOM() { return 0; } }
// 0x67BFA0
namespace gamemd { void* System_Load_67BFA0(void* a1) { return nullptr; } }
// 0x681060
namespace gamemd { int Map_Save(int a1) { return 0; } }
// 0x681080
namespace gamemd { int Map_Save_681080(int a1) { return 0; } }
// 0x6810A0
namespace gamemd { void* Map_Save_6810A0(void* a1) { return nullptr; } }
// 0x6810D0
namespace gamemd { void* Map_Save_6810D0(void* a1) { return nullptr; } }
// 0x681110
namespace gamemd { int Map_Save_681110(int a1) { return 0; } }
// 0x681130
namespace gamemd { int Map_Save_681130(int a1) { return 0; } }
// 0x6811C0
namespace gamemd { void* Map_Save_6811C0(void* a1) { return nullptr; } }
// 0x681200
namespace gamemd { int Map_Save_681200(void* a1) { return 0; } }
// 0x681240
namespace gamemd { int Map_Save_681240(void* a1) { return 0; } }
// 0x681280
namespace gamemd { int Map_Save_681280(void* a1) { return 0; } }
// 0x6812C0
namespace gamemd { int Map_Save_6812C0(int a1) { return 0; } }
// 0x681840
namespace gamemd { int ScenarioPropertyReadCOM(int a1) { return 0; } }
// 0x683050
namespace gamemd { int Map_Read_683050() { return 0; } }
// 0x683060
namespace gamemd { int ReleaseCOM() { return 0; } }
// 0x68C260
namespace gamemd { int DynamicVector_PushBack(void* a1) { return 0; } }
// 0x68C860
namespace gamemd { int LoadTheaterClassMIX_Load(void* a1, int a2, int a3, int a4, int a5) { return 0; } }
// 0x68FBB0
namespace gamemd { int RenderScoreTypeText(int a1, int a2, int a3) { return 0; } }
// 0x68FFE0
namespace gamemd { int Render_Render_68FFE0(int a1, int a2) { return 0; } }
// 0x691590
namespace gamemd { int SetLandTypeMap() { return 0; } }
// 0x692290
namespace gamemd { int SmallFunc_692290() { return 0; } }
// 0x693440
namespace gamemd { int ScrollMapEdge(void* a1) { return 0; } }
// 0x695BC0
namespace gamemd { int ApplyModemConfigSettings() { return 0; } }
// 0x696200
namespace gamemd { int InitializeModemPortSelect() { return 0; } }
// 0x6967B0
namespace gamemd { int DlgProcLoadGame_Load() { return 0; } }
// 0x696AE0
namespace gamemd { int DlgProcLoadGame_Load_696AE0() { return 0; } }
// 0x696C40
namespace gamemd { int DlgProcLoadGame_Load_696C40() { return 0; } }
// 0x697F10
namespace gamemd { int ReadGameSettingsINI(void* a1, int a2, void* a3, void* a4) { return 0; } }
// 0x6990A0
namespace gamemd { void SaveConfigWOL() { } }
// 0x69B170
namespace gamemd { void ParseAndApplyAlliances() { } }
// 0x69BBF0
namespace gamemd { void Network_Disconnect_69BBF0(int a1) { } }
// 0x69D870
namespace gamemd { void* ParseAndApplyAlliances_Parse(int a1, int a2) { return nullptr; } }
// 0x69E430
namespace gamemd { void* LoadSHPFile(void* a1) { return nullptr; } }
// 0x69E900
namespace gamemd { int Helper_69E900(int a1) { return 0; } }
// 0x6A4F20
namespace gamemd { int UI_Init(int a1) { return 0; } }
// 0x6A94F0
namespace gamemd { int SmallFunc_6A94F0(int a1) { return 0; } }
// 0x6AC840
namespace gamemd { void* System_Init_6AC840(int a1) { return nullptr; } }
// 0x6AC8D0
namespace gamemd { void* System_Init_6AC8D0(int a1, int a2) { return nullptr; } }
// 0x6B0490
namespace gamemd { void* Event_Process_6B0490() { return nullptr; } }
// 0x6B2520
namespace gamemd { int System_Init_6B2520() { return 0; } }
// 0x6B4100
namespace gamemd { int Map_Get_6B4100() { return 0; } }
// 0x6B5440
namespace gamemd { int Object_Read_6B5440() { return 0; } }
// 0x6B8AF0
namespace gamemd { bool ApplyGameOptions_Helper(void* a1) { return false; } }
// 0x6BAFA0
namespace gamemd { void Render_Load_6BAFA0() { } }
// 0x6BB990
namespace gamemd { int TopLevelExceptionFilter() { return 0; } }
// 0x6BFD40
namespace gamemd { void* WinMain_Helper_6BFD40() { return nullptr; } }
// 0x6BFEC0
namespace gamemd { void* WinMain_Helper_6BFEC0() { return nullptr; } }
// 0x6C0040
namespace gamemd { void* WinMain_Helper_6C0040() { return nullptr; } }
// 0x6C01C0
namespace gamemd { void* WinMain_Helper_6C01C0() { return nullptr; } }
// 0x6C0340
namespace gamemd { void* WinMain_Helper_6C0340() { return nullptr; } }
// 0x6C04C0
namespace gamemd { void* WinMain_Helper_6C04C0() { return nullptr; } }
// 0x6C0640
namespace gamemd { void* WinMain_Helper_6C0640() { return nullptr; } }
// 0x6C07C0
namespace gamemd { void* WinMain_Helper_6C07C0() { return nullptr; } }
// 0x6C0940
namespace gamemd { void* WinMain_Helper_6C0940() { return nullptr; } }
// 0x6C0C40
namespace gamemd { void* WinMain_Helper_6C0C40() { return nullptr; } }
// 0x6C0DC0
namespace gamemd { void* WinMain_Helper_6C0DC0() { return nullptr; } }
// 0x6C0F40
namespace gamemd { void* WinMain_Helper_6C0F40() { return nullptr; } }
// 0x6C10C0
namespace gamemd { void* WinMain_Helper_6C10C0() { return nullptr; } }
// 0x6C1240
namespace gamemd { void* WinMain_Helper_6C1240() { return nullptr; } }
// 0x6C13C0
namespace gamemd { void* WinMain_Helper_6C13C0() { return nullptr; } }
// 0x6C1540
namespace gamemd { void* WinMain_Helper_6C1540() { return nullptr; } }
// 0x6C16C0
namespace gamemd { void* WinMain_Helper_6C16C0() { return nullptr; } }
// 0x6C1840
namespace gamemd { void* WinMain_Helper_6C1840() { return nullptr; } }
// 0x6C19C0
namespace gamemd { void* WinMain_Helper_6C19C0() { return nullptr; } }
// 0x6C1B40
namespace gamemd { void* WinMain_Helper_6C1B40() { return nullptr; } }
// 0x6C1CC0
namespace gamemd { void* WinMain_Helper_6C1CC0() { return nullptr; } }
// 0x6C1E40
namespace gamemd { void* WinMain_Helper_6C1E40() { return nullptr; } }
// 0x6C1FC0
namespace gamemd { void* WinMain_Helper_6C1FC0() { return nullptr; } }
// 0x6C2140
namespace gamemd { void* WinMain_Helper_6C2140() { return nullptr; } }
// 0x6C22C0
namespace gamemd { void* WinMain_Helper_6C22C0() { return nullptr; } }
// 0x6C2440
namespace gamemd { void* WinMain_Helper_6C2440() { return nullptr; } }
// 0x6C25C0
namespace gamemd { void* WinMain_Helper_6C25C0() { return nullptr; } }
// 0x6C2740
namespace gamemd { void* WinMain_Helper_6C2740() { return nullptr; } }
// 0x6C28C0
namespace gamemd { void* WinMain_Helper_6C28C0() { return nullptr; } }
// 0x6C2A40
namespace gamemd { void* WinMain_Helper_6C2A40() { return nullptr; } }
// 0x6C2BC0
namespace gamemd { void* WinMain_Helper_6C2BC0() { return nullptr; } }
// 0x6C2D40
namespace gamemd { void* WinMain_Helper_6C2D40() { return nullptr; } }
// 0x6C2EC0
namespace gamemd { void* WinMain_Helper_6C2EC0() { return nullptr; } }
// 0x6C3040
namespace gamemd { void* WinMain_Helper_6C3040() { return nullptr; } }
// 0x6C31C0
namespace gamemd { void* WinMain_Helper_6C31C0() { return nullptr; } }
// 0x6C3340
namespace gamemd { void* WinMain_Helper_6C3340() { return nullptr; } }
// 0x6C34C0
namespace gamemd { void* WinMain_Helper_6C34C0() { return nullptr; } }
// 0x6C3640
namespace gamemd { void* WinMain_Helper_6C3640() { return nullptr; } }
// 0x6C37C0
namespace gamemd { void* WinMain_Helper_6C37C0() { return nullptr; } }
// 0x6C3940
namespace gamemd { void* WinMain_Helper_6C3940() { return nullptr; } }
// 0x6C3AC0
namespace gamemd { void* WinMain_Helper_6C3AC0() { return nullptr; } }
// 0x6C3C40
namespace gamemd { void* WinMain_Helper_6C3C40() { return nullptr; } }
// 0x6C3DC0
namespace gamemd { void* WinMain_Helper_6C3DC0() { return nullptr; } }
// 0x6C3F40
namespace gamemd { void* WinMain_Helper_6C3F40() { return nullptr; } }
// 0x6C40C0
namespace gamemd { void* WinMain_Helper_6C40C0() { return nullptr; } }
// 0x6C4240
namespace gamemd { void* WinMain_Helper_6C4240() { return nullptr; } }
// 0x6C43C0
namespace gamemd { void* WinMain_Helper_6C43C0() { return nullptr; } }
// 0x6C4540
namespace gamemd { void* WinMain_Helper_6C4540() { return nullptr; } }
// 0x6C46C0
namespace gamemd { void* WinMain_Helper_6C46C0() { return nullptr; } }
// 0x6C4840
namespace gamemd { void* WinMain_Helper_6C4840() { return nullptr; } }
// 0x6C49C0
namespace gamemd { void* WinMain_Helper_6C49C0() { return nullptr; } }
// 0x6C4B40
namespace gamemd { void* WinMain_Helper_6C4B40() { return nullptr; } }
// 0x6C4CC0
namespace gamemd { void* WinMain_Helper_6C4CC0() { return nullptr; } }
// 0x6C4E40
namespace gamemd { void* WinMain_Helper_6C4E40() { return nullptr; } }
// 0x6C4FC0
namespace gamemd { void* WinMain_Helper_6C4FC0() { return nullptr; } }
// 0x6C5140
namespace gamemd { void* WinMain_Helper_6C5140() { return nullptr; } }
// 0x6C52C0
namespace gamemd { void* WinMain_Helper_6C52C0() { return nullptr; } }
// 0x6C5440
namespace gamemd { void* WinMain_Helper_6C5440() { return nullptr; } }
// 0x6C55C0
namespace gamemd { void* WinMain_Helper_6C55C0() { return nullptr; } }
// 0x6C5740
namespace gamemd { void* WinMain_Helper_6C5740() { return nullptr; } }
// 0x6C58C0
namespace gamemd { void* WinMain_Helper_6C58C0() { return nullptr; } }
// 0x6C5A40
namespace gamemd { void* WinMain_Helper_6C5A40() { return nullptr; } }
// 0x6C5BC0
namespace gamemd { void* WinMain_Helper_6C5BC0() { return nullptr; } }
// 0x6C5D40
namespace gamemd { void* WinMain_Helper_6C5D40() { return nullptr; } }
// 0x6C5EC0
namespace gamemd { void* WinMain_Helper_6C5EC0() { return nullptr; } }
// 0x6C6040
namespace gamemd { void* WinMain_Helper_6C6040() { return nullptr; } }
// 0x6C61C0
namespace gamemd { int COM_SafeRelease() { return 0; } }
// 0x6C6B00
namespace gamemd { void* Audio_Read_6C6B00(void* a1) { return nullptr; } }
// 0x6C8870
namespace gamemd { int Audio_Read_6C8870() { return 0; } }
// 0x6C9900
namespace gamemd { void* Render_Parse() { return nullptr; } }
// 0x6C9F10
namespace gamemd { int ParseMovieSubtitles(void* a1) { return 0; } }
// 0x6CABA0
namespace gamemd { void* Render_Parse_6CABA0(int a1, int a2) { return nullptr; } }
// 0x6CEE60
namespace gamemd { int ObjectTypeClass_Read() { return 0; } }
// 0x6CF1D0
namespace gamemd { void SmallFunc_6CF1D0() { } }
// 0x6D04D0
namespace gamemd { int SidebarUpdateAll() { return 0; } }
// 0x6D1E30
namespace gamemd { void* SmallFunc_6D1E30(int a1) { return nullptr; } }
// 0x6D3290
namespace gamemd { int DrawBuildingAnimFrame(void* a1, void* a2, int a3) { return 0; } }
// 0x6D3470
namespace gamemd { int DrawBuildingShadow(void* a1, void* a2, int a3) { return 0; } }
// 0x6D5730
namespace gamemd { int RenderBridgeRadarBlips(int a1, void* a2) { return 0; } }
// 0x6D5C50
namespace gamemd { int RenderRadarBlips(int a1, int a2) { return 0; } }
// 0x6D6170
namespace gamemd { void* RequestMapSnapshot(void* a1) { return nullptr; } }
// 0x6D9CE0
namespace gamemd { int FindBuildingsInScreenRect(int a1, int a2, int a3, int a4) { return 0; } }
// 0x6DA9D0
namespace gamemd { void* RenderSelectionBeacons(int a1) { return nullptr; } }
// 0x6DAD60
namespace gamemd { int RenderRallyPointLines(int a1) { return 0; } }
// 0x6DB620
namespace gamemd { int RenderLWCViewCells() { return 0; } }
// 0x6DC420
namespace gamemd { int GetHeightMap() { return 0; } }
// 0x6E0490
namespace gamemd { int PlayWaypointEffect(int a1, int a2, int a3, int a4) { return 0; } }
// 0x6E14A0
namespace gamemd { int ProcessDataObjectClass(int a1, int a2, int a3, int a4) { return 0; } }
// 0x6E5FE0
namespace gamemd { int SaveTriggerTagsToINI() { return 0; } }
// 0x6E7330
namespace gamemd { int System_Read_6E7330() { return 0; } }
// 0x6E7C20
namespace gamemd { void* Network_Process_6E7C20() { return nullptr; } }
// 0x6EA0D0
namespace gamemd { void SelectTeamProductionBuilding() { } }
// 0x6ED200
namespace gamemd { int AssignTeamProductionFacilities(int a1, int a2) { return 0; } }
// 0x6EE800
namespace gamemd { int SelectTeamMembers(int a1, int a2) { return 0; } }
// 0x6EF110
namespace gamemd { int DispatchTeamOrders(int a1, int a2) { return 0; } }
// 0x6EF470
namespace gamemd { int Team_Create() { return 0; } }
// 0x6EF700
namespace gamemd { void DeployTeamMembersAtStart(int a1, int a2) { } }
// 0x6F2230
namespace gamemd { void* Team_Helper_6F2230(int a1, int a2) { return nullptr; } }
// 0x6F25E0
namespace gamemd { int Team_Helper_6F25E0(void* a1) { return 0; } }
// 0x6F26E0
namespace gamemd { void* Team_Helper_6F26E0(int a1) { return nullptr; } }
// 0x6F2780
namespace gamemd { void* Team_Helper_6F2780(void* a1) { return nullptr; } }
// 0x6F27F0
namespace gamemd { void* Team_Helper_6F27F0(int a1, void* a2) { return nullptr; } }
// 0x6FD800
namespace gamemd { int SpreadRadiationAreaEffect(int a1) { return 0; } }
// 0x706BD0
namespace gamemd { int QueueTechnoVoiceLine(void* a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11) { return 0; } }
// 0x707280
namespace gamemd { void* RenderTechnoOverlaySHP(void* a1, int a2, int a3, int a4, void* a5, int a6, int a7, int a8, int a9, int a10, int a11) { return nullptr; } }
// 0x7087C0
namespace gamemd { bool ValidateAttackTarget(void* a1, int a2) { return false; } }
// 0x70E5A0
namespace gamemd { int UpdateTechnoIdleTimer() { return 0; } }
// 0x70F1D0
namespace gamemd { int DrawBuildingRangeIndicator(void* a1, int a2) { return 0; } }
// 0x710750
namespace gamemd { int Object_Helper_710750(int a1) { return 0; } }
// 0x721D10
namespace gamemd { int SmallFunc_721D10() { return 0; } }
// 0x722440
namespace gamemd { void PropagateCellOccupancy() { } }
// 0x722F00
namespace gamemd { void RebuildBuildingOccupancy() { } }
// 0x724200
namespace gamemd { void HandleToolTipMessage(int a1) { } }
// 0x724510
namespace gamemd { int sub_724510(int a1) { return 0; } }
// 0x727880
namespace gamemd { int ReadAudioEventINI() { return 0; } }
// 0x729580
namespace gamemd { int FindUnitPlacementTarget() { return 0; } }
// 0x730990
namespace gamemd { int SidebarHasAvailableUnit() { return 0; } }
// 0x730A10
namespace gamemd { int SidebarCountAvailableUnits() { return 0; } }
// 0x7310D0
namespace gamemd { void SidebarClearReferences() { } }
// 0x7342C0
namespace gamemd { int SelectAllOfType_Helper() { return 0; } }
// 0x734330
namespace gamemd { void* SelectFactionThemeMusic_Helper_734330(int a1, int a2) { return nullptr; } }
// 0x734390
namespace gamemd { int SelectFactionThemeMusic_Helper_734390(void* a1) { return 0; } }
// 0x736DF0
namespace gamemd { int UpdateTechnoFiring() { return 0; } }
// 0x737180
namespace gamemd { int UpdateInfantryIdleWander() { return 0; } }
// 0x7436E0
namespace gamemd { int ReadFootINI() { return 0; } }
// 0x746D90
namespace gamemd { bool Event_Process_746D90() { return false; } }
// 0x74C9F0
namespace gamemd { int DestroyVeinholeMonster() { return 0; } }
// 0x74CDB0
namespace gamemd { int Helper_486E30_Helper() { return 0; } }
// 0x74D7C0
namespace gamemd { void UpdateVeinholeMonster() { } }
// 0x74E1C0
namespace gamemd { void ProcessVeinholeMonster() { } }
// 0x74E8A0
namespace gamemd { void System_Init_74E8A0() { } }
// 0x74EA70
namespace gamemd { int LoadVeinholeMonsters() { return 0; } }
// 0x74F620
namespace gamemd { void DestroyVeinholeMonster_Destroy() { } }
// 0x74F6F0
namespace gamemd { int DestroyVeinholeMonster_Destroy_74F6F0(int a1) { return 0; } }
// 0x750060
namespace gamemd { int Team_Create_750060(int a1) { return 0; } }
// 0x750440
namespace gamemd { int LoadVocFromINI(void* a1) { return 0; } }
// 0x751520
namespace gamemd { int System_Get_751520() { return 0; } }
// 0x7515C0
namespace gamemd { int System_Get_7515C0() { return 0; } }
// 0x756860
namespace gamemd { int InitializeTileAudioOcclusion(int a1, void* a2) { return 0; } }
// 0x758B70
namespace gamemd { int GenerateLightRemapTable(void* a1, int a2) { return 0; } }
// 0x7597A0
namespace gamemd { int Render_Load_7597A0() { return 0; } }
// 0x759830
namespace gamemd { int Render_Load_759830(int a1) { return 0; } }
// 0x759850
namespace gamemd { bool Render_Render_759850(int a1, int a2) { return false; } }
// 0x759880
namespace gamemd { bool Render_Render_759880(int a1, int a2, int a3) { return false; } }
// 0x759EA0
namespace gamemd { int Render_Load_759EA0() { return 0; } }
// 0x759EB0
namespace gamemd { bool Render_Load_759EB0(int a1, int a2, int a3, int a4, int a5) { return false; } }
// 0x759F20
namespace gamemd { int Render_Load_759F20(int a1) { return 0; } }
// 0x7639A0
namespace gamemd { int WaypointClass_Find(void* a1) { return 0; } }
// 0x764FA0
namespace gamemd { bool Team_Start_764FA0() { return false; } }
// 0x764FC0
namespace gamemd { bool ConstructWDTSelection_Create(int a1) { return false; } }
// 0x765380
namespace gamemd { void* FindWDTTerritoryClass_Find(void* a1, int a2) { return nullptr; } }
// 0x765410
namespace gamemd { void* Team_Start_765410(void* a1) { return nullptr; } }
// 0x765C90
namespace gamemd { void* Team_Create_765C90(int a1, void* a2) { return nullptr; } }
// 0x766060
namespace gamemd { int FindWDTTerritoryClass_Find_Find() { return 0; } }
// 0x7665D0
namespace gamemd { void* TerritorySelectWDT_Create(void* a1) { return nullptr; } }
// 0x7668F0
namespace gamemd { void* System_Init_7668F0() { return nullptr; } }
// 0x766900
namespace gamemd { void* System_Init_766900() { return nullptr; } }
// 0x766910
namespace gamemd { void* System_Init_766910() { return nullptr; } }
// 0x766A10
namespace gamemd { void* System_Init_766A10(int a1, int a2, void* a3, int a4) { return nullptr; } }
// 0x766EE0
namespace gamemd { int System_Init_766EE0(int a1) { return 0; } }
// 0x766F70
namespace gamemd { void* System_Init_766F70(int a1) { return nullptr; } }
// 0x767820
namespace gamemd { void* ConstructorWDTFlagOption_Create(int a1, void* a2, int a3, void* a4, int a5) { return nullptr; } }
// 0x768000
namespace gamemd { void* ConstructWDTSelection_Create_767FB0_Create(int a1, int a2, int a3) { return nullptr; } }
// 0x7692F0
namespace gamemd { int ConstructWDTSelection_Create_76EEB0_Create(void* a1, void* a2) { return 0; } }
// 0x7694C0
namespace gamemd { void* Map_Load_7694C0(void* a1) { return nullptr; } }
// 0x769C20
namespace gamemd { void* Map_Load_769C20(int a1) { return nullptr; } }
// 0x76A7E0
namespace gamemd { void* ConstructWDTSelection_Create_767FB0_Create_Create(int a1, void* a2) { return nullptr; } }
// 0x76AAF0
namespace gamemd { void* ParseWDTTerritories_Parse() { return nullptr; } }
// 0x76B180
namespace gamemd { int ParseWDTTerritories(int a1, int a2) { return 0; } }
// 0x76B790
namespace gamemd { void* ParseWDTTerritories_Parse_76B790(int a1) { return nullptr; } }
// 0x76BF00
namespace gamemd { void* Audio_Create_76BF00(int a1) { return nullptr; } }
// 0x76BFC0
namespace gamemd { int ConstructWDTSelection_Create_76BFC0() { return 0; } }
// 0x76C290
namespace gamemd { int ConstructWDTSelection(int a1, int a2) { return 0; } }
// 0x76C6E0
namespace gamemd { void SelectionInitializeWOL() { } }
// 0x76C970
namespace gamemd { void ConstructWDTSelection_Create_76C970(void* a1, int a2) { } }
// 0x76CA60
namespace gamemd { void ConstructWDTSelection_Create_76CA60(void* a1, void* a2) { } }
// 0x76CBF0
namespace gamemd { void ConstructWDTSelection_Create_76CBF0(void* a1, void* a2) { } }
// 0x76CDA0
namespace gamemd { int ShowWDTTerritorySelection(int a1) { return 0; } }
// 0x76DAD0
namespace gamemd { bool TerritorySelectWDT(int a1) { return false; } }
// 0x76E180
namespace gamemd { void ShowWDTTerritorySelection_Show() { } }
// 0x76E2F0
namespace gamemd { void* Team_Start_76E2F0(int a1) { return nullptr; } }
// 0x76E430
namespace gamemd { int Team_Start_76E430(int a1, void* a2) { return 0; } }
// 0x76E750
namespace gamemd { void* Team_Start_76E750(int a1) { return nullptr; } }
// 0x76E8B0
namespace gamemd { bool Team_Start_76E8B0(int a1, int a2) { return false; } }
// 0x76EEB0
namespace gamemd { int ConstructWDTSelection_Create_76EEB0() { return 0; } }
// 0x76F210
namespace gamemd { void* ConstructWDTSelection_Create_76F210(int a1, int a2) { return nullptr; } }
// 0x76F500
namespace gamemd { void* ConstructWDTSelection_Create_76F500() { return nullptr; } }
// 0x76FEB0
namespace gamemd { void TerritorySelectWDT_Process(int a1, void* a2) { } }
// 0x770430
namespace gamemd { void System_Init_770430() { } }
// 0x7714B0
namespace gamemd { void TerritorySelectWDT_Delete(int a1, int a2, int a3) { } }
// 0x771800
namespace gamemd { void* ConstructWDTSelection_Create_771800() { return nullptr; } }
// 0x776880
namespace gamemd { bool System_Read_776880() { return false; } }
// 0x7768A0
namespace gamemd { bool System_Read_7768A0() { return false; } }
// 0x778710
namespace gamemd { void* LoadAccountInfoWOL() { return nullptr; } }
// 0x779690
namespace gamemd { void* LoadAccountInfoWOL_Load(void* a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, void* a13, void* a14) { return nullptr; } }
// 0x779B50
namespace gamemd { void* ReadAutoLoginWOL() { return nullptr; } }
// 0x779C90
namespace gamemd { int ReadSettingsWOL() { return 0; } }
// 0x779DD0
namespace gamemd { void* LoadConfigWOL() { return nullptr; } }
// 0x779F10
namespace gamemd { int SavePersonaConfigWOL() { return 0; } }
// 0x77A080
namespace gamemd { void SaveProfileWOL(void* a1) { } }
// 0x77A760
namespace gamemd { int MainLobbyDlgProcWOL_Helper(int a1) { return 0; } }
// 0x77A780
namespace gamemd { int MainLobbyDlgProcWOL_Helper_77A780(int a1) { return 0; } }
// 0x77A7A0
namespace gamemd { int MainLobbyDlgProcWOL_Helper_77A7A0(int a1) { return 0; } }
// 0x77A870
namespace gamemd { int Event_Process_77A870(int a1) { return 0; } }
// 0x77A890
namespace gamemd { int Event_Process_77A890(int a1) { return 0; } }
// 0x77A8B0
namespace gamemd { int Event_Process_77A8B0(int a1) { return 0; } }
// 0x77A9F0
namespace gamemd { void FillPersonaInfoWOL() { } }
// 0x77D1F0
namespace gamemd { void ConnectAndLoginWOL_Connect() { } }
// 0x77D4C0
namespace gamemd { bool IsBuddyOrIgnoreWOL() { return false; } }
// 0x77E1D0
namespace gamemd { int FillPlayerListWOL() { return 0; } }
// 0x77E300
namespace gamemd { int FillBuddyListExWOL() { return 0; } }
// 0x77EBA0
namespace gamemd { int SendMultiplayerStartSignal_Start_77EBA0() { return 0; } }
// 0x783B80
namespace gamemd { int Render_Find() { return 0; } }
// 0x783C80
namespace gamemd { void DisplayRankingsWOL() { } }
// 0x785370
namespace gamemd { int InitializeWestwoodOnline() { return 0; } }
// 0x785740
namespace gamemd { void LeaveChannelWOL() { } }
// 0x7864C0
namespace gamemd { int ConnectAndLoginWOL() { return 0; } }
// 0x78A470
namespace gamemd { int HandleOnlineWOL() { return 0; } }
// 0x78A6B0
namespace gamemd { void* HandlePageWOL() { return nullptr; } }
// 0x78A8F0
namespace gamemd { void* HandleReplyWOL() { return nullptr; } }
// 0x78F200
namespace gamemd { void* BuildWOLPlayerTooltip() { return nullptr; } }
// 0x791AA0
namespace gamemd { void UI_Setup_791AA0() { } }
// 0x795650
namespace gamemd { int QueryNATPortWOL() { return 0; } }
// 0x798F50
namespace gamemd { void* MainLobbyDlgProcWOL_Read() { return nullptr; } }
// 0x79AF10
namespace gamemd { int FillBuddyListWOL() { return 0; } }
// 0x79C040
namespace gamemd { void ShowUserProfileWOL() { } }
// 0x79C8D0
namespace gamemd { void QueueWOLAuthRequest() { } }
// 0x7A28B0
namespace gamemd { void PlayerSkirmishSlotHandler_Handle_7A28B0() { } }
// 0x7A2FC0
namespace gamemd { void* System_Init_7A2FC0() { return nullptr; } }
// 0x7A41A0
namespace gamemd { void* System_Init_7A41A0() { return nullptr; } }
// 0x7AC610
namespace gamemd { void* CreateGameWOL_Create_7AC610() { return nullptr; } }
// 0x7AC670
namespace gamemd { int System_Init_7AC670() { return 0; } }
// 0x7AC680
namespace gamemd { int System_Init_7AC680() { return 0; } }
// 0x7AC9D0
namespace gamemd { int GetBuddyEntryWOL(void* a1, int a2) { return 0; } }
// 0x7ACB90
namespace gamemd { int StartGameWOL_Start_7ACB90(void* a1, int a2) { return 0; } }
// 0x7ACBE0
namespace gamemd { int ConnectAndLoginWOL_Connect_7ACBE0(void* a1, void* a2) { return 0; } }
// 0x7AD2F0
namespace gamemd { void* ResetSystemWOL_Reset(int a1) { return nullptr; } }
// 0x7AD410
namespace gamemd { void* System_Init_7AD410(int a1) { return nullptr; } }
// 0x7ADB00
namespace gamemd { int Network_Helper_7ADB00(void* a1, int a2) { return 0; } }
// 0x7AE180
namespace gamemd { bool ConnectAndLoginWOL_Connect_7AE180(void* a1, void* a2) { return false; } }
// 0x7AE7C0
namespace gamemd { bool GameOptionsScreenWOL_Helper_7AE7C0(void* a1, void* a2) { return false; } }
// 0x7AE830
namespace gamemd { void RemoveWOLPlayerLogin_Remove() { } }
// 0x7AE8E0
namespace gamemd { bool GameOptionsScreenWOL_Helper_7AE8E0(void* a1, void* a2) { return false; } }
// 0x7AECD0
namespace gamemd { void* QueryNATPortWOL_Helper(int a1, int a2) { return nullptr; } }
// 0x7AF3D0
namespace gamemd { void* GetRegionStringWOL() { return nullptr; } }
// 0x7AF500
namespace gamemd { void Team_Start_7AF500() { } }
// 0x7AF540
namespace gamemd { int WorldDominationFactionDlgProc_Helper() { return 0; } }
// 0x7B0490
namespace gamemd { void* Team_Start_7B0490() { return nullptr; } }
// 0x7B4A10
namespace gamemd { int String_Process_7B4A10(void* a1) { return 0; } }
// 0x7B6780
namespace gamemd { bool String_Helper(void* a1) { return false; } }
// 0x7B67C0
namespace gamemd { bool SendMultiplayerStartSignal_Start_77EBA0_Start(void* a1) { return false; } }
// 0x7B71D0
namespace gamemd { int Render_Helper_7B71D0() { return 0; } }
// 0x7B7660
namespace gamemd { int String_Helper_7B7660() { return 0; } }
// 0x7B7740
namespace gamemd { void* SendMultiplayerStartSignal_Start_77EBA0_Start_7B7740(void* a1) { return nullptr; } }
// 0x7B7980
namespace gamemd { int UI_Helper_7B7980() { return 0; } }
// 0x7BD170
namespace gamemd { int Audio_Render_7BD170() { return 0; } }
// 0x7BD290
namespace gamemd { int Audio_Process_7BD290() { return 0; } }
// 0x7BD2B0
namespace gamemd { int Audio_Process_7BD2B0() { return 0; } }
// 0x7BE4A0
namespace gamemd { int Audio_Process_7BE4A0() { return 0; } }
// 0x7BE660
namespace gamemd { int Audio_Process_7BE660() { return 0; } }
// 0x7BE670
namespace gamemd { int Audio_Render_7BE670() { return 0; } }
// 0x7C0490
namespace gamemd { int Audio_Process_7C0490() { return 0; } }
// 0x7C1150
namespace gamemd { int Audio_Render_7C1150() { return 0; } }
// 0x7C1A70
namespace gamemd { int Audio_Render_7C1A70() { return 0; } }
// 0x7C1BE0
namespace gamemd { int Audio_Render_7C1BE0() { return 0; } }
// 0x7C3750
namespace gamemd { int Audio_Process_7C3750() { return 0; } }
// 0x7CAACB
namespace gamemd { void* RTtypeid_Helper(void* a1) { return nullptr; } }
// 0x7DCDC0
namespace gamemd { void* ThrowErrorCOM_Helper(int a1, int a2, int a3) { return nullptr; } }
