#pragma once

// Auto-generated from tools/functions_by_module.json (render+ui module)
// 329 functions total: 155 member (80 classes) + 174 global

namespace gamemd {

class AircraftClass;
class BinkMovie;
class BinkMovieClass;
class BlitTransLucent25Alpha_ushort;
class BlitTransXlatAlphaZRead_ushort;
class ButtonOwnerDraw;
class CCToolTip;
class CDROM;
class CStreamClass;
class Campaign;
class CampaignClass;
class CampaignMenu;
class CampaignScore;
class CampaignScreen;
class CampaignSelect;
class CaptureManagerClass;
class ChatDialog;
class ComboBoxOwnerDraw;
class Commands;
class Credits;
class CreditsPower;
class CreditsScreen;
class DDraw;
class DSurface;
class Dialog;
class DialogClass;
class Display;
class DisplayClass;
class FontRenderer;
class GadgetClass;
class Game;
class GameSetup;
class InfantryClass;
class JumpjetLocomotionClass;
class LoadScreen;
class MSFrameAnim;
class MainMenu;
class Mouse;
class MouseClass;
class MultiplayerBattleTeam;
class MultiplayerConfig;
class MultiplayerGameMode;
class MultiplayerObserverTeam;
class MultiplayerSiege;
class MultiplayerSiegeDefenderTeam;
class Network;
class ObjectClass;
class Options;
class Palette;
class ParticleClass;
class Power;
class PowerBar;
class PowerClass;
class RadarClass;
class Render;
class ScoreScreen;
class Screen;
class ScreenCapture;
class ScreenCaptureCommandClass;
class ScreenEffect;
class Sidebar;
class SidebarClass;
class Skirmish;
class SkirmishDialog;
class SkirmishMapGen;
class SkirmishSetup;
class Surface;
class TabClass;
class TabControl;
class Tactical;
class TacticalClass;
class TechnoClass;
class TextRenderer;
class ToolTipManager;
class Voxel;
class VoxelClass;
class VoxelModel;
class VoxelRenderer;
class WonlineStringDialogControl_28;
class XSurface;

} // namespace gamemd
