// AUTO-GENERATED by tools/gen_gap2_stubs.py -- DO NOT EDIT MANUALLY.
// Gap 2 stub registry: IDA-confirmed no_cpp_body functions (annotation-only).
// Documents address<->symbol mapping for tools/audit_consistency.py.
// Wrapped in `#if 0` so this header is a no-op if ever #included (NEVER compiled).
#ifndef GAMEMD_RENDER_STUB_DECLS_HPP
#define GAMEMD_RENDER_STUB_DECLS_HPP
#if 0  // annotation-only; never compiled
// 0x40D280 [stub]
int MouseClass::ProcessInput();
// 0x40D290 [stub]
char * MouseClass::InitMouse(char p0);
// 0x40D540 [stub]
void MouseClass::initCursor();
// 0x40D570 [stub]
unsigned int MouseClass::updateCursorState(int p0);
// 0x40D720 [stub]
char MouseClass::selectCursor(int p0, int* p1);
// 0x40D7D0 [stub]
int MouseClass::getCursorFrame(int* p0);
// 0x40D850 [stub]
_DWORD * MouseClass::applyCursorSettings(char p0);
// 0x410CE0 [stub]
_DWORD * BSurface::Construct(int p0, int p1, int p2, int p3);
// 0x411330 [stub]
unsigned int TacticalClass::FillScanlinesTransparent(int p0, int p1, int p2, int p3);
// 0x411650 [stub]
char * BSurface::ScalarDtor(char p0);
// 0x41BFA0 [stub]
char TacticalClass::ProcessFrame();
// 0x41C030 [stub]
int TacticalClass::CheckAction();
// 0x41C050 [stub]
BOOL TacticalClass::ProcessTick();
// 0x41C150 [stub]
_DWORD * TacticalClass::ProcessTick2(int* p0);
// 0x41C160 [stub]
int TacticalClass::ProcessTick3(int p0);
// 0x42A6D0 [stub]
char * Tactical::ConstructTacticalSurface();
// 0x42C1C0 [stub]
_DWORD * MapClass::AllocArrays();
// 0x430980 [stub]
void Game::initScenario();
// 0x430F30 [stub]
char MapClass::isCellAccessible(int p0);
// 0x432690 [stub]
_DWORD * BinkMovie::Close(char* p0);
// 0x4326C0 [stub]
_DWORD * BinkMovie::Open(char* p0, int p1);
// 0x432700 [stub]
int BinkMovie::Stop();
// 0x432750 [stub]
char BinkMovie::InitFromFile(int* p0);
// 0x432BD0 [stub]
int BinkMovieHandle::Check(int p0);
// 0x432C30 [stub]
int BinkMovie::Pause(uint8_t p0);
// 0x432C50 [stub]
BOOL BinkMovie::IsAtEnd();
// 0x432C70 [stub]
int BinkMovie::Play();
// 0x432E40 [stub]
bool BinkMovie::RenderLoop(int p0, int p1, int p2);
// 0x433040 [stub]
bool BinkMovie::RenderFrameToSurface();
// 0x433060 [stub]
_DWORD * BinkMovieHandle::CopyFrameToSurface();
// 0x4331F0 [stub]
int BinkMovie::RenderSingleFrame(int p0, int p1, int p2, char p3);
// 0x433270 [stub]
_DWORD * BinkMovie::BlitToTarget(int p0);
// 0x433330 [stub]
int BinkMovie::AdjustSurfaceFormat(int p0);
// 0x43A5D0 [stub]
int Power::Update(int* p0);
// 0x45F1D0 [stub]
char TacticalClass::initTacticalMap(int* p0, int* p1);
// 0x46CCD0 [stub]
char CampaignClass::GetMapData(uint8_t*** p0);
// 0x46CFC0 [stub]
int CampaignClass::Stat(int* p0);
// 0x4758C0 [stub]
char MapClass::loadTheaterINI(uint8_t* p0, char* p1, int p2);
// 0x4790A0 [stub]
int Game::CheckForGameCD();
// 0x484050 [stub]
int Tactical::CreateTacticalLightSurface(int* p0, int* p1, int* p2, int* p3, int p4, int p5);
// 0x484180 [stub]
int Tactical::CalculateTacticalLighting(int* p0, int* p1, int* p2, int* p3, int* p4, int* p5, int64_t p6);
// 0x485130 [stub]
int MapClass::RemoveCellReference(int p0);
// 0x487630 [stub]
char DisplayClass::UpdateDisplayTimer();
// 0x487690 [stub]
int DisplayClass::AdvanceFrameCounter();
// 0x488EE0 [stub]
int ColorListClass::GetColor(int p0);
// 0x488F00 [stub]
char * ColorListClass::QueryInterface(char p0);
// 0x494500 [stub]
int BlitTransLucent25Alpha_ushort::CallBlit0(int p0, int p1, int p2, int p3, int p4, int p5, int p6);
// 0x494530 [stub]
int BlitTransLucent25Alpha_ushort::CallBlit0_0(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8);
// 0x494560 [stub]
int BlitTransLucent25Alpha_ushort::CallBlit0_1(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7);
// 0x494890 [stub]
int BlitTransXlatAlphaZRead_ushort::CallBlit0_2(int p0, int p1, int p2, int p3, int p4, int p5, int p6);
// 0x4948C0 [stub]
int BlitTransXlatAlphaZRead_ushort::CallBlit0_3(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8);
// 0x4948F0 [stub]
int BlitTransXlatAlphaZRead_ushort::CallBlit0_4(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7);
// 0x494920 [stub]
_WORD * BlitTransXlatAlphaZRead_ushort::Blit_Alpha_Lucent50(uint16_t* p0, uint8_t* p1, int p2, int p3, int p4, uint16_t* p5, int p6, int p7);
// 0x4949B0 [stub]
int BlitTransXlatAlphaZRead_ushort::CallBlit0_5(int p0, int p1, int p2, int p3, int p4, int p5, int p6);
// 0x4949E0 [stub]
int BlitTransXlatAlphaZRead_ushort::CallBlit0_6(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8);
// 0x494A10 [stub]
int BlitTransXlatAlphaZRead_ushort::CallBlit0_7(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7);
// 0x494A40 [stub]
_WORD * BlitTransXlatAlphaZRead_ushort::Blit_Alpha_Lucent50_0(uint16_t* p0, uint8_t* p1, int p2, int p3, int p4, uint16_t* p5, int p6, int p7);
// 0x494AD0 [stub]
int BlitTransXlatAlphaZRead_ushort::CallBlit0_8(int p0, int p1, int p2, int p3, int p4, int p5, int p6);
// 0x494B00 [stub]
int BlitTransXlatAlphaZRead_ushort::CallBlit0_9(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8);
// 0x494B30 [stub]
int BlitTransXlatAlphaZRead_ushort::CallBlit0_10(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7);
// 0x494C40 [stub]
int BlitTransXlatAlphaZRead_ushort::BlitRect(uint16_t* p0, uint8_t* p1, int p2, int p3, uint16_t* p4, uint16_t* p5, int p6, int p7, int16_t p8);
// 0x494D50 [stub]
int BlitTransXlatAlphaZRead_ushort::GetSize(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7);
// 0x496130 [stub]
int BlitTransLucent25AlphaZReadWrite_ushort::CallBlit0(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10);
// 0x496170 [stub]
int BlitTransLucent25AlphaZReadWrite_ushort::Blit_RLE_Remap(int p0, uint8_t* p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9);
// 0x496210 [stub]
int BlitTransLucent25AlphaZReadWrite_ushort::CallBlit0_0(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10);
// 0x496250 [stub]
_WORD * BlitTransLucent25AlphaZReadWrite_ushort::Blit_RLE_Lucent50(uint16_t* p0, uint8_t* p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9);
// 0x4962D0 [stub]
int BlitTransLucent25AlphaZReadWrite_ushort::CallBlit0_1(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10);
// 0x497880 [stub]
int RLEBlitTransZRemapXlatAlpha_ushort::CallBlit0_1(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10);
// 0x497A10 [stub]
unsigned __int16 * RLEBlitTransZRemapXlatAlpha_ushort::AddRef(int p0, uint8_t* p1, int p2, int p3, int p4, int p5, uint16_t* p6, int p7, int p8, int p9);
// 0x497B40 [stub]
int RLEBlitTransZRemapXlatAlpha_ushort::Release(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10);
// 0x49A340 [stub]
_DWORD * BlitTransLucent25Alpha_ushort::Blit(char p0);
// 0x49A420 [stub]
_DWORD * BlitTransXlatAlphaZRead_ushort::Blit(char p0);
// 0x49A720 [stub]
_DWORD * BlitTransLucent25AlphaZReadWrite_ushort::Blit(char p0);
// 0x49AA40 [stub]
_DWORD * RLEBlitTransZRemapXlatAlpha_ushort::QueryInterface(char p0);
// 0x49DB00 [stub]
int CampaignClass::LoadFromINI();
// 0x49E400 [stub]
char CampaignClass::FindMission(char* p0, int* p1);
// 0x49E4F0 [stub]
char CampaignClass::GetValue(int* p0);
// 0x49ECD0 [stub]
_DWORD * CampaignClass::Constructor(int p0, int p1);
// 0x49F090 [stub]
_DWORD * CampaignClass::Constructor_0(int p0, int p1);
// 0x4A1C10 [stub]
int Power::FinalizeDrain(int p0);
// 0x4A1CA0 [stub]
int Power::FlagProcess(int p0);
// 0x4A35F0 [stub]
char * Tactical::SetCellTransform(int p0, int p1, int p2, int p3, int p4, int p5);
// 0x4A4780 [stub]
LPDIRECTDRAW Surface::CreateSurfacePalette();
// 0x4A8730 [stub]
_DWORD * RadarClass::RenderSpySatellite();
// 0x4A8850 [stub]
int DisplayClass::LoadTypeData();
// 0x4A88C0 [stub]
int DisplayClass::SetSize();
// 0x4A8BF0 [stub]
int Mouse::SetBounds(const void* p0);
// 0x4A91B0 [stub]
_DWORD * Tactical::MouseMove(int* p0, int* p1);
// 0x4A95A0 [stub]
char MapClass::SetCellFlagsAlongPath(uint16_t* p0, uint16_t* p1);
// 0x4A9700 [stub]
void DisplayClass::Update(int p0, int p1);
// 0x4A9890 [stub]
char DisplayClass::UpdateCellPassability(int16_t* p0, int p1);
// 0x4A9DD0 [stub]
char DisplayClass::ProcessCellReveal(int16_t* p0, int p1);
// 0x4AA050 [stub]
bool DisplayClass::RevealFogCell(int16_t* p0, int p1);
// 0x4AAC10 [stub]
int DisplayClass::ProcessTacticalMouseInput(char p0, int p1, int p2);
// 0x4AAD30 [stub]
int TacticalClass::DispatchMode(int p0);
// 0x4AAE90 [stub]
int TacticalClass::HandlePlayerAction(int16_t* p0, char p1, void* p2, int p3, int p4);
// 0x4AC310 [stub]
char DisplayClass::InitViewBounds(int* p0);
// 0x4AC820 [stub]
char TacticalClass::SetObserverMode(int p0);
// 0x4AC960 [stub]
int MapClass::ToggleZoom(int p0);
// 0x4ACAC0 [stub]
int MapClass::ProcessVisibilityFlags();
// 0x4ACBC0 [stub]
int MapClass::ProcessFogTransition();
// 0x4ACDA0 [stub]
char MapClass::RevealCell(int16_t* p0);
// 0x4AD7E0 [stub]
int MapClass::SaveCellTagsToINI(char* p0);
// 0x4AE450 [stub]
int TacticalClass::Initialize();
// 0x4AE4F0 [stub]
wchar_t * DisplayClass::Draw(int p0);
// 0x4AEAD0 [stub]
int DisplayClass::ExitMode();
// 0x4AEB10 [stub]
int MapClass::GetScrollMode();
// 0x4AEB30 [stub]
bool MapClass::SetScrollMode(int p0);
// 0x4AEBB0 [stub]
_DWORD * DisplayClass::updateRenderState(char p0);
// 0x4AEBF0 [stub]
char * DisplayClass::Read(char p0);
// 0x4AEC30 [stub]
int * DisplayClass::processDisplayMode(char p0);
// 0x4AEC60 [stub]
_DWORD * Surface::Construct(int p0, int p1);
// 0x4C6B60 [stub]
char * SidebarClass::SetFlashEntry(int p0, char p1, int p2, uint16_t* p3);
// 0x4D0980 [stub]
int FoggedObjectClass::InitBuildingFog(int* p0, int p1, int p2);
// 0x4D0C40 [stub]
int FoggedObjectClass::InitTerrainFog(int* p0, int p1, int p2);
// 0x4D0EF0 [stub]
int FoggedObjectClass::Constructor(int* p0, char p1);
// 0x4D1370 [stub]
int FoggedObjectClass::InitDrawRecord(int* p0);
// 0x4D2810 [stub]
int FoggedObjectClass::PowerDrainUpdate(int p0);
// 0x4D28D0 [stub]
_DWORD * FoggedObjectClass::CheckVisibility(int* p0);
// 0x4D29B0 [stub]
char FoggedObjectClass::AddRef(int p0);
// 0x4D2BC0 [stub]
char FoggedObjectClass::ResizeArray(int p0, char* p1);
// 0x4D2CD0 [stub]
int FoggedObjectClass::Read(int* p0);
// 0x4D2D10 [stub]
_DWORD * FoggedObject_DrawVector::QueryInterface(char p0);
// 0x4D2D60 [stub]
_DWORD * FoggedObjectClass::QueryInterface(char p0);
// 0x4E12F0 [stub]
_DWORD * GadgetClass::Construct(int p0, int p1, int p2, int p3, int p4, char p5);
// 0x4E1550 [stub]
int GadgetClass::ClearState(int p0);
// 0x4E1A60 [stub]
_DWORD * GadgetClass::QueryInterface(char p0);
// 0x4F1720 [stub]
HWND Options::InitDialogControls();
// 0x4F4450 [stub]
char Tactical::SelectObject(int p0);
// 0x4FA350 [stub]
int Sidebar::StartSidebarProduction(void* p0, int p1, char p2, char p3);
// 0x4FB840 [stub]
char BuildingPlacement::Activate(int p0, int* p1);
// 0x5005B0 [stub]
char SidebarClass::MarkTabForRebuild(int p0, char p1, int p2);
// 0x500700 [stub]
char SidebarClass::getTypeProductionCount(int p0, char p1, int p2);
// 0x5007A0 [stub]
char Sidebar::Dispatch(int p0, char p1, int p2, char p3);
// 0x533F50 [stub]
int Sidebar::ScrollSidebarSkipGame();
// 0x53EC90 [stub]
SHORT Mouse::GetKeyState();
// 0x540D10 [stub]
int TacticalClass::SetCameraPosition(int p0, int p1, int p2);
// 0x547020 [stub]
int MapClass::LoadFileData();
// 0x54C550 [stub]
char BuildingPlacement::ProcessBuildingPlacementAction();
// 0x550000 [stub]
int Game::loadCampaignData();
// 0x5519B0 [stub]
bool DisplayClass::RenderStatusText(int p0, char p1);
// 0x551A90 [stub]
int DisplayClass::InsertPriorityText(int p0);
// 0x554760 [stub]
_DWORD * LightSourceClass::Construct(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7);
// 0x554830 [stub]
int LightSourceClass::Constructor();
// 0x554A80 [stub]
char MapClass::ScrollOnce(char p0);
// 0x554AA0 [stub]
char TacticalClass::UpdateScrollTarget(int p0, int p1, int p2, int p3, char p4);
// 0x554AF0 [stub]
char TacticalClass::ScrollView(char p0);
// 0x555070 [stub]
int LightSourceClass::Stat(int p0);
// 0x555150 [stub]
void ** LightSourceClass::CopyTo(char p0);
// 0x556B30 [stub]
int TacticalClass::GetField();
// 0x557AE0 [stub]
int ColorListClass::SetColor();
// 0x557BE0 [stub]
int GadgetClass::InitControls();
// 0x557F40 [stub]
int ColorListClass::Clear(unsigned int p0);
// 0x558010 [stub]
void ColorListClass::RemoveColor(int* p0);
// 0x558840 [stub]
bool Options::PrepareSaveLoadDlg();
// 0x55AF40 [stub]
void RadarClass::SetGlobal();
// 0x55FAA0 [stub]
HWND Options::Screen_Save();
// 0x565090 [stub]
int RadarClass::RenderMapPreview();
// 0x565190 [stub]
char * RadarClass::Render(int p0);
// 0x565800 [stub]
int MapClass::Destru_vt05();
// 0x5659F0 [stub]
void MapClass::Destru_vt07();
// 0x565AA0 [stub]
int MapClass::InitCellVector();
// 0x565B00 [stub]
int MapClass::FreeAllCells();
// 0x565BC0 [stub]
_DWORD * MapClass::InitAllCells();
// 0x5673A0 [stub]
int MapClass::RevealArea0(int* p0, int p1, int* p2, char p3, char p4, char p5, char p6, char p7);
// 0x568350 [stub]
bool Tactical::IsCellVisible(int* p0);
// 0x5683C0 [stub]
void MapClass::FillRevealBuffer(uint16_t* p0, uint8_t* p1);
// 0x5687F0 [stub]
void MapClass::ApplyOverlayReveal(uint16_t* p0, char* p1);
// 0x568BB0 [stub]
int MapClass::PostProcessReveal(char p0);
// 0x56B3F0 [stub]
int MapClass::DecompressCellData(int p0);
// 0x56D230 [stub]
int MapClass::GetTileIndex(int16_t* p0, int p1, char p2);
// 0x56D6E0 [stub]
int MapClass::ProcessRegion();
// 0x56DAE0 [stub]
char MapClass::ClearRegions(int16_t* p0);
// 0x574C20 [stub]
void MapClass::ApplyTerrainDamage(int16_t* p0);
// 0x577F30 [stub]
#375 * MapClass::ClearShroud(int p0);
// 0x578390 [stub]
BOOL MapClass::IsRectInBounds();
// 0x578710 [stub]
void * MapClass::SpiralSearch();
// 0x578880 [stub]
_DWORD * MapClass::FastCellLookup(int16_t* p0, int p1, char p2);
// 0x578AC0 [stub]
void MapClass::IncrementRedrawCounter();
// 0x57A320 [stub]
int MapClass::BuildTileConnectivityGraph(int p0, int p1, int p2);
// 0x581F50 [stub]
_DWORD * MapClass::BuildSubzones();
// 0x582D70 [stub]
int RadarClass::RenderBlips(int* p0, int p1);
// 0x5856B0 [stub]
char MapClass::InitializeTileData(int p0);
// 0x585D00 [stub]
char MapClass::LoadTerrainData(int p0);
// 0x586780 [stub]
bool MapClass::IsAreaFree(int* p0, int p1);
// 0x588BF0 [stub]
char * MapClass::Destru_vt04(char p0);
// 0x588DE0 [stub]
unsigned int MapClass::initCellVectors(int p0);
// 0x588EF0 [stub]
int MapClass::InitCellVe_vt06(int p0);
// 0x589060 [stub]
_DWORD * MapClass::InitCellVe_vt00(char p0);
// 0x589370 [stub]
char MapClass::AllocateCellDataBuffer(int p0, char* p1);
// 0x5894A0 [stub]
void MapClass::allocateCellArrays();
// 0x5894D0 [stub]
int MapClass::FindSubzoneConnectionIndex(uint16_t* p0);
// 0x589530 [stub]
unsigned int MapClass::initSubzoneData(int p0);
// 0x589A60 [stub]
char MapClass::AllocateMapDataBuffer(int p0, int* p1);
// 0x589BD0 [stub]
_DWORD * MapClass::allocateMapBuffers();
// 0x589CA0 [stub]
char MapClass::InitCellVe_vt01(int p0);
// 0x589CE0 [stub]
char MapClass::InitCellVe_vt02(int p0, int* p1);
// 0x589D90 [stub]
void MapClass::InitCellVe_vt03();
// 0x589DC0 [stub]
int MapClass::InitCellVe_vt04(int* p0);
// 0x589E00 [stub]
unsigned int MapClass::InitCellVe_vt05(int p0);
// 0x589E20 [stub]
char RadarClass::updateRadarCells(int p0, int* p1);
// 0x58ADB0 [stub]
_DWORD * RadarClass::drawRadarTerrain(int p0, int p1);
// 0x58AE60 [stub]
_DWORD * RadarClass::RenderJammerRadius(int p0, int* p1);
// 0x58AF80 [stub]
char RadarClass::drawRadarEvents(int* p0);
// 0x58C2A0 [stub]
char * Tactical::GetCellData();
// 0x594F40 [stub]
_DWORD * BuildingPlacement::SelectBuildingPlacementCells(int p0);
// 0x597260 [stub]
int Skirmish::RandomizeSettings(int p0);
// 0x599530 [stub]
int MapClass::ProcessTile();
// 0x5A0410 [stub]
char MapClass::GrowLayer(int p0, int p1, int p2);
// 0x5AC5A0 [stub]
void MapClass::checkCellBounds();
// 0x5AC5D0 [stub]
unsigned int MapClass::validateCellCoord(int p0);
// 0x5AD0C0 [stub]
int MapClass::updatePathfindingGrid(int* p0);
// 0x5AE220 [stub]
char CampaignClass::LoadMovieDisplay(int p0);
// 0x5AE460 [stub]
int CampaignClass::ReleaseSubobjectsAndDestruct();
// 0x5B56F0 [stub]
void Game::processStartup();
// 0x5B7090 [stub]
char Game::StartModemMultiplayer(char p0);
// 0x5BA660 [stub]
int Game::BuildGameSetupPacket();
// 0x5BDAA0 [stub]
int MouseClass::GetPosition();
// 0x5BDAB0 [stub]
char MouseClass::SetPosition(char p0);
// 0x5BDC80 [stub]
char Mouse::SetCursor(int p0, char p1);
// 0x5BDF30 [stub]
void * MouseClass::LoadTypeData();
// 0x5BDF50 [stub]
int MouseClass::HandleClick();
// 0x5BDF70 [stub]
int MouseClass::LoadGameAssets();
// 0x5BE6D0 [stub]
HRESULT MouseClass::DrawCursor();
// 0x5BE9B0 [stub]
_DWORD * MouseClass::drawCursor(int p0);
// 0x5BEA30 [stub]
_DWORD * MouseClass::loadCursor(int p0, int p1);
// 0x5C01F0 [stub]
void BinkMovie::Cleanup();
// 0x5C0540 [stub]
int BinkMovieHandle::?(uint8_t p0);
// 0x5C0550 [stub]
int BinkMovieHandle::InitFromFile();
// 0x5C0570 [stub]
BOOL BinkMovieHandle::COMStub();
// 0x5C0580 [stub]
bool BinkMovieHandle::AddRef();
// 0x5C0590 [stub]
int BinkMovieHandle::Release();
// 0x5C05A0 [stub]
int BinkMovieHandle::Pause(int p0, int p1);
// 0x5C05C0 [stub]
int BinkMovieHandle::RenderLoop(int p0);
// 0x5C05D0 [stub]
int BinkMovieHandle::AdjustSurfaceFormat(int p0);
// 0x5C05E0 [stub]
unsigned int BinkMovieHandle::BlitToTarget();
// 0x5C05F0 [stub]
_DWORD * BinkMovieHandle::Close();
// 0x5C0A30 [stub]
_DWORD * BinkMovieHandle::QueryInterface(char p0);
// 0x5C0A70 [stub]
void TacticalClass::ClearVector();
// 0x5C0AA0 [stub]
unsigned int TacticalClass::ProbeCalling(int p0);
// 0x5C0AC0 [stub]
int TacticalClass::ProbeCalling2(int p0);
// 0x5C0AD0 [stub]
char TacticalClass::CompareVector(int p0);
// 0x5C0C50 [stub]
char TacticalClass::ReallocVector(int p0, int* p1);
// 0x5C0D00 [stub]
int TacticalClass::FindInVector(int* p0);
// 0x5C0D80 [stub]
_DWORD * TacticalClass::DestroyVector(char p0);
// 0x5C2500 [stub]
void Campaign::SetupMovie();
// 0x5CA110 [stub]
int Game::GetMultiplayerScoreScreenBar();
// 0x5CF760 [stub]
int CampaignClass::DeleteAndZero(const char** p0);
// 0x5CF810 [stub]
int CampaignClass::Check(uint16_t p0);
// 0x5D1FD0 [stub]
_DWORD * Surface::CopyRect(int* p0);
// 0x5D2E00 [stub]
_BYTE * CampaignClass::Constructor_1(int16_t p0);
// 0x5D49A0 [stub]
char TacticalMap::DrawCursor();
// 0x5D4AD0 [stub]
char TacticalClass::processInput(int p0);
// 0x5D7F20 [stub]
char * MultiplayerGameMode::QueryInterface(char p0);
// 0x5D89F0 [stub]
_DWORD * MultiplayerGameMode::ConstructMultiplayerGameModeVectorClass(int p0, int p1);
// 0x5DBB60 [stub]
void Game::BuildGameSettingsPacket();
// 0x5F60A0 [stub]
int MapClass::SetCellOverlayFlag();
// 0x5F6120 [stub]
int MapClass::ClearCellOverlayFlag();
// 0x5F6220 [stub]
bool DisplayClass::checkScreenBounds(int p0);
// 0x60CBA0 [stub]
int CampaignScore::LookupDialogHash();
// 0x60CC00 [stub]
int CampaignScore::FindDialogTemplate();
// 0x60D320 [stub]
int GameSetup::LookupDialogHash();
// 0x622720 [stub]
HWND Dialog::Destroy();
// 0x622800 [stub]
int Dialog::Show();
// 0x623560 [stub]
void GadgetClass::SetTooltip(int* p0);
// 0x623610 [stub]
_DWORD * DialogClass::CopyTemplateStruct(int* p0);
// 0x624460 [stub]
void Options::ClearComboBoxes();
// 0x6244E0 [stub]
int Options::DeleteAndZero();
// 0x6248A0 [stub]
char Options::EnsureCapacity();
// 0x6253B0 [stub]
char Options::GrowBuffer();
// 0x6254D0 [stub]
char Options::ReadOptionValue();
// 0x625560 [stub]
void * Options::DestroyComposite(char p0);
// 0x6255F0 [stub]
int * Options::RebuildDropdownList(int* p0);
// 0x6258E0 [stub]
void ComboBoxOwnerDraw::SetCapacity();
// 0x625990 [stub]
char ComboBoxOwnerDraw::GrowBuffer();
// 0x625A20 [stub]
char Options::SaveOptionValue();
// 0x631E30 [stub]
_DWORD * TacticalClass::saveConfig(int p0);
// 0x636310 [stub]
void Sidebar::CancelSidebarProductionQueue();
// 0x637060 [stub]
void TabClass::processTabInput();
// 0x637AB0 [stub]
int SidebarClass::ResetProductionState();
// 0x63E880 [stub]
char SidebarClass::addToList(int* p0);
// 0x63F040 [stub]
char Sidebar::RemoveItem(int p0);
// 0x63F6B0 [stub]
int RadarClass::Create();
// 0x63F730 [stub]
PowerClass * PowerClass::updateDrain();
// 0x63F7C0 [stub]
void PowerClass::checkBlackout();
// 0x63FB20 [stub]
int Sidebar::Render(char p0);
// 0x63FEA0 [stub]
void PowerClass::updatePowerBarAnimation();
// 0x6403A0 [stub]
char PowerClass::getDrain();
// 0x640450 [stub]
wchar_t * PowerClass::getAvailable(int p0);
// 0x6404B0 [stub]
_DWORD * PowerClass::Initialize(char p0);
// 0x640710 [stub]
int Skirmish::RenderPreview();
// 0x641DB0 [stub]
char Surface::LoadToSurfaceSHP(char* p0);
// 0x642C80 [stub]
char TextRenderer::MeasureBuilding(int p0, int p1, int p2, char p3, char p4);
// 0x643E60 [stub]
BOOL LoadScreen::IsActive();
// 0x652960 [stub]
_DWORD * RadarClass::Construct();
// 0x652CF0 [stub]
int RadarClass::Destru_vt05();
// 0x652DE0 [stub]
void RadarClass::Destru_vt07();
// 0x652E90 [stub]
int RadarClass::Destru_vt53();
// 0x653100 [stub]
char RadarClass::Destru_vt16(char p0);
// 0x654320 [stub]
char RadarClass::Destru_vt34();
// 0x654EA0 [stub]
int RadarClass::UpdateBlips(int p0, int* p1);
// 0x655250 [stub]
int Surface::RenderRadar();
// 0x655990 [stub]
int RadarClass::Process();
// 0x655A90 [stub]
void TacticalClass::FreeResources();
// 0x655B20 [stub]
void RadarClass::InitializeHashTable();
// 0x6563B0 [stub]
char RadarClass::UpdateFoundationShapesCustom();
// 0x6568A0 [stub]
int SidebarClass::Load(int p0);
// 0x656AC0 [stub]
int SidebarClass::Save(int p0);
// 0x656BE0 [stub]
void RadarClass::Toggle(char p0, char p1);
// 0x656CB0 [stub]
int RadarClass::SetViewMode(int p0, char p1);
// 0x656E50 [stub]
int RadarClass::IsActiveMode();
// 0x656E90 [stub]
BOOL RadarClass::SetFlag();
// 0x6578F0 [stub]
void TacticalClass::ProcessChronoEffect();
// 0x6579E0 [stub]
unsigned __int8 Game::ManageGameSpeed();
// 0x657CE0 [stub]
int FogOfWar::Render();
// 0x658770 [stub]
wchar_t * RadarClass::Destru_vt33(int p0);
// 0x6587A0 [stub]
_DWORD * RadarClass::Destru_vt04(char p0);
// 0x65ACE0 [stub]
int TacticalClass::UpdateObjects();
// 0x6612C0 [stub]
unsigned __int8 Color::Lerp(uint8_t p0, uint8_t* p1);
// 0x661350 [stub]
int Palette::CalcColorDistance(uint8_t* p0);
// 0x674650 [stub]
int SidebarClass::ReadButtonList();
// 0x67C3A0 [stub]
_DWORD * Game::LockMutex(int p0, int p1);
// 0x67C6E0 [stub]
_DWORD * Power::UpdateAll();
// 0x67E440 [stub]
char Game::LoadSaved();
// 0x67F9C0 [stub]
int Game::SerializeGameSaveState();
// 0x67FDE0 [stub]
int Game::readIniSettings();
// 0x680F70 [stub]
int Game::validateScenario(int* p0);
// 0x68B940 [stub]
int Power::ComputeHousePowerChecksum(unsigned int* p0);
// 0x690360 [stub]
int Screen::CleanupTransitionObjects();
// 0x692F30 [stub]
void TacticalClass::ProcessView();
// 0x693060 [stub]
bool MouseClass::GetHotspot();
// 0x6930A0 [stub]
char Tactical::HandleTacticalMouseInput();
// 0x693840 [stub]
int MouseClass::GetButtonState(int p0);
// 0x693880 [stub]
char MouseClass::CheckCapture(int* p0);
// 0x6938C0 [stub]
HWND Mouse::ReleaseCapture();
// 0x698CB0 [stub]
char Game::DumpMultiplayerGameInfo(int* p0);
// 0x698F90 [stub]
int GameSetup::WriteINI(char* p0, uint8_t* p1);
// 0x69DFC0 [stub]
char SidebarClass::startButtonFlash(int p0, int p1, char p2);
// 0x69E010 [stub]
char SidebarClass::updateFlashTimer();
// 0x6A4E60 [stub]
char * TabClass::initTabData();
// 0x6A5310 [stub]
char SidebarClass::Init();
// 0x6A5F20 [stub]
char SidebarClass::UpdateCameoProductionState(int* p0);
// 0x6A6140 [stub]
char Sidebar::FindProductionType(int p0, int p1, int p2);
// 0x6A6610 [stub]
int Tactical::UpdateUIVisibility();
// 0x6A70E0 [stub]
void Sidebar::FlushSidebarTooltip(char p0);
// 0x6A7780 [stub]
void SidebarClass::UpdateStrips(int* p0, int* p1);
// 0x6A80A0 [stub]
_BYTE * TabClass::updateTabProduction(int p0);
// 0x6A8220 [stub]
int SidebarClass::InitCameoGrid(int p0);
// 0x6A8330 [stub]
char SidebarClass::RefreshCameoGrid();
// 0x6A83E0 [stub]
char SidebarClass::sortCameoList();
// 0x6A8B30 [stub]
char SidebarClass::UpdateCameos(int p0, int p1);
// 0x6AA600 [stub]
char SidebarClass::UpdateProduction();
// 0x6AAD00 [stub]
int SidebarClass::ProcessInput(int p0, int* p1, char p2);
// 0x6AC5D0 [stub]
int SidebarClass::saveLoadPrefix(int p0);
// 0x6AC5E0 [stub]
int SidebarClass::saveLoadPrefix2(int p0);
// 0x6AC780 [stub]
_DWORD * SidebarClass::queryInterface(char p0);
// 0x6AC7C0 [stub]
int TabClass::drawTabBackground();
// 0x6AC870 [stub]
_BYTE * SidebarClass::initButtons();
// 0x6ACD60 [stub]
HWND Skirmish::EnableSpawnButtons();
// 0x6C9930 [stub]
void BinkMovie::Destroy();
// 0x6C99D0 [stub]
_DWORD * BinkMovie::CreateSurfaceTracker();
// 0x6C9AE0 [stub]
int BinkMovie::FreeSurfaceTracker();
// 0x6C9B40 [stub]
char BinkMovie::InitKeyframeTracking(char* p0);
// 0x6C9C60 [stub]
char BinkMovie::CheckKeyframeTransition(unsigned int p0);
// 0x6C9D40 [stub]
void BinkMovie::ProcessKeyframe(int* p0);
// 0x6C9EC0 [stub]
_DWORD * BinkMovie::VtableDispatch(int p0);
// 0x6CBEE0 [stub]
int SidebarClass::GetProductionState();
// 0x6CFCC0 [stub]
int SidebarClass::findEntryIndexByName();
// 0x6CFE20 [stub]
TabClass * TabClass::Constructor();
// 0x6D02B0 [stub]
int SidebarClass::LoadButtonSHPs();
// 0x6D03A0 [stub]
char SidebarClass::InitButtons();
// 0x6D0A20 [stub]
int SidebarClass::DrawTabs(char p0);
// 0x6D2420 [stub]
int TacticalClass::SetPosition(int* p0, int p1);
// 0x6D2B60 [stub]
int TacticalMap::RenderCell(char p0, int p1, int p2, int p3);
// 0x6D3870 [stub]
int TacticalClass::ClickFindBuilding(int* p0, int* p1, char p2);
// 0x6D3AC0 [stub]
int TacticalClass::ClickFindOverlay(int* p0, int* p1, char p2);
// 0x6D3D10 [stub]
int TacticalMap::Render(int p0, int p1, int p2);
// 0x6D4E20 [stub]
void Tactical::DisplayTacticalOverlayText(int* p0);
// 0x6D5030 [stub]
char RadarClass::DrawBlips(char p0);
// 0x6D59D0 [stub]
int RadarClass::DrawBlip(char p0, int p1);
// 0x6D6070 [stub]
unsigned int Tactical::SetTacticalPosition(int* p0);
// 0x6D6590 [stub]
_DWORD * Tactical::PixelToCell(int* p0, int* p1);
// 0x6D8260 [stub]
unsigned int MapClass::TransformCoordToScreen(int p0, int* p1);
// 0x6D8530 [stub]
int DisplayClass::ScrollTacticalView(int p0, int p1);
// 0x6D8DB0 [stub]
int TacticalMap::RenderAllObjects(int p0);
// 0x6D9F80 [stub]
int TacticalClass::InitScrollBounds(int* p0);
// 0x6D9FC0 [stub]
int TacticalClass::UpdateScrollMaxBounds(int* p0);
// 0x6DA160 [stub]
int TacticalClass::ResetScrollBounds();
// 0x6DA180 [stub]
int TacticalMap::DrawOccupiedRegion();
// 0x6DA230 [stub]
int DisplayClass::GetCoordDelta(int p0);
// 0x6DA7D0 [stub]
int Tactical::AddCellToDrawList(int p0);
// 0x6DB210 [stub]
int Tactical::DrawTacticalConnectorLines();
// 0x6DBB60 [stub]
char Tactical::DrawOverlay(int* p0, int* p1, int p2, int p3);
// 0x6DC470 [stub]
_DWORD * Tactical::UpdateView(char p0);
// 0x6E4970 [stub]
int Tactical::Init(int* p0);
// 0x6EE100 [stub]
int TacticalClass::Get(int p0, int p1);
// 0x703590 [stub]
_DWORD * MapClass::FindPlacementCellsAlt(int* p0, int p1);
// 0x707480 [stub]
void Surface::BlitTechnoTo(int16_t* p0, int* p1, int* p2, int p3, int p4, int p5);
// 0x723EA0 [stub]
int GadgetClass::Show();
// 0x723EB0 [stub]
int GadgetClass::Hide();
// 0x723EC0 [stub]
int GadgetClass::ProcessMouseOver(unsigned int p0, int* p1, int p2);
// 0x724520 [stub]
int SidebarClass::initializeStrip(int p0);
// 0x724530 [stub]
int SidebarClass::updateStripVisibility();
// 0x724540 [stub]
int SidebarClass::updateStripPosition();
// 0x724AB0 [stub]
int ToolTipManager::release(int p0);
// 0x727CD0 [stub]
void * TextRenderer::Destructor(char p0);
// 0x72AD20 [stub]
int * Display::GetViewport();
// 0x72AD90 [stub]
int * SidebarClass::calcSidebarRect();
// 0x72B820 [stub]
int Palette::LoadFile();
// 0x72D300 [stub]
char CampaignScore::LoadCampaignScoreAssetsGame();
// 0x72D460 [stub]
void * CampaignScore::LoadScreenAssets();
// 0x72D730 [stub]
char Game::LoadMultiplayerScoreAssets();
// 0x72D830 [stub]
void * Game::shutdownGame();
// 0x72F440 [stub]
char Game::InitializeToolTipColor();
// 0x7311C0 [stub]
int TacticalClass::SetObserverView();
// 0x7313A0 [stub]
int TacticalClass::ResetView();
// 0x734250 [stub]
int SidebarClass::registerBuildingType();
// 0x7343E0 [stub]
_DWORD * TacticalClass::updateScroll(int p0, int p1);
// 0x750090 [stub]
char Power::ChangedHouse(char p0);
// 0x759FB0 [stub]
BOOL VoxelRenderer::InitializeBuffers();
// 0x75F540 [stub]
_DWORD * Color::RGBFromFloat(int p0, float p1);
// 0x75F5C0 [stub]
_DWORD * TacticalClass::CalcInverseAlpha(int p0, float p1);
// 0x7602E0 [stub]
void Surface::RenderToSurfaceVoxel(int* p0, int* p1);
// 0x769330 [stub]
int Surface::PixelToIndex(int* p0);
// 0x769BD0 [stub]
_DWORD * MSFrameAnim::QueryInterface(char p0);
// 0x769C50 [stub]
int MSFrameAnim::initAnimation();
// 0x769C80 [stub]
unsigned int MSFrameAnim::startAnimation(int p0);
// 0x769CD0 [stub]
void MSFrameAnim::stopAnimation();
// 0x769D00 [stub]
unsigned int MSFrameAnim::pauseAnimation(int p0);
// 0x769D90 [stub]
_DWORD * MSFrameAnim::resumeAnimation(char p0);
// 0x769FE0 [stub]
char MSFrameAnim::setFrameRate(int p0, int* p1);
// 0x76A100 [stub]
int MSFrameAnim::getCurrentFrame(int p0);
// 0x76A2B0 [stub]
char MSFrameAnim::loopAnimation(int p0, int* p1);
// 0x76A360 [stub]
int MSFrameAnim::resetAnimation(int* p0);
// 0x76A680 [stub]
_DWORD * MSFrameAnim::setPosition(char p0);
// 0x76A720 [stub]
_DWORD * MSFrameAnim::setScale(char p0);
// 0x76A7C0 [stub]
_DWORD * MSFrameAnim::drawFrame();
// 0x77A700 [stub]
char GadgetClass::TrackState(int p0, int p1);
// 0x77DA50 [stub]
void * SidebarClass::FindProductionData();
// 0x77E430 [stub]
void Game::EncodeGameSetupState();
// 0x7A2330 [stub]
char Game::SetupWOLTournament();
// 0x7B8730 [stub]
_DWORD * MouseClass::Construct(int p0, int p1);
// 0x7B8960 [stub]
void MouseClass::CalcConfiningRect();
// 0x7B8C60 [stub]
bool BSurface::CreateTripleBuffer();
// 0x7B93F0 [stub]
void Mouse::DrawCursor(int* p0, int p1, int p2);
// 0x7BA4D0 [stub]
int DisplayClass::ReadFromBuffer(void* p0, int p1);
// 0x7BC970 [stub]
_DWORD * BSurface::ConstructEx(int p0, int p1, int p2, int p3);
// 0x7BCF50 [stub]
int MapClass::isCellShrouded(uint16_t p0);
// 0x7BCFB0 [stub]
unsigned int TacticalMap::FillScanlinesOpaque(int p0, int p1, int p2, int p3);
// 0x7BD690 [stub]
int Surface::CommitSurfaceBuffersAudio();
#endif  // 0
#endif  // GAMEMD_RENDER_STUB_DECLS_HPP
