// AUTO-GENERATED by tools/gen_gap2_defs.py -- DO NOT EDIT MANUALLY.
// Gap 2: REAL stub DEFINITIONS for IDA-confirmed no_cpp_body functions.
// Symbols genuinely exist (NOT #if 0). Declarations live in the class hpp
// bodies with `// 0xADDR` after the semicolon. Bodies return a safe default.
#include <cstdint>
// neutralise Win32 macros that collide with IDA method names
#ifdef _WIN32
#include <windows.h>
#undef CreateDialog
#endif
#include "object/abstract.hpp"
#include "app/cmdline.hpp"

// 0x5D67B0
namespace gamemd { void* GameConfig::Constructor() {
// [IDA decompile]
char *__thiscall GameConfig::Constructor(char **this)
{
  char **v1; // edi
  _DWORD *v2; // eax
  _DWORD *v3; // esi
  _DWORD v6[22]; // [esp+Ch] [ebp-6Ch] BYREF
  char v7[12]; // [esp+64h] [ebp-14h] BYREF
  int v8; // [esp+70h] [ebp-8h]

  v1 = this;
  if ( !*(this + 14) )
  {
    v2 = (_DWORD *)__2_YAPAXI_Z(88);
    v3 = v2;
    if ( v2 )
    {
      v2[1] = 0;
      v2[2] = 0;
      v2[5] = 0;
      v2[6] = 0;
      v2[4] = &GenericNode::`vftable';
      GenericNode::Constructor(v2 + 7);
      v3[3] = &GenericList::`vftable';
      LinkedList::Prepend(v3 + 4, (int)(v3 + 7));
      v1 = this;
      v3[3] = &List<INIClass::INISection *>::`vftable';
      v3[10] = 0;
      v3[11] = 0;
      v3[12] = 0;
      *((_BYTE *)v3 + 52) = 0;
      v3[14] = 0;
      v3[15] = 0;
      *((_BYTE *)v3 + 64) = 0;
      *v3 = &CCINIClass_Vtable;
    }
    else
    {
      v3 = 0;
    }
    v1[14] = (char *)v3;
    CCFileClass::Construct2(v6, v1 + 11);
    if ( CCFileClass::Open(v6, 0) )
      CCINIClass::Load(v1[14], (int)v6, 0, 0);
    v6[0] = &CCFileClass::`vftable';
    v8 = 0;
    Vector::Clear((int)v7);
    v6[0] = &off_7E1668;
    BufferIOFileClass::Dtor(v6);
  }
  return v1[14];
}

/* ASM:
sub     esp, 70h
push    ebx
push    edi
mov     edi, ecx
xor     ebx, ebx
mov     [esp+78h+var_70], edi
cmp     [edi+38h], ebx
jnz     loc_5D6885
push    esi
push    58h ; 'X'       ; Size
call    ??2_YAPAXI_Z
mov     esi, eax
add     esp, 4
cmp     esi, ebx
jz      short loc_5D682F
push    ebp
lea     edi, [esi+10h]
lea     ebp, [esi+1Ch]
mov     [esi+4], ebx
mov     [esi+8], ebx
mov     ecx, ebp
mov     [edi+4], ebx
mov     [edi+8], ebx
mov     dword ptr [edi], offset ??_7GenericNode@@6B@ ; const GenericNode::`vftable'
call    GenericNode__Constructor
push    ebp
mov     ecx, edi
mov     dword ptr [esi+0Ch], offset ??_7GenericList@@6B@ ; const GenericList::`vftable'
call    LinkedList__Prepend
mov     edi, [esp+80h+var_70]
mov     dword ptr [esi+0Ch], offset ??_7?$List@PAUINISection@INIClass@@@@6B@ ; const List<INIClass::INISection *>::`vftable'
mov     [esi+28h], ebx
mov     [esi+2Ch], ebx
mov     [esi+30h], ebx
mov     [esi+34h], bl
mov     [esi+38h], ebx
mov     [esi+3Ch], ebx
mov     [esi+40h], bl
mov     dword ptr [esi], offset CCINIClass_Vtable
pop     ebp
jmp     short loc_5D6831
; ---------------------------------------------------------------------------

loc_5D682F:                             ; CODE XREF: GameConfig__Constructor+25↑j
xor     esi, esi

loc_5D6831:                             ; CODE XREF: GameConfig__Constructor+7D↑j
lea     eax, [edi+2Ch]
lea     ecx, [esp+7Ch+var_6C]
push    eax
mov     [edi+38h], esi
call    CCFileClass__Construct2
push    ebx
lea     ecx, [esp+80h+var_6C]
call    CCFileClass__Open
test    al, al
pop     esi
jz      short loc_5D685F
push    ebx
lea     ecx, [esp+7Ch+var_6C]
push    ebx
push    ecx
mov     ecx, [edi+38h]
call    CCINIClass__Load

loc_5D685F:                             ; CODE XREF: GameConfig__Constructor+9E↑j
lea     ecx, [esp+78h+var_14]
mov     [esp+78h+var_6C], offset ??_7CCFileClass@@6B@ ; const CCFileClass::`vftable'
mov     [esp+78h+var_8], ebx
call    Vector__Clear
lea     ecx, [esp+78h+var_6C]
mov     [esp+78h+var_6C], offset off_7E1668
call    BufferIOFileClass__Dtor

loc_5D6885:                             ; CODE XREF: GameConfig__Constructor+10↑j
mov     eax, [edi+38h]
pop     edi
pop     ebx
add     esp, 70h
retn
*/
} }
// 0x77E7A0
namespace gamemd { int GameConfig::BuildChecksum() {
// [IDA decompile]
int __thiscall GameConfig_BuildChecksum(char *Buffer)
{
  int v2; // ecx
  int *v3; // eax
  int v4; // esi
  char v5; // al
  unsigned __int8 v6; // al
  int Entry; // eax
  int v9; // [esp-10h] [ebp-1Ch]
  int v10; // [esp-Ch] [ebp-18h]
  int v11; // [esp-8h] [ebp-14h]
  const char *v12; // [esp-4h] [ebp-10h]

  v2 = MEMORY[0xB76B1C];
  if ( MEMORY[0xB76B1C] > 0 )
  {
    v3 = MEMORY[0xB76E58];
    do
    {
      v3 += 37;
      --v2;
    }
    while ( v2 );
  }
  v4 = MEMORY[0xB77E00] ^ MEMORY[0xB77E08] ^ MEMORY[0xB77E04];
  v5 = GameOption::CheckDuplicate(&MEMORY[0xA8B8E0]);
  v6 = Hash_Check_5E9580(v5 == 0);
  v9 = Hash_Check_5E94D0(v6);
  Entry = GameOptions::GetEntry();
  return sprintf(Buffer, "%d,%d,%d,%d,%d,%s", Entry, v4, v9, v10, v11, v12);
}

/* ASM:
push    ecx
push    esi
push    edi
mov     edi, ecx
mov     ecx, dword_A8ED54+0E7DC8h
test    ecx, ecx
jle     short loc_77E7C2
mov     eax, (offset dword_A8ED54+0E8104h)

loc_77E7B4:                             ; CODE XREF: GameConfig__BuildChecksum+20↓j
mov     edx, [eax]
add     eax, 94h
dec     ecx
mov     [esp+0Ch+var_4], edx
jnz     short loc_77E7B4

loc_77E7C2:                             ; CODE XREF: GameConfig__BuildChecksum+D↑j
mov     esi, dword_A8ED54+0E90B0h
mov     edx, dword_A8ED54+0E90B4h
mov     ecx, dword_A8ED54+0E90ACh
xor     esi, edx
push    0A8B8E0h
xor     esi, ecx
call    GameOption__CheckDuplicate
neg     al
sbb     eax, eax
inc     eax
push    eax
call    Hash_Check_5E9580
and     eax, 0FFh
push    eax
call    Hash_Check_5E94D0
push    eax
push    esi
call    GameOptions__GetEntry
push    eax
push    offset aDDDDDS  ; "%d,%d,%d,%d,%d,%s"
push    edi             ; Buffer
call    _sprintf
add     esp, 20h
pop     edi
pop     esi
pop     ecx
retn
*/
} }
