// AUTO-GENERATED by tools/gen_gap2_stubs.py -- DO NOT EDIT MANUALLY.
// Gap 2 stub registry: IDA-confirmed no_cpp_body functions (annotation-only).
// Documents address<->symbol mapping for tools/audit_consistency.py.
// Wrapped in `#if 0` so this header is a no-op if ever #included (NEVER compiled).
#ifndef GAMEMD_HOUSE_STUB_DECLS_HPP
#define GAMEMD_HOUSE_STUB_DECLS_HPP
#if 0  // annotation-only; never compiled
// 0x41C500 [stub]
char BuildingTypeClass::Enqueue(int p0);
// 0x41C590 [stub]
size_t BuildingTypeClass::Dequeue();
// 0x41CB20 [stub]
int AircraftTypeClass::ConstructAircraft(int* p0);
// 0x41CDB0 [stub]
int AircraftTypeClass::PowerDrainUpdate(int* p0);
// 0x41CFD0 [stub]
int AircraftTypeClass::GetAuxField();
// 0x42E6F0 [stub]
_DWORD * BaseClass::Constructor();
// 0x42F180 [stub]
int BaseClass::ProcessPowerTimer(unsigned int* p0);
// 0x42F1E0 [stub]
_DWORD * BaseClass::Construct(int p0);
// 0x42F3A0 [stub]
void BaseClass::ddtor();
// 0x42F3D0 [stub]
unsigned int BaseClass::Write(int p0);
// 0x42F3F0 [stub]
int BaseClass::Seek(int p0, int p1);
// 0x42F490 [stub]
char BaseClass::AddRef(int p0);
// 0x42F4F0 [stub]
char BaseClass::Release(int p0, char* p1);
// 0x42F5E0 [stub]
int BaseClass::Read(int p0);
// 0x42F970 [stub]
_DWORD * BaseClass::QueryInterface(char p0);
// 0x42FC40 [stub]
_DWORD * BaseNodeClass::Vector_Constructor(int p0, int p1);
// 0x43B680 [stub]
_DWORD * BuildingClass::ctor(int p0);
// 0x43DA80 [stub]
int FootClass::DrawPlacementPreview();
// 0x443410 [stub]
int BuildingClass::HandleFactoryCommand();
// 0x44D760 [stub]
int BuildingClass::PushScriptAction();
// 0x459FF0 [stub]
void BuildingClass::initBuildingData();
// 0x45A020 [stub]
unsigned int BuildingClass::updateFactoryProduction(int p0);
// 0x45A040 [stub]
int FootClass::Get(int p0);
// 0x45A3E0 [stub]
char FootClass::Add(int p0);
// 0x45A420 [stub]
char FootClass::Release(int p0, int* p1);
// 0x45A500 [stub]
int FootClass::GetSize(int* p0);
// 0x45AA60 [stub]
_DWORD * FootClass::QueryInterface(char p0);
// 0x45DD90 [stub]
int BuildingTypeClass::ConstructFull(char* p0);
// 0x45E520 [stub]
_DWORD * BuildingTypeClass::loadBuildingProperty_b_545E520(int p0);
// 0x45E580 [stub]
int BuildingTypeClass::CleanupMembers();
// 0x45E7B0 [stub]
int BuildingTypeClass::FindIndexByName();
// 0x45ECE0 [stub]
int BuildingTypeClass::GetMaxPips();
// 0x45F230 [stub]
int BuildingTypeClass::LoadAnimations(int p0);
// 0x45FA90 [stub]
void BuildingTypeClass::LoadVoxel();
// 0x464AF0 [stub]
_DWORD * BuildingTypeClass::GetSizeInLeptons(int* p0);
// 0x464B30 [stub]
int BuildingTypeClass::UpdatePower();
// 0x465010 [stub]
int BuildingTypeClass::SaveLoad_Prefix();
// 0x465300 [stub]
int BuildingTypeClass::SaveLoad_Prefix_0();
// 0x465D70 [stub]
int BuildingClass::processPowerState();
// 0x465DB0 [stub]
int BuildingTypeClass::GetAuxField();
// 0x4734B0 [stub]
void FootClass::updateMovementAnimation(int p0);
// 0x474A90 [stub]
int BuildingTypeClass::FindAnimByName(uint8_t* p0, uint8_t* p1, int p2);
// 0x4756F0 [stub]
int HouseTypeClass::loadCountryData(uint8_t* p0, uint8_t* p1, int p2);
// 0x478850 [stub]
_DWORD * BuildingTypeClass::loadBuildingProperty_b_5478850(int p0, int p1);
// 0x485460 [stub]
char BuildingClass::CheckAdjacentCells();
// 0x487110 [stub]
_DWORD * BuildingClass::checkOccupant(char p0);
// 0x487130 [stub]
_DWORD * BuildingClass::updateOccupiedState(char p0);
// 0x487170 [stub]
int BuildingClass::processGarrison(int p0);
// 0x487180 [stub]
int BuildingClass::evaulateDefense(int p0);
// 0x49D9F0 [stub]
int SideClass::FindByName();
// 0x49F9B0 [stub]
_DWORD * CounterClass::Construct();
// 0x49FA70 [stub]
int CounterClass::Decrement(int p0);
// 0x49FB40 [stub]
int CounterClass::ddtor();
// 0x49FBE0 [stub]
int CounterClass::Load(int p0);
// 0x49FCE0 [stub]
_DWORD * CounterClass::QueryInterface(char p0);
// 0x4AA290 [stub]
int BuildingClass::updateSellBack(int16_t* p0, int* p1);
// 0x4C9680 [stub]
int BuildingTypeClass::GetPowerOutput(int p0);
// 0x4D31E0 [stub]
_DWORD * FootClass::Construct(int p0);
// 0x4E38A0 [stub]
wchar_t * SideClass::GetName();
// 0x4F9700 [stub]
void FactoryClass::AccumulateCreditsProgress(int p0, int p1);
// 0x4F9750 [stub]
double BuildingClass::checkRepairEligibility();
// 0x50B760 [stub]
char BuildingTypeClass::ProcessData(int* p0, int16_t* p1);
// 0x50BDF0 [stub]
double TechnoTypeClass::Dispatch(int* p0);
// 0x50BEB0 [stub]
double TechnoTypeClass::GetThreatMultiplier(int* p0);
// 0x50DAA0 [stub]
unsigned int FootClass::checkTurning();
// 0x511650 [stub]
_DWORD * HouseTypeClass::loadVeteranWeapons(int p0);
// 0x512170 [stub]
int HouseTypeClass::ProcessPower(int* p0);
// 0x512760 [stub]
void ** HouseTypeClass::Destructor(char p0);
// 0x512960 [stub]
_DWORD * HouseTypeClass::readStartUnit();
// 0x512BD0 [stub]
_DWORD * HouseTypeClass::readStartInfantry(int* p0);
// 0x513370 [stub]
_DWORD * HouseTypeClass::readBaseDefense(int* p0);
// 0x513560 [stub]
_DWORD * HouseTypeClass::readDefaultAlly(int p0, int p1);
// 0x5136C0 [stub]
char HouseTypeClass::readPowerPlants(int* p0);
// 0x5137D0 [stub]
_DWORD * HouseTypeClass::readParaDropTypes(int* p0);
// 0x513860 [stub]
_DWORD * HouseTypeClass::readAllowedUnits(int* p0);
// 0x523980 [stub]
_DWORD * InfantryTypeClass::Constructor_523980(int p0);
// 0x523B10 [stub]
int InfantryTypeClass::ConstructInfantry(int* p0);
// 0x524840 [stub]
int InfantryTypeClass::PowerDrainUpdate(int* p0);
// 0x524D60 [stub]
int InfantryTypeClass::GetAuxField();
// 0x524F20 [stub]
_DWORD * InfantryTypeClass::CopyDataArray(int* p0);
// 0x594010 [stub]
char BuildingTypeClass::CheckPlacementArea(uint16_t* p0, int p1);
// 0x5AEAD0 [stub]
void BuildingClass::processBaseExpansion(float p0);
// 0x5AEAF0 [stub]
void BuildingClass::updateFoundation(float p0);
// 0x5AEB20 [stub]
void BuildingClass::recalcAdjacency(float p0);
// 0x5FEC70 [stub]
int BuildingTypeClass::FindOrCreate2();
// 0x635120 [stub]
int FactoryClass::ClearObjects();
// 0x635F80 [stub]
void FactoryClass::FindAvailable();
// 0x636590 [stub]
int FactoryClass::CompleteCurrentItem(int p0);
// 0x63D540 [stub]
int BuildingClass::updateAnimationState();
// 0x63D9C0 [stub]
int * FactoryClass::RemoveFromArrays(char p0);
// 0x63DFD0 [stub]
char FactoryClass::RemoveItemAt(int p0);
// 0x63F000 [stub]
char FactoryClass::RemoveItem(int p0);
// 0x644890 [stub]
int BuildingTypeClass::LoadOrGet();
// 0x645430 [stub]
int BuildingTypeClass::FindOrCreateEx();
// 0x6727D0 [stub]
int FactoryClass::LoadType();
// 0x6A4550 [stub]
_DWORD * SideClass::Construct(char* p0);
// 0x6A46D0 [stub]
int HouseTypeClass::Find();
// 0x6A4710 [stub]
int SideClass::GetCountry(int* p0);
// 0x6A4930 [stub]
void ** SideClass::Init(char p0);
// 0x6B04C0 [stub]
int FactoryClass::PlaceExitUnits();
// 0x6B0750 [stub]
_DWORD * FactoryClass::GetBridgeCell(int* p0);
// 0x6B0C80 [stub]
wchar_t * FactoryClass::ResetProductionTimers();
// 0x6B4DD0 [stub]
char UnitTypeClass::ReadINIEntry();
// 0x6B5910 [stub]
int FactoryClass::FindOrCreate();
// 0x6CE220 [stub]
void * SuperClass::ProcessEvent(char p0);
// 0x6CE270 [stub]
int SuperClass::SetFieldX();
// 0x6CE280 [stub]
void SuperClass::AdvanceCountdown();
// 0x6CE2C0 [stub]
wchar_t * SuperClass::SetCurrentFrame();
// 0x6CE320 [stub]
char SuperClass::RemoveFromPointerArray(int p0);
// 0x6E1C40 [stub]
char SuperClass::Get(int p0, int p1, int p2, int p3);
// 0x6E52F0 [stub]
_DWORD * FootClass::processScriptAction(int* p0);
// 0x6E5610 [stub]
int TagClass::CheckEvent(int p0, int p1);
// 0x6E56E0 [stub]
int TagClass::ProcessTag(int* p0);
// 0x6E58B0 [stub]
void ** TagClass::ProcessTrigger(char p0);
// 0x6E6220 [stub]
char TagClass::HasValidHouse();
// 0x6F06E0 [stub]
_DWORD * TechnoTypeClass::LoadBase(char* p0);
// 0x7091D0 [stub]
bool FootClass::CanEnterBuilding();
// 0x70D0D0 [stub]
bool TechnoTypeClass::HasVoiceResponse(int p0);
// 0x70DDC0 [stub]
int BuildingClass::checkPlacement();
// 0x70FEB0 [stub]
BOOL FootClass::checkPassability();
// 0x710AF0 [stub]
char * TechnoTypeClass::ReadINI(char* p0, int p1);
// 0x711EE0 [stub]
double TechnoTypeClass::ComputeBuildTime();
// 0x711F00 [stub]
int TechnoTypeClass::ComputeValueSimple(int p0);
// 0x711F60 [stub]
int TechnoTypeClass::ComputeValue(int* p0, float p1);
// 0x7171A0 [stub]
int BuildingTypeClass::ProcessPower(int* p0);
// 0x7178C0 [stub]
_DWORD * BuildingTypeClass::GetUpgradeOffset(int* p0);
// 0x7179A0 [stub]
void * TechnoTypeClass::ddtor(char p0);
// 0x717AF0 [stub]
_DWORD * TechnoTypeClass::Constructor();
// 0x717B20 [stub]
int TechnoTypeClass::SaveLoadDataArray(int* p0);
// 0x717BC0 [stub]
_DWORD * TechnoTypeClass::Constructor_0(int p0);
// 0x717BE0 [stub]
_DWORD * TechnoTypeClass::Constructor_1(int p0);
// 0x717DB0 [stub]
char TechnoTypeClass::RemoveItem(int p0);
// 0x71ABC0 [stub]
_DWORD * FactoryClass::CompleteItem();
// 0x71ADE0 [stub]
int TagClass::Unlink();
// 0x721290 [stub]
int TechnoTypeClass::CheckFlag(int p0);
// 0x729AA0 [stub]
void FootClass::Process();
// 0x73D630 [stub]
int FactoryClass::CompleteProduction();
// 0x746000 [stub]
bool BuildingTypeClass::IsPlacementValid(int16_t* p0, int16_t* p1);
// 0x746D80 [stub]
char FootClass::updateScanRange();
// 0x747560 [stub]
int UnitTypeClass::ConstructUnit();
// 0x747590 [stub]
int * UnitTypeClass::GetDimensions(int* p0);
// 0x747F70 [stub]
int UnitTypeClass::PowerDrainUpdate(int* p0);
// 0x7480D0 [stub]
int BuildingTypeClass::FindOrCreateAlt();
// 0x748180 [stub]
int UnitTypeClass::GetAuxField();
#endif  // 0
#endif  // GAMEMD_HOUSE_STUB_DECLS_HPP
