// Auto-generated sub_* function stubs
// 2 stubs from IDA decompiled pseudocode
// Generated by tools/gen_sub_stubs.py

#include <cstdint>

namespace gamemd {

// 0x005C00E0 (177 bytes)
char Frame_Test_5C00E0() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/005C00E0.json)
    // Size: 177 bytes, calling convention: thiscall
    // IDA pseudocode:
//   char __usercall sub_5C00E0 ( int a1, int a2, int a3 ) { char result ; // al int v4 ; // edx !int v5 ! ; // ecx int v6 ; // edi int v7 ; // [esp+4h] [ebp-20h] BYREF int v8 ; // [esp+8h] [ebp-1Ch] int *v9 ; // [esp+Ch] [ebp-18h] int v10 ; // [esp+10h] [ebp-14h] !struct tagRECT Rect ! ; // [esp+14h] [ebp-10h] BYREF result = g_BigIntPool ; if ( g_BigIntPool ) { ( * ( void (__thiscall **)(int, _DWORD) ) ( * ( _DWORD * ) DSurface_Alternate + 24 ) ) ( DSurface_Alternate , 0 ) ; Frame::Present ( DSurface_Alternate , a1 , a2 , a3 , 0 , v7 , v8 , v9 ) ; result = TestBitArray ( 15 ) ; if ( ! result ) { "GetClientRect " ( g_hWnd , & Rect ) ; "ClientToScreen " ( g_hWnd , ( LPPOINT ) & Rect ) ; v4 = * ( _DWORD * ) ( g_BigIntPool + 64 ) ; v5 = Rect . top + * ( _DWORD * ) ( g_BigIntPool + 56 ) ; v6 = * ( _DWORD * ) ( g_BigIntPool + 52 ) ; v9 = * ( int ** ) ( g_BigIntPool + 60 ) ; v8 = v5 ; v7 = Rect . left + v6 ; v10 = v4 ; return ( * ( int (__thiscall **)(int, int *, _DWORD, int, _DWORD, int) ) ( * ( _DWORD * ) DSurface_Primary + 8 ) ) ( DSurface_Primary , & v7 , * ( _DWORD * ) ( g_BigIntPool + 8 ) , g_BigIntPool + 36 , 0 , 1 ) ; } } return result ; }
    return 0;
}

// 0x00437F50 (110 bytes)
int GameClass_Wrapper_437F50() {
    // TODO: Translate from IDA decompile (tools/sub_decompiles/00437F50.json)
    // Size: 110 bytes, calling convention: thiscall
    // IDA pseudocode:
//   _DWORD *__thiscall sub_437F50 ( _DWORD *this ) { !HRESULT v2 ! ; // esi !LPVOID ppv ! ; // [esp+Ch] [ebp-4h] BYREF * this = 0 ; v2 = "CoCreateInstance " ( & stru_7E9500 , 0 , 7u , & riid , & ppv ) ; if ( v2 < 0 ) goto LABEL_5 ; v2 = "OleRun " ( ( LPUNKNOWN ) ppv ) ; if ( v2 >= 0 ) v2 = ( * * ( int (__stdcall ***)(LPVOID, void *, _DWORD *) ) ppv ) ( ppv , & unk_818C08 , this ) ; ( * ( void (__stdcall **)(LPVOID) ) ( * ( _DWORD * ) ppv + 8 ) ) ( ppv ) ; if ( v2 < 0 ) { LABEL_5 : if ( v2 != -2147467262 ) WinAPI::Wrapper ( v2 ) ; } return this ; }
    return 0;
}

} // namespace gamemd