// AUTO-GENERATED by tools/gen_gap2_defs.py -- DO NOT EDIT MANUALLY.
// Gap 2: REAL stub DEFINITIONS for IDA-confirmed no_cpp_body functions.
// Symbols genuinely exist (NOT #if 0). Declarations live in the class hpp
// bodies with `// 0xADDR` after the semicolon. Bodies return a safe default.
#include <cstdint>
// neutralise Win32 macros that collide with IDA method names
#ifdef _WIN32
#include <windows.h>
#undef CreateDialog
#endif
#include "object/abstract.hpp"
#include "type/abstract_type.hpp"
#include "type/building_type.hpp"
#include "type/techno_type.hpp"

// 0x45EC90
namespace gamemd { short BuildingTypeClass::GetFoundationWidth() const { return 0; } }
// 0x0 (lnk)
namespace gamemd { AbstractTypeClass::AbstractTypeClass(char const *) noexcept {} }
// 0x45ECA0
namespace gamemd { short BuildingTypeClass::GetFoundationHeight(bool) const { return 0; } }
// 0x0 (lnk)
namespace gamemd { bool BuildingTypeClass::IsCellClearOfTerrainObstacles(gamemd::Vector2D<short> const &) const { return false; } }
// 0x0 (lnk)
namespace gamemd { gamemd::Vector3D<int> * TechnoTypeClass::GetParticleSysOffset(gamemd::Vector3D<int> *) const { return nullptr; } }
