// Auto-generated from tools/functions_by_module.json (core module)
// DO NOT EDIT MANUALLY — regenerate with: python tools/gen_core_funcs.py
// Total functions: 7186

#pragma once

namespace gamemd {

// ============================================================================
// Core Module Function Declarations
// ============================================================================

// Statistics: 2234 named, 4952 sub_* (total 7186)
// Address ranges are 0x10000 chunks

// === 0x400000 - 0x40FFFF (322 funcs: 39 named, 283 sub_) ===

// All relocatable declarations were moved to class bodies / src/_generated/global_funcs.hpp by tools/move_funcs_decls.py.
// Residual declarations below could not be relocated (invalid name / no class / collision):

    void sub_40BE10(/* param_bytes: 0 */) noexcept; // 0x40BE10 [global: cdecl]
    void sub_40C590(/* param_bytes: 0 */) noexcept; // 0x40C590 [global: unknown]
    // int Math::InitDegToRad(/* param_bytes: 0 */) noexcept; // 0x40FFFF [member: unknown]
    // void FractalNoise::Release(/* param_bytes: 4 */) noexcept; // 0x420270 [member: stdcall]
    // _DWORD * AbstractClass::sub_464A70(/* param_bytes: 0 */) noexcept; // 0x464A70 [member: unknown]
    // LONG VectorClass_ptr_BulletClass::sub_46B990(/* param_bytes: 4 */) noexcept; // 0x46B990 [member: stdcall]
    // LONG VectorClass_ptr_BulletClass::sub_46B9A0(/* param_bytes: 4 */) noexcept; // 0x46B9A0 [member: stdcall]
    // void Math::InitArcTan(/* param_bytes: 0 */) noexcept; // 0x473650 [member: unknown]
    // void * CStreamClass::ddtor(/* param_bytes: 0 */) noexcept; // 0x4A3110 [member: unknown]
    // int DiskLaserClass::ddtor(/* param_bytes: 8 */) noexcept; // 0x4A7C30 [member: stdcall]
    // BOOL StreamClass::IsInactive(/* param_bytes: 4 */) noexcept; // 0x4B4C30 [member: stdcall]
    // int StreamClass::Vt32Thunk(/* param_bytes: 4 */) noexcept; // 0x4B4C50 [member: stdcall]
    // void EventClass::ProcessEvent(/* param_bytes: 0 */) noexcept; // 0x4C6CB0 [member: unknown]
    // double Math::Sqrt(/* param_bytes: 0 */) noexcept; // 0x4CAC40 [member: cdecl]
    // double Math::SinCos(/* param_bytes: 0 */) noexcept; // 0x4CACB0 [member: cdecl]
    // double Math::ArcTan2(/* param_bytes: 0 */) noexcept; // 0x4CAD00 [member: cdecl]
    // double Math::Sin(/* param_bytes: 0 */) noexcept; // 0x4CAD50 [member: cdecl]
    // double Math::ArcTan2_Table(/* param_bytes: 0 */) noexcept; // 0x4CADB0 [member: cdecl]
    // double Math::ArcTan(/* param_bytes: 0 */) noexcept; // 0x4CADE0 [member: cdecl]
    // double Math::CalcAngle(/* param_bytes: 0 */) noexcept; // 0x4CAE30 [member: cdecl]
    // int FoggedObjectClass::SaveToINI(/* param_bytes: 12 */) noexcept; // 0x4D24A0 [member: stdcall]
    // int FoggedObjectClass::LoadTypeData(/* param_bytes: 8 */) noexcept; // 0x4D2510 [member: stdcall]
    // int FoggedObjectClass::GetClassIdentifier(/* param_bytes: 8 */) noexcept; // 0x4D27D0 [member: stdcall]
    // int Options::DlgProc(/* param_bytes: 16 */) noexcept; // 0x4F11B0 [member: stdcall]
    // bool VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6910(/* param_bytes: 4 */) noexcept; // 0x4F6910 [member: stdcall]
    // BSTR VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6950(/* param_bytes: 4 */) noexcept; // 0x4F6950 [member: stdcall]
    // __int64 VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6990(/* param_bytes: 4 */) noexcept; // 0x4F6990 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F69D0(/* param_bytes: 4 */) noexcept; // 0x4F69D0 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6A00(/* param_bytes: 4 */) noexcept; // 0x4F6A00 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6A10(/* param_bytes: 4 */) noexcept; // 0x4F6A10 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6A20(/* param_bytes: 8 */) noexcept; // 0x4F6A20 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6A80(/* param_bytes: 8 */) noexcept; // 0x4F6A80 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6AE0(/* param_bytes: 8 */) noexcept; // 0x4F6AE0 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6B50(/* param_bytes: 8 */) noexcept; // 0x4F6B50 [member: stdcall]
    // _DWORD * VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6BC0(/* param_bytes: 8 */) noexcept; // 0x4F6BC0 [member: stdcall]
    // _DWORD * VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6D10(/* param_bytes: 8 */) noexcept; // 0x4F6D10 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_4F6E60(/* param_bytes: 4 */) noexcept; // 0x4F6E60 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_5013A0(/* param_bytes: 4 */) noexcept; // 0x5013A0 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_501400(/* param_bytes: 4 */) noexcept; // 0x501400 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_5024F0(/* param_bytes: 8 */) noexcept; // 0x5024F0 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_502550(/* param_bytes: 12 */) noexcept; // 0x502550 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_510A50(/* param_bytes: 12 */) noexcept; // 0x510A50 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_510A60(/* param_bytes: 4 */) noexcept; // 0x510A60 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_510A70(/* param_bytes: 4 */) noexcept; // 0x510A70 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_510A80(/* param_bytes: 12 */) noexcept; // 0x510A80 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_510A90(/* param_bytes: 4 */) noexcept; // 0x510A90 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_510AA0(/* param_bytes: 4 */) noexcept; // 0x510AA0 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_510AB0(/* param_bytes: 4 */) noexcept; // 0x510AB0 [member: stdcall]
    // BSTR VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_510AC0(/* param_bytes: 4 */) noexcept; // 0x510AC0 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_510AD0(/* param_bytes: 12 */) noexcept; // 0x510AD0 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_510AE0(/* param_bytes: 4 */) noexcept; // 0x510AE0 [member: stdcall]
    // int VectorClass_ptr_BuildChoiceClass_int_ouseClass::sub_510AF0(/* param_bytes: 4 */) noexcept; // 0x510AF0 [member: stdcall]
    // int SaveGame::WriteObject(/* param_bytes: 8 */) noexcept; // 0x513CB0 [member: stdcall]
    // int Game::DestroyAllObjects(/* param_bytes: 0 */) noexcept; // 0x534450 [member: unknown]
    // wchar_t * CreateTeamCommand::ddtor(/* param_bytes: 0 */) noexcept; // 0x535C70 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_535D30(/* param_bytes: 0 */) noexcept; // 0x535D30 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_535D50(/* param_bytes: 0 */) noexcept; // 0x535D50 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_535D70(/* param_bytes: 0 */) noexcept; // 0x535D70 [member: unknown]
    // char CreateTeamCommand::sub_535D90(/* param_bytes: 4 */) noexcept; // 0x535D90 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_535DF0(/* param_bytes: 0 */) noexcept; // 0x535DF0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_535E10(/* param_bytes: 0 */) noexcept; // 0x535E10 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_535E30(/* param_bytes: 0 */) noexcept; // 0x535E30 [member: unknown]
    // char CreateTeamCommand::sub_535E50(/* param_bytes: 4 */) noexcept; // 0x535E50 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_535EB0(/* param_bytes: 0 */) noexcept; // 0x535EB0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_535ED0(/* param_bytes: 0 */) noexcept; // 0x535ED0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_535EF0(/* param_bytes: 0 */) noexcept; // 0x535EF0 [member: unknown]
    // int CreateTeamCommand::sub_535F10(/* param_bytes: 4 */) noexcept; // 0x535F10 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_535F40(/* param_bytes: 0 */) noexcept; // 0x535F40 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_535F60(/* param_bytes: 0 */) noexcept; // 0x535F60 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_535F80(/* param_bytes: 0 */) noexcept; // 0x535F80 [member: unknown]
    // int CreateTeamCommand::sub_535FA0(/* param_bytes: 4 */) noexcept; // 0x535FA0 [member: stdcall]
    // wchar_t * SelectTeamCommand::ddtor(/* param_bytes: 0 */) noexcept; // 0x536030 [member: unknown]
    // wchar_t * AddTeamCommand::ddtor(/* param_bytes: 0 */) noexcept; // 0x536120 [member: unknown]
    // wchar_t * TauntCommandClass::ddtor(/* param_bytes: 0 */) noexcept; // 0x536300 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5365B0(/* param_bytes: 0 */) noexcept; // 0x5365B0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5365D0(/* param_bytes: 0 */) noexcept; // 0x5365D0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5365F0(/* param_bytes: 0 */) noexcept; // 0x5365F0 [member: unknown]
    // _BYTE * CreateTeamCommand::sub_536610(/* param_bytes: 4 */) noexcept; // 0x536610 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_5366B0(/* param_bytes: 0 */) noexcept; // 0x5366B0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5366D0(/* param_bytes: 0 */) noexcept; // 0x5366D0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5366F0(/* param_bytes: 0 */) noexcept; // 0x5366F0 [member: unknown]
    // BOOL CreateTeamCommand::sub_536710(/* param_bytes: 2 */) noexcept; // 0x536710 [member: stdcall]
    // unsigned int CreateTeamCommand::sub_536740(/* param_bytes: 4 */) noexcept; // 0x536740 [member: stdcall]
    // int CreateTeamCommand::sub_536750(/* param_bytes: 2 */) noexcept; // 0x536750 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536780(/* param_bytes: 0 */) noexcept; // 0x536780 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5367A0(/* param_bytes: 0 */) noexcept; // 0x5367A0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5367C0(/* param_bytes: 0 */) noexcept; // 0x5367C0 [member: unknown]
    // int CreateTeamCommand::sub_5367E0(/* param_bytes: 4 */) noexcept; // 0x5367E0 [member: stdcall]
    // int CreateTeamCommand::sub_5367F0(/* param_bytes: 4 */) noexcept; // 0x5367F0 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536820(/* param_bytes: 0 */) noexcept; // 0x536820 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536840(/* param_bytes: 0 */) noexcept; // 0x536840 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536860(/* param_bytes: 0 */) noexcept; // 0x536860 [member: unknown]
    // int CreateTeamCommand::sub_536880(/* param_bytes: 4 */) noexcept; // 0x536880 [member: stdcall]
    // unsigned int CreateTeamCommand::sub_5368A0(/* param_bytes: 4 */) noexcept; // 0x5368A0 [member: stdcall]
    // char CreateTeamCommand::sub_5368B0(/* param_bytes: 2 */) noexcept; // 0x5368B0 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_5368E0(/* param_bytes: 0 */) noexcept; // 0x5368E0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536900(/* param_bytes: 0 */) noexcept; // 0x536900 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536920(/* param_bytes: 0 */) noexcept; // 0x536920 [member: unknown]
    // int CreateTeamCommand::sub_536940(/* param_bytes: 4 */) noexcept; // 0x536940 [member: stdcall]
    // int CreateTeamCommand::sub_536950(/* param_bytes: 2 */) noexcept; // 0x536950 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536980(/* param_bytes: 0 */) noexcept; // 0x536980 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5369A0(/* param_bytes: 0 */) noexcept; // 0x5369A0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5369C0(/* param_bytes: 0 */) noexcept; // 0x5369C0 [member: unknown]
    // int CreateTeamCommand::sub_5369E0(/* param_bytes: 4 */) noexcept; // 0x5369E0 [member: stdcall]
    // int CreateTeamCommand::sub_5369F0(/* param_bytes: 2 */) noexcept; // 0x5369F0 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536A20(/* param_bytes: 0 */) noexcept; // 0x536A20 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536A40(/* param_bytes: 0 */) noexcept; // 0x536A40 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536A60(/* param_bytes: 0 */) noexcept; // 0x536A60 [member: unknown]
    // _BYTE * CreateTeamCommand::sub_536A80(/* param_bytes: 4 */) noexcept; // 0x536A80 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536B20(/* param_bytes: 0 */) noexcept; // 0x536B20 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536B40(/* param_bytes: 0 */) noexcept; // 0x536B40 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536B60(/* param_bytes: 0 */) noexcept; // 0x536B60 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536B80(/* param_bytes: 4 */) noexcept; // 0x536B80 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536BA0(/* param_bytes: 0 */) noexcept; // 0x536BA0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536BC0(/* param_bytes: 0 */) noexcept; // 0x536BC0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536BE0(/* param_bytes: 0 */) noexcept; // 0x536BE0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536C00(/* param_bytes: 4 */) noexcept; // 0x536C00 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536C20(/* param_bytes: 0 */) noexcept; // 0x536C20 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536C40(/* param_bytes: 0 */) noexcept; // 0x536C40 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536C60(/* param_bytes: 0 */) noexcept; // 0x536C60 [member: unknown]
    // char CreateTeamCommand::sub_536C80(/* param_bytes: 4 */) noexcept; // 0x536C80 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536CA0(/* param_bytes: 0 */) noexcept; // 0x536CA0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536CC0(/* param_bytes: 0 */) noexcept; // 0x536CC0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536CE0(/* param_bytes: 0 */) noexcept; // 0x536CE0 [member: unknown]
    // char CreateTeamCommand::sub_536D00(/* param_bytes: 4 */) noexcept; // 0x536D00 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536D20(/* param_bytes: 0 */) noexcept; // 0x536D20 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536D40(/* param_bytes: 0 */) noexcept; // 0x536D40 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536D60(/* param_bytes: 0 */) noexcept; // 0x536D60 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536D80(/* param_bytes: 4 */) noexcept; // 0x536D80 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536DA0(/* param_bytes: 0 */) noexcept; // 0x536DA0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536DC0(/* param_bytes: 0 */) noexcept; // 0x536DC0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536DE0(/* param_bytes: 0 */) noexcept; // 0x536DE0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536E00(/* param_bytes: 4 */) noexcept; // 0x536E00 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536E40(/* param_bytes: 0 */) noexcept; // 0x536E40 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536E60(/* param_bytes: 0 */) noexcept; // 0x536E60 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536E80(/* param_bytes: 0 */) noexcept; // 0x536E80 [member: unknown]
    // int CreateTeamCommand::sub_536EA0(/* param_bytes: 4 */) noexcept; // 0x536EA0 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536EC0(/* param_bytes: 0 */) noexcept; // 0x536EC0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536EE0(/* param_bytes: 0 */) noexcept; // 0x536EE0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536F00(/* param_bytes: 0 */) noexcept; // 0x536F00 [member: unknown]
    // char * CreateTeamCommand::sub_536F20(/* param_bytes: 4 */) noexcept; // 0x536F20 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_536F40(/* param_bytes: 0 */) noexcept; // 0x536F40 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536F60(/* param_bytes: 0 */) noexcept; // 0x536F60 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536F80(/* param_bytes: 0 */) noexcept; // 0x536F80 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536FC0(/* param_bytes: 0 */) noexcept; // 0x536FC0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_536FE0(/* param_bytes: 0 */) noexcept; // 0x536FE0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537000(/* param_bytes: 0 */) noexcept; // 0x537000 [member: unknown]
    // char CreateTeamCommand::sub_537020(/* param_bytes: 4 */) noexcept; // 0x537020 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_537040(/* param_bytes: 0 */) noexcept; // 0x537040 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537060(/* param_bytes: 0 */) noexcept; // 0x537060 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537080(/* param_bytes: 0 */) noexcept; // 0x537080 [member: unknown]
    // int CreateTeamCommand::sub_5370A0(/* param_bytes: 4 */) noexcept; // 0x5370A0 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_5370D0(/* param_bytes: 0 */) noexcept; // 0x5370D0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5370F0(/* param_bytes: 0 */) noexcept; // 0x5370F0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537110(/* param_bytes: 0 */) noexcept; // 0x537110 [member: unknown]
    // unsigned __int16 CreateTeamCommand::sub_537130(/* param_bytes: 4 */) noexcept; // 0x537130 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_537150(/* param_bytes: 0 */) noexcept; // 0x537150 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537170(/* param_bytes: 0 */) noexcept; // 0x537170 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537190(/* param_bytes: 0 */) noexcept; // 0x537190 [member: unknown]
    // char CreateTeamCommand::sub_5371B0(/* param_bytes: 4 */) noexcept; // 0x5371B0 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_5371E0(/* param_bytes: 0 */) noexcept; // 0x5371E0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537200(/* param_bytes: 0 */) noexcept; // 0x537200 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537220(/* param_bytes: 0 */) noexcept; // 0x537220 [member: unknown]
    // char CreateTeamCommand::sub_537240(/* param_bytes: 4 */) noexcept; // 0x537240 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_537270(/* param_bytes: 0 */) noexcept; // 0x537270 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537290(/* param_bytes: 0 */) noexcept; // 0x537290 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5372B0(/* param_bytes: 0 */) noexcept; // 0x5372B0 [member: unknown]
    // char CreateTeamCommand::sub_5372D0(/* param_bytes: 4 */) noexcept; // 0x5372D0 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_5372F0(/* param_bytes: 0 */) noexcept; // 0x5372F0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537310(/* param_bytes: 0 */) noexcept; // 0x537310 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537330(/* param_bytes: 0 */) noexcept; // 0x537330 [member: unknown]
    // _DWORD * CreateTeamCommand::sub_537350(/* param_bytes: 4 */) noexcept; // 0x537350 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_5373E0(/* param_bytes: 0 */) noexcept; // 0x5373E0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537400(/* param_bytes: 0 */) noexcept; // 0x537400 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537420(/* param_bytes: 0 */) noexcept; // 0x537420 [member: unknown]
    // _DWORD * CreateTeamCommand::sub_537440(/* param_bytes: 4 */) noexcept; // 0x537440 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_5374D0(/* param_bytes: 0 */) noexcept; // 0x5374D0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5374F0(/* param_bytes: 0 */) noexcept; // 0x5374F0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537510(/* param_bytes: 0 */) noexcept; // 0x537510 [member: unknown]
    // _DWORD * CreateTeamCommand::sub_537530(/* param_bytes: 4 */) noexcept; // 0x537530 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_5375C0(/* param_bytes: 0 */) noexcept; // 0x5375C0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5375E0(/* param_bytes: 0 */) noexcept; // 0x5375E0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537600(/* param_bytes: 0 */) noexcept; // 0x537600 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5376B0(/* param_bytes: 0 */) noexcept; // 0x5376B0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5376D0(/* param_bytes: 0 */) noexcept; // 0x5376D0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5376F0(/* param_bytes: 0 */) noexcept; // 0x5376F0 [member: unknown]
    // void * CreateTeamCommand::sub_537710(/* param_bytes: 4 */) noexcept; // 0x537710 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_537770(/* param_bytes: 0 */) noexcept; // 0x537770 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537790(/* param_bytes: 0 */) noexcept; // 0x537790 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5377B0(/* param_bytes: 0 */) noexcept; // 0x5377B0 [member: unknown]
    // void * CreateTeamCommand::sub_5377D0(/* param_bytes: 4 */) noexcept; // 0x5377D0 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_537830(/* param_bytes: 0 */) noexcept; // 0x537830 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537850(/* param_bytes: 0 */) noexcept; // 0x537850 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537870(/* param_bytes: 0 */) noexcept; // 0x537870 [member: unknown]
    // void * CreateTeamCommand::sub_537890(/* param_bytes: 4 */) noexcept; // 0x537890 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_5378F0(/* param_bytes: 0 */) noexcept; // 0x5378F0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537910(/* param_bytes: 0 */) noexcept; // 0x537910 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537930(/* param_bytes: 0 */) noexcept; // 0x537930 [member: unknown]
    // void * CreateTeamCommand::sub_537950(/* param_bytes: 4 */) noexcept; // 0x537950 [member: stdcall]
    // wchar_t * CreateTeamCommand::sub_5379B0(/* param_bytes: 0 */) noexcept; // 0x5379B0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5379D0(/* param_bytes: 0 */) noexcept; // 0x5379D0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_5379F0(/* param_bytes: 0 */) noexcept; // 0x5379F0 [member: unknown]
    // bool CreateTeamCommand::sub_537A10(/* param_bytes: 4 */) noexcept; // 0x537A10 [member: stdcall]
    // int CreateTeamCommand::sub_537AF0(/* param_bytes: 4 */) noexcept; // 0x537AF0 [member: stdcall]
    // int Game::MakeScreenshot(/* param_bytes: 4 */) noexcept; // 0x537BC0 [member: stdcall]
    // wchar_t * PageUserCommandClass::ddtor(/* param_bytes: 0 */) noexcept; // 0x537E10 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537E90(/* param_bytes: 0 */) noexcept; // 0x537E90 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537EB0(/* param_bytes: 0 */) noexcept; // 0x537EB0 [member: unknown]
    // wchar_t * CreateTeamCommand::sub_537ED0(/* param_bytes: 0 */) noexcept; // 0x537ED0 [member: unknown]
    // bool CreateTeamCommand::sub_537EF0(/* param_bytes: 4 */) noexcept; // 0x537EF0 [member: stdcall]
    // wchar_t * DeleteCommandClass::ddtor(/* param_bytes: 0 */) noexcept; // 0x537F50 [member: unknown]
    // void LoadProgressMgr::Destroy(/* param_bytes: 0 */) noexcept; // 0x552AA0 [member: unknown]
    // int LightSourceClass::ddtor(/* param_bytes: 8 */) noexcept; // 0x555080 [member: stdcall]
    // int StreamClass::SetDirty(/* param_bytes: 4 */) noexcept; // 0x55A8F0 [member: stdcall]
    // int StreamClass::ClearDirty(/* param_bytes: 4 */) noexcept; // 0x55A910 [member: stdcall]
    // char StreamClass::GetDirty(/* param_bytes: 4 */) noexcept; // 0x55A930 [member: stdcall]
    // int LocomotionClass::QueryInterface(/* param_bytes: 12 */) noexcept; // 0x55A9B0 [com: stdcall]
    // int SwizzleManager::SaveLoad(/* param_bytes: 8 */) noexcept; // 0x55AAC0 [member: stdcall]
    // char RandomMap::LoadInfo(/* param_bytes: 8 */) noexcept; // 0x597D60 [member: stdcall]
    // void RandomMap::PlaceShoreObjects(/* param_bytes: 0 */) noexcept; // 0x59B740 [member: unknown]
    // char Debug::Printf(/* param_bytes: 0 */) noexcept; // 0x5BD1F0 [member: unknown]
    // void Movie::Play(/* param_bytes: 0 */) noexcept; // 0x5BED40 [member: unknown]
    // void Movie::PlayWrapper(/* param_bytes: 0 */) noexcept; // 0x5BF260 [member: unknown]
    // HWND MPCooperative::CheckReady(/* param_bytes: 4 */) noexcept; // 0x5C21A0 [member: stdcall]
    // _DWORD * MPCooperative::sub_5C2DE0(/* param_bytes: 16 */) noexcept; // 0x5C2DE0 [member: stdcall]
    // char MPCooperative::GetPlayerCount(/* param_bytes: 4 */) noexcept; // 0x5C2EF0 [member: stdcall]
    // char MPCooperative::GetMapData(/* param_bytes: 0 */) noexcept; // 0x5C3220 [member: unknown]
    // _DWORD * MPCooperative::QueryInterface(/* param_bytes: 0 */) noexcept; // 0x5C4F10 [com: unknown]
    // int WideString::WordWrap(/* param_bytes: 20 */) noexcept; // 0x5D4B20 [member: stdcall]
    // MMRESULT Timer::DisableHighPrecision(/* param_bytes: 0 */) noexcept; // 0x5D5880 [member: unknown]
    // _DWORD * MPBattleClass::MPBattleClass(/* param_bytes: 21 */) noexcept; // 0x5D8170 [member: stdcall]
    // void GameClass::InitDifficultyButtons(/* param_bytes: 0 */) noexcept; // 0x5E8AE0 [member: unknown]
    // char Game::ResetFlags(/* param_bytes: 0 */) noexcept; // 0x5E8B40 [member: unknown]
    // int Game::ResetReadyStates(/* param_bytes: 0 */) noexcept; // 0x5E9850 [member: unknown]
    // char NullModem::TestConnection(/* param_bytes: 0 */) noexcept; // 0x5F03B0 [member: unknown]
    // int String::NormalizeNewlines(/* param_bytes: 0 */) noexcept; // 0x5F3350 [member: unknown]
    // _DWORD * Math::QuaternionSlerp(/* param_bytes: 0 */) noexcept; // 0x646590 [member: fastcall]
    // int RadSiteClass::ddtor(/* param_bytes: 8 */) noexcept; // 0x65B470 [member: stdcall]
    // int GameClass::FindPlayerName(/* param_bytes: 4 */) noexcept; // 0x69BC60 [member: stdcall]
    // unsigned int SHA1::Transform(/* param_bytes: 8 */) noexcept; // 0x69DB30 [member: stdcall]
    // int SideClass::ddtor(/* param_bytes: 8 */) noexcept; // 0x6A4740 [member: stdcall]
    // void GameClass::Shutdown(/* param_bytes: 0 */) noexcept; // 0x6BEC60 [member: unknown]
    // LONG TClassFactory_CampaignClass::sub_6C00C0(/* param_bytes: 4 */) noexcept; // 0x6C00C0 [com: stdcall]
    // int TClassFactory_CampaignClass::sub_6C0110(/* param_bytes: 16 */) noexcept; // 0x6C0110 [com: stdcall]
    // int TClassFactory_CampaignClass::sub_6C0190(/* param_bytes: 8 */) noexcept; // 0x6C0190 [com: stdcall]
    // LONG TClassFactory_CampaignClass::GetClassName(/* param_bytes: 4 */) noexcept; // 0x6C0260 [com: stdcall]
    // int TClassFactory_CampaignClass::ddtor(/* param_bytes: 16 */) noexcept; // 0x6C0290 [com: stdcall]
    // LONG TClassFactory_MechLocomotionClass::GetClassName(/* param_bytes: 4 */) noexcept; // 0x6C4D60 [com: stdcall]
    // int TClassFactory_MechLocomotionClass::ddtor(/* param_bytes: 16 */) noexcept; // 0x6C4D90 [com: stdcall]
    // int Timer::UpdateDelta(/* param_bytes: 0 */) noexcept; // 0x6C8820 [member: unknown]
    // int SuperClass::ddtor(/* param_bytes: 8 */) noexcept; // 0x6CDEB0 [member: stdcall]
    // int SwizzleManagerClass::Process(/* param_bytes: 12 */) noexcept; // 0x6CF430 [member: stdcall]
    // int TaskForceClass::LoadFromINI(/* param_bytes: 0 */) noexcept; // 0x6E8220 [member: fastcall]
    // int TaskForceClass::SaveTaskForce(/* param_bytes: 12 */) noexcept; // 0x6E8680 [member: stdcall]
    // int TaskForceClass::LoadTaskForce(/* param_bytes: 8 */) noexcept; // 0x6E86A0 [member: stdcall]
    // int TaskForceClass::ddtor(/* param_bytes: 8 */) noexcept; // 0x6E8710 [member: stdcall]
    // int IPersistStream::GetSizeMax(/* param_bytes: 12 */) noexcept;
    // char LoadingScreen::Init(/* param_bytes: 0 */) noexcept; // 0x72CF40 [member: unknown]
    // int VeinholeMonsterClass::ddtor(/* param_bytes: 8 */) noexcept; // 0x74F2D0 [member: stdcall]
    // CHAR * Waypoint::To_String(/* param_bytes: 0 */) noexcept; // 0x763610 [member: fastcall]
    // char MSFrameAnim::Load(/* param_bytes: 8 */) noexcept; // 0x767ED0 [member: stdcall]
    // _DWORD * MSFrameAnim::UpdateFrame(/* param_bytes: 4 */) noexcept; // 0x767F80 [member: stdcall]
    // int WeaponTypeClass::GetClassIdentifier(/* param_bytes: 8 */) noexcept; // 0x772C90 [member: stdcall]
    // char Game::ProcessIdle(/* param_bytes: 0 */) noexcept; // 0x77F900 [member: unknown]
    // int Game::CreateAIPlayer(/* param_bytes: 0 */) noexcept; // 0x796DE0 [member: unknown]
    // int Game::CreateAIPlayer_Potato(/* param_bytes: 0 */) noexcept; // 0x796ED0 [member: unknown]
    // int C07F766C::ddtor(/* param_bytes: 20 */) noexcept; // 0x7A40F0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_32(/* param_bytes: 16 */) noexcept; // 0x7A4EC0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_20(/* param_bytes: 12 */) noexcept; // 0x7A5220 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::GetTypeInfoCount(/* param_bytes: 12 */) noexcept; // 0x7A5240 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::GetTypeInfo(/* param_bytes: 12 */) noexcept; // 0x7A5290 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::GetIDsOfNames(/* param_bytes: 12 */) noexcept; // 0x7A55F0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::FireEvent(/* param_bytes: 12 */) noexcept; // 0x7A5690 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::Disconnect(/* param_bytes: 16 */) noexcept; // 0x7A70E0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_23(/* param_bytes: 20 */) noexcept; // 0x7A7B60 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_22(/* param_bytes: 20 */) noexcept; // 0x7A7EA0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_16(/* param_bytes: 20 */) noexcept; // 0x7A8DA0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_40(/* param_bytes: 20 */) noexcept; // 0x7A8ED0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_17(/* param_bytes: 16 */) noexcept; // 0x7A8FC0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_41(/* param_bytes: 16 */) noexcept; // 0x7A9110 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_28(/* param_bytes: 16 */) noexcept; // 0x7A9200 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_44(/* param_bytes: 16 */) noexcept; // 0x7A9550 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_27(/* param_bytes: 8 */) noexcept; // 0x7A9800 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_18(/* param_bytes: 12 */) noexcept; // 0x7AA6A0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_19(/* param_bytes: 0 */) noexcept; // 0x7AA6D0 [member: unknown]
    // int CComObject_CChatEventSink___ATL::Unadvise(/* param_bytes: 16 */) noexcept; // 0x7AAFB0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_42(/* param_bytes: 16 */) noexcept; // 0x7AB0A0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::EnumDependents(/* param_bytes: 20 */) noexcept; // 0x7AB170 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_43(/* param_bytes: 20 */) noexcept; // 0x7AB260 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_29(/* param_bytes: 12 */) noexcept; // 0x7AB350 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_31(/* param_bytes: 16 */) noexcept; // 0x7AB3C0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_30(/* param_bytes: 20 */) noexcept; // 0x7AB440 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_24(/* param_bytes: 20 */) noexcept; // 0x7AB670 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_33(/* param_bytes: 12 */) noexcept; // 0x7AB8E0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_35(/* param_bytes: 12 */) noexcept; // 0x7ABAF0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_34(/* param_bytes: 12 */) noexcept; // 0x7ABD40 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_36(/* param_bytes: 12 */) noexcept; // 0x7ABFA0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::DispatchStub_37(/* param_bytes: 12 */) noexcept; // 0x7AC220 [member: stdcall]
    // LONG CComObject_CChatEventSink___ATL::AddRef(/* param_bytes: 4 */) noexcept; // 0x7AC690 [member: stdcall]
    // LONG CComObject_CChatEventSink___ATL::Release(/* param_bytes: 4 */) noexcept; // 0x7AC6B0 [member: stdcall]
    // int CComObject_CChatEventSink___ATL::QueryInterface(/* param_bytes: 12 */) noexcept; // 0x7AC700 [com: stdcall]
    // __int64 Math::RoundToInt(/* param_bytes: 0 */) noexcept; // 0x7C5F00 [member: unknown]
    // unsigned __int64 Timer::ReadTSC(/* param_bytes: 0 */) noexcept; // 0x7C6064 [member: cdecl]
    // int String::Wrapper5to4(/* param_bytes: 0 */) noexcept; // 0x7CCA19 [member: cdecl]


} // namespace gamemd
