// AUTO-GENERATED by tools/gen_gap2_defs.py -- DO NOT EDIT MANUALLY.
// Gap 2: REAL stub DEFINITIONS for IDA-confirmed no_cpp_body functions.
// Symbols genuinely exist (NOT #if 0). Declarations live in the class hpp
// bodies with `// 0xADDR` after the semicolon. Bodies return a safe default.
#include <cstdint>
// neutralise Win32 macros that collide with IDA method names
#ifdef _WIN32
#include <windows.h>
#undef CreateDialog
#endif
#include "object/abstract.hpp"
#include "core/game_loop.hpp"
#include "core/load_options.hpp"
#include "core/math.hpp"
#include "core/stream_ext.hpp"

// 0x41DB40
namespace gamemd { int WTFMode::ResetUnitFlags() { return 0; } }
// 0x47EC40
namespace gamemd { void* WTFMode::FindObjectByType(int a1) { return nullptr; } }
// 0x4A31F0
namespace gamemd { bool CStreamClass::IsEmpty() { return false; } }
// 0x4A4AD0
namespace gamemd { void CStreamClass::ClearBuffer() { } }
// 0x4A4B00
namespace gamemd { int CStreamClass::PointerToIndex(int a1) { return 0; } }
// 0x4A4CB0
namespace gamemd { int CStreamClass::CopyItems(int a1, void* a2) { return 0; } }
// 0x4A4D60
namespace gamemd { int CStreamClass::FindItem(void* a1) { return 0; } }
// 0x4A4DE0
namespace gamemd { void* CStreamClass::Constructor_VectorClass__DDSURFACEDESC___(int a1) { return nullptr; } }
// 0x55A150
namespace gamemd { void LoadOptions::vt03() { } }
// 0x5AE6F0
namespace gamemd { void* Matrix3D::Constructor(float a1, float a2) { return nullptr; } }
// 0x5AF080
namespace gamemd { void Matrix3D::RotateZ(float a1) { } }
// 0x5F1BF0
namespace gamemd { int Stream::WriteBlock(int a1, int a2, int a3) { return 0; } }
// 0x5F1C60
namespace gamemd { int Stream::ReadPacket() { return 0; } }
// 0x67C690
namespace gamemd { int Stream::ReadOLEObjects() { return 0; } }
// 0x7B0440
namespace gamemd { void* StreamWrapper::QueryInterface(int a1) { return nullptr; } }
// 0x7BCAE0
namespace gamemd { int Stream::GetField() { return 0; } }
// 0x7BE640
namespace gamemd { void Stream::CopyFromTemplate() { } }
