// Auto-generated by tools/task17_generate.py
// Module: core | Functions: 300
// Regenerate: python tools/task17_generate.py

#include <cstdint>
#include <cstddef>

// IDA-named globals referenced (extern stubs)
extern unsigned char byte_A83CD9;
extern unsigned char byte_B04878;
extern unsigned char byte_B0488C;
extern unsigned char byte_B0488D;
extern double dbl_AC0AC0;
extern double dbl_AC0CE8;
extern double dbl_AC0D28;
extern double dbl_AC0D38;
extern double dbl_AC10D0;
extern double dbl_AC10E8;
extern double dbl_AC1160;
extern double dbl_AC11D0;
extern double dbl_AC1210;
extern double dbl_AC1218;
extern double dbl_AC1220;
extern double dbl_AC1238;
extern double dbl_AC1248;
extern double dbl_AC1260;
extern double dbl_AC1270;
extern double dbl_AC12E0;
extern double dbl_AC12F0;
extern double dbl_AC12F8;
extern double dbl_AC1310;
extern double dbl_AC1320;
extern double dbl_AC1338;
extern double dbl_AC1348;
extern double dbl_AC1368;
extern double dbl_AC1370;
extern double dbl_AC1378;
extern double dbl_AC1390;
extern double dbl_AC13A8;
extern double dbl_AC13C0;
extern double dbl_AC13D0;
extern double dbl_AC13F0;
extern double dbl_AC13F8;
extern double dbl_AC1400;
extern double dbl_AC1430;
extern double dbl_AC1448;
extern double dbl_AC1468;
extern double dbl_AC1490;
extern double dbl_AC14B0;
extern double dbl_AC14B8;
extern double dbl_AC14C0;
extern double dbl_AC14D8;
extern double dbl_AC14E8;
extern double dbl_AC1500;
extern double dbl_AC1510;
extern double dbl_AC1530;
extern double dbl_AC1538;
extern double dbl_AC1540;
extern double dbl_AC1580;
extern double dbl_AC15C0;
extern double dbl_AC15D8;
extern double dbl_AC15F0;
extern double dbl_AC1610;
extern double dbl_AC1618;
extern double dbl_AC1620;
extern double dbl_AC1638;
extern double dbl_AC1650;
extern double dbl_AC1668;
extern double dbl_AC1690;
extern double dbl_AC17D8;
extern double dbl_AC17E0;
extern double dbl_AC17E8;
extern double dbl_AC1800;
extern double dbl_AC1810;
extern double dbl_AC1828;
extern double dbl_AC1898;
extern double dbl_AC1B40;
extern double dbl_AC1B88;
extern double dbl_AC1CA0;
extern double dbl_AC4610;
extern double dbl_AC4838;
extern double dbl_AC48A0;
extern double dbl_AC48F8;
extern double dbl_AC4930;
extern double dbl_AC4938;
extern double dbl_AC4940;
extern double dbl_AC4958;
extern double dbl_AC4968;
extern double dbl_AC4980;
extern double dbl_AC4990;
extern double dbl_AC49B8;
extern double dbl_AC49C0;
extern double dbl_AC49C8;
extern double dbl_AC49E8;
extern double dbl_AC49F8;
extern double dbl_AC4A10;
extern double dbl_AC4A20;
extern double dbl_AC4A40;
extern double dbl_AC4A48;
extern double dbl_AC4A50;
extern double dbl_AC4A68;
extern double dbl_AC4A78;
extern double dbl_AC4A90;
extern double dbl_AC4AB0;
extern double dbl_AC4AD0;
extern double dbl_AC4AD8;
extern double dbl_AC4AE0;
extern double dbl_AC4AF8;
extern double dbl_AC4B08;
extern double dbl_AC4B20;
extern double dbl_AC4B68;
extern double dbl_AC4BE8;
extern double dbl_AC4C10;
extern double dbl_AC4C30;
extern double dbl_AC4C70;
extern double dbl_AC4CC0;
extern double dbl_AC4CE8;
extern double dbl_AC4CF8;
extern double dbl_AC4D18;
extern double dbl_AC4D20;
extern double dbl_AC4D28;
extern double dbl_AC4E40;
extern double dbl_AC4E50;
extern double dbl_AC4E68;
extern double dbl_AC4E88;
extern double dbl_AC4EB0;
extern double dbl_AC4EB8;
extern double dbl_AC4EC0;
extern double dbl_AC4ED8;
extern double dbl_AC4EE8;
extern double dbl_AC4F00;
extern double dbl_AC4F10;
extern double dbl_AC4F30;
extern double dbl_AC4F38;
extern double dbl_AC4F40;
extern double dbl_AC4FE0;
extern double dbl_AC4FF0;
extern double dbl_AC5008;
extern double dbl_AC5018;
extern double dbl_AC5028;
extern double dbl_AC5030;
extern double dbl_AC5038;
extern double dbl_AC5050;
extern double dbl_AC5060;
extern double dbl_AC5078;
extern double dbl_AC5088;
extern double dbl_AC5098;
extern double dbl_AC50A0;
extern double dbl_AC50A8;
extern double dbl_AC50C0;
extern double dbl_AC50D0;
extern double dbl_AC50E8;
extern double dbl_AC5208;
extern double dbl_AC6650;
extern double dbl_AFA260;
extern double dbl_AFA270;
extern double dbl_AFA330;
extern double dbl_AFA410;
extern double dbl_AFA460;
extern double dbl_B048A0;
extern double dbl_B048D8;
extern double dbl_B048E8;
extern double dbl_B048F0;
extern double dbl_B04970;
extern double dbl_B049E0;
extern double dbl_B049F8;
extern double dbl_B04A40;
extern double dbl_B04A78;
extern double dbl_B04A80;
extern double dbl_B04A88;
extern double dbl_B04AA0;
extern double dbl_B04AB0;
extern double dbl_B04AC8;
extern double dbl_B04AD8;
extern double dbl_B04AF8;
extern double dbl_B04B00;
extern double dbl_B04B08;
extern double dbl_B04B20;
extern double dbl_B04B30;
extern double dbl_B04B48;
extern double dbl_B04B58;
extern double dbl_B04B78;
extern double dbl_B04B80;
extern double dbl_B04B88;
extern double dbl_B04BA0;
extern double dbl_B04BB0;
extern double dbl_B04BC8;
extern double dbl_B04C20;
extern double dbl_B04C40;
extern double dbl_B04C48;
extern double dbl_B04C50;
extern double dbl_B04C68;
extern double dbl_B04C78;
extern double dbl_B04C90;
extern int dword_AC0230;
extern int dword_AC0238;
extern int dword_AC0B38;
extern int dword_AC0B3C;
extern int dword_AC0B40;
extern int dword_AC0B44;
extern int dword_AC0B90;
extern int dword_AC0E98;
extern int dword_AC0E9C;
extern int dword_AC0EA0;
extern int dword_AC1158;
extern int dword_AC1168;
extern int dword_AC11D8;
extern int dword_AC11DC;
extern int dword_AC11E0;
extern int dword_AC11E4;
extern int dword_AC1228;
extern int dword_AC122C;
extern int dword_AC1230;
extern int dword_AC125C;
extern int dword_AC1268;
extern int dword_AC1278;
extern int dword_AC127C;
extern int dword_AC1280;
extern int dword_AC1284;
extern int dword_AC1300;
extern int dword_AC1304;
extern int dword_AC1308;
extern int dword_AC1334;
extern int dword_AC1340;
extern int dword_AC1350;
extern int dword_AC1354;
extern int dword_AC1358;
extern int dword_AC135C;
extern int dword_AC1360;
extern int dword_AC1380;
extern int dword_AC1384;
extern int dword_AC1388;
extern int dword_AC13BC;
extern int dword_AC13C8;
extern int dword_AC13D8;
extern int dword_AC13DC;
extern int dword_AC13E0;
extern int dword_AC13E4;
extern int dword_AC1408;
extern int dword_AC140C;
extern int dword_AC1410;
extern int dword_AC1460;
extern int dword_AC1474;
extern int dword_AC1498;
extern int dword_AC149C;
extern int dword_AC14A0;
extern int dword_AC14A4;
extern int dword_AC14C8;
extern int dword_AC14CC;
extern int dword_AC14D0;
extern int dword_AC14FC;
extern int dword_AC1508;
extern int dword_AC1518;
extern int dword_AC151C;
extern int dword_AC1520;
extern int dword_AC1524;
extern int dword_AC1570;
extern int dword_AC1574;
extern int dword_AC1578;
extern int dword_AC15D4;
extern int dword_AC15E0;
extern int dword_AC15F8;
extern int dword_AC15FC;
extern int dword_AC1600;
extern int dword_AC1604;
extern int dword_AC1628;
extern int dword_AC162C;
extern int dword_AC1630;
extern int dword_AC1664;
extern int dword_AC1670;
extern int dword_AC17C0;
extern int dword_AC17C4;
extern int dword_AC17C8;
extern int dword_AC17CC;
extern int dword_AC17F0;
extern int dword_AC17F4;
extern int dword_AC17F8;
extern int dword_AC1824;
extern int dword_AC1830;
extern int dword_AC18B0;
extern int dword_AC18B4;
extern int dword_AC18B8;
extern int dword_AC18BC;
extern int dword_AC1CC8;
extern int dword_AC1DCC;
extern int dword_AC1DD0;
extern int dword_AC1DD4;
extern int dword_AC1DF8;
extern int dword_AC1DFC;
extern int dword_AC1E00;
extern int dword_AC489C;
extern int dword_AC48AC;
extern int dword_AC4900;
extern int dword_AC4904;
extern int dword_AC4908;
extern int dword_AC490C;
extern int dword_AC4928;
extern int dword_AC4948;
extern int dword_AC494C;
extern int dword_AC4950;
extern int dword_AC497C;
extern int dword_AC4988;
extern int dword_AC49A0;
extern int dword_AC49A4;
extern int dword_AC49A8;
extern int dword_AC49AC;
extern int dword_AC49D8;
extern int dword_AC49DC;
extern int dword_AC49E0;
extern int dword_AC4A0C;
extern int dword_AC4A18;
extern int dword_AC4A28;
extern int dword_AC4A2C;
extern int dword_AC4A30;
extern int dword_AC4A34;
extern int dword_AC4A58;
extern int dword_AC4A5C;
extern int dword_AC4A60;
extern int dword_AC4A8C;
extern int dword_AC4A98;
extern int dword_AC4AA0;
extern int dword_AC4AA4;
extern int dword_AC4AA8;
extern int dword_AC4AAC;
extern int dword_AC4AB8;
extern int dword_AC4ABC;
extern int dword_AC4AC0;
extern int dword_AC4AC4;
extern int dword_AC4AE8;
extern int dword_AC4AEC;
extern int dword_AC4AF0;
extern int dword_AC4B1C;
extern int dword_AC4B28;
extern int dword_AC4B70;
extern int dword_AC4B74;
extern int dword_AC4B78;
extern int dword_AC4B7C;
extern int dword_AC4C58;
extern int dword_AC4C5C;
extern int dword_AC4C60;
extern int dword_AC4C90;
extern int dword_AC4CE4;
extern int dword_AC4CF0;
extern int dword_AC4D00;
extern int dword_AC4D04;
extern int dword_AC4D08;
extern int dword_AC4D0C;
extern int dword_AC4E30;
extern int dword_AC4E34;
extern int dword_AC4E38;
extern int dword_AC4E64;
extern int dword_AC4E70;
extern int dword_AC4E98;
extern int dword_AC4E9C;
extern int dword_AC4EA0;
extern int dword_AC4EA4;
extern int dword_AC4EC8;
extern int dword_AC4ECC;
extern int dword_AC4ED0;
extern int dword_AC4EFC;
extern int dword_AC4F08;
extern int dword_AC4F18;
extern int dword_AC4F1C;
extern int dword_AC4F20;
extern int dword_AC4F24;
extern int dword_AC4F48;
extern int dword_AC4F4C;
extern int dword_AC4F50;
extern int dword_AC5004;
extern int dword_AC5010;
extern int dword_AC5040;
extern int dword_AC5044;
extern int dword_AC5048;
extern int dword_AC5074;
extern int dword_AC5080;
extern int dword_AC50B0;
extern int dword_AC50B4;
extern int dword_AC50B8;
extern int dword_AC50E4;
extern int dword_AC50F0;
extern int dword_AC6630;
extern int dword_AC6634;
extern int dword_AC6638;
extern int dword_AC663C;
extern int dword_AC6640;
extern int dword_AC6648;
extern int dword_AFA320;
extern int dword_AFA324;
extern int dword_AFA328;
extern int dword_AFA45C;
extern int dword_B0446C;
extern int dword_B04884;
extern int dword_B04888;
extern int dword_B048B0;
extern int dword_B048B4;
extern int dword_B048B8;
extern int dword_B048BC;
extern int dword_B048C0;
extern int dword_B04900;
extern int dword_B04904;
extern int dword_B04908;
extern int dword_B049F4;
extern int dword_B04A34;
extern int dword_B04A48;
extern int dword_B04A4C;
extern int dword_B04A50;
extern int dword_B04A54;
extern int dword_B04A90;
extern int dword_B04A94;
extern int dword_B04A98;
extern int dword_B04AC4;
extern int dword_B04AD0;
extern int dword_B04AE0;
extern int dword_B04AE4;
extern int dword_B04AE8;
extern int dword_B04AEC;
extern int dword_B04B10;
extern int dword_B04B14;
extern int dword_B04B18;
extern int dword_B04B44;
extern int dword_B04B50;
extern int dword_B04B60;
extern int dword_B04B64;
extern int dword_B04B68;
extern int dword_B04B6C;
extern int dword_B04B90;
extern int dword_B04B94;
extern int dword_B04B98;
extern int dword_B04BC4;
extern int dword_B04BE8;
extern int dword_B04C38;
extern int dword_B04C8C;
extern int dword_B04C98;
extern unsigned short word_AC120C;
extern unsigned short word_AC120E;
extern unsigned short word_AC12D8;
extern unsigned short word_AC12DA;
extern unsigned short word_AC13E8;
extern unsigned short word_AC13EA;
extern unsigned short word_AC14A8;
extern unsigned short word_AC14AA;
extern unsigned short word_AC1528;
extern unsigned short word_AC152A;
extern unsigned short word_AC1608;
extern unsigned short word_AC160A;
extern unsigned short word_AC17D0;
extern unsigned short word_AC17D2;
extern unsigned short word_AC1B38;
extern unsigned short word_AC1B3A;
extern unsigned short word_AC1CCC;
extern unsigned short word_AC49B0;
extern unsigned short word_AC49B2;
extern unsigned short word_AC4A38;
extern unsigned short word_AC4A3A;
extern unsigned short word_AC4AC8;
extern unsigned short word_AC4ACA;
extern unsigned short word_AC4BE4;
extern unsigned short word_AC4BE6;
extern unsigned short word_AC4D10;
extern unsigned short word_AC4D12;
extern unsigned short word_AC4EA8;
extern unsigned short word_AC4EAA;
extern unsigned short word_AC4F28;
extern unsigned short word_AC4F2A;
extern unsigned short word_AC5020;
extern unsigned short word_AC5022;
extern unsigned short word_AC5090;
extern unsigned short word_AC5092;
extern unsigned short word_B04A58;
extern unsigned short word_B04A5A;
extern unsigned short word_B04AF0;
extern unsigned short word_B04AF2;
extern unsigned short word_B04B70;
extern unsigned short word_B04B72;

namespace gamemd {

// IDA: 0x5DAEE0  proposal: GetTimer5DAEE0
// IDA: int sub_5DAEE0()
//   dword_AC0230 = Timer::GetTicks();
//   dword_AC0238 = 0;
//   return atexit(nullsub_194);
int GetTimer5DAEE0()
{
  return 0;
}

// IDA: 0x5E2410  proposal: ReturnZero5E2410
// IDA: int sub_5E2410()
//   dword_AC0B38 = 0;
//   dword_AC0B3C = 0;
//   dword_AC0B40 = 0;
//   dword_AC0B44 = 0;
//   return 0;
int ReturnZero5E2410()
{
  return 0;
}

// IDA: 0x5E2430  proposal: MathDispatch5E2430
// IDA: void sub_5E2430()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC0CE8 = Math::Sqrt(v0 + v0);
void MathDispatch5E2430()
{
}

// IDA: 0x5E2480  proposal: InitFloatConst5E2480
// IDA: void sub_5E2480()
//   dbl_AC10E8 = 1.0 / dbl_AC1160;
void InitFloatConst5E2480()
{
}

// IDA: 0x5E2500  proposal: MathDispatch5E2500
// IDA: __int64 sub_5E2500()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC0AC0 - dbl_AC0D28);
//   result = Math::RoundToInt(v0 * dbl_AC0CE8 * 0.5);
//   dword_AC1168 = result;
//   return result;
int MathDispatch5E2500()
{
  return 0;
}

// IDA: 0x5E2540  proposal: ArcMath5E2540
// IDA: void sub_5E2540()
//   dbl_AC0D38 = Math::ArcTan((double)dword_AC1168 * 0.00390625);
void ArcMath5E2540()
{
}

// IDA: 0x5E2570  proposal: ArcMath5E2570
// IDA: void sub_5E2570()
//   dbl_AC10D0 = Math::ArcTan((double)(2 * dword_AC1168) / dbl_AC0CE8);
void ArcMath5E2570()
{
}

// IDA: 0x5E25A0  proposal: MathRoundToInt5E25A0
// IDA: __int64 sub_5E25A0()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC1168) + 0.5);
//   dword_AC1158 = result;
//   return result;
int MathRoundToInt5E25A0()
{
  return 0;
}

// IDA: 0x5E25D0  proposal: ReturnZero5E25D0
// IDA: int sub_5E25D0()
//   dword_AC0B90 = 0;
//   return 0;
int ReturnZero5E25D0()
{
  return 0;
}

// IDA: 0x5E25E0  proposal: ReturnZero5E25E0
// IDA: int sub_5E25E0()
//   dword_AC0E98 = 0;
//   dword_AC0E9C = 0;
//   dword_AC0EA0 = 0;
//   return 0;
int ReturnZero5E25E0()
{
  return 0;
}

// IDA: 0x5EF270  proposal: Return24
// IDA: int sub_5EF270()
//   return 24;
int Return24()
{
  return 24;
}

// IDA: 0x5EF2D0  proposal: ReturnZero5EF2D0
// IDA: int sub_5EF2D0()
//   dword_AC11D8 = 0;
//   dword_AC11DC = 0;
//   dword_AC11E0 = 0;
//   dword_AC11E4 = 0;
//   return 0;
int ReturnZero5EF2D0()
{
  return 0;
}

// IDA: 0x5EF2F0  proposal: MathDispatch5EF2F0
// IDA: void sub_5EF2F0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC1210 = Math::Sqrt(v0 + v0);
void MathDispatch5EF2F0()
{
}

// IDA: 0x5EF340  proposal: InitFloatConst5EF340
// IDA: void sub_5EF340()
//   dbl_AC1248 = 1.0 / dbl_AC1260;
void InitFloatConst5EF340()
{
}

// IDA: 0x5EF3C0  proposal: MathDispatch5EF3C0
// IDA: __int64 sub_5EF3C0()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC11D0 - dbl_AC1218);
//   result = Math::RoundToInt(v0 * dbl_AC1210 * 0.5);
//   dword_AC1268 = result;
//   return result;
int MathDispatch5EF3C0()
{
  return 0;
}

// IDA: 0x5EF400  proposal: ArcMath5EF400
// IDA: void sub_5EF400()
//   dbl_AC1220 = Math::ArcTan((double)dword_AC1268 * 0.00390625);
void ArcMath5EF400()
{
}

// IDA: 0x5EF430  proposal: ArcMath5EF430
// IDA: void sub_5EF430()
//   dbl_AC1238 = Math::ArcTan((double)(2 * dword_AC1268) / dbl_AC1210);
void ArcMath5EF430()
{
}

// IDA: 0x5EF460  proposal: MathRoundToInt5EF460
// IDA: __int64 sub_5EF460()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC1268) + 0.5);
//   dword_AC125C = result;
//   return result;
int MathRoundToInt5EF460()
{
  return 0;
}

// IDA: 0x5EF490  proposal: ReturnZero5EF490
// IDA: int sub_5EF490()
//   word_AC120C = 0;
//   word_AC120E = 0;
//   return 0;
int ReturnZero5EF490()
{
  return 0;
}

// IDA: 0x5EF4A0  proposal: ReturnZero5EF4A0
// IDA: int sub_5EF4A0()
//   dword_AC1228 = 0;
//   dword_AC122C = 0;
//   dword_AC1230 = 0;
//   return 0;
int ReturnZero5EF4A0()
{
  return 0;
}

// IDA: 0x5F13B0  proposal: ReturnZero5F13B0
// IDA: int sub_5F13B0()
//   dword_AC1278 = 0;
//   dword_AC127C = 0;
//   dword_AC1280 = 0;
//   dword_AC1284 = 0;
//   return 0;
int ReturnZero5F13B0()
{
  return 0;
}

// IDA: 0x5F13D0  proposal: MathDispatch5F13D0
// IDA: void sub_5F13D0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC12E0 = Math::Sqrt(v0 + v0);
void MathDispatch5F13D0()
{
}

// IDA: 0x5F1420  proposal: InitFloatConst5F1420
// IDA: void sub_5F1420()
//   dbl_AC1320 = 1.0 / dbl_AC1338;
void InitFloatConst5F1420()
{
}

// IDA: 0x5F14A0  proposal: MathDispatch5F14A0
// IDA: __int64 sub_5F14A0()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC1270 - dbl_AC12F0);
//   result = Math::RoundToInt(v0 * dbl_AC12E0 * 0.5);
//   dword_AC1340 = result;
//   return result;
int MathDispatch5F14A0()
{
  return 0;
}

// IDA: 0x5F14E0  proposal: ArcMath5F14E0
// IDA: void sub_5F14E0()
//   dbl_AC12F8 = Math::ArcTan((double)dword_AC1340 * 0.00390625);
void ArcMath5F14E0()
{
}

// IDA: 0x5F1510  proposal: ArcMath5F1510
// IDA: void sub_5F1510()
//   dbl_AC1310 = Math::ArcTan((double)(2 * dword_AC1340) / dbl_AC12E0);
void ArcMath5F1510()
{
}

// IDA: 0x5F1540  proposal: MathRoundToInt5F1540
// IDA: __int64 sub_5F1540()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC1340) + 0.5);
//   dword_AC1334 = result;
//   return result;
int MathRoundToInt5F1540()
{
  return 0;
}

// IDA: 0x5F1570  proposal: ReturnZero5F1570
// IDA: int sub_5F1570()
//   word_AC12D8 = 0;
//   word_AC12DA = 0;
//   return 0;
int ReturnZero5F1570()
{
  return 0;
}

// IDA: 0x5F1580  proposal: ReturnZero5F1580
// IDA: int sub_5F1580()
//   dword_AC1300 = 0;
//   dword_AC1304 = 0;
//   dword_AC1308 = 0;
//   return 0;
int ReturnZero5F1580()
{
  return 0;
}

// IDA: 0x5F36F0  proposal: MathDispatch5F36F0
// IDA: void sub_5F36F0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC1368 = Math::Sqrt(v0 + v0);
void MathDispatch5F36F0()
{
}

// IDA: 0x5F3740  proposal: InitFloatConst5F3740
// IDA: void sub_5F3740()
//   dbl_AC13A8 = 1.0 / dbl_AC13C0;
void InitFloatConst5F3740()
{
}

// IDA: 0x5F37C0  proposal: MathDispatch5F37C0
// IDA: __int64 sub_5F37C0()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC1348 - dbl_AC1370);
//   result = Math::RoundToInt(v0 * dbl_AC1368 * 0.5);
//   dword_AC13C8 = result;
//   return result;
int MathDispatch5F37C0()
{
  return 0;
}

// IDA: 0x5F3800  proposal: ArcMath5F3800
// IDA: void sub_5F3800()
//   dbl_AC1378 = Math::ArcTan((double)dword_AC13C8 * 0.00390625);
void ArcMath5F3800()
{
}

// IDA: 0x5F3830  proposal: ArcMath5F3830
// IDA: void sub_5F3830()
//   dbl_AC1390 = Math::ArcTan((double)(2 * dword_AC13C8) / dbl_AC1368);
void ArcMath5F3830()
{
}

// IDA: 0x5F3860  proposal: MathRoundToInt5F3860
// IDA: __int64 sub_5F3860()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC13C8) + 0.5);
//   dword_AC13BC = result;
//   return result;
int MathRoundToInt5F3860()
{
  return 0;
}

// IDA: 0x5F3890  proposal: ReturnZero5F3890
// IDA: int sub_5F3890()
//   dword_AC1360 = 0;
//   return 0;
int ReturnZero5F3890()
{
  return 0;
}

// IDA: 0x5F38A0  proposal: ReturnZero5F38A0
// IDA: int sub_5F38A0()
//   dword_AC1380 = 0;
//   dword_AC1384 = 0;
//   dword_AC1388 = 0;
//   return 0;
int ReturnZero5F38A0()
{
  return 0;
}

// IDA: 0x5F38E0  proposal: ReturnZero5F38E0
// IDA: int sub_5F38E0()
//   dword_AC1350 = 0;
//   dword_AC1354 = 0;
//   dword_AC1358 = 0;
//   dword_AC135C = 0;
//   return 0;
int ReturnZero5F38E0()
{
  return 0;
}

// IDA: 0x5F6DE0  proposal: MathDispatch5F6DE0
// IDA: void sub_5F6DE0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC13F0 = Math::Sqrt(v0 + v0);
void MathDispatch5F6DE0()
{
}

// IDA: 0x5F6E30  proposal: InitFloatConst5F6E30
// IDA: void sub_5F6E30()
//   dbl_AC1448 = 1.0 / dbl_AC1468;
void InitFloatConst5F6E30()
{
}

// IDA: 0x5F6EB0  proposal: MathDispatch5F6EB0
// IDA: __int64 sub_5F6EB0()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC13D0 - dbl_AC13F8);
//   result = Math::RoundToInt(v0 * dbl_AC13F0 * 0.5);
//   dword_AC1474 = result;
//   return result;
int MathDispatch5F6EB0()
{
  return 0;
}

// IDA: 0x5F6EF0  proposal: ArcMath5F6EF0
// IDA: void sub_5F6EF0()
//   dbl_AC1400 = Math::ArcTan((double)dword_AC1474 * 0.00390625);
void ArcMath5F6EF0()
{
}

// IDA: 0x5F6F20  proposal: ArcMath5F6F20
// IDA: void sub_5F6F20()
//   dbl_AC1430 = Math::ArcTan((double)(2 * dword_AC1474) / dbl_AC13F0);
void ArcMath5F6F20()
{
}

// IDA: 0x5F6F50  proposal: MathRoundToInt5F6F50
// IDA: __int64 sub_5F6F50()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC1474) + 0.5);
//   dword_AC1460 = result;
//   return result;
int MathRoundToInt5F6F50()
{
  return 0;
}

// IDA: 0x5F6F80  proposal: ReturnZero5F6F80
// IDA: int sub_5F6F80()
//   word_AC13E8 = 0;
//   word_AC13EA = 0;
//   return 0;
int ReturnZero5F6F80()
{
  return 0;
}

// IDA: 0x5F6F90  proposal: ReturnZero5F6F90
// IDA: int sub_5F6F90()
//   dword_AC1408 = 0;
//   dword_AC140C = 0;
//   dword_AC1410 = 0;
//   return 0;
int ReturnZero5F6F90()
{
  return 0;
}

// IDA: 0x5F6FD0  proposal: ReturnZero5F6FD0
// IDA: int sub_5F6FD0()
//   dword_AC13D8 = 0;
//   dword_AC13DC = 0;
//   dword_AC13E0 = 0;
//   dword_AC13E4 = 0;
//   return 0;
int ReturnZero5F6FD0()
{
  return 0;
}

// IDA: 0x5FA0D0  proposal: MathDispatch5FA0D0
// IDA: void sub_5FA0D0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC14B0 = Math::Sqrt(v0 + v0);
void MathDispatch5FA0D0()
{
}

// IDA: 0x5FA120  proposal: InitFloatConst5FA120
// IDA: void sub_5FA120()
//   dbl_AC14E8 = 1.0 / dbl_AC1500;
void InitFloatConst5FA120()
{
}

// IDA: 0x5FA1A0  proposal: MathDispatch5FA1A0
// IDA: __int64 sub_5FA1A0()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC1490 - dbl_AC14B8);
//   result = Math::RoundToInt(v0 * dbl_AC14B0 * 0.5);
//   dword_AC1508 = result;
//   return result;
int MathDispatch5FA1A0()
{
  return 0;
}

// IDA: 0x5FA1E0  proposal: ArcMath5FA1E0
// IDA: void sub_5FA1E0()
//   dbl_AC14C0 = Math::ArcTan((double)dword_AC1508 * 0.00390625);
void ArcMath5FA1E0()
{
}

// IDA: 0x5FA210  proposal: ArcMath5FA210
// IDA: void sub_5FA210()
//   dbl_AC14D8 = Math::ArcTan((double)(2 * dword_AC1508) / dbl_AC14B0);
void ArcMath5FA210()
{
}

// IDA: 0x5FA240  proposal: MathRoundToInt5FA240
// IDA: __int64 sub_5FA240()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC1508) + 0.5);
//   dword_AC14FC = result;
//   return result;
int MathRoundToInt5FA240()
{
  return 0;
}

// IDA: 0x5FA270  proposal: ReturnZero5FA270
// IDA: int sub_5FA270()
//   word_AC14A8 = 0;
//   word_AC14AA = 0;
//   return 0;
int ReturnZero5FA270()
{
  return 0;
}

// IDA: 0x5FA280  proposal: ReturnZero5FA280
// IDA: int sub_5FA280()
//   dword_AC14C8 = 0;
//   dword_AC14CC = 0;
//   dword_AC14D0 = 0;
//   return 0;
int ReturnZero5FA280()
{
  return 0;
}

// IDA: 0x5FA2C0  proposal: ReturnZero5FA2C0
// IDA: int sub_5FA2C0()
//   dword_AC1498 = 0;
//   dword_AC149C = 0;
//   dword_AC14A0 = 0;
//   dword_AC14A4 = 0;
//   return 0;
int ReturnZero5FA2C0()
{
  return 0;
}

// IDA: 0x5FC170  proposal: MathDispatch5FC170
// IDA: void sub_5FC170()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC1530 = Math::Sqrt(v0 + v0);
void MathDispatch5FC170()
{
}

// IDA: 0x5FC1C0  proposal: InitFloatConst5FC1C0
// IDA: void sub_5FC1C0()
//   dbl_AC15C0 = 1.0 / dbl_AC15D8;
void InitFloatConst5FC1C0()
{
}

// IDA: 0x5FC240  proposal: MathDispatch5FC240
// IDA: __int64 sub_5FC240()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC1510 - dbl_AC1538);
//   result = Math::RoundToInt(v0 * dbl_AC1530 * 0.5);
//   dword_AC15E0 = result;
//   return result;
int MathDispatch5FC240()
{
  return 0;
}

// IDA: 0x5FC280  proposal: ArcMath5FC280
// IDA: void sub_5FC280()
//   dbl_AC1540 = Math::ArcTan((double)dword_AC15E0 * 0.00390625);
void ArcMath5FC280()
{
}

// IDA: 0x5FC2B0  proposal: ArcMath5FC2B0
// IDA: void sub_5FC2B0()
//   dbl_AC1580 = Math::ArcTan((double)(2 * dword_AC15E0) / dbl_AC1530);
void ArcMath5FC2B0()
{
}

// IDA: 0x5FC2E0  proposal: MathRoundToInt5FC2E0
// IDA: __int64 sub_5FC2E0()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC15E0) + 0.5);
//   dword_AC15D4 = result;
//   return result;
int MathRoundToInt5FC2E0()
{
  return 0;
}

// IDA: 0x5FC310  proposal: ReturnZero5FC310
// IDA: int sub_5FC310()
//   word_AC1528 = 0;
//   word_AC152A = 0;
//   return 0;
int ReturnZero5FC310()
{
  return 0;
}

// IDA: 0x5FC320  proposal: ReturnZero5FC320
// IDA: int sub_5FC320()
//   dword_AC1570 = 0;
//   dword_AC1574 = 0;
//   dword_AC1578 = 0;
//   return 0;
int ReturnZero5FC320()
{
  return 0;
}

// IDA: 0x5FC360  proposal: ReturnZero5FC360
// IDA: int sub_5FC360()
//   dword_AC1518 = 0;
//   dword_AC151C = 0;
//   dword_AC1520 = 0;
//   dword_AC1524 = 0;
//   return 0;
int ReturnZero5FC360()
{
  return 0;
}

// IDA: 0x5FE040  proposal: ReturnZero5FE040
// IDA: int sub_5FE040()
//   dword_AC15F8 = 0;
//   dword_AC15FC = 0;
//   dword_AC1600 = 0;
//   dword_AC1604 = 0;
//   return 0;
int ReturnZero5FE040()
{
  return 0;
}

// IDA: 0x5FE060  proposal: MathDispatch5FE060
// IDA: void sub_5FE060()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC1610 = Math::Sqrt(v0 + v0);
void MathDispatch5FE060()
{
}

// IDA: 0x5FE0B0  proposal: InitFloatConst5FE0B0
// IDA: void sub_5FE0B0()
//   dbl_AC1650 = 1.0 / dbl_AC1668;
void InitFloatConst5FE0B0()
{
}

// IDA: 0x5FE130  proposal: MathDispatch5FE130
// IDA: __int64 sub_5FE130()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC15F0 - dbl_AC1618);
//   result = Math::RoundToInt(v0 * dbl_AC1610 * 0.5);
//   dword_AC1670 = result;
//   return result;
int MathDispatch5FE130()
{
  return 0;
}

// IDA: 0x5FE170  proposal: ArcMath5FE170
// IDA: void sub_5FE170()
//   dbl_AC1620 = Math::ArcTan((double)dword_AC1670 * 0.00390625);
void ArcMath5FE170()
{
}

// IDA: 0x5FE1A0  proposal: ArcMath5FE1A0
// IDA: void sub_5FE1A0()
//   dbl_AC1638 = Math::ArcTan((double)(2 * dword_AC1670) / dbl_AC1610);
void ArcMath5FE1A0()
{
}

// IDA: 0x5FE1D0  proposal: MathRoundToInt5FE1D0
// IDA: __int64 sub_5FE1D0()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC1670) + 0.5);
//   dword_AC1664 = result;
//   return result;
int MathRoundToInt5FE1D0()
{
  return 0;
}

// IDA: 0x5FE200  proposal: ReturnZero5FE200
// IDA: int sub_5FE200()
//   word_AC1608 = 0;
//   word_AC160A = 0;
//   return 0;
int ReturnZero5FE200()
{
  return 0;
}

// IDA: 0x5FE210  proposal: ReturnZero5FE210
// IDA: int sub_5FE210()
//   dword_AC1628 = 0;
//   dword_AC162C = 0;
//   dword_AC1630 = 0;
//   return 0;
int ReturnZero5FE210()
{
  return 0;
}

// IDA: 0x5FEFC0  proposal: MathDispatch5FEFC0
// IDA: void sub_5FEFC0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC17D8 = Math::Sqrt(v0 + v0);
void MathDispatch5FEFC0()
{
}

// IDA: 0x5FF010  proposal: InitFloatConst5FF010
// IDA: void sub_5FF010()
//   dbl_AC1810 = 1.0 / dbl_AC1828;
void InitFloatConst5FF010()
{
}

// IDA: 0x5FF090  proposal: MathDispatch5FF090
// IDA: __int64 sub_5FF090()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC1690 - dbl_AC17E0);
//   result = Math::RoundToInt(v0 * dbl_AC17D8 * 0.5);
//   dword_AC1830 = result;
//   return result;
int MathDispatch5FF090()
{
  return 0;
}

// IDA: 0x5FF0D0  proposal: ArcMath5FF0D0
// IDA: void sub_5FF0D0()
//   dbl_AC17E8 = Math::ArcTan((double)dword_AC1830 * 0.00390625);
void ArcMath5FF0D0()
{
}

// IDA: 0x5FF100  proposal: ArcMath5FF100
// IDA: void sub_5FF100()
//   dbl_AC1800 = Math::ArcTan((double)(2 * dword_AC1830) / dbl_AC17D8);
void ArcMath5FF100()
{
}

// IDA: 0x5FF130  proposal: MathRoundToInt5FF130
// IDA: __int64 sub_5FF130()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC1830) + 0.5);
//   dword_AC1824 = result;
//   return result;
int MathRoundToInt5FF130()
{
  return 0;
}

// IDA: 0x5FF160  proposal: ReturnZero5FF160
// IDA: int sub_5FF160()
//   word_AC17D0 = 0;
//   word_AC17D2 = 0;
//   return 0;
int ReturnZero5FF160()
{
  return 0;
}

// IDA: 0x5FF170  proposal: ReturnZero5FF170
// IDA: int sub_5FF170()
//   dword_AC17F0 = 0;
//   dword_AC17F4 = 0;
//   dword_AC17F8 = 0;
//   return 0;
int ReturnZero5FF170()
{
  return 0;
}

// IDA: 0x5FF1B0  proposal: ReturnZero5FF1B0
// IDA: int sub_5FF1B0()
//   dword_AC17C0 = 0;
//   dword_AC17C4 = 0;
//   dword_AC17C8 = 0;
//   dword_AC17CC = 0;
//   return 0;
int ReturnZero5FF1B0()
{
  return 0;
}

// IDA: 0x600320  proposal: ReturnZero600320
// IDA: int sub_600320()
//   dword_AC18B0 = 0;
//   dword_AC18B4 = 0;
//   dword_AC18B8 = 0;
//   dword_AC18BC = 0;
//   return 0;
int ReturnZero600320()
{
  return 0;
}

// IDA: 0x600340  proposal: MathDispatch600340
// IDA: void sub_600340()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC1B40 = Math::Sqrt(v0 + v0);
void MathDispatch600340()
{
}

// IDA: 0x600390  proposal: InitFloatConst600390
// IDA: void sub_600390()
//   dbl_AC4838 = 1.0 / dbl_AC48A0;
void InitFloatConst600390()
{
}

// IDA: 0x600410  proposal: MathDispatch600410
// IDA: __int64 sub_600410()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC1898 - dbl_AC1B88);
//   result = Math::RoundToInt(v0 * dbl_AC1B40 * 0.5);
//   dword_AC48AC = result;
//   return result;
int MathDispatch600410()
{
  return 0;
}

// IDA: 0x600450  proposal: ArcMath600450
// IDA: void sub_600450()
//   dbl_AC1CA0 = Math::ArcTan((double)dword_AC48AC * 0.00390625);
void ArcMath600450()
{
}

// IDA: 0x600480  proposal: ArcMath600480
// IDA: void sub_600480()
//   dbl_AC4610 = Math::ArcTan((double)(2 * dword_AC48AC) / dbl_AC1B40);
void ArcMath600480()
{
}

// IDA: 0x6004B0  proposal: MathRoundToInt6004B0
// IDA: __int64 sub_6004B0()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC48AC) + 0.5);
//   dword_AC489C = result;
//   return result;
int MathRoundToInt6004B0()
{
  return 0;
}

// IDA: 0x6004E0  proposal: ReturnZero6004E0
// IDA: int sub_6004E0()
//   word_AC1B38 = 0;
//   word_AC1B3A = 0;
//   return 0;
int ReturnZero6004E0()
{
  return 0;
}

// IDA: 0x6004F0  proposal: ReturnZero6004F0
// IDA: int sub_6004F0()
//   dword_AC1DF8 = 0;
//   dword_AC1DFC = 0;
//   dword_AC1E00 = 0;
//   return 0;
int ReturnZero6004F0()
{
  return 0;
}

// IDA: 0x600530  proposal: Callatexit600530
// IDA: int sub_600530()
//   sub_6B9450(g_DialogHashTable);
//   return atexit(unknown_libname_26);
int Callatexit600530()
{
  return 0;
}

// IDA: 0x60D520  proposal: Sub60D520
// IDA: LRESULT __stdcall sub_60D520(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
//   return DefWindowProcA(hWnd, Msg, wParam, lParam);
int Sub60D520(int a0, int a1, int a2, int a3) // stdcall
{
  return 0;
}

// IDA: 0x6107A0  proposal: ReturnZero6107A0
// IDA: int sub_6107A0()
//   xmmword_AC1CB8 = 0u;
//   dword_AC1CC8 = 0;
//   word_AC1CCC = 0;
//   dword_AC1DCC = 0;
//   dword_AC1DD0 = 0;
//   dword_AC1DD4 = 0;
//   return 0;
int ReturnZero6107A0()
{
  return 0;
}

// IDA: 0x6107E0  proposal: SetMember16107E0
// IDA: _DWORD *__thiscall sub_6107E0(_DWORD *this)
//   *this = 0;
//   *(this + 1) = 0;
//   *(this + 2) = 0;
//   *(this + 3) = 0;
//   *(this + 4) = 0;
//   *((_WORD *)this + 10) = 0;
//   *(this + 69) = 0;
//   *(this + 70) = 0;
//   *(this + 71) = 0;
//   return this;
int* SetMember16107E0(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x624080  proposal: MethodStub624080
// IDA: _DWORD *__thiscall sub_624080(_DWORD *this)
//   *this = &OwnerDraw::DialogControl::`vftable';
//   return this;
int* MethodStub624080(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x624090  proposal: MethodStub624090
// IDA: void __thiscall sub_624090(_DWORD *this)
//   *this = &OwnerDraw::DialogControl::`vftable';
void MethodStub624090(void* _this) // thiscall
{
}

// IDA: 0x626070  proposal: MethodStub626070
// IDA: void *__thiscall sub_626070(char *this, const void *a2)
//   void *result; // eax
//   _BYTE *v3; // ecx
//   int v4; // edx
//   result = this;
//   v3 = this + 2;
//   v4 = 256;
//   do
//   {
//   *(v3 - 2) = 0;
//   *(v3 - 1) = 0;
//   *v3 = 0;
//   v3 += 3;
//   --v4;
//   }
//   while ( v4 );
//   qmemcpy(result, a2, 0x300u);
//   return result;
void* MethodStub626070(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x6260A0  proposal: MethodStub6260A0
// IDA: bool __thiscall sub_6260A0(const void *this, const void *a2)
//   return this == a2 || memcmp(this, a2, 0x300u) == 0;
bool MethodStub6260A0(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x6260F0  proposal: Color::Lerp
// IDA: unsigned __int8 __thiscall sub_6260F0(unsigned __int8 *this, unsigned __int8 a2)
//   int v3; // edi
//   unsigned __int8 result; // al
//   v3 = 256;
//   do
//   {
//   result = Color::Lerp(this, a2, (unsigned __int8 *)&byte_A83CD9);
//   this += 3;
//   --v3;
//   }
//   while ( v3 );
//   return result;
int Color_Lerp(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x628F80  proposal: MathDispatch628F80
// IDA: void sub_628F80()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC4930 = Math::Sqrt(v0 + v0);
void MathDispatch628F80()
{
}

// IDA: 0x628FD0  proposal: InitFloatConst628FD0
// IDA: void sub_628FD0()
//   dbl_AC4968 = 1.0 / dbl_AC4980;
void InitFloatConst628FD0()
{
}

// IDA: 0x629050  proposal: MathDispatch629050
// IDA: __int64 sub_629050()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC48F8 - dbl_AC4938);
//   result = Math::RoundToInt(v0 * dbl_AC4930 * 0.5);
//   dword_AC4988 = result;
//   return result;
int MathDispatch629050()
{
  return 0;
}

// IDA: 0x629090  proposal: ArcMath629090
// IDA: void sub_629090()
//   dbl_AC4940 = Math::ArcTan((double)dword_AC4988 * 0.00390625);
void ArcMath629090()
{
}

// IDA: 0x6290C0  proposal: ArcMath6290C0
// IDA: void sub_6290C0()
//   dbl_AC4958 = Math::ArcTan((double)(2 * dword_AC4988) / dbl_AC4930);
void ArcMath6290C0()
{
}

// IDA: 0x6290F0  proposal: MathRoundToInt6290F0
// IDA: __int64 sub_6290F0()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC4988) + 0.5);
//   dword_AC497C = result;
//   return result;
int MathRoundToInt6290F0()
{
  return 0;
}

// IDA: 0x629120  proposal: ReturnZero629120
// IDA: int sub_629120()
//   dword_AC4928 = 0;
//   return 0;
int ReturnZero629120()
{
  return 0;
}

// IDA: 0x629130  proposal: ReturnZero629130
// IDA: int sub_629130()
//   dword_AC4948 = 0;
//   dword_AC494C = 0;
//   dword_AC4950 = 0;
//   return 0;
int ReturnZero629130()
{
  return 0;
}

// IDA: 0x629170  proposal: ReturnZero629170
// IDA: int sub_629170()
//   dword_AC4900 = 0;
//   dword_AC4904 = 0;
//   dword_AC4908 = 0;
//   dword_AC490C = 0;
//   return 0;
int ReturnZero629170()
{
  return 0;
}

// IDA: 0x629710  proposal: SetMember20
// IDA: int __thiscall sub_629710(_DWORD *this)
//   *(this + 20) = 0;
//   *(this + 19) = 0;
//   return 0;
int SetMember20(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x62B3D0  proposal: MathDispatch62B3D0
// IDA: void sub_62B3D0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC49B8 = Math::Sqrt(v0 + v0);
void MathDispatch62B3D0()
{
}

// IDA: 0x62B420  proposal: InitFloatConst62B420
// IDA: void sub_62B420()
//   dbl_AC49F8 = 1.0 / dbl_AC4A10;
void InitFloatConst62B420()
{
}

// IDA: 0x62B4A0  proposal: MathDispatch62B4A0
// IDA: __int64 sub_62B4A0()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC4990 - dbl_AC49C0);
//   result = Math::RoundToInt(v0 * dbl_AC49B8 * 0.5);
//   dword_AC4A18 = result;
//   return result;
int MathDispatch62B4A0()
{
  return 0;
}

// IDA: 0x62B4E0  proposal: ArcMath62B4E0
// IDA: void sub_62B4E0()
//   dbl_AC49C8 = Math::ArcTan((double)dword_AC4A18 * 0.00390625);
void ArcMath62B4E0()
{
}

// IDA: 0x62B510  proposal: ArcMath62B510
// IDA: void sub_62B510()
//   dbl_AC49E8 = Math::ArcTan((double)(2 * dword_AC4A18) / dbl_AC49B8);
void ArcMath62B510()
{
}

// IDA: 0x62B540  proposal: MathRoundToInt62B540
// IDA: __int64 sub_62B540()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC4A18) + 0.5);
//   dword_AC4A0C = result;
//   return result;
int MathRoundToInt62B540()
{
  return 0;
}

// IDA: 0x62B570  proposal: ReturnZero62B570
// IDA: int sub_62B570()
//   word_AC49B0 = 0;
//   word_AC49B2 = 0;
//   return 0;
int ReturnZero62B570()
{
  return 0;
}

// IDA: 0x62B580  proposal: ReturnZero62B580
// IDA: int sub_62B580()
//   dword_AC49D8 = 0;
//   dword_AC49DC = 0;
//   dword_AC49E0 = 0;
//   return 0;
int ReturnZero62B580()
{
  return 0;
}

// IDA: 0x62B5C0  proposal: ReturnZero62B5C0
// IDA: int sub_62B5C0()
//   dword_AC49A0 = 0;
//   dword_AC49A4 = 0;
//   dword_AC49A8 = 0;
//   dword_AC49AC = 0;
//   return 0;
int ReturnZero62B5C0()
{
  return 0;
}

// IDA: 0x62DA40  proposal: MathDispatch62DA40
// IDA: void sub_62DA40()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC4A40 = Math::Sqrt(v0 + v0);
void MathDispatch62DA40()
{
}

// IDA: 0x62DA90  proposal: InitFloatConst62DA90
// IDA: void sub_62DA90()
//   dbl_AC4A78 = 1.0 / dbl_AC4A90;
void InitFloatConst62DA90()
{
}

// IDA: 0x62DB10  proposal: MathDispatch62DB10
// IDA: __int64 sub_62DB10()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC4A20 - dbl_AC4A48);
//   result = Math::RoundToInt(v0 * dbl_AC4A40 * 0.5);
//   dword_AC4A98 = result;
//   return result;
int MathDispatch62DB10()
{
  return 0;
}

// IDA: 0x62DB50  proposal: ArcMath62DB50
// IDA: void sub_62DB50()
//   dbl_AC4A50 = Math::ArcTan((double)dword_AC4A98 * 0.00390625);
void ArcMath62DB50()
{
}

// IDA: 0x62DB80  proposal: ArcMath62DB80
// IDA: void sub_62DB80()
//   dbl_AC4A68 = Math::ArcTan((double)(2 * dword_AC4A98) / dbl_AC4A40);
void ArcMath62DB80()
{
}

// IDA: 0x62DBB0  proposal: MathRoundToInt62DBB0
// IDA: __int64 sub_62DBB0()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC4A98) + 0.5);
//   dword_AC4A8C = result;
//   return result;
int MathRoundToInt62DBB0()
{
  return 0;
}

// IDA: 0x62DBE0  proposal: ReturnZero62DBE0
// IDA: int sub_62DBE0()
//   word_AC4A38 = 0;
//   word_AC4A3A = 0;
//   return 0;
int ReturnZero62DBE0()
{
  return 0;
}

// IDA: 0x62DBF0  proposal: ReturnZero62DBF0
// IDA: int sub_62DBF0()
//   dword_AC4A58 = 0;
//   dword_AC4A5C = 0;
//   dword_AC4A60 = 0;
//   return 0;
int ReturnZero62DBF0()
{
  return 0;
}

// IDA: 0x62DC30  proposal: ReturnZero62DC30
// IDA: int sub_62DC30()
//   dword_AC4A28 = 0;
//   dword_AC4A2C = 0;
//   dword_AC4A30 = 0;
//   dword_AC4A34 = 0;
//   return 0;
int ReturnZero62DC30()
{
  return 0;
}

// IDA: 0x6302F0  proposal: ReturnZero6302F0
// IDA: int sub_6302F0()
//   dword_AC4AA0 = 0;
//   dword_AC4AA4 = 0;
//   dword_AC4AA8 = 0;
//   dword_AC4AAC = 0;
//   return 0;
int ReturnZero6302F0()
{
  return 0;
}

// IDA: 0x630980  proposal: ReturnZero630980
// IDA: int sub_630980()
//   dword_AC4AB8 = 0;
//   dword_AC4ABC = 0;
//   dword_AC4AC0 = 0;
//   dword_AC4AC4 = 0;
//   return 0;
int ReturnZero630980()
{
  return 0;
}

// IDA: 0x6309A0  proposal: MathDispatch6309A0
// IDA: void sub_6309A0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC4AD0 = Math::Sqrt(v0 + v0);
void MathDispatch6309A0()
{
}

// IDA: 0x6309F0  proposal: InitFloatConst6309F0
// IDA: void sub_6309F0()
//   dbl_AC4B08 = 1.0 / dbl_AC4B20;
void InitFloatConst6309F0()
{
}

// IDA: 0x630A70  proposal: MathDispatch630A70
// IDA: __int64 sub_630A70()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC4AB0 - dbl_AC4AD8);
//   result = Math::RoundToInt(v0 * dbl_AC4AD0 * 0.5);
//   dword_AC4B28 = result;
//   return result;
int MathDispatch630A70()
{
  return 0;
}

// IDA: 0x630AB0  proposal: ArcMath630AB0
// IDA: void sub_630AB0()
//   dbl_AC4AE0 = Math::ArcTan((double)dword_AC4B28 * 0.00390625);
void ArcMath630AB0()
{
}

// IDA: 0x630AE0  proposal: ArcMath630AE0
// IDA: void sub_630AE0()
//   dbl_AC4AF8 = Math::ArcTan((double)(2 * dword_AC4B28) / dbl_AC4AD0);
void ArcMath630AE0()
{
}

// IDA: 0x630B10  proposal: MathRoundToInt630B10
// IDA: __int64 sub_630B10()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC4B28) + 0.5);
//   dword_AC4B1C = result;
//   return result;
int MathRoundToInt630B10()
{
  return 0;
}

// IDA: 0x630B40  proposal: ReturnZero630B40
// IDA: int sub_630B40()
//   word_AC4AC8 = 0;
//   word_AC4ACA = 0;
//   return 0;
int ReturnZero630B40()
{
  return 0;
}

// IDA: 0x630B50  proposal: ReturnZero630B50
// IDA: int sub_630B50()
//   dword_AC4AE8 = 0;
//   dword_AC4AEC = 0;
//   dword_AC4AF0 = 0;
//   return 0;
int ReturnZero630B50()
{
  return 0;
}

// IDA: 0x631F10  proposal: SetMember12631F10
// IDA: int __thiscall sub_631F10(_DWORD *this, int a2, int a3)
//   *(this + 12) = a2;
//   *(this + 13) = a3;
//   return a2;
int SetMember12631F10(void* _this, int a0, int a1) // thiscall
{
  return 0;
}

// IDA: 0x631F30  proposal: MethodStub631F30
// IDA: void __thiscall sub_631F30(_DWORD *this)
//   *this = &PixelFXClass::`vftable';
void MethodStub631F30(void* _this) // thiscall
{
}

// IDA: 0x631FC0  proposal: MethodEncodeVarInt
// IDA: int __thiscall sub_631FC0(void *this, _BYTE *a2)
//   if ( a2 )
//   return EncodeVarInt((int)this, a2, 64);
//   else
//   return 0;
int MethodEncodeVarInt(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x631FE0  proposal: MethodEncodeVarInt631FE0
// IDA: int __thiscall sub_631FE0(void *this, _BYTE *a2)
//   if ( a2 )
//   return EncodeVarInt((int)this + 256, a2, 64);
//   else
//   return 0;
int MethodEncodeVarInt631FE0(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x632A70  proposal: MethodSub5C8E40
// IDA: int __thiscall sub_632A70(int *this, int a2, int a3, int a4)
//   int result; // eax
//   sub_5C8E40(this, a2, a3, a4, 64);
//   result = *this;
//   LOBYTE(result) = *this | 1;
//   *this = result;
//   return result;
int MethodSub5C8E40(void* _this, int a0, int a1, int a2) // thiscall
{
  return 0;
}

// IDA: 0x6333D0  proposal: MathDispatch6333D0
// IDA: void sub_6333D0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC4BE8 = Math::Sqrt(v0 + v0);
void MathDispatch6333D0()
{
}

// IDA: 0x633420  proposal: InitFloatConst633420
// IDA: void sub_633420()
//   dbl_AC4CC0 = 1.0 / dbl_AC4CE8;
void InitFloatConst633420()
{
}

// IDA: 0x6334A0  proposal: MathDispatch6334A0
// IDA: __int64 sub_6334A0()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC4B68 - dbl_AC4C10);
//   result = Math::RoundToInt(v0 * dbl_AC4BE8 * 0.5);
//   dword_AC4CF0 = result;
//   return result;
int MathDispatch6334A0()
{
  return 0;
}

// IDA: 0x6334E0  proposal: ArcMath6334E0
// IDA: void sub_6334E0()
//   dbl_AC4C30 = Math::ArcTan((double)dword_AC4CF0 * 0.00390625);
void ArcMath6334E0()
{
}

// IDA: 0x633510  proposal: ArcMath633510
// IDA: void sub_633510()
//   dbl_AC4C70 = Math::ArcTan((double)(2 * dword_AC4CF0) / dbl_AC4BE8);
void ArcMath633510()
{
}

// IDA: 0x633540  proposal: MathRoundToInt633540
// IDA: __int64 sub_633540()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC4CF0) + 0.5);
//   dword_AC4CE4 = result;
//   return result;
int MathRoundToInt633540()
{
  return 0;
}

// IDA: 0x633570  proposal: ReturnZero633570
// IDA: int sub_633570()
//   word_AC4BE4 = 0;
//   word_AC4BE6 = 0;
//   return 0;
int ReturnZero633570()
{
  return 0;
}

// IDA: 0x633580  proposal: ReturnZero633580
// IDA: int sub_633580()
//   dword_AC4C58 = 0;
//   dword_AC4C5C = 0;
//   dword_AC4C60 = 0;
//   return 0;
int ReturnZero633580()
{
  return 0;
}

// IDA: 0x6335C0  proposal: ReturnZero6335C0
// IDA: int sub_6335C0()
//   dword_AC4B70 = 0;
//   dword_AC4B74 = 0;
//   dword_AC4B78 = 0;
//   dword_AC4B7C = 0;
//   return 0;
int ReturnZero6335C0()
{
  return 0;
}

// IDA: 0x633A20  proposal: SetMember1633A20
// IDA: _DWORD *__thiscall sub_633A20(_DWORD *this)
//   *this = 0;
//   *(this + 1) = 0;
//   *(this + 2) = -1;
//   *((_BYTE *)this + 12) = 0;
//   return this;
int* SetMember1633A20(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x633A40  proposal: MethodStub633A40
// IDA: int __thiscall sub_633A40(_DWORD *this, int a2)
//   *this = a2;
//   return a2;
int MethodStub633A40(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x633A50  proposal: SetMember1633A50
// IDA: int __thiscall sub_633A50(_DWORD *this, int a2)
//   *(this + 1) = a2;
//   return a2;
int SetMember1633A50(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x633A60  proposal: SetMember2633A60
// IDA: int __thiscall sub_633A60(_DWORD *this, int a2)
//   *(this + 2) = a2;
//   return a2;
int SetMember2633A60(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x633A70  proposal: SetMember12633A70
// IDA: char __thiscall sub_633A70(_BYTE *this, char a2)
//   *(this + 12) = a2;
//   return a2;
char SetMember12633A70(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x633A90  proposal: GetMember1
// IDA: int __thiscall sub_633A90(_DWORD *this)
//   return *(this + 1);
int GetMember1(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x633AA0  proposal: GetMember2633AA0
// IDA: int __thiscall sub_633AA0(_DWORD *this)
//   return *(this + 2);
int GetMember2633AA0(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x633AB0  proposal: GetMember12633AB0
// IDA: // ?do_decimal_point@?$_Mpunct@D@std@@MBEDXZ
//       // doubtful name
//       char __thiscall sub_633AB0(_BYTE *this)
//   return *(this + 12);
int GetMember12633AB0(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x633AE0  proposal: MethodStub633AE0
// IDA: void __thiscall sub_633AE0(void *this, const void *a2)
//   qmemcpy(this, a2, 0x6Fu);
void MethodStub633AE0(void* _this, int a0) // thiscall
{
}

// IDA: 0x633B00  proposal: SetMember28633B00
// IDA: int __thiscall sub_633B00(_DWORD *this, int a2)
//   *(this + 28) = a2;
//   return a2;
int SetMember28633B00(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x633B10  proposal: SetMember29
// IDA: int __thiscall sub_633B10(_DWORD *this, int a2)
//   *(this + 29) = a2;
//   return a2;
int SetMember29(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x633B20  proposal: SetMember28633B20
// IDA: void __thiscall sub_633B20(_DWORD *this)
//   *(this + 28) = 0;
void SetMember28633B20(void* _this) // thiscall
{
}

// IDA: 0x633B30  proposal: SetMember28633B30
// IDA: int __thiscall sub_633B30(_DWORD *this)
//   int result; // eax
//   result = *(this + 28) + 1;
//   *(this + 28) = result;
//   return result;
int SetMember28633B30(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x633B40  proposal: SetMember28633B40
// IDA: int __thiscall sub_633B40(_DWORD *this)
//   int result; // eax
//   result = *(this + 28) - 1;
//   *(this + 28) = result;
//   return result;
int SetMember28633B40(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x633B70  proposal: GetMember28
// IDA: int __thiscall sub_633B70(_DWORD *this)
//   return *(this + 28);
int GetMember28(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x633B80  proposal: GetMember29
// IDA: int __thiscall sub_633B80(_DWORD *this)
//   return *(this + 29);
int GetMember29(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x633E50  proposal: GetMember6633E50
// IDA: int __thiscall sub_633E50(_DWORD *this)
//   return *(this + 6);
int GetMember6633E50(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x633E60  proposal: GetMember4633E60
// IDA: int __thiscall sub_633E60(_DWORD *this)
//   return *(this + 4);
int GetMember4633E60(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x6343B0  proposal: MethodStub6343B0
// IDA: int __thiscall sub_6343B0(_DWORD ***this)
//   return *(_DWORD *)(***(this + 1) + 540);
int MethodStub6343B0(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x634700  proposal: GetMember12634700
// IDA: int __thiscall sub_634700(_DWORD *this)
//   return *(this + 12);
int GetMember12634700(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x6347A0  proposal: MethodStub6347A0
// IDA: int __thiscall sub_6347A0(_DWORD *this, int a2)
//   return *(_DWORD *)(*(this + 9) + 4 * a2);
int MethodStub6347A0(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x634800  proposal: MethodStub634800
// IDA: char *__thiscall sub_634800(char *this)
//   return this + 56;
char* MethodStub634800(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x634850  proposal: MethodGet634850
// IDA: _DWORD *__thiscall sub_634850(_BYTE *this, _DWORD *a2)
//   int *ScenarioClassActionCoords; // eax
//   int v3; // ecx
//   int v4; // edx
//   int v5; // esi
//   _DWORD v7[3]; // [esp+8h] [ebp-Ch] BYREF
//   ScenarioClassActionCoords = GetScenarioClassActionCoords(v7, this + 56);
//   v3 = *ScenarioClassActionCoords;
//   v4 = ScenarioClassActionCoords[1];
//   v5 = ScenarioClassActionCoords[2];
//   *a2 = v3;
//   a2[1] = v4;
//   a2[2] = v5;
//   return a2;
int* MethodGet634850(void* _this, int a0) // thiscall
{
  return 0;
}

// IDA: 0x634950  proposal: SetMember28634950
// IDA: void __thiscall sub_634950(_BYTE *this)
//   *(this + 28) = 1;
void SetMember28634950(void* _this) // thiscall
{
}

// IDA: 0x634960  proposal: GetMember28634960
// IDA: char __thiscall sub_634960(_BYTE *this)
//   return *(this + 28);
char GetMember28634960(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x6352D0  proposal: MethodStub6352D0
// IDA: char __thiscall sub_6352D0(int *this)
//   int v2; // esi
//   int v3; // ebx
//   _BYTE *v4; // ecx
//   char result; // al
//   v2 = 0;
//   v3 = *(this + 4);
//   if ( v3 > 0 )
//   {
//   do
//   {
//   v4 = **(_BYTE ***)(*(this + 1) + 4 * v2);
//   result = v4[131];
//   if ( !result )
//   result = (*(int (__thiscall **)(_BYTE *))(*(_DWORD *)v4 + 332))(v4);
//   ++v2;
//   }
//   while ( v2 < v3 );
//   }
//   return result;
char MethodStub6352D0(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x635310  proposal: MethodStub635310
// IDA: char __thiscall sub_635310(int *this)
//   int v2; // esi
//   int v3; // ebx
//   _BYTE *v4; // ecx
//   char result; // al
//   v2 = 0;
//   v3 = *(this + 4);
//   if ( v3 > 0 )
//   {
//   do
//   {
//   v4 = **(_BYTE ***)(*(this + 1) + 4 * v2);
//   result = v4[131];
//   if ( result )
//   result = (*(int (__thiscall **)(_BYTE *))(*(_DWORD *)v4 + 336))(v4);
//   ++v2;
//   }
//   while ( v2 < v3 );
//   }
//   return result;
char MethodStub635310(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x636520  proposal: SetMember28636520
// IDA: void __thiscall sub_636520(_BYTE *this)
//   *(this + 28) = 1;
void SetMember28636520(void* _this) // thiscall
{
}

// IDA: 0x636530  proposal: SetMember28636530
// IDA: void __thiscall sub_636530(_BYTE *this)
//   *(this + 28) = 0;
void SetMember28636530(void* _this) // thiscall
{
}

// IDA: 0x636540  proposal: GetMember28636540
// IDA: char __thiscall sub_636540(_BYTE *this)
//   return *(this + 28);
char GetMember28636540(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x636FA0  proposal: MethodStub636FA0
// IDA: int __thiscall sub_636FA0(int this, int a2, int a3)
//   *(_DWORD *)(this + 144) = a2;
//   *(_DWORD *)(this + 148) = a3;
//   *(_BYTE *)(this + 152) = 1;
//   return a2;
int MethodStub636FA0(void* _this, int a0, int a1) // thiscall
{
  return 0;
}

// IDA: 0x636FD0  proposal: GetMember37
// IDA: int __thiscall sub_636FD0(_DWORD *this)
//   return *(this + 37);
int GetMember37(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x637030  proposal: GetMember153
// IDA: char __thiscall sub_637030(_BYTE *this)
//   return *(this + 153);
char GetMember153(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x63A4A0  proposal: MethodStub63A4A0
// IDA: void __thiscall sub_63A4A0(void *this)
//   dword_AC4C90 = (int)this;
void MethodStub63A4A0(void* _this) // thiscall
{
}

// IDA: 0x63AD30  proposal: MethodStub63AD30
// IDA: void __thiscall sub_63AD30(void *this)
//   g_ScriptState = (int)this;
void MethodStub63AD30(void* _this) // thiscall
{
}

// IDA: 0x63B080  proposal: MethodStub63B080
// IDA: void __thiscall sub_63B080(void *this)
//   g_ScriptActionPool = (int)this;
void MethodStub63B080(void* _this) // thiscall
{
}

// IDA: 0x63B090  proposal: Sub63B090
// IDA: void sub_63B090()
//   g_ScriptActionPool = 0;
void Sub63B090()
{
}

// IDA: 0x63F4A0  proposal: ReturnZero63F4A0
// IDA: int sub_63F4A0()
//   dword_AC4D00 = 0;
//   dword_AC4D04 = 0;
//   dword_AC4D08 = 0;
//   dword_AC4D0C = 0;
//   return 0;
int ReturnZero63F4A0()
{
  return 0;
}

// IDA: 0x63F4C0  proposal: MathDispatch63F4C0
// IDA: void sub_63F4C0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC4D18 = Math::Sqrt(v0 + v0);
void MathDispatch63F4C0()
{
}

// IDA: 0x63F510  proposal: InitFloatConst63F510
// IDA: void sub_63F510()
//   dbl_AC4E50 = 1.0 / dbl_AC4E68;
void InitFloatConst63F510()
{
}

// IDA: 0x63F590  proposal: MathDispatch63F590
// IDA: __int64 sub_63F590()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC4CF8 - dbl_AC4D20);
//   result = Math::RoundToInt(v0 * dbl_AC4D18 * 0.5);
//   dword_AC4E70 = result;
//   return result;
int MathDispatch63F590()
{
  return 0;
}

// IDA: 0x63F5D0  proposal: ArcMath63F5D0
// IDA: void sub_63F5D0()
//   dbl_AC4D28 = Math::ArcTan((double)dword_AC4E70 * 0.00390625);
void ArcMath63F5D0()
{
}

// IDA: 0x63F600  proposal: ArcMath63F600
// IDA: void sub_63F600()
//   dbl_AC4E40 = Math::ArcTan((double)(2 * dword_AC4E70) / dbl_AC4D18);
void ArcMath63F600()
{
}

// IDA: 0x63F630  proposal: MathRoundToInt63F630
// IDA: __int64 sub_63F630()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC4E70) + 0.5);
//   dword_AC4E64 = result;
//   return result;
int MathRoundToInt63F630()
{
  return 0;
}

// IDA: 0x63F660  proposal: ReturnZero63F660
// IDA: int sub_63F660()
//   word_AC4D10 = 0;
//   word_AC4D12 = 0;
//   return 0;
int ReturnZero63F660()
{
  return 0;
}

// IDA: 0x63F670  proposal: ReturnZero63F670
// IDA: int sub_63F670()
//   dword_AC4E30 = 0;
//   dword_AC4E34 = 0;
//   dword_AC4E38 = 0;
//   return 0;
int ReturnZero63F670()
{
  return 0;
}

// IDA: 0x6404D0  proposal: ReturnZero6404D0
// IDA: int sub_6404D0()
//   dword_AC4E98 = 0;
//   dword_AC4E9C = 0;
//   dword_AC4EA0 = 0;
//   dword_AC4EA4 = 0;
//   return 0;
int ReturnZero6404D0()
{
  return 0;
}

// IDA: 0x6404F0  proposal: MathDispatch6404F0
// IDA: void sub_6404F0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC4EB0 = Math::Sqrt(v0 + v0);
void MathDispatch6404F0()
{
}

// IDA: 0x640540  proposal: InitFloatConst640540
// IDA: void sub_640540()
//   dbl_AC4EE8 = 1.0 / dbl_AC4F00;
void InitFloatConst640540()
{
}

// IDA: 0x6405C0  proposal: MathDispatch6405C0
// IDA: __int64 sub_6405C0()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC4E88 - dbl_AC4EB8);
//   result = Math::RoundToInt(v0 * dbl_AC4EB0 * 0.5);
//   dword_AC4F08 = result;
//   return result;
int MathDispatch6405C0()
{
  return 0;
}

// IDA: 0x640600  proposal: ArcMath640600
// IDA: void sub_640600()
//   dbl_AC4EC0 = Math::ArcTan((double)dword_AC4F08 * 0.00390625);
void ArcMath640600()
{
}

// IDA: 0x640630  proposal: ArcMath640630
// IDA: void sub_640630()
//   dbl_AC4ED8 = Math::ArcTan((double)(2 * dword_AC4F08) / dbl_AC4EB0);
void ArcMath640630()
{
}

// IDA: 0x640660  proposal: MathRoundToInt640660
// IDA: __int64 sub_640660()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC4F08) + 0.5);
//   dword_AC4EFC = result;
//   return result;
int MathRoundToInt640660()
{
  return 0;
}

// IDA: 0x640690  proposal: ReturnZero640690
// IDA: int sub_640690()
//   word_AC4EA8 = 0;
//   word_AC4EAA = 0;
//   return 0;
int ReturnZero640690()
{
  return 0;
}

// IDA: 0x6406A0  proposal: ReturnZero6406A0
// IDA: int sub_6406A0()
//   dword_AC4EC8 = 0;
//   dword_AC4ECC = 0;
//   dword_AC4ED0 = 0;
//   return 0;
int ReturnZero6406A0()
{
  return 0;
}

// IDA: 0x642770  proposal: ReturnZero642770
// IDA: int sub_642770()
//   dword_AC4F18 = 0;
//   dword_AC4F1C = 0;
//   dword_AC4F20 = 0;
//   dword_AC4F24 = 0;
//   return 0;
int ReturnZero642770()
{
  return 0;
}

// IDA: 0x642790  proposal: MathDispatch642790
// IDA: void sub_642790()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC4F30 = Math::Sqrt(v0 + v0);
void MathDispatch642790()
{
}

// IDA: 0x6427E0  proposal: InitFloatConst6427E0
// IDA: void sub_6427E0()
//   dbl_AC4FF0 = 1.0 / dbl_AC5008;
void InitFloatConst6427E0()
{
}

// IDA: 0x642860  proposal: MathDispatch642860
// IDA: __int64 sub_642860()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC4F10 - dbl_AC4F38);
//   result = Math::RoundToInt(v0 * dbl_AC4F30 * 0.5);
//   dword_AC5010 = result;
//   return result;
int MathDispatch642860()
{
  return 0;
}

// IDA: 0x6428A0  proposal: ArcMath6428A0
// IDA: void sub_6428A0()
//   dbl_AC4F40 = Math::ArcTan((double)dword_AC5010 * 0.00390625);
void ArcMath6428A0()
{
}

// IDA: 0x6428D0  proposal: ArcMath6428D0
// IDA: void sub_6428D0()
//   dbl_AC4FE0 = Math::ArcTan((double)(2 * dword_AC5010) / dbl_AC4F30);
void ArcMath6428D0()
{
}

// IDA: 0x642900  proposal: MathRoundToInt642900
// IDA: __int64 sub_642900()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC5010) + 0.5);
//   dword_AC5004 = result;
//   return result;
int MathRoundToInt642900()
{
  return 0;
}

// IDA: 0x642930  proposal: ReturnZero642930
// IDA: int sub_642930()
//   word_AC4F28 = 0;
//   word_AC4F2A = 0;
//   return 0;
int ReturnZero642930()
{
  return 0;
}

// IDA: 0x642940  proposal: ReturnZero642940
// IDA: int sub_642940()
//   dword_AC4F48 = 0;
//   dword_AC4F4C = 0;
//   dword_AC4F50 = 0;
//   return 0;
int ReturnZero642940()
{
  return 0;
}

// IDA: 0x642980  proposal: Callatexit642980
// IDA: int sub_642980()
//   sub_6429E0(g_UIManager);
//   return atexit(sub_6429A0);
int Callatexit642980()
{
  return 0;
}

// IDA: 0x643EB0  proposal: MathDispatch643EB0
// IDA: void sub_643EB0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC5028 = Math::Sqrt(v0 + v0);
void MathDispatch643EB0()
{
}

// IDA: 0x643F00  proposal: InitFloatConst643F00
// IDA: void sub_643F00()
//   dbl_AC5060 = 1.0 / dbl_AC5078;
void InitFloatConst643F00()
{
}

// IDA: 0x643F80  proposal: MathDispatch643F80
// IDA: __int64 sub_643F80()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC5018 - dbl_AC5030);
//   result = Math::RoundToInt(v0 * dbl_AC5028 * 0.5);
//   dword_AC5080 = result;
//   return result;
int MathDispatch643F80()
{
  return 0;
}

// IDA: 0x643FC0  proposal: ArcMath643FC0
// IDA: void sub_643FC0()
//   dbl_AC5038 = Math::ArcTan((double)dword_AC5080 * 0.00390625);
void ArcMath643FC0()
{
}

// IDA: 0x643FF0  proposal: ArcMath643FF0
// IDA: void sub_643FF0()
//   dbl_AC5050 = Math::ArcTan((double)(2 * dword_AC5080) / dbl_AC5028);
void ArcMath643FF0()
{
}

// IDA: 0x644020  proposal: MathRoundToInt644020
// IDA: __int64 sub_644020()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC5080) + 0.5);
//   dword_AC5074 = result;
//   return result;
int MathRoundToInt644020()
{
  return 0;
}

// IDA: 0x644050  proposal: ReturnZero644050
// IDA: int sub_644050()
//   word_AC5020 = 0;
//   word_AC5022 = 0;
//   return 0;
int ReturnZero644050()
{
  return 0;
}

// IDA: 0x644060  proposal: ReturnZero644060
// IDA: int sub_644060()
//   dword_AC5040 = 0;
//   dword_AC5044 = 0;
//   dword_AC5048 = 0;
//   return 0;
int ReturnZero644060()
{
  return 0;
}

// IDA: 0x6449F0  proposal: MathDispatch6449F0
// IDA: void sub_6449F0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC5098 = Math::Sqrt(v0 + v0);
void MathDispatch6449F0()
{
}

// IDA: 0x644A40  proposal: InitFloatConst644A40
// IDA: void sub_644A40()
//   dbl_AC50D0 = 1.0 / dbl_AC50E8;
void InitFloatConst644A40()
{
}

// IDA: 0x644AC0  proposal: MathDispatch644AC0
// IDA: __int64 sub_644AC0()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC5088 - dbl_AC50A0);
//   result = Math::RoundToInt(v0 * dbl_AC5098 * 0.5);
//   dword_AC50F0 = result;
//   return result;
int MathDispatch644AC0()
{
  return 0;
}

// IDA: 0x644B00  proposal: ArcMath644B00
// IDA: void sub_644B00()
//   dbl_AC50A8 = Math::ArcTan((double)dword_AC50F0 * 0.00390625);
void ArcMath644B00()
{
}

// IDA: 0x644B30  proposal: ArcMath644B30
// IDA: void sub_644B30()
//   dbl_AC50C0 = Math::ArcTan((double)(2 * dword_AC50F0) / dbl_AC5098);
void ArcMath644B30()
{
}

// IDA: 0x644B60  proposal: MathRoundToInt644B60
// IDA: __int64 sub_644B60()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_AC50F0) + 0.5);
//   dword_AC50E4 = result;
//   return result;
int MathRoundToInt644B60()
{
  return 0;
}

// IDA: 0x644B90  proposal: ReturnZero644B90
// IDA: int sub_644B90()
//   word_AC5090 = 0;
//   word_AC5092 = 0;
//   return 0;
int ReturnZero644B90()
{
  return 0;
}

// IDA: 0x644BA0  proposal: ReturnZero644BA0
// IDA: int sub_644BA0()
//   dword_AC50B0 = 0;
//   dword_AC50B4 = 0;
//   dword_AC50B8 = 0;
//   return 0;
int ReturnZero644BA0()
{
  return 0;
}

// IDA: 0x645BA0  proposal: ReturnOff7F0248
// IDA: char *__fastcall sub_645BA0(int a1)
//   return off_7F0248[a1];
char* ReturnOff7F0248(int a0) // fastcall
{
  return 0;
}

// IDA: 0x645CD0  proposal: SetMember1645CD0
// IDA: void __thiscall sub_645CD0(float *this, float a2)
//   *this = a2 * *this;
//   *(this + 1) = a2 * *(this + 1);
//   *(this + 2) = a2 * *(this + 2);
//   *(this + 3) = a2 * *(this + 3);
void SetMember1645CD0(void* _this, int a0) // thiscall
{
}

// IDA: 0x646464  proposal: ArithmeticCompute646464
// IDA: // positive sp value has been detected, the output may be wrong!
//       int __userpurge sub_646464@<eax>(int a1@<eax>, int a2@<ecx>, int a3@<esi>, int a4, int a5, int a6, int a7, int a8)
//   *(_DWORD *)(a2 + 12) = a1;
//   return a3;
int ArithmeticCompute646464(int a0, int a1, int a2, int a3, int a4, int a5, int a6, int a7)
{
  return 0;
}

// IDA: 0x646A80  proposal: MathDispatch646A80
// IDA: void sub_646A80()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_AC6650 = Math::Sqrt(v0 + v0);
void MathDispatch646A80()
{
}

// IDA: 0x646AD0  proposal: InitFloatConst646AD0
// IDA: void sub_646AD0()
//   dbl_AFA410 = 1.0 / dbl_AFA460;
void InitFloatConst646AD0()
{
}

// IDA: 0x646B50  proposal: MathDispatch646B50
// IDA: __int64 sub_646B50()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_AC5208 - dbl_AFA260);
//   result = Math::RoundToInt(v0 * dbl_AC6650 * 0.5);
//   dword_B0446C = result;
//   return result;
int MathDispatch646B50()
{
  return 0;
}

// IDA: 0x646B90  proposal: ArcMath646B90
// IDA: void sub_646B90()
//   dbl_AFA270 = Math::ArcTan((double)dword_B0446C * 0.00390625);
void ArcMath646B90()
{
}

// IDA: 0x646BC0  proposal: ArcMath646BC0
// IDA: void sub_646BC0()
//   dbl_AFA330 = Math::ArcTan((double)(2 * dword_B0446C) / dbl_AC6650);
void ArcMath646BC0()
{
}

// IDA: 0x646BF0  proposal: MathRoundToInt646BF0
// IDA: __int64 sub_646BF0()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_B0446C) + 0.5);
//   dword_AFA45C = result;
//   return result;
int MathRoundToInt646BF0()
{
  return 0;
}

// IDA: 0x646C20  proposal: ReturnZero646C20
// IDA: int sub_646C20()
//   dword_AC6640 = 0;
//   return 0;
int ReturnZero646C20()
{
  return 0;
}

// IDA: 0x646C30  proposal: ReturnZero646C30
// IDA: int sub_646C30()
//   dword_AFA320 = 0;
//   dword_AFA324 = 0;
//   dword_AFA328 = 0;
//   return 0;
int ReturnZero646C30()
{
  return 0;
}

// IDA: 0x646C70  proposal: ReturnZero646C70
// IDA: int sub_646C70()
//   dword_AC6630 = 0;
//   dword_AC6634 = 0;
//   dword_AC6638 = 0;
//   dword_AC663C = 0;
//   return 0;
int ReturnZero646C70()
{
  return 0;
}

// IDA: 0x646D00  proposal: SetMember1646D00
// IDA: _DWORD *__thiscall sub_646D00(_DWORD *this)
//   *this = -1;
//   *(this + 1) = 0;
//   *(this + 2) = 0;
//   *(this + 3) = 0;
//   *(this + 4) = 0;
//   *(this + 5) = 0;
//   return this;
int* SetMember1646D00(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x646D20  proposal: ArithmeticCompute646D20
// IDA: _DWORD *sub_646D20()
//   _DWORD *result; // eax
//   int v1; // edx
//   result = &unk_AFA280;
//   v1 = 7;
//   do
//   {
//   *(result - 2) = -1;
//   *(result - 1) = 0;
//   *result = 0;
//   result[1] = 0;
//   result[2] = 0;
//   result[3] = 0;
//   result += 6;
//   --v1;
//   }
//   while ( v1 );
//   return result;
int* ArithmeticCompute646D20()
{
  return 0;
}

// IDA: 0x646D90  proposal: GetTimer646D90
// IDA: int sub_646D90()
//   dword_AC6648 = Timer::GetTicks();
//   return atexit(nullsub_216);
int GetTimer646D90()
{
  return 0;
}

// IDA: 0x646DC0  proposal: ArithmeticCompute646DC0
// IDA: _DWORD *sub_646DC0()
//   _DWORD *result; // eax
//   int v1; // edx
//   result = &unk_AFA360;
//   v1 = 7;
//   do
//   {
//   *(result - 2) = -1;
//   *(result - 1) = 0;
//   *result = 0;
//   result[1] = 0;
//   result[2] = 0;
//   result[3] = 0;
//   result += 6;
//   --v1;
//   }
//   while ( v1 );
//   return result;
int* ArithmeticCompute646DC0()
{
  return 0;
}

// IDA: 0x64AE30  proposal: ReturnZero64AE30
// IDA: int sub_64AE30()
//   dword_B04884 = 0;
//   dword_B04888 = 0;
//   byte_B0488C = 0;
//   byte_B0488D = 0;
//   byte_B04878 = 0;
//   return 0;
int ReturnZero64AE30()
{
  return 0;
}

// IDA: 0x652630  proposal: ReturnZero652630
// IDA: int __cdecl sub_652630(_DWORD *a1, _DWORD *a2)
//   if ( *a1 == *a2 )
//   return 0;
//   else
//   return *a1 >= *a2 ? 1 : -1;
int ReturnZero652630(int a0, int a1)
{
  return 0;
}

// IDA: 0x652660  proposal: ReturnZero652660
// IDA: int sub_652660()
//   dword_B048B0 = 0;
//   dword_B048B4 = 0;
//   dword_B048B8 = 0;
//   dword_B048BC = 0;
//   return 0;
int ReturnZero652660()
{
  return 0;
}

// IDA: 0x652680  proposal: MathDispatch652680
// IDA: void sub_652680()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_B048D8 = Math::Sqrt(v0 + v0);
void MathDispatch652680()
{
}

// IDA: 0x6526D0  proposal: InitFloatConst6526D0
// IDA: void sub_6526D0()
//   dbl_B049E0 = 1.0 / dbl_B049F8;
void InitFloatConst6526D0()
{
}

// IDA: 0x652750  proposal: MathDispatch652750
// IDA: __int64 sub_652750()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_B048A0 - dbl_B048E8);
//   result = Math::RoundToInt(v0 * dbl_B048D8 * 0.5);
//   dword_B04A34 = result;
//   return result;
int MathDispatch652750()
{
  return 0;
}

// IDA: 0x652790  proposal: ArcMath652790
// IDA: void sub_652790()
//   dbl_B048F0 = Math::ArcTan((double)dword_B04A34 * 0.00390625);
void ArcMath652790()
{
}

// IDA: 0x6527C0  proposal: ArcMath6527C0
// IDA: void sub_6527C0()
//   dbl_B04970 = Math::ArcTan((double)(2 * dword_B04A34) / dbl_B048D8);
void ArcMath6527C0()
{
}

// IDA: 0x6527F0  proposal: MathRoundToInt6527F0
// IDA: __int64 sub_6527F0()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_B04A34) + 0.5);
//   dword_B049F4 = result;
//   return result;
int MathRoundToInt6527F0()
{
  return 0;
}

// IDA: 0x652820  proposal: ReturnZero652820
// IDA: int sub_652820()
//   dword_B048C0 = 0;
//   return 0;
int ReturnZero652820()
{
  return 0;
}

// IDA: 0x652830  proposal: ReturnZero652830
// IDA: int sub_652830()
//   dword_B04900 = 0;
//   dword_B04904 = 0;
//   dword_B04908 = 0;
//   return 0;
int ReturnZero652830()
{
  return 0;
}

// IDA: 0x652CD0  proposal: SetMember1323
// IDA: void __thiscall sub_652CD0(_DWORD *this)
//   *(this + 1323) = 4;
//   *(this + 1343) = 25;
void SetMember1323(void* _this) // thiscall
{
}

// IDA: 0x655890  proposal: MethodStub655890
// IDA: int __thiscall sub_655890(_DWORD *this)
//   return *this + 251 * *(this + 1);
int MethodStub655890(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x658E80  proposal: MathDispatch658E80
// IDA: void sub_658E80()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_B04A78 = Math::Sqrt(v0 + v0);
void MathDispatch658E80()
{
}

// IDA: 0x658ED0  proposal: InitFloatConst658ED0
// IDA: void sub_658ED0()
//   dbl_B04AB0 = 1.0 / dbl_B04AC8;
void InitFloatConst658ED0()
{
}

// IDA: 0x658F50  proposal: MathDispatch658F50
// IDA: __int64 sub_658F50()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_B04A40 - dbl_B04A80);
//   result = Math::RoundToInt(v0 * dbl_B04A78 * 0.5);
//   dword_B04AD0 = result;
//   return result;
int MathDispatch658F50()
{
  return 0;
}

// IDA: 0x658F90  proposal: ArcMath658F90
// IDA: void sub_658F90()
//   dbl_B04A88 = Math::ArcTan((double)dword_B04AD0 * 0.00390625);
void ArcMath658F90()
{
}

// IDA: 0x658FC0  proposal: ArcMath658FC0
// IDA: void sub_658FC0()
//   dbl_B04AA0 = Math::ArcTan((double)(2 * dword_B04AD0) / dbl_B04A78);
void ArcMath658FC0()
{
}

// IDA: 0x658FF0  proposal: MathRoundToInt658FF0
// IDA: __int64 sub_658FF0()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_B04AD0) + 0.5);
//   dword_B04AC4 = result;
//   return result;
int MathRoundToInt658FF0()
{
  return 0;
}

// IDA: 0x659020  proposal: ReturnZero659020
// IDA: int sub_659020()
//   word_B04A58 = 0;
//   word_B04A5A = 0;
//   return 0;
int ReturnZero659020()
{
  return 0;
}

// IDA: 0x659030  proposal: ReturnZero659030
// IDA: int sub_659030()
//   dword_B04A90 = 0;
//   dword_B04A94 = 0;
//   dword_B04A98 = 0;
//   return 0;
int ReturnZero659030()
{
  return 0;
}

// IDA: 0x659070  proposal: ReturnZero659070
// IDA: int sub_659070()
//   dword_B04A48 = 0;
//   dword_B04A4C = 0;
//   dword_B04A50 = 0;
//   dword_B04A54 = 0;
//   return 0;
int ReturnZero659070()
{
  return 0;
}

// IDA: 0x659560  proposal: SetMember9659560
// IDA: void __thiscall sub_659560(_BYTE *this)
//   *(this + 9) = 0;
void SetMember9659560(void* _this) // thiscall
{
}

// IDA: 0x659570  proposal: GetMember9659570
// IDA: char __thiscall sub_659570(_BYTE *this)
//   return *(this + 9);
char GetMember9659570(void* _this) // thiscall
{
  return 0;
}

// IDA: 0x65A540  proposal: MathDispatch65A540
// IDA: void sub_65A540()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_B04AF8 = Math::Sqrt(v0 + v0);
void MathDispatch65A540()
{
}

// IDA: 0x65A590  proposal: InitFloatConst65A590
// IDA: void sub_65A590()
//   dbl_B04B30 = 1.0 / dbl_B04B48;
void InitFloatConst65A590()
{
}

// IDA: 0x65A610  proposal: MathDispatch65A610
// IDA: __int64 sub_65A610()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_B04AD8 - dbl_B04B00);
//   result = Math::RoundToInt(v0 * dbl_B04AF8 * 0.5);
//   dword_B04B50 = result;
//   return result;
int MathDispatch65A610()
{
  return 0;
}

// IDA: 0x65A650  proposal: ArcMath65A650
// IDA: void sub_65A650()
//   dbl_B04B08 = Math::ArcTan((double)dword_B04B50 * 0.00390625);
void ArcMath65A650()
{
}

// IDA: 0x65A680  proposal: ArcMath65A680
// IDA: void sub_65A680()
//   dbl_B04B20 = Math::ArcTan((double)(2 * dword_B04B50) / dbl_B04AF8);
void ArcMath65A680()
{
}

// IDA: 0x65A6B0  proposal: MathRoundToInt65A6B0
// IDA: __int64 sub_65A6B0()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_B04B50) + 0.5);
//   dword_B04B44 = result;
//   return result;
int MathRoundToInt65A6B0()
{
  return 0;
}

// IDA: 0x65A6E0  proposal: ReturnZero65A6E0
// IDA: int sub_65A6E0()
//   word_B04AF0 = 0;
//   word_B04AF2 = 0;
//   return 0;
int ReturnZero65A6E0()
{
  return 0;
}

// IDA: 0x65A6F0  proposal: ReturnZero65A6F0
// IDA: int sub_65A6F0()
//   dword_B04B10 = 0;
//   dword_B04B14 = 0;
//   dword_B04B18 = 0;
//   return 0;
int ReturnZero65A6F0()
{
  return 0;
}

// IDA: 0x65A730  proposal: ReturnZero65A730
// IDA: int sub_65A730()
//   dword_B04AE0 = 0;
//   dword_B04AE4 = 0;
//   dword_B04AE8 = 0;
//   dword_B04AEC = 0;
//   return 0;
int ReturnZero65A730()
{
  return 0;
}

// IDA: 0x65AF50  proposal: MathDispatch65AF50
// IDA: void sub_65AF50()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_B04B78 = Math::Sqrt(v0 + v0);
void MathDispatch65AF50()
{
}

// IDA: 0x65AFA0  proposal: InitFloatConst65AFA0
// IDA: void sub_65AFA0()
//   dbl_B04BB0 = 1.0 / dbl_B04BC8;
void InitFloatConst65AFA0()
{
}

// IDA: 0x65B020  proposal: MathDispatch65B020
// IDA: __int64 sub_65B020()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_B04B58 - dbl_B04B80);
//   result = Math::RoundToInt(v0 * dbl_B04B78 * 0.5);
//   dword_B04BE8 = result;
//   return result;
int MathDispatch65B020()
{
  return 0;
}

// IDA: 0x65B060  proposal: ArcMath65B060
// IDA: void sub_65B060()
//   dbl_B04B88 = Math::ArcTan((double)dword_B04BE8 * 0.00390625);
void ArcMath65B060()
{
}

// IDA: 0x65B090  proposal: ArcMath65B090
// IDA: void sub_65B090()
//   dbl_B04BA0 = Math::ArcTan((double)(2 * dword_B04BE8) / dbl_B04B78);
void ArcMath65B090()
{
}

// IDA: 0x65B0C0  proposal: MathRoundToInt65B0C0
// IDA: __int64 sub_65B0C0()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_B04BE8) + 0.5);
//   dword_B04BC4 = result;
//   return result;
int MathRoundToInt65B0C0()
{
  return 0;
}

// IDA: 0x65B0F0  proposal: ReturnZero65B0F0
// IDA: int sub_65B0F0()
//   word_B04B70 = 0;
//   word_B04B72 = 0;
//   return 0;
int ReturnZero65B0F0()
{
  return 0;
}

// IDA: 0x65B100  proposal: ReturnZero65B100
// IDA: int sub_65B100()
//   dword_B04B90 = 0;
//   dword_B04B94 = 0;
//   dword_B04B98 = 0;
//   return 0;
int ReturnZero65B100()
{
  return 0;
}

// IDA: 0x65B140  proposal: ReturnZero65B140
// IDA: int sub_65B140()
//   dword_B04B60 = 0;
//   dword_B04B64 = 0;
//   dword_B04B68 = 0;
//   dword_B04B6C = 0;
//   return 0;
int ReturnZero65B140()
{
  return 0;
}

// IDA: 0x65C890  proposal: SetMember165C890
// IDA: _DWORD *__thiscall sub_65C890(_DWORD *this, int a2, int a3)
//   *this = a2;
//   *(this + 1) = a3;
//   return this;
int* SetMember165C890(void* _this, int a0, int a1) // thiscall
{
  return 0;
}

// IDA: 0x65D6C0  proposal: MathDispatch65D6C0
// IDA: void sub_65D6C0()
//   long double v0; // st7
//   v0 = pow(256.0, 2.0);
//   dbl_B04C40 = Math::Sqrt(v0 + v0);
void MathDispatch65D6C0()
{
}

// IDA: 0x65D710  proposal: InitFloatConst65D710
// IDA: void sub_65D710()
//   dbl_B04C78 = 1.0 / dbl_B04C90;
void InitFloatConst65D710()
{
}

// IDA: 0x65D790  proposal: MathDispatch65D790
// IDA: __int64 sub_65D790()
//   double v0; // st7
//   __int64 result; // rax
//   v0 = Math::Sin(dbl_B04C20 - dbl_B04C48);
//   result = Math::RoundToInt(v0 * dbl_B04C40 * 0.5);
//   dword_B04C98 = result;
//   return result;
int MathDispatch65D790()
{
  return 0;
}

// IDA: 0x65D7D0  proposal: ArcMath65D7D0
// IDA: void sub_65D7D0()
//   dbl_B04C50 = Math::ArcTan((double)dword_B04C98 * 0.00390625);
void ArcMath65D7D0()
{
}

// IDA: 0x65D800  proposal: ArcMath65D800
// IDA: void sub_65D800()
//   dbl_B04C68 = Math::ArcTan((double)(2 * dword_B04C98) / dbl_B04C40);
void ArcMath65D800()
{
}

// IDA: 0x65D830  proposal: MathRoundToInt65D830
// IDA: __int64 sub_65D830()
//   __int64 result; // rax
//   result = Math::RoundToInt((double)(4 * dword_B04C98) + 0.5);
//   dword_B04C8C = result;
//   return result;
int MathRoundToInt65D830()
{
  return 0;
}

// IDA: 0x65D860  proposal: ReturnZero65D860
// IDA: int sub_65D860()
//   dword_B04C38 = 0;
//   return 0;
int ReturnZero65D860()
{
  return 0;
}

} // namespace gamemd
