#!/usr/bin/env python3
"""Convert include/gamemd/*.hpp → src/*.hpp with camelCase natural language naming.
Reads original headers, applies rename mapping, writes to src/ mirror structure.
"""

import os, re

BASE = r"D:\RA2YR_ReSource"
SRC = os.path.join(BASE, "include", "gamemd")
DST = os.path.join(BASE, "src")

# Rename mapping: old_name → new_name (applied as simple string replacement)
# Ordered from longest→shortest to avoid partial matches
RENAMES = [
    # ── Virtual methods (base classes) ──
    ("WhatAmI", "whatAmI"),
    ("FetchID", "fetchId"),
    ("CreateID", "createId"),
    ("OnNotice", "onNotice"),
    ("NotifySinks", "notifySinks"),
    ("PointerExpired(", "pointerExpired("),
    (" Size() const override", " objectSize() const override"),
    (" Size() override", " objectSize() override"),
    (" Size() const {", " objectSize() const {"),
    ("CalculateChecksum(", "calculateChecksum("),
    ("GetOwningHouseIndex(", "owningHouseIndex("),
    ("GetOwningHouse(", "owningHouse("),
    ("GetArrayIndex(", "arrayIndex("),
    ("IsDead(", "isDead("),
    ("IsOnFloor(", "isOnGround("),
    ("IsInAir(", "isAirborne("),
    ("IsAlive(", "isAlive("),
    ("GetAltCoords(", "fetchAlternateCoordinates("),
    ("GetDestination(", "fetchDestination("),
    ("GetCoordsEx(", "fetchExtendedCoordinates("),
    ("GetCoords(", "fetchCoordinatesHere("),
    ("GetCoords()", "getCoordinates()"),
    ("ProcessPower(", "processPowerDrain("),
    ("Update()", "updateLogic()"),
    ("Initialize()", "initialize()"),
    ("kAbsID", "kObjectTypeId"),
    
    # ── Member renames (m_ prefix removal) ──
    ("m_unique_id", "uniqueId"),
    ("m_abstract_flags", "abstractFlags"),
    ("m_ref_count", "referenceCount"),
    ("m_dirty", "needsSave"),
    ("m_unknown_18", "nextArrayIndex"),
    ("m_padding_21", "alignmentPadding"),
    
    # ObjectClass members
    ("m_unknown_24", "objectTypeFlags"),
    ("m_unknown_28", "owningHouseIndex"),
    ("m_unknown_78", "spawnStatus"),
    ("m_unknown_7C", "visibilityFlags"),
    ("m_align_69", "alignmentPadding69"),
    ("m_align_75", "alignmentPadding75"),
    ("m_align_85", "alignmentPadding85"),
    ("m_align_91", "alignmentPadding91"),
    ("m_align_99", "alignmentPadding99"),
    ("m_needs_redraw", "needsRedraw"),
    ("m_in_limbo", "inLimbo"),
    ("m_is_selected", "isSelected"),
    ("m_has_parachute", "hasParachute"),
    ("m_location", "location"),
    ("m_is_alive", "isAliveFlag"),
    ("m_is_on_map", "isOnMap"),
    ("m_is_a_bomb", "isBomb"),
    ("m_is_falling_down", "isFallingDown"),
    ("m_was_falling_down", "wasFallingDown"),
    ("m_is_in_logic", "isInLogic"),
    ("m_is_visible", "isVisible"),
    ("m_last_layer", "lastLayer"),
    ("m_next_object", "nextObject"),
    ("m_attached_tag", "attachedTag"),
    ("m_attached_bomb", "attachedBomb"),
    ("m_fall_rate", "fallRate"),
    ("m_bomb_visible", "bombVisible"),
    ("m_health", "health"),
    ("m_estimated_health", "estimatedHealth"),
    ("m_custom_sound", "customSound"),
    ("m_line_trailer", "lineTrailer"),
    ("m_parachute", "parachute"),
    ("m_on_bridge", "onBridge"),
    ("m_in_open_topped_transport", "inOpenToppedTransport"),
    ("m_ambient_sound_controller", "ambientSoundController"),
    ("m_custom_sound_controller", "customSoundController"),
    ("kAbsDeriveID", "kObjectDeriveId"),
    
    # MissionClass
    ("m_current_mission", "currentMission"),
    ("m_suspended_mission", "suspendedMission"),
    ("m_queued_mission", "queuedMission"),
    ("m_mission_queued", "missionQueued"),
    ("m_mission_status", "missionStatus"),
    ("m_mission_start_time", "missionStartTime"),
    ("m_mission_data", "missionData"),
    ("m_mission_timer", "missionTimer"),
    ("m_padding_B9", "alignmentPaddingB9"),
    ("QueueMission(", "queueMission("),
    ("NextMission(", "nextMission("),
    ("ForceMission(", "forceMission("),
    ("Mission_Revert(", "revertMission("),
    
    # RadioClass
    ("m_last_commands", "lastCommands"),
    ("m_radio_links", "radioLinks"),
    ("SendToFirstLink(", "sendToFirstLink("),
    ("SendCommand(", "sendCommand("),
    ("SendCommandWithData(", "sendCommandWithData("),
    ("SendToEachLink(", "sendToEachLink("),
    ("GetNthLink(", "getNthLink("),
    ("HasFreeLink(", "hasFreeLink("),
    ("HasAnyLink(", "hasAnyLink("),
    
    # vt_entry → named (from IDA analysis)
    ("vt_entry_1F4", "onMissionChanged"),
    ("vt_entry_1FC", "isMissionDone"),
    ("vt_entry_200", "hasValidTarget"),
    ("vt_entry_140", "spawnInfantry"),
    ("vt_entry_128", "getBoundsRect"),
    ("vt_entry_12C", "getBoundsRectMut"),
    ("vt_entry_1A8", "onDeployComplete"),
    ("vt_entry_1B0", "canDeployHere"),
    # TechnoClass vt_entry (50+ from IDA)
    ("vt_entry_29C", "canSelfRepair"),
    ("vt_entry_2B0", "onSpawnComplete"),
    ("vt_entry_2C4", "canBeAttacked"),
    ("vt_entry_2C8", "getSpecialValue"),
    ("vt_entry_2CC", "canCrush"),
    ("vt_entry_2FC", "getOccupiedCell"),
    ("vt_entry_300", "getTurretCoords"),
    ("vt_entry_304", "getWeaponRangeValue"),
    ("vt_entry_310", "isInAirAlt"),
    ("vt_entry_320", "canEnterTransport"),
    ("vt_entry_3A0", "getDamageReduction"),
    ("vt_entry_3B4", "getSightRange"),
    ("vt_entry_3D8", "onHouseChange"),
    ("vt_entry_3E8", "canAct"),
    ("vt_entry_41C", "onBridgeRepair"),
    ("vt_entry_428", "onReloadComplete"),
    ("vt_entry_434", "canChronoShift"),
    ("vt_entry_444", "drawSelectionBox"),
    ("vt_entry_448", "onSelect"),
    ("vt_entry_464", "getSight"),
    ("vt_entry_47C", "onDamage"),
    ("vt_entry_484", "canRecruit"),
    ("vt_entry_48C", "onPlacement"),
    ("vt_entry_4A4", "onRadarEvent"),
    ("vt_entry_4A8", "onSpawn"),
    ("vt_entry_4AC", "canSpawn"),
    ("vt_entry_4B0", "isSpawning"),
    ("vt_entry_4B4", "getSpawnCount"),
    ("vt_entry_4B8", "getSpawnCoords"),
    ("vt_entry_4BC", "processSpawn"),
    ("vt_entry_4C4", "canTarget"),
    ("vt_entry_4C8", "selectTarget"),
    ("vt_entry_4CC", "onTargetChange"),
    ("vt_entry_4D0", "canFire"),
    # FootClass vt_entry
    ("vt_entry_4E0", "canMove"),
    ("vt_entry_4E8", "onCellEntry"),
    ("vt_entry_4F0", "getMoveCoords"),
    ("vt_entry_4F4", "onMoveStart"),
    ("vt_entry_4F8", "canStop"),
    ("vt_entry_514", "onDrawComplete"),
    ("vt_entry_524", "getMovementMode"),
    ("vt_entry_528", "getPathDistance"),
    ("vt_entry_52C", "getPathCost"),
    ("vt_entry_530", "isAreaClear"),
    ("vt_entry_534", "onAreaEntry"),
    ("vt_entry_53C", "getWaypointData"),
    ("vt_entry_540", "onWaypointReached"),
    ("vt_entry_548", "onPathComplete"),
    ("vt_entry_54C", "onMovementDone"),
    ("vt_entry_550", "canEnterCell"),
    # BuildingClass vt_entry
    ("vt_entry_490", "onBuildingPlacement"),
    ("vt_entry_4D4", "getFoundationCell"),
    ("vt_entry_4D8", "canPlaceHere"),
    ("vt_entry_4E4", "onProductionComplete"),
    ("vt_entry_4EC", "processSuperWeapon"),
    ("vt_entry_504", "canRecruitTeamMember"),
    
    # ── Remaining PascalCase methods ──
    ("IsUnitFactory(", "isUnitfactory("),
    ("IsCloakable(", "isCloakable("),
    ("CanScatter(", "canScatter("),
    ("BelongsToATeam(", "belongsToATeam("),
    ("ShouldSelfHealOneStep(", "shouldSelfHealOneStep("),
    ("IsVoxel(", "isVoxel("),
    ("ShouldBeCloaked(", "shouldBeCloaked("),
    ("ShouldNotBeCloaked(", "shouldNotBeCloaked("),
    ("GetFacing(", "getFacing("),
    ("IsArmed(", "isArmed("),
    ("GetStoragePercentage(", "getStoragePercentage("),
    ("GetPipFillLevel(", "getPipFillLevel("),
    ("GetRefund(", "getRefund("),
    ("GetThreatValue(", "getThreatValue("),
    ("GetCrewCount(", "getCrewCount("),
    ("GetAntiAirValue(", "getAntiAirValue("),
    ("GetAntiArmorValue(", "getAntiArmorValue("),
    ("GetAntiInfantryValue(", "getAntiInfantryValue("),
    ("GotHijacked(", "gotHijacked("),
    ("SelectNavalTargeting(", "selectNavalTargeting("),
    ("GetZAdjustment(", "getZAdjustment("),
    ("IsPowerOnline(", "isPowerOnline("),
    ("IsUnderEMP(", "isUnderEmp("),
    ("IsParalyzed(", "isParalyzed("),
    ("CanCheer(", "canCheer("),
    ("CanAttackOnTheMove(", "canAttackOnTheMove("),
    ("IsClearlyVisibleTo(", "isClearlyVisibleTo("),
    ("GetOccupyRangeBonus(", "getOccupyRangeBonus("),
    ("GetOccupantCount(", "getOccupantCount("),
    ("IsAreaFire(", "isAreaFire("),
    ("IsNotSprayAttack(", "isNotSprayAttack("),
    ("IsNotSprayAttack2(", "isNotSprayAttack2("),
    ("HasTurret(", "hasTurret("),
    ("CanBeOccupied(", "canBeOccupied("),
    ("CanOccupyFire(", "canOccupyFire("),
    
    # ── TechnoClass m_ prefix removal (all ~150 members) ──
    ("m_flashing", "flashing"), ("m_animation", "animation"),
    ("m_passengers", "passengers"), ("m_transporter", "transporter"),
    ("m_unknown_int_120", "turretChargeTimer"),
    ("m_current_turret_number", "currentTurretNumber"),
    ("m_unknown_int_128", "secondaryTurretIndex"),
    ("m_behind_anim", "behindAnim"), ("m_deploy_anim", "deployAnim"),
    ("m_in_air", "inAirFlag"), ("m_padding_139", "alignmentPadding139"),
    ("m_current_weapon_number", "currentWeaponSlot"),
    ("m_current_ranking", "currentRank"),
    ("m_current_gattling_stage", "gattlingStage"),
    ("m_gattling_value", "gattlingValue"),
    ("m_unknown_148", "ammoReloadTimer"),
    ("m_initial_owner", "initialOwner"),
    ("m_veterancy", "veterancy"), ("m_align_154", "alignmentPadding154"),
    ("m_armor_multiplier", "armorMultiplier"),
    ("m_firepower_multiplier", "firepowerMultiplier"),
    ("m_idle_action_timer", "idleActionTimer"),
    ("m_radar_flash_timer", "radarFlashTimer"),
    ("m_targeting_timer", "targetingTimer"),
    ("m_iron_curtain_timer", "ironCurtainTimer"),
    ("m_iron_tint_timer", "ironTintTimer"),
    ("m_iron_tint_stage", "ironTintStage"),
    ("m_airstrike_timer", "airstrikeTimer"),
    ("m_airstrike_tint_timer", "airstrikeTintTimer"),
    ("m_airstrike_tint_stage", "airstrikeTintStage"),
    ("m_force_shielded", "forceShielded"),
    ("m_deactivated", "isDeactivated"),
    ("m_padding_1BD", "alignmentPadding1BD"),
    ("m_drain_target", "drainTarget"),
    ("m_draining_me", "drainingMe"), ("m_drain_anim", "drainAnim"),
    ("m_disguised", "isDisguisedFlag"),
    ("m_padding_1CE", "alignmentPadding1CE"),
    ("m_disguise_creation_frame", "disguiseCreationFrame"),
    ("m_infantry_blink_timer", "infantryBlinkTimer"),
    ("m_disguise_blink_timer", "disguiseBlinkTimer"),
    ("m_unknown_bool_1F8", "isTargetedByChrono"),
    ("m_padding_1F9", "alignmentPadding1F9"),
    ("m_reload_timer", "reloadTimer"),
    ("m_unknown_208", "currentBurstCount"),
    ("m_unknown_20C", "currentBarrelIndex"),
    ("m_display_production_to", "displayProductionTo"),
    ("m_group", "group"), ("m_focus", "focus"), ("m_owner", "owner"),
    ("m_cloak_state", "cloakState"), ("m_cloak_progress", "cloakProgress"),
    ("m_cloak_delay_timer", "cloakDelayTimer"),
    ("m_warp_factor", "warpFactor"),
    ("m_unknown_bool_250", "isChronosphereImmune"),
    ("m_padding_251", "alignmentPadding251"),
    ("m_last_sight_coords", "lastSightCoords"),
    ("m_last_sight_range", "lastSightRange"),
    ("m_last_sight_height", "lastSightHeight"),
    ("m_gap_super_charged", "gapSuperCharged"),
    ("m_generating_gap", "isGeneratingGap"),
    ("m_padding_27E", "alignmentPadding27E"),
    ("m_gap_radius", "gapRadius"),
    ("m_being_warped_out", "isBeingWarpedOut"),
    ("m_warping_out", "isWarpingOut"),
    ("m_unknown_bool_272", "isWarpEffectActive"),
    ("m_unused_273", "unusedField273"),
    ("m_temporal_im_using", "temporalUsing"),
    ("m_temporal_targeting_me", "temporalTargetingMe"),
    ("m_is_immobilized", "isImmobilized"),
    ("m_padding_27D", "alignmentPadding27D"),
    ("m_chrono_lock_remaining", "chronoLockRemaining"),
    ("m_chrono_dest_coords", "chronoDestCoords"),
    ("m_airstrike", "airstrike"),
    ("m_berzerk", "isBerserk"),
    ("m_padding_29D", "alignmentPadding29D"),
    ("m_berzerk_duration_left", "berserkRemaining"),
    ("m_spray_offset_index", "sprayOffsetIndex"),
    ("m_uncrushable", "isUncrushable"),
    ("m_padding_2A9", "alignmentPadding2A9"),
    ("m_direct_rocker_linked_unit", "rockerLinkedUnit"),
    ("m_locomotor_target", "locomotorTarget"),
    ("m_locomotor_source", "locomotorSource"),
    ("m_target", "target"), ("m_last_target", "lastTarget"),
    ("m_capture_manager", "captureManager"),
    ("m_mind_controlled_by", "mindControlledBy"),
    ("m_mind_controlled_by_a_unit", "mindControlledByUnit"),
    ("m_padding_2C2", "alignmentPadding2C2"),
    ("m_mind_control_ring_anim", "mindControlRingAnim"),
    ("m_mind_controlled_by_house", "mindControlledByHouse"),
    ("m_spawn_manager", "spawnManager"),
    ("m_spawn_owner", "spawnOwner"),
    ("m_slave_manager", "slaveManager"),
    ("m_slave_owner", "slaveOwner"),
    ("m_originally_owned_by_house", "originalOwnerHouse"),
    ("m_bunker_linked_item", "bunkerLinkedUnit"),
    ("m_pitch_angle", "pitchAngle"),
    ("m_disk_laser_timer", "diskLaserTimer"),
    ("m_unknown_2F8", "diskLaserChargeState"),
    ("m_ammo", "ammo"), ("m_value", "unitValue"),
    ("m_fire_particle_system", "fireParticles"),
    ("m_spark_particle_system", "sparkParticles"),
    ("m_natural_particle_system", "ambientParticles"),
    ("m_damage_particle_system", "damageParticles"),
    ("m_railgun_particle_system", "railgunParticles"),
    ("m_unk1_particle_system", "auxParticles1"),
    ("m_unk2_particle_system", "auxParticles2"),
    ("m_firing_particle_system", "firingParticles"),
    ("m_wave", "waveEffect"),
    ("m_angle_rotated_sideways", "tiltSidewaysAngle"),
    ("m_angle_rotated_forwards", "tiltForwardsAngle"),
    ("m_rocking_sideways_per_frame", "tiltSidewaysRate"),
    ("m_rocking_forwards_per_frame", "tiltForwardsRate"),
    ("m_hijacker_infantry_type", "hijackerInfantryType"),
    ("m_tiberium", "storedTiberium"),
    ("m_unknown_34C", "tiberiumCollectionState"),
    ("m_unload_timer", "unloadTimer"),
    ("m_barrel_facing", "barrelFacing"), ("m_facing", "facing"),
    ("m_turret_facing", "turretFacing"),
    ("m_current_burst_index", "currentBurstIndex"),
    ("m_target_laser_timer", "targetLaserTimer"),
    ("m_unknown_short_3C8", "targetLaserOpacity"),
    ("m_unknown_3CA", "targetLaserFlags"),
    ("m_counted_as_owned", "isCountedAsOwned"),
    ("m_is_sinking", "isSinking"),
    ("m_was_sinking_already", "wasAlreadySinking"),
    ("m_unknown_bool_3CF", "isReceivingDamageEffect"),
    ("m_unknown_bool_3D0", "isPlayingDamageSound"),
    ("m_has_been_attacked", "hasBeenAttacked"),
    ("m_cloakable", "isCloakableFlag"),
    ("m_is_primary_factory", "isPrimaryFactory"),
    ("m_spawned", "isSpawned"),
    ("m_is_in_playfield", "isInPlayfield"),
    ("m_turret_recoil", "turretRecoil"),
    ("m_barrel_recoil", "barrelRecoil"),
    ("m_unknown_bool_418", "isTurretLocked"),
    ("m_unknown_bool_419", "isBarrelLocked"),
    ("m_is_human_controlled", "isHumanControlled"),
    ("m_discovered_by_player", "isDiscoveredByPlayer"),
    ("m_discovered_by_computer", "isDiscoveredByComputer"),
    ("m_unknown_bool_41D", "isSelectedByPlayer"),
    ("m_unknown_bool_41E", "isUnderCursor"),
    ("m_unknown_bool_41F", "isCommandLineTarget"),
    ("m_sight_increase", "sightRangeBonus"),
    ("m_recruitable_a", "isRecruitableByAlly"),
    ("m_recruitable_b", "isRecruitableByEnemy"),
    ("m_is_radar_tracked", "isRadarTracked"),
    ("m_is_on_carryall", "isOnCarryall"),
    ("m_is_crashing", "isCrashing"),
    ("m_was_crashing_already", "wasAlreadyCrashing"),
    ("m_is_being_manipulated", "isBeingManipulated"),
    ("m_being_manipulated_by", "manipulatedByUnit"),
    ("m_chrono_warped_by_house", "chronoWarpedByHouse"),
    ("m_unknown_bool_430", "isChronoImmuneFlag"),
    ("m_unknown_bool_431", "isEMPImmune"),
    ("m_unknown_bool_432", "isRadiationImmune"),
    ("m_padding_433", "alignmentPadding433"),
    ("m_old_team", "previousTeam"),
    ("m_counted_as_owned_special", "isCountedAsOwnedSpecial"),
    ("m_absorbed", "isAbsorbed"),
    ("m_unknown_bool_43A", "isGrindingInProgress"),
    ("m_padding_43B", "alignmentPadding43B"),
    ("m_unknown_43C", "grindingAnimHandle"),
    ("m_current_target_threat_values", "currentTargetThreatValues"),
    ("m_current_targets", "currentTargets"),
    ("m_attacked_targets", "attackedTargets"),
    ("m_audio3", "audioController3"),
    ("m_unknown_49C", "audioLoopIndex3"),
    ("m_unknown_4A0", "audioVolume3"),
    ("m_audio4", "audioController4"),
    ("m_unknown_bool_4B8", "isAudio4Active"),
    ("m_padding_4B9", "alignmentPadding4B9"),
    ("m_unknown_4BC", "audioHandle4"),
    ("m_audio5", "audioController5"),
    ("m_unknown_bool_4D4", "isAudio5Active"),
    ("m_padding_4D5", "alignmentPadding4D5"),
    ("m_unknown_4D8", "audioHandle5"),
    ("m_audio6", "audioController6"),
    ("m_queued_voice_index", "queuedVoiceIndex"),
    ("m_unknown_4F4", "voiceFlags"),
    ("m_unknown_bool_4F8", "isVoiceOverride"),
    ("m_padding_4F9", "alignmentPadding4F9"),
    ("m_unknown_4FC", "voiceHandle"),
    ("m_unknown_500", "voiceVolumeModifier"),
    ("m_emp_lock_remaining", "empLockRemaining"),
    ("m_threat_posed", "threatPosed"),
    ("m_should_lose_target_now", "shouldLoseTarget"),
    ("m_firing_rad_beam", "firingRadBeam"),
    ("m_planning_token", "planningToken"),
    ("m_disguise", "disguiseAsType"),
    ("m_disguised_as_house", "disguisedAsHouse"),
    
    # ── FootClass m_ prefix removal ──
    ("m_destination", "movementDestination"),
    ("m_speed", "currentSpeed"),
    ("m_form_speed", "formationSpeed"),
    ("m_speed_multiplier", "speedMultiplier"),
    ("m_is_driving", "isDriving"),
    ("m_unknown_bool_6C4", "isMovingFlag"),
    ("m_path_index", "pathIndex"),
    ("m_path_update_timer", "pathUpdateTimer"),
    ("m_pathfinding_retry_count", "pathRetryCount"),
    ("m_nav_list", "navigationList"),
    ("m_locomotor", "locomotor"),
    ("m_prev_loc", "previousLocation"),
    ("m_head_to_coord", "headingToCoord"),
    ("m_movement_destination", "movementTarget"),
    ("m_unk_coord_730", "lastValidPosition"),
    ("m_draw_matrix", "drawMatrix"),
    ("m_turret_angle", "turretAngle"),
    ("m_barrel_angle", "barrelAngle"),
    ("m_unknown_angle_788", "bodyRotationAngle"),
    ("m_deploying_timer", "deployingTimer"),
    ("m_undeploying_timer", "undeployingTimer"),
    ("m_is_undeploying", "isUndeploying"),
    ("m_unknown_7BC", "deploymentState"),
    ("m_scripted_move_coord", "scriptedMoveCoord"),
    ("m_occupied_cells", "occupiedCells"),
    ("m_occupied_cell_count", "occupiedCellCount"),
    ("m_unknown_7D4", "occupiedCellCapacity"),
    
    # ── BuildingClass m_ prefix removal ──
    ("m_type", "buildingType"),
    ("m_factory", "productionFactory"),
    ("m_c4_timer", "c4Timer"),
    ("m_owner_country_index", "ownerCountryIndex"),
    ("m_c4_applied_by", "c4AppliedBy"),
    ("m_firestorm_anim", "firestormAnim"),
    ("m_psi_warn_anim", "psiWarnAnim"),
    ("m_anims", "animationSlots"),
    ("m_anim_states", "animationStates"),
    ("m_damage_fire_anims", "damageFireAnimations"),
    ("m_upgrades", "upgradeSlots"),
    ("m_firing_sw_type", "firingSuperWeaponType"),
    ("m_spotlight", "spotlightEffect"),
    ("m_gate_timer", "gateTimer"),
    ("m_light_source", "lightSourceEffect"),
    ("m_laser_fence_frame", "laserFenceFrame"),
    ("m_firestorm_wall_frame", "firestormWallFrame"),
    ("m_repair_progress", "repairProgress"),
    ("m_has_power", "hasPower"),
    ("m_is_overpowered", "isOverpowered"),
    ("m_registered_as_powered_source", "isRegisteredAsPowerSource"),
    ("m_supporting_prisms", "supportingPrisms"),
    ("m_has_extra_power_bonus", "hasExtraPowerBonus"),
    ("m_has_extra_power_drain", "hasExtraPowerDrain"),
    ("m_overpowerers", "overpoweringInfantry"),
    ("m_occupants", "occupyingInfantry"),
    ("m_firing_occupant_index", "firingOccupantIndex"),
    ("m_audio7", "audioController7"),
    ("m_audio8", "audioController8"),
    ("m_was_online", "wasOnline"),
    ("m_show_real_name", "showRealName"),
    ("m_being_produced", "isBeingProduced"),
    ("m_should_rebuild", "shouldRebuild"),
    ("m_has_engineer", "hasEngineer"),
    ("m_cash_production_timer", "cashProductionTimer"),
    ("m_needs_repairs", "needsRepairs"),
    ("m_c4_applied", "isC4Applied"),
    ("m_no_crew", "hasNoCrew"),
    ("m_has_been_captured", "hasBeenCaptured"),
    ("m_actually_placed_on_map", "isActuallyPlaced"),
    ("m_is_damaged", "isDamaged"),
    ("m_is_fogged", "isFogged"),
    ("m_is_being_repaired", "isBeingRepaired"),
    ("m_stuff_enabled", "isPrimaryEnabled"),
    ("m_has_cloaking_data", "hasCloakingData"),
    ("m_cloak_radius", "cloakRadius"),
    ("m_translucency", "translucency"),
    ("m_storage_filled_slots", "storageFilledSlots"),
    ("m_secret_production", "secretProductionType"),
    ("m_color_add", "colorTint"),
    ("m_upgrade_level", "upgradeLevel"),
    ("m_gate_stage", "gateStage"),
    ("m_prism_stage", "prismChargeState"),
    ("m_prism_target_coords", "prismTargetCoords"),
    ("m_delay_before_firing", "delayBeforeFiring"),
    ("m_bunker_state", "bunkerState"),
    ("m_production_timer", "productionTimer"),
    ("m_placement_allowed", "isPlacementAllowed"),
    ("m_production_blocked", "isProductionBlocked"),
    ("m_production_accum", "productionAccumulator"),
    ("m_production_frame", "productionFrame"),
    ("m_production_rate", "productionRate"),
    ("m_production_speed", "productionSpeed"),
    ("m_cost_accumulator", "costAccumulator"),
    ("m_pipeline_step", "pipelineStep"),
    
    # ── Remaining vt_entry items ──
    ("vt_entry_A0", "onTypeLoaded"),
    ("vt_entry_6C", "onCellChanged"),
    ("vt_entry_1E8", "onParticleExpired"),
    ("vt_entry_CC", "worldToScreenCoords"),
    ("vt_entry_D0", "onRadarClick"),
    ("vt_entry_78", "onTypeLoadComplete"),
    ("vt_entry_7C", "onTypeUnload"),
    
    # ── More Type class member renames ──
    ("m_array_index", "arrayIndex"),
    ("m_unknown_1538", "productionQueueSize"),
    ("m_unknown_153C", "productionBatchSize"),
    ("m_unknown_1540", "productionStepDelay"),
    ("m_unknown_1544", "productionCompletionThreshold"),
]

def convert_file(src_path, dst_path):
    """Read src_path, apply renames, write to dst_path."""
    with open(src_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    # Phase 1: Explicit rename mappings (longest→shortest for safety)
    for old, new in RENAMES:
        content = content.replace(old, new)
    
    # Phase 2: Generic m_ prefix removal for remaining members
    # Matches m_xxx patterns in member declarations and accesses
    # But NOT in comments, strings, or include guards
    import re
    # Remove m_ prefix from identifiers: m_some_name → someName (camelCase)
    def m_to_camel(match):
        full = match.group(0)
        prefix = match.group(1) or ''  # whitespace/operators before
        name = match.group(2)  # the m_xxx name
        # Convert snake_case to camelCase
        parts = name.split('_')
        camel = parts[0] + ''.join(p.capitalize() for p in parts[1:])
        return prefix + camel
    
    # Only process lines that look like member declarations or accesses
    # Pattern: whitespace/operator + m_ + snake_case_name
    content = re.sub(r'([\s>\*&,\(\)\[\]\.\-\+!])m_([a-z][a-z0-9_]*(?:_[a-z0-9]+)*)\b', m_to_camel, content)
    
    if content != original:
        os.makedirs(os.path.dirname(dst_path), exist_ok=True)
        with open(dst_path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(content)
        return True
    return False

def main():
    # Files to convert (include/gamemd/ → src/)
    files = [
        "object/abstract.hpp", "object/object.hpp",
        "object/mission.hpp", "object/radio.hpp",
        "object/techno.hpp", "object/foot.hpp",
        "structure/building.hpp", "structure/unit.hpp",
        "structure/infantry.hpp", "structure/aircraft.hpp",
        "type/techno_type.hpp", "type/building_type.hpp",
        "type/unit_type.hpp", "type/infantry_type.hpp",
        "type/aircraft_type.hpp", "type/object_type.hpp",
        "type/abstract_type.hpp",
        "type/anim_type.hpp", "type/bullet_type.hpp",
        "type/warhead_type.hpp", "type/weapon_type.hpp",
        "type/overlay_type.hpp", "type/smudge_type.hpp",
        "type/terrain_type.hpp",
        "type/particle_type.hpp", "type/particle_system_type.hpp",
        "entity/anim.hpp", "entity/bullet.hpp",
        "entity/overlay.hpp", "entity/particle.hpp",
        "entity/particle_system.hpp", "entity/smudge.hpp",
        "entity/terrain.hpp", "entity/tiberium.hpp",
        "entity/tube.hpp", "entity/wave.hpp",
        "entity/voxel_anim.hpp",
        "house/house.hpp", "house/house_type.hpp", "house/side.hpp",
        "misc/super_weapon.hpp", "misc/audio.hpp",
        "misc/rules.hpp",
        "render/surface.hpp", "render/display.hpp",
        "render/bink_control.hpp", "render/bounce.hpp",
        "render/fog.hpp", "render/light_source.hpp",
        "render/palette.hpp", "render/movie.hpp",
        "system/cell.hpp", "system/map.hpp",
        "system/scenario.hpp", "system/tactical.hpp",
        "system/factory.hpp", "system/cc_file.hpp",
        "system/mix_file.hpp", "system/ini_class.hpp",
        "system/radar.hpp",
        "ui/sidebar.hpp", "ui/mouse.hpp",
        "ui/gadget.hpp", "ui/menu_screen.hpp",
        "ui/message_list.hpp", "ui/tool_tip.hpp",
        "ui/g_screen.hpp", "ui/command_class.hpp",
        "team/campaign.hpp", "team/script.hpp",
        "team/tag.hpp", "team/team.hpp", "team/trigger.hpp",
        "network/connection.hpp", "network/multiplayer.hpp",
        "network/session.hpp", "network/winsock.hpp",
        "wdt/wdt.hpp",
    ]
    
    converted = 0
    for f in files:
        src = os.path.join(SRC, f)
        dst = os.path.join(DST, f)
        if os.path.exists(src):
            if convert_file(src, dst):
                print(f"  OK {f}")
                converted += 1
            else:
                print(f"  - {f} (no changes)")
        else:
            print(f"  MISSING {f}")
    
    print(f"\nConverted {converted}/{len(files)} files")

if __name__ == "__main__":
    main()
