"""Definitive member rename pass — applies ALL m_ prefix removals and
PascalCase->camelCase member renames to ALL .hpp/.cpp files."""
import os

RENAMES = [
    # m_ prefix removal (most common)
    ("m_unique_id", "uniqueId"), ("m_abstract_flags", "abstractFlags"),
    ("m_ref_count", "refCount"), ("m_dirty", "isDirty"),
    ("m_unknown_18", "arrayIndexCache"), ("m_padding_21", "padding21"),
    ("m_unknown_24", "unknown24"), ("m_unknown_28", "unknown28"),
    ("m_unknown_78", "unknown78"), ("m_unknown_7C", "unknown7C"),
    ("m_fall_rate", "fallRate"), ("m_next_object", "nextObject"),
    ("m_attached_tag", "attachedTag"), ("m_attached_bomb", "attachedBomb"),
    ("m_ambient_sound_controller", "ambientSoundController"),
    ("m_custom_sound_controller", "customSoundController"),
    ("m_custom_sound", "customSound"), ("m_bomb_visible", "bombVisible"),
    ("m_align_69", "align69"), ("m_align_75", "align75"),
    ("m_health", "health"), ("m_estimated_health", "estimatedHealth"),
    ("m_is_on_map", "isOnMap"), ("m_needs_redraw", "needsRedraw"),
    ("m_in_limbo", "inLimbo"), ("m_in_open_topped_transport", "inOpenToppedTransport"),
    ("m_is_selected", "isSelected"), ("m_has_parachute", "hasParachute"),
    ("m_align_85", "align85"), ("m_parachute", "parachute"),
    ("m_on_bridge", "onBridge"), ("m_is_falling_down", "isFallingDown"),
    ("m_was_falling_down", "wasFallingDown"), ("m_is_a_bomb", "isBomb"),
    ("m_is_alive", "isAliveFlag"), ("m_align_91", "align91"),
    ("m_last_layer", "lastLayer"), ("m_is_in_logic", "isInLogic"),
    ("m_is_visible", "isVisible"), ("m_align_99", "align99"),
    ("m_location", "location"), ("m_line_trailer", "lineTrailer"),
    # TechnoClass members
    ("m_flashing", "flashing"), ("m_animation", "animation"),
    ("m_passengers", "passengers"), ("m_transporter", "transporter"),
    ("m_unknown_int_120", "unknownInt120"), ("m_current_turret_number", "currentTurretNumber"),
    ("m_unknown_int_128", "unknownInt128"), ("m_behind_anim", "behindAnim"),
    ("m_deploy_anim", "deployAnim"), ("m_in_air", "inAir"),
    ("m_padding_139", "padding139"), ("m_current_weapon_number", "currentWeaponNumber"),
    ("m_current_ranking", "currentRanking"), ("m_current_gattling_stage", "currentGattlingStage"),
    ("m_gattling_value", "gattlingValue"), ("m_unknown_148", "unknown148"),
    ("m_initial_owner", "initialOwner"), ("m_veterancy", "veterancy"),
    ("m_align_154", "align154"), ("m_armor_multiplier", "armorMultiplier"),
    ("m_firepower_multiplier", "firepowerMultiplier"),
    ("m_idle_action_timer", "idleActionTimer"), ("m_radar_flash_timer", "radarFlashTimer"),
    ("m_targeting_timer", "targetingTimer"), ("m_iron_curtain_timer", "ironCurtainTimer"),
    ("m_iron_tint_timer", "ironTintTimer"), ("m_iron_tint_stage", "ironTintStage"),
    ("m_airstrike_timer", "airstrikeTimer"), ("m_airstrike_tint_timer", "airstrikeTintTimer"),
    ("m_airstrike_tint_stage", "airstrikeTintStage"),
    ("m_force_shielded", "forceShielded"), ("m_deactivated", "deactivated"),
    ("m_padding_1BD", "padding1BD"), ("m_drain_target", "drainTarget"),
    ("m_draining_me", "drainingMe"), ("m_drain_anim", "drainAnim"),
    ("m_disguised", "disguised"), ("m_padding_1CE", "padding1CE"),
    ("m_disguise_creation_frame", "disguiseCreationFrame"),
    ("m_infantry_blink_timer", "infantryBlinkTimer"),
    ("m_disguise_blink_timer", "disguiseBlinkTimer"),
    ("m_unknown_bool_1F8", "unknownBool1F8"), ("m_padding_1F9", "padding1F9"),
    ("m_reload_timer", "reloadTimer"), ("m_unknown_208", "unknown208"),
    ("m_unknown_20C", "unknown20C"), ("m_display_production_to", "displayProductionTo"),
    ("m_group", "group"), ("m_focus", "focus"), ("m_owner", "owner"),
    ("m_cloak_state", "cloakState"), ("m_cloak_progress", "cloakProgress"),
    ("m_cloak_delay_timer", "cloakDelayTimer"), ("m_warp_factor", "warpFactor"),
    ("m_unknown_bool_250", "unknownBool250"), ("m_padding_251", "padding251"),
    ("m_last_sight_coords", "lastSightCoords"), ("m_last_sight_range", "lastSightRange"),
    ("m_last_sight_height", "lastSightHeight"), ("m_gap_super_charged", "gapSuperCharged"),
    ("m_generating_gap", "generatingGap"), ("m_padding_27E", "padding27E"),
    ("m_gap_radius", "gapRadius"), ("m_being_warped_out", "beingWarpedOut"),
    ("m_warping_out", "warpingOut"), ("m_unknown_bool_272", "unknownBool272"),
    ("m_unused_273", "unused273"), ("m_temporal_im_using", "temporalImUsing"),
    ("m_temporal_targeting_me", "temporalTargetingMe"),
    ("m_is_immobilized", "isImmobilized"), ("m_padding_27D", "padding27D"),
    ("m_chrono_lock_remaining", "chronoLockRemaining"),
    ("m_chrono_dest_coords", "chronoDestCoords"), ("m_airstrike", "airstrike"),
    ("m_berzerk", "berzerk"), ("m_padding_29D", "padding29D"),
    ("m_berzerk_duration_left", "berzerkDurationLeft"),
    ("m_spray_offset_index", "sprayOffsetIndex"), ("m_uncrushable", "uncrushable"),
    ("m_padding_2A9", "padding2A9"),
    ("m_direct_rocker_linked_unit", "directRockerLinkedUnit"),
    ("m_locomotor_target", "locomotorTarget"), ("m_locomotor_source", "locomotorSource"),
    ("m_target", "target"), ("m_last_target", "lastTarget"),
    ("m_capture_manager", "captureManager"),
    ("m_mind_controlled_by", "mindControlledBy"),
    ("m_mind_controlled_by_a_unit", "mindControlledByAUnit"),
    ("m_padding_2C2", "padding2C2"),
    ("m_mind_control_ring_anim", "mindControlRingAnim"),
    ("m_mind_controlled_by_house", "mindControlledByHouse"),
    ("m_spawn_manager", "spawnManager"), ("m_spawn_owner", "spawnOwner"),
    ("m_slave_manager", "slaveManager"), ("m_slave_owner", "slaveOwner"),
    ("m_originally_owned_by_house", "originallyOwnedByHouse"),
    ("m_bunker_linked_item", "bunkerLinkedItem"),
    ("m_pitch_angle", "pitchAngle"), ("m_disk_laser_timer", "diskLaserTimer"),
    ("m_unknown_2F8", "unknown2F8"), ("m_ammo", "ammo"), ("m_value", "value"),
    ("m_fire_particle_system", "fireParticleSystem"),
    ("m_spark_particle_system", "sparkParticleSystem"),
    ("m_natural_particle_system", "naturalParticleSystem"),
    ("m_damage_particle_system", "damageParticleSystem"),
    ("m_railgun_particle_system", "railgunParticleSystem"),
    ("m_unk1_particle_system", "unk1ParticleSystem"),
    ("m_unk2_particle_system", "unk2ParticleSystem"),
    ("m_firing_particle_system", "firingParticleSystem"),
    ("m_wave", "wave"), ("m_angle_rotated_sideways", "angleRotatedSideways"),
    ("m_angle_rotated_forwards", "angleRotatedForwards"),
    ("m_rocking_sideways_per_frame", "rockingSidewaysPerFrame"),
    ("m_rocking_forwards_per_frame", "rockingForwardsPerFrame"),
    ("m_hijacker_infantry_type", "hijackerInfantryType"),
    ("m_tiberium", "tiberium"), ("m_unknown_34C", "unknown34C"),
    ("m_unload_timer", "unloadTimer"),
    ("m_barrel_facing", "barrelFacing"), ("m_facing", "facing"),
    ("m_turret_facing", "turretFacing"),
    ("m_current_burst_index", "currentBurstIndex"),
    ("m_target_laser_timer", "targetLaserTimer"),
    ("m_unknown_short_3C8", "unknownShort3C8"), ("m_unknown_3CA", "unknown3CA"),
    ("m_counted_as_owned", "countedAsOwned"),
    ("m_is_sinking", "isSinking"), ("m_was_sinking_already", "wasSinkingAlready"),
    ("m_unknown_bool_3CF", "unknownBool3CF"), ("m_unknown_bool_3D0", "unknownBool3D0"),
    ("m_has_been_attacked", "hasBeenAttacked"), ("m_cloakable", "cloakableFlag"),
    ("m_is_primary_factory", "isPrimaryfactory"),
    ("m_spawned", "spawned"), ("m_is_in_playfield", "isInPlayfield"),
    ("m_turret_recoil", "turretRecoil"), ("m_barrel_recoil", "barrelRecoil"),
    ("m_unknown_bool_418", "unknownBool418"), ("m_unknown_bool_419", "unknownBool419"),
    ("m_is_human_controlled", "isHumanControlled"),
    ("m_discovered_by_player", "discoveredByPlayer"),
    ("m_discovered_by_computer", "discoveredByComputer"),
    ("m_unknown_bool_41D", "unknownBool41D"), ("m_unknown_bool_41E", "unknownBool41E"),
    ("m_unknown_bool_41F", "unknownBool41F"), ("m_sight_increase", "sightIncrease"),
    ("m_recruitable_a", "recruitableA"), ("m_recruitable_b", "recruitableB"),
    ("m_is_radar_tracked", "isRadarTracked"), ("m_is_on_carryall", "isOnCarryall"),
    ("m_is_crashing", "isCrashing"), ("m_was_crashing_already", "wasCrashingAlready"),
    ("m_is_being_manipulated", "isBeingManipulated"),
    ("m_being_manipulated_by", "beingManipulatedBy"),
    ("m_chrono_warped_by_house", "chronoWarpedByhouse"),
    ("m_unknown_bool_430", "unknownBool430"), ("m_unknown_bool_431", "unknownBool431"),
    ("m_unknown_bool_432", "unknownBool432"), ("m_padding_433", "padding433"),
    ("m_old_team", "oldTeam"),
    ("m_counted_as_owned_special", "countedAsOwnedSpecial"),
    ("m_absorbed", "absorbed"), ("m_unknown_bool_43A", "unknownBool43A"),
    ("m_padding_43B", "padding43B"), ("m_unknown_43C", "unknown43C"),
    ("m_current_target_threat_values", "currentTargetThreatValues"),
    ("m_current_targets", "currentTargets"),
    ("m_attacked_targets", "attackedTargets"),
    ("m_audio3", "audio3"), ("m_unknown_49C", "unknown49C"),
    ("m_unknown_4A0", "unknown4A0"), ("m_audio4", "audio4"),
    ("m_unknown_bool_4B8", "unknownBool4B8"), ("m_padding_4B9", "padding4B9"),
    ("m_unknown_4BC", "unknown4BC"), ("m_audio5", "audio5"),
    ("m_unknown_bool_4D4", "unknownBool4D4"), ("m_padding_4D5", "padding4D5"),
    ("m_unknown_4D8", "unknown4D8"), ("m_audio6", "audio6"),
    ("m_queued_voice_index", "queuedVoiceIndex"),
    ("m_unknown_4F4", "unknown4F4"), ("m_unknown_bool_4F8", "unknownBool4F8"),
    ("m_padding_4F9", "padding4F9"), ("m_unknown_4FC", "unknown4FC"),
    ("m_unknown_500", "unknown500"), ("m_emp_lock_remaining", "empLockRemaining"),
    ("m_threat_posed", "threatPosed"), ("m_should_lose_target_now", "shouldLoseTargetNow"),
    ("m_firing_rad_beam", "firingRadBeam"), ("m_planning_token", "planningToken"),
    ("m_disguise", "disguiseType"), ("m_disguised_as_house", "disguisedAsHouse"),
    # BuildingClass members
    ("unknown_int_534", "unknownInt534"), ("unknown_int_538", "unknownInt538"),
    ("OwnerCountryIndex", "ownerCountryIndex"), ("C4AppliedBy", "c4AppliedBy"),
    ("unknown_544", "unknown544"), ("FirestormAnim", "firestormAnim"),
    ("PsiWarnAnim", "psiWarnAnim"), ("unknown_timer_550", "unknownTimer550"),
    ("AnimStates", "animStates"), ("DamageFireAnims", "damageFireAnims"),
    ("RequiresDamageFires", "requiresDamageFires"),
    ("FiringSWType", "firingSwType"), ("unknown_5FC", "unknown5FC"),
    ("Spotlight", "spotlight"), ("GateTimer", "gateTimer"),
    ("LightSource", "lightSource"), ("LaserFenceFrame", "laserFenceFrame"),
    ("FirestormWallFrame", "firestormWallFrame"),
    ("RepairProgress", "repairProgress"),
    ("unknown_rect_63C", "unknownRect63C"), ("unknown_coord_64C", "unknownCoord64C"),
    ("unknown_int_658", "unknownInt658"), ("unknown_65C", "unknown65C"),
    ("HasPower", "hasPower"), ("IsOverpowered", "isOverpowered"),
    ("RegisteredAsPoweredUnitSource", "registeredAsPoweredUnitSource"),
    ("SupportingPrisms", "supportingPrisms"),
    ("HasExtraPowerBonus", "hasExtraPowerBonus"),
    ("HasExtraPowerDrain", "hasExtraPowerDrain"),
    ("Occupants", "occupants"), ("FiringOccupantIndex", "firingOccupantIndex"),
    ("WasOnline", "wasOnline"), ("ShowRealName", "showRealName"),
    ("BeingProduced", "beingProduced"), ("ShouldRebuild", "shouldRebuild"),
    ("HasEngineer", "hasEngineer"), ("CashProductionTimer", "cashProductionTimer"),
    ("unknown_bool_6DC", "unknownBool6DC"), ("unknown_bool_6DD", "unknownBool6DD"),
    ("NeedsRepairs", "needsRepairs"), ("C4Applied", "c4Applied"),
    ("NoCrew", "noCrew"), ("unknown_bool_6E1", "unknownBool6E1"),
    ("unknown_bool_6E2", "unknownBool6E2"),
    ("HasBeenCaptured", "hasBeenCaptured"),
    ("ActuallyPlacedOnMap", "actuallyPlacedOnMap"),
    ("unknown_bool_6E5", "unknownBool6E5"), ("IsDamaged", "isDamaged"),
    ("IsFogged", "isFogged"), ("IsBeingRepaired", "isBeingRepaired"),
    ("unknown_bool_6E9", "unknownBool6E9"), ("StuffEnabled", "stuffEnabled"),
    ("HasCloakingData", "hasCloakingData"), ("CloakRadius", "cloakRadius"),
    ("Translucency", "translucency"), ("StorageFilledSlots", "storageFilledSlots"),
    ("SecretProduction", "secretProduction"), ("ColorAdd", "colorAdd"),
    ("unknown_int_6FC", "unknownInt6FC"), ("unknown_short_700", "unknownShort700"),
    ("UpgradeLevel", "upgradeLevel"), ("GateStage", "gateStage"),
    ("PrismStage", "prismStage"), ("PrismTargetCoords", "prismTargetCoords"),
    ("DelayBeforeFiring", "delayBeforeFiring"), ("BunkerState", "bunkerState"),
    ("ProductionTimer", "productionTimer"), ("PlacementAllowed", "placementAllowed"),
    ("ProductionBlocked", "productionBlocked"),
    ("m_pad_prod_1", "padProd1"), ("m_pad_prod_2", "padProd2"),
    ("ProductionAccum", "productionAccum"), ("ProductionFrame", "productionFrame"),
    ("ProductionRate", "productionRate"), ("ProductionSpeed", "productionSpeed"),
    ("CostAccumulator", "costAccumulator"), ("PipelineStep", "pipelineStep"),
    ("m_pad_prod_3", "padProd3"),
    # Entity class members  
    ("IsbuildingAnim", "isBuildingAnim"),
    ("UnderTemporal", "underTemporal"), ("PausedAnimFrame", "pausedAnimFrame"),
    ("Unpaused", "unpaused"), ("Reverse", "reverse"),
    ("TranslucencyLevel", "translucencyLevel"), ("TimeToDie", "timeToDie"),
    ("AttachedBullet", "attachedBullet"), ("LoopDelay", "loopDelay"),
    ("HasExtras", "hasExtras"), ("RemainingIterations", "remainingIterations"),
    ("IsPlaying", "isPlaying"), ("FlamingGuyExpire", "flamingGuyExpire"),
    ("UnableToContinue", "unableToContinue"), ("SkipProcessOnce", "skipProcessOnce"),
    ("Invisible", "invisible"), ("PowerOff", "powerOff"),
    ("unused_19F", "unused19F"), ("PaletteName", "paletteName"),
    ("AnimFlags", "animFlags"), ("FlamingGuyCoords", "flamingGuyCoords"),
    ("FlamingGuyRetries", "flamingGuyRetries"),
    ("ZAdjust", "zAdjust"), ("YSortAdjust", "ySortAdjust"),
    ("TintColor", "tintColor"), ("LightConvert", "lightConvert"),
    ("LightConvertIndex", "lightConvertIndex"),
    ("OwnerObject", "ownerObject"), ("Bounce", "bounce"),
    ("unknown_D0", "unknownD0"), ("unknown_124", "unknown124"),
    ("unknown_196", "unknown196"), ("unknown_197", "unknown197"),
    ("unknown_E4", "unknownE4"), ("unknown_100", "unknown100"),
    ("unknown_104", "unknown104"), ("unknown_108", "unknown108"),
    ("unknown_118", "unknown118"), ("unknown_11C", "unknown11C"),
    ("unknown_120", "unknown120"), ("unknown_B4", "unknownB4"),
    ("AnimFrame", "animFrame"), ("AnimRateCounter", "animRateCounter"),
    ("InheritedColor", "inheritedColor"), ("Bright", "bright"),
    ("LastMapCoords", "lastMapCoords"), ("SourceCoords", "sourceCoords"),
    ("TargetCoords", "targetCoords"), ("DamageMultiplier", "damageMultiplier"),
    ("NextAnim", "nextAnim"), ("SpawnNextAnim", "spawnNextAnim"),
    ("Range", "range"), ("WeaponType", "weaponType"),
    ("DistributedFire", "distributedFire"),
    ("unknown_B0", "unknownB0"), ("unknown_B1", "unknownB1"),
    ("unknown_B2", "unknownB2"), ("unknown_B4", "unknownB4p"),
    ("unknown_B8", "unknownB8"), ("unknown_BC", "unknownBC"),
    # Misc members
    ("SidebarImageFile", "sidebarImageFile"),
    ("FlashSidebarTabFrames", "flashSidebarTabFrames"),
    ("IsPowered", "isPowered"), ("SuperWeaponType", "superWeaponType"),
    ("SidebarImage", "sidebarImage"),
    ("Location", "location_member"),  # careful - Location is also a type
    ("FrameStep", "frameStep"),
    ("Animation", "animation_member"),  # careful
    ("Damage", "damage"),
]

def main():
    base = r"D:\RA2YR_ReSource"
    changed = 0
    for sub in ["include\\gamemd", "src"]:
        for root, dirs, files in os.walk(os.path.join(base, sub)):
            if "gen" in root or "injectFunctionTest" in root:
                continue
            for fn in files:
                if not (fn.endswith(".hpp") or fn.endswith(".cpp") or fn.endswith(".h")):
                    continue
                fp = os.path.join(root, fn)
                with open(fp, "r", encoding="utf-8") as f:
                    txt = f.read()
                orig = txt
                for old, new in RENAMES:
                    txt = txt.replace(old, new)
                if txt != orig:
                    with open(fp, "w", encoding="utf-8", newline="\n") as f:
                        f.write(txt)
                    changed += 1
    print(f"Changed {changed} files")

if __name__ == "__main__":
    main()
