"""Generate render_globals.cpp"""
import os

lines = []

def L(s):
    lines.append(s)

L("// render_globals.cpp - Global rendering utility functions (HIGH priority)")
L("// Reverse-engineered from gamemd.exe via IDA MCP decompilation.")
L("")
L("#include <windows.h>")
L("#include <cstdint>")
L("#include <cstring>")
L("")
L('#include "core/reverse_marker.hpp"')
L('#include "render/globals_render.hpp"')
L('#include "render/surface.hpp"')
L('#include "core/ddraw_init.hpp"')
L('#include "core/globals_core.hpp"')
L('#include "app/cmdline.hpp"')
L("")
L("namespace gamemd {")
L("")
L("extern char BlitterCopySHP(void* dest, void* locked_dest, void* rect,")
L("    void* param4, void* src_surf, void* locked_src, void* frame,")
L("    int x, int y, int w, int h, int flag);")
L("")
L("extern void* RenderTextLabelWordWrap(void* cs, int x, int y, int w, int h,")
L("    int color, int a7, int a8, int a9, int a10);")
L("")
L("extern int CompressLCWBuffer(void* src, int* dst_len, int max_len);")
L("")
L("extern void Coord_To_Screen(void* tactical, void* coord, int out[2]);")
L("")
L("extern void* BuildingClass_GetSHPFrame(int frame_idx);")
L("")
L("extern char DrawTacticalLine2D(int x, int y, int a3, int a4, int a5, int a6, int flag);")
L("")
L("extern char ChangeVideoMode(int w, int h);")
L("")
L("extern void Debug_Log(const char* fmt, ...);")
L("")
L("extern uint8_t byte_A8F91C[65536];")
L("")
L("// ======================================================================")
L("// BlitterCopySimpleSHP @ 0x437350 (91B)")
L("// ======================================================================")
L('REVERSE(0x437350, "BlitterCopySimpleSHP", "None")')
L("char BlitterCopySimpleSHP(")
L("    void* dest_surf, void* param2, int a3, int a4,")
L("    void* frame, int a6, int a7, int a8, int a9)")
L("{")
L("    uint8_t lock_buf[20];")
L("    int src_surf = a3;")
L("    auto src_vt = *(uint32_t**)src_surf;")
L("    void* locked_src = ((void*(__thiscall*)(void*,void*,int))")
L("        src_vt[30])((void*)src_surf, lock_buf, a4);")
L("")
L("    auto dest_vt = *(uint32_t**)dest_surf;")
L("    void* locked_dest = ((void*(__thiscall*)(void*))")
L("        dest_vt[30])(dest_surf);")
L("")
L("    int rect[3];")
L("    return BlitterCopySHP(dest_surf, locked_dest, rect,")
L("        param2, (void*)src_surf, locked_src, frame,")
L("        a6, a7, a8, a9, 0);")
L("}")
L("")
L("// ======================================================================")
L("// FillRectangle @ 0x4A6500 (192B)")
L("// ======================================================================")
L('extern "C" void* Color_ConvertToRGB(void* out_buf, int color_idx);')
L("")
L('REVERSE(0x4A6500, "FillRectangle", "None")')
L("void* FillRectangle(void* result_ptr, int x, int y, int w, int h,")
L("    void* color_src, int arg18, int arg1C, int arg20, int arg24)")
L("{")
L("    uint8_t rgb_buf[4];")
L("    uint8_t* color_base = (uint8_t*)color_src;")
L("    void* rgb_ptr = Color_ConvertToRGB(rgb_buf,")
L("        *(int*)(color_base + 0x308));")
L("")
L("    uint16_t rgb16 = *(uint16_t*)rgb_ptr;")
L("    uint8_t rgb_blue = *((uint8_t*)rgb_ptr + 2);")
L("")
L("    uint32_t blue = (rgb_blue >> g_BitMask_Red) << g_BitShift_Blue;")
L("    uint32_t green = (HIBYTE(rgb16) >> g_BitMask_Blue) << g_BitMask_Green;")
L("    uint32_t red = ((uint8_t)rgb16 >> g_BitShift_Green_0) << g_BitShift_Red;")
L("    int color = (int)(red | green | blue);")
L("")
L("    void* wr = RenderTextLabelWordWrap(&rgb16, x, y, w, h,")
L("        color, arg18, arg1C, arg20, arg24);")
L("")
L("    ((uint32_t*)result_ptr)[0] = *(uint32_t*)wr;")
L("    ((uint32_t*)result_ptr)[1] = ((uint32_t*)wr)[1];")
L("    return result_ptr;")
L("}")
L("")
L("// ======================================================================")
L("// BlitterDrawSHP @ 0x4AF2A0 (144B)")
L("// ======================================================================")
L('REVERSE(0x4AF2A0, "BlitterDrawSHP", "None")')
L("char BlitterDrawSHP(void* dest_surf, void* obj, void* src_surf,")
L("    void* paint_bounds, void* src_rect, void* locked_buf,")
L("    int draw_flag, void* frame_data, int x, int y, int w, int h, int flags)")
L("{")
L("    *(int*)((uint8_t*)obj + 0x17C) = draw_flag;")
L("")
L("    if (!frame_data) {")
L("        int frame_idx = draw_flag ? 0x10 : 0;")
L("        frame_data = BuildingClass_GetSHPFrame(frame_idx);")
L("    }")
L("")
L("    int rect[4];")
L("    rect[0] = ((int*)src_rect)[0];")
L("    rect[1] = ((int*)src_rect)[1];")
L("    rect[2] = ((int*)paint_bounds)[2];")
L("    rect[3] = ((int*)paint_bounds)[3];")
L("")
L("    uint8_t lock_buf[16];")
L("    auto src_vt = *(uint32_t**)src_surf;")
L("    void* locked_src = ((void*(__thiscall*)(void*,void*))")
L("        src_vt[30])(src_surf, lock_buf);")
L("")
L("    return BlitterCopySHP(dest_surf, locked_buf, rect,")
L("        src_surf, locked_src, paint_bounds,")
L("        frame_data, x, y, w, h, flags);")
L("}")
L("")
L("// ======================================================================")
L("// BlendMinimapPixel @ 0x4BF650 (119B)")
L("// ======================================================================")
L('REVERSE(0x4BF650, "BlendMinimapPixel", "None")')
L("uint16_t BlendMinimapPixel(uint16_t a1, uint16_t a2, int percentage)")
L("{")
L("    if (percentage > 100)")
L("        return a1;")
L("    switch (percentage) {")
L("    case 0:")
L("        return a2;")
L("    case 25:")
L("        return (uint16_t)(4 * (HIWORD(g_DDraw_Gray127) & (a1 >> 2)));")
L("    case 50:")
L("        return (uint16_t)(")
L("            ((uint16_t)g_DDraw_Gray127 & (a2 >> 1)) +")
L("            ((uint16_t)g_DDraw_Gray127 & (a1 >> 1)));")
L("    case 75:")
L("        return (uint16_t)(4 * (HIWORD(g_DDraw_Gray127) & (a1 >> 2)));")
L("    default:")
L("        return a1;")
L("    }")
L("}")
L("")
L("// ======================================================================")
L("// GetComboBoxSelectedRaw @ 0x4E4E20 (53B)")
L("// ======================================================================")
L('REVERSE(0x4E4E20, "GetComboBoxSelectedRaw", "None")')
L("LRESULT GetComboBoxSelectedRaw(HWND hDlg, int nIDDlgItem, LRESULT wParam)")
L("{")
L("    if (wParam == (LRESULT)-1)")
L("        wParam = SendDlgItemMessageA(hDlg, nIDDlgItem, CB_GETCURSEL, 0, 0);")
L("    return SendDlgItemMessageA(hDlg, nIDDlgItem, CB_GETLBTEXT, (WPARAM)wParam, 0);")
L("}")
L("")
L("// ======================================================================")
L("// GetComboBoxSelectedRaw2 @ 0x4E6030 (53B)")
L("// ======================================================================")
L('REVERSE(0x4E6030, "GetComboBoxSelectedRaw2", "None")')
L("LRESULT GetComboBoxSelectedRaw2(HWND hDlg, int nIDDlgItem, LRESULT wParam)")
L("{")
L("    if (wParam == (LRESULT)-1)")
L("        wParam = SendDlgItemMessageA(hDlg, nIDDlgItem, CB_GETCURSEL, 0, 0);")
L("    return SendDlgItemMessageA(hDlg, nIDDlgItem, CB_GETLBTEXT, (WPARAM)wParam, 0);")
L("}")
L("")
L("// ======================================================================")
L("// WriteCompressionBlock @ 0x55BB90 (103B)")
L("// ======================================================================")
L('REVERSE(0x55BB90, "WriteCompressionBlock", "None")')
L("int WriteCompressionBlock(uint8_t* src, uint32_t src_len,")
L("    uint8_t* dst, int* out_len, int max_len)")
L("{")
L("    int result = 0;")
L("    if (src_len > 0) {")
L("        if (src_len > 13) {")
L("            result = CompressLCWBuffer(src, out_len, max_len);")
L("            if (result) return result;")
L("        } else {")
L("            dst[0] = (uint8_t)(src_len + 0x11);")
L("            uint8_t* d = dst + 1;")
L("            for (uint32_t i = 0; i < src_len; i++)")
L("                *d++ = *src++;")
L("            *out_len = (int)(d - dst);")
L("        }")
L("    } else {")
L("        *out_len = 0;")
L("    }")
L("    int len = *out_len;")
L("    dst[len] = 0x11;")
L("    dst[len + 1] = 0;")
L("    dst[len + 2] = 0;")
L("    *out_len += 3;")
L("    return result;")
L("}")
L("")
L("// ======================================================================")
L("// ToCoordPixel @ 0x6339E0 (59B)")
L("// ======================================================================")
L('REVERSE(0x6339E0, "ToCoordPixel", "None")')
L("void* ToCoordPixel(void* result, void* coord)")
L("{")
L("    extern void* TacticalClass_Instance;")
L("    extern int Map_VisibleRect;")
L("    int screen[2];")
L("    Coord_To_Screen(TacticalClass_Instance, coord, screen);")
L("    ((int*)result)[0] = (int)DSurface_ViewBounds + screen[0];")
L("    ((int*)result)[1] = Map_VisibleRect + screen[1];")
L("    return result;")
L("}")
L("")
L("// ======================================================================")
L("// DrawTacticalFillScanline @ 0x63D910 (67B)")
L("// ======================================================================")
L('REVERSE(0x63D910, "DrawTacticalFillScanline", "None")')
L("char DrawTacticalFillScanline(int y, int a2, int a3, int a4, int a5, int a6)")
L("{")
L("    char result = 0;")
L("    int start = y / 2 - y + 1;")
L("    int end = y / 2;")
L("    for (int i = start; i <= end; i++)")
L("        result = DrawTacticalLine2D(i, a2, a3, a4, a5, a6, 0);")
L("    return result;")
L("}")
L("")
L("// ======================================================================")
L("// ToggleDisplayMode @ 0x6842F0 (126B)")
L("// ======================================================================")
L('REVERSE(0x6842F0, "ToggleDisplayMode", "None")')
L("char ToggleDisplayMode(char a1)")
L("{")
L("    char result;")
L("    if (a1) {")
L("        result = (char)g_CommandLineFlags;")
L("        if (g_CreditsScreenBounds != g_CommandLineFlags ||")
L("            g_CreditsScreenConfig != g_CommandLineParam) {")
L('            Debug_Log("Toggle display mode to %d x %d\\n",')
L("                g_CommandLineFlags, g_CommandLineParam);")
L("            return ChangeVideoMode(g_CommandLineFlags, g_CommandLineParam);")
L("        }")
L("    } else {")
L("        result = (char)g_CreditsScreenBounds;")
L("        if (g_CreditsScreenBounds != xRight) {")
L("            result = (char)yBottom;")
L("            if (g_CreditsScreenConfig != yBottom) {")
L('                Debug_Log("Toggle display mode back to shell res\\n");')
L("                return ChangeVideoMode(xRight, yBottom);")
L("            }")
L("        }")
L("    }")
L("    return result;")
L("}")
L("")
L("// ======================================================================")
L("// ObfuscateDataBlock @ 0x7E0170 (98B)")
L("// ======================================================================")
L("#ifdef _MSC_VER")
L('#include <intrin.h>')
L("#pragma intrinsic(_rotr)")
L("#define ROR4(v, n) _rotr((unsigned int)(v), (n))")
L("#else")
L("static inline uint32_t ROR4(uint32_t v, int n) {")
L("    return (v >> n) | (v << (32 - n));")
L("}")
L("#endif")
L("")
L('REVERSE(0x7E0170, "ObfuscateDataBlock", "None")')
L("void ObfuscateDataBlock(int* src, uint32_t* dst, int count)")
L("{")
L("    unsigned int remaining = ((unsigned int)(count - 2)) >> 1;")
L("    while (remaining--) {")
L("        int v6 = *src;")
L("        src = (int*)((char*)src + 2);")
L("        uint32_t v7 = ROR4(v6, 8);")
L("        ((uint8_t*)&v7)[0] = byte_A8F91C[(uint16_t)v6];")
L("        ((uint8_t*)&v7)[1] = ((uint8_t*)&v6)[1];")
L("        uint32_t v8 = ROR4(v7, 8);")
L("        ((uint8_t*)&v8)[1] = byte_A8F91C[(v6 & 0xFFFF00u) >> 8];")
L("        *dst++ = ROR4(v8, 16);")
L("    }")
L("    uint16_t v9 = *(uint16_t*)src;")
L("    uint8_t* d2 = (uint8_t*)dst;")
L("    *d2++ = (uint8_t)v9;")
L("    *d2++ = byte_A8F91C[v9];")
L("    *d2++ = HIBYTE(v9);")
L("    *d2 = 0;")
L("}")
L("")
L("} // namespace gamemd")

output_path = os.path.join(os.path.dirname(__file__), '..', 'src', 'render', 'render_globals.cpp')
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print(f"Written {len(lines)} lines to {output_path}")