#!/usr/bin/env python3
"""Generate template instantiation stubs. Usage: python tools/gen_template_stubs.py [--apply]"""
import json, re, sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).parent.parent
INVALID_FILE = ROOT / ".omo" / "gap2_invalid_names.json"

def main():
    apply_flag = '--apply' in sys.argv
    with open(INVALID_FILE) as f:
        data = json.load(f)
    
    entries_by_class = defaultdict(list)
    
    for e in data['invalid']:
        addr = e['address']
        name = e['name']
        reason = e['reason']
        if reason not in ('template_underscore', 'bracket_array'): continue
        if '::' not in name: continue
        cls_part, method = name.rsplit('::', 1)
        if method.startswith('Constructor') or method.startswith('Destructor') or method.startswith('ScalarDeleting'): continue
        
        class_name = None
        if reason == 'template_underscore':
            for ct in ('DynamicVectorClass', 'VectorClass', 'TypeList'):
                if cls_part.startswith(ct + '_'):
                    rest = cls_part[len(ct)+1:]
                    ptr_type = ''
                    for pt, prefix in [('cptr','cptr_'),('ptr','ptr_'),('rc_ptr','rc_ptr_')]:
                        if rest.startswith(prefix): ptr_type = pt; rest = rest[len(prefix):]; break
                    tn = rest.rstrip('_')
                    if '__' in tn: continue
                    if ptr_type in ('ptr','rc_ptr'): cpp_param = f"{tn}*"
                    elif ptr_type == 'cptr': cpp_param = f"{tn} const*"
                    else: cpp_param = tn
                    class_name = f"VectorClass<{cpp_param}>"
                    break
        elif reason == 'bracket_array':
            m = re.match(r'(.+?)\[(\d+)\]$', cls_part)
            if m:
                prefix, cap = m.group(1), int(m.group(2))
                known = {
                    'Tactical':'TActionClass','AITriggerTypeClass':'AlphaLightingRemapClass',
                    'BlowPipe':'EventClass','Dial8Class':'DiskLaserClass',
                    'HouseClass':'GraphicMenuItem','VectorClass__N':'TeamTypeClass',
                    'FoggedObjectClass':'FoggedObjectClass','ParticleSystemClass':'ParticleSystemClass',
                    'FilePipe':'FileClass','FactoryClass':'FactoryClass',
                    'CStreamClass':'CStreamClass','ConnectionPointClass':'ConnectionPointClass',
                    'HouseTypeClass':'HouseTypeClass','TeamTypeClass':'TeamTypeClass',
                    'SpawnManagerClass':'SpawnManagerClass','SlaveManagerClass':'SlaveManagerClass',
                    'SwizzleManagerClass':'SwizzleManagerClass','ToolTipManager':'ToolTipManager',
                    'MapSeedClass':'MapSeedClass','JumpjetLocomotionClass':'JumpjetLocomotionClass',
                    'RocketLocomotionClass':'RocketLocomotionClass',
                    'DeleteCommandClass':'DeleteCommandClass','CheckListClass':'CheckListClass',
                    'MSFont':'MSFont','WDTState':'WDTState','WonlineStringDialogControl':'WonlineStringDialogControl',
                    'BlowStraw':'BlowStraw','NeuronClass':'NeuronClass',
                    'VectorClass_K':'K','VectorClass_UAngerStruct__':'UAngerStruct',
                    'VectorClass_UDirtyAreaStruct__':'UDirtyAreaStruct','VectorClass_UScoutStruct__':'UScoutStruct',
                    'DynamicVectorClass_PAD':'PAD',
                    'CampaignProperties_WorldDominationTour':'CampaignProperties',
                    'Campaign_WorldDominationTour':'Campaign','Conflict_WorldDominationTour':'Conflict',
                    'Map_WorldDominationTour':'Map','Territory_WorldDominationTour':'Territory',
                    'VectorCursor_uint_DynamicVectorClass_uint___':'uint',
                }
                if prefix == 'MSPCXAnim':
                    if cap == 42: inner = 'MSAnimEntry*'
                    elif cap == 26: inner = 'MapStage*'
                    else: inner = f'{prefix}*'
                elif prefix in known: inner = f'{known[prefix]}*'
                else: inner = f'{prefix}*'
                class_name = f"VectorClass<{inner}>"  # capacity is runtime, not template param
        
        if class_name:
            entries_by_class[class_name].append((addr, method))
    
    lines = []
    lines.append("// Auto-generated template instantiation stubs with // 0xADDR annotations")
    lines.append("// Generated by tools/gen_template_stubs.py — DO NOT EDIT MANUALLY")
    lines.append("// Primary template (vector.hpp) provides all method declarations.")
    lines.append("// These explicit instantiations ensure symbols exist for each address.")
    lines.append("")
    lines.append('#include "core/vector.hpp"')
    lines.append("")
    lines.append("namespace gamemd {")
    lines.append("")
    
    type_names = set()
    for cn in entries_by_class:
        m = re.match(r'VectorClass<\s*(.+?)(?:\s*,\s*\d+)?\s*>', cn)
        if m:
            for p in m.group(1).split(','):
                base = p.strip().rstrip('*').replace('const','').strip()
                if base and re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', base): type_names.add(base)
    if type_names:
        lines.append("// Forward declarations")
        for tn in sorted(type_names): lines.append(f"class {tn};")
        lines.append("")
    
    for cn in sorted(entries_by_class.keys()):
        entries = entries_by_class[cn]
        addrs = sorted(set(a for a,_ in entries))
        methods = sorted(set(m for _,m in entries))
        lines.append(f"// === {cn} ===")
        lines.append(f"// Methods: {', '.join(methods)}")
        for addr in addrs:
            am = [m for a,m in entries if a==addr]
            lines.append(f"// {addr}  ({', '.join(sorted(set(am)))})")
        lines.append(f"template class {cn};")
        lines.append("")
    
    lines.append("} // namespace gamemd")
    output = '\n'.join(lines)
    
    print(f"Classes: {len(entries_by_class)}")
    if apply_flag:
        (ROOT / "src" / "core" / "template_stubs.cpp").write_text(output + '\n', encoding='utf-8')
        print(f"Wrote. Lines: {output.count(chr(10)):,}")
    else:
        print("[DRY RUN] Use --apply")

if __name__ == '__main__': main()
