#!/usr/bin/env python3
"""gen_symbol_anchors_e.py — Stage E: comment-only symbol anchors for real-IDA
functions that cannot be safe member declarations (headerless classes, ctor/dtor/
vt-slots, type-name collisions, namespace funcs).

Each anchor is a COMMENT line (zero compile impact) in the BARE form:
    // 0xADDR | Class::Method
The bare `|` form (no `--`) means audit_consistency.py extracts NO name from the
line -> the address is counted as annotated but NO name comparison is performed
-> ZERO chance of introducing a name_mismatch. (The audit's previous-line `--`
dash fallback would otherwise bleed a neighbour's name onto a name-less line.)
The IDA name remains human-readable in the comment text.

Output: src/_generated/symbol_anchors.hpp (comment-only, grouped by class).
Excludes templates (compiler-generated, per project directive) and non-IDA addrs.

Usage: python tools/gen_symbol_anchors_e.py --apply
"""
import json, re, sys
from pathlib import Path
from collections import defaultdict

ROOT = Path(r"D:\RA2YR_ReSource")
OUT = ROOT / "src" / "_generated" / "symbol_anchors.hpp"

def norm(a): return "0X" + str(a).upper().replace("0X", "").zfill(8)
def fmt_addr(a): return "0x" + str(a).lower().replace("0x", "")

# categories to anchor (real-IDA, non-template, not junk-skip)
ANCHOR_CATS = ["absent_class", "namespace", "real_already_declared",
               "abbrev_already_declared", "real_class_other", "abbrev_other", "junk"]

def main():
    apply = "--apply" in sys.argv
    rem = json.load(open(ROOT / ".omo" / "symanchor_remaining.json"))
    fj = json.load(open(ROOT / "injectFunctionTest" / "functions.json"))
    fm = {norm(e["address"]): e for e in fj["functions"]}

    by_class = defaultdict(list)   # group key -> [(addr, name)]
    total = 0
    for cat in ANCHOR_CATS:
        for ent in rem.get(cat, []):
            a = norm(ent["addr"]); name = ent["name"]
            entry = fm.get(a)
            addr = fmt_addr(entry["address"]) if entry else fmt_addr(a)
            grp = name.split("::")[0] if "::" in name else "(global)"
            by_class[grp].append((addr, name))
            total += 1

    print(f"Comment anchors to write: {total} across {len(by_class)} groups")

    if not apply:
        print("(dry-run; pass --apply)")
        return

    lines = [
        "#pragma once",
        "// Auto-generated by tools/gen_symbol_anchors_e.py — DO NOT EDIT MANUALLY",
        "//",
        "// Comment-only symbol anchors: address <-> IDA name for real functions that",
        "// have no project header (headerless classes), or are constructors/",
        "// destructors/vtable-slots/type-name-collisions that cannot be safe member",
        "// declarations. These document the symbol mapping and are counted by",
        "// tools/audit_consistency.py. Compiler-generated template instances are",
        "// intentionally NOT listed here.",
        "//",
        f"// {total} anchors across {len(by_class)} groups",
        "",
    ]
    for grp in sorted(by_class):
        anchors = sorted(by_class[grp], key=lambda x: x[0])
        lines.append(f"// ---- {grp} ({len(anchors)}) ----")
        for addr, name in anchors:
            lines.append(f"// {addr} | {name}")
        lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(lines)} lines)")

if __name__ == "__main__":
    main()
