#!/usr/bin/env python3
"""Scan source files for REVERSE macros, generate DEFINE_HOOK stubs with call logging.

Usage:
    python gen_reverse_hooks.py
    
Scans: src/**/*.cpp, app/**/*.cpp, include/gamemd/**/*.hpp
Generates: injectFunctionTest/gen/reverse_hooks.cpp with DEFINE_HOOKs
"""
import os, re, json

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
OUTPUT_PATH = os.path.join(SCRIPT_DIR, "gen", "reverse_hooks.cpp")
JSON_PATH   = os.path.join(SCRIPT_DIR, "functions.json")

def load_json():
    if not os.path.exists(JSON_PATH):
        return {}
    with open(JSON_PATH) as f:
        data = json.load(f)
    return {fn['address'].lower(): fn for fn in data['functions']}

def find_reverse_markers():
    markers = []
    pattern = re.compile(
        r'REVERSE\(\s*(0x[0-9A-Fa-f]+)\s*,\s*"([^"]*)"\s*,\s*(true|false)\s*\)',
        re.IGNORECASE
    )
    search_dirs = [
        os.path.join(PROJECT_ROOT, "src"),
        os.path.join(PROJECT_ROOT, "app"),
        os.path.join(PROJECT_ROOT, "include", "gamemd"),
    ]
    fn_name_pattern = re.compile(
        r'(?:inline\s+)?(?:static\s+)?(?:const\s+)?(?:virtual\s+)?'
        r'(?:\w+(?:::+\w+)*[\*\s&]+)+'
        r'(\w+)'
        r'\s*\(', re.IGNORECASE
    )
    for search_dir in search_dirs:
        for root, dirs, files in os.walk(search_dir):
            for fname in files:
                if not fname.endswith(('.cpp', '.hpp', '.h')):
                    continue
                fpath = os.path.join(root, fname)
                with open(fpath, errors='ignore') as f:
                    content = f.read()
                for m in pattern.finditer(content):
                    # Skip if inside a comment
                    line_start = content.rfind('\n', 0, m.start()) + 1
                    line = content[line_start:m.end()]
                    if line.lstrip().startswith('//') or line.lstrip().startswith('/*'):
                        continue
                    addr = m.group(1).lower()
                    desc = m.group(2)
                    enabled = m.group(3) == 'true'
                    if not enabled:
                        continue
                    rest = content[m.end():m.end()+200]
                    fn_match = fn_name_pattern.search(rest)
                    fn_name = fn_match.group(1) if fn_match else "unknown"
                    relpath = os.path.relpath(fpath, PROJECT_ROOT)
                    markers.append({
                        'addr': addr, 'desc': desc,
                        'fn_name': fn_name, 'file': relpath,
                    })
    return markers

def sanitize(name):
    return name.replace('::', '_').replace('@', '_').replace('<','_').replace('>','_')

def generate_hooks(markers, functions):
    out = []
    w = out.append
    w('// Auto-generated by gen_reverse_hooks.py — DO NOT EDIT')
    w('#include <windows.h>')
    w('#include <cstdio>')
    w('#include "Syringe.h"')
    w('#include "tls_storage.h"')
    w('')
    w('extern "C" void PostProcStub();')
    w('static FILE* g_log_file = nullptr;')
    w('static int   g_call_counters[8192] = {};')
    w('')
    w('struct CallInputs {')
    w('    DWORD eax, ecx, edx, ebx, esi, edi, ebp, esp;')
    w('    DWORD re_result;')
    w('};')
    w('static CallInputs g_inputs[8192] = {};')
    w('')
    w('static int GetHookIndex(DWORD addr) {')
    w('    static DWORD addrs[] = {')
    for m in markers:
        addr_int = int(m['addr'], 16)
        w(f'        0x{addr_int:08X},  // {m["fn_name"]}')
    w('        0 };')
    w('    for (int i = 0; addrs[i]; ++i)')
    w('        if (addrs[i] == addr) return i;')
    w('    return -1;')
    w('}')
    w('')

    w('static void LogCall(const char* name, DWORD addr, int idx,')
    w('                    DWORD eax, DWORD ecx, DWORD edx, DWORD ebx,')
    w('                    DWORD esi, DWORD edi, DWORD ebp, DWORD esp,')
    w('                    DWORD re_out, DWORD orig_out) {')
    w('    if (!g_log_file) {')
    w('        g_log_file = fopen("comparisonResult.log", "a");')
    w('        if (!g_log_file) return;')
    w('    }')
    w('    int call_num = ++g_call_counters[idx];')
    w('    if (call_num == 1)')
    w('        fprintf(g_log_file, "[%s] @ 0x%08X\\n", name, addr);')
    w('    fprintf(g_log_file, "Call %d\\n", call_num);')
    w('    fprintf(g_log_file, "  EAX=0x%08X ECX=0x%08X EDX=0x%08X EBX=0x%08X\\n", eax, ecx, edx, ebx);')
    w('    fprintf(g_log_file, "  ESI=0x%08X EDI=0x%08X EBP=0x%08X ESP=0x%08X\\n", esi, edi, ebp, esp);')
    w('    fprintf(g_log_file, "  RE=0x%08X Orig=0x%08X\\n\\n", re_out, orig_out);')
    w('    fflush(g_log_file);')
    w('}')
    w('')

    for m in markers:
        addr_hex = m['addr'].lstrip('0x').upper()
        safe = sanitize(m['fn_name'])
        fn = functions.get(m['addr'])
        conv = fn.get('call', {}).get('convention', 'unknown') if fn else 'unknown'
        hook_size = fn.get('hook', {}).get('min_safe_size', 5) if fn else 5

        w(f'// {m["fn_name"]} @ {m["addr"]} ({conv}) — {m["file"]}')
        w(f'// {m["desc"]}')
        w(f'DEFINE_HOOK({addr_hex}, Reverse_{safe}, {hook_size})')
        w('{')
        w(f'    int idx = GetHookIndex(0x{addr_hex});')
        w('    auto& inp = g_inputs[idx];')
        w('    inp.eax = R->EAX();')
        w('    inp.ecx = R->ECX();')
        w('    inp.edx = R->EDX();')
        w('    inp.ebx = R->EBX();')
        w('    inp.esi = R->ESI();')
        w('    inp.edi = R->EDI();')
        w('    inp.ebp = R->EBP();')
        w('    inp.esp = R->ESP();')
        w('')
        w(f'    // TODO: call RE version — {m["fn_name"]}(params)')
        w('    inp.re_result = 0; // placeholder')
        w('')
        w('    auto* slot = shadow::GetSlot();')
        w('    slot->re_result_eax = inp.re_result;')
        w(f'    slot->hook_addr = 0x{addr_hex};')
        w('    slot->original_ret_addr = R->Stack<DWORD>(0);')
        w('    R->Stack(0, (DWORD)&PostProcStub);')
        w('')
        w('    return 0;')
        w('}')
        w('')

    w('// ============================================================')
    w('// Post-process logging (called from PostProcStub after original RET)')
    w('// ============================================================')
    w('extern "C" void __cdecl LogComparison(DWORD orig_result, DWORD hook_addr) {')
    w('    int idx = GetHookIndex(hook_addr);')
    w('    if (idx < 0) return;')
    w('    auto& inp = g_inputs[idx];')
    w('    DWORD re_out = inp.re_result;')
    w('    LogCall("ReverseHook", hook_addr, idx,')
    w('        inp.eax, inp.ecx, inp.edx, inp.ebx,')
    w('        inp.esi, inp.edi, inp.ebp, inp.esp,')
    w('        re_out, orig_result);')
    w('}')
    return '\n'.join(out)

def main():
    print("Scanning for REVERSE markers...")
    markers = find_reverse_markers()
    print(f"  Found {len(markers)} enabled markers:")
    for m in markers:
        print(f"    {m['addr']}: {m['fn_name']} — {m['desc'][:60]}")
    if not markers:
        print("  No enabled markers found. Aborting.")
        return
    print(f"\nLoading functions.json...")
    functions = load_json()
    print(f"  {len(functions)} functions in database")
    print(f"\nGenerating {OUTPUT_PATH}...")
    code = generate_hooks(markers, functions)
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, 'w') as f:
        f.write(code)
    print(f"  Generated {len(markers)} hooks")
    print("\nNext: rebuild hook DLL, launch game, check comparisonResult.log")

if __name__ == '__main__':
    main()
