#!/usr/bin/env python3
"""Auto-generate RE_* wrapper functions for hook DLL shadow comparison."""

import os

SCRIPT = os.path.dirname(os.path.abspath(__file__))
OUT_IMPL = os.path.join(SCRIPT, "gen", "re_impl.cpp")

CATEGORY_MAP = {
    "0x421b60": "global", "0x7bc2b0": "global",
    "0x7baeb0": "pixel_write", "0x7bae60": "pixel_read",
    "0x7baf90": "pixel_write", "0x7baf10": "pixel_read",
    "0x7bab90": "callback_line", "0x7ba610": "bresenham_line",
    "0x7ba5e0": "thin_wrapper", "0x7ba8c0": "dashed_line",
    "0x7bad90": "thin_wrapper", "0x7badc0": "rectangle",
    "0x7bbab0": "fill", "0x7bb350": "ellipse",
    "0x4f4780": "frame_present",
}

VT_LOCK=0x5C; VT_UNLOCK=0x60; VT_GETBPP=0x70; VT_GETPITCH=0x74
VT_GETRECT=0x78; VT_DRAWLINE_EX=0x2C; VT_FILLRECT_EX=0x10

def F(name, addr, param_names):
    """Return lines for a RE function header. param_names = ['this_', 'point_ptr', 'color'] etc."""
    params = ', '.join(f'DWORD {p}' for p in param_names) if param_names else ''
    return [f'// {name} @ {addr}', f'extern "C" DWORD RE_{name}({params}) {{']

def L(*args): return list(args)

PREAMBLE = [
    'DWORD vt = *(DWORD*)ecx;',
    'typedef void* (__thiscall *LockFn)(void*,int,int);',
    'typedef bool (__thiscall *UnlockFn)(void*);',
    'typedef int (__thiscall *BppFn)(void*);',
    'typedef int (__thiscall *PitchFn)(void*);',
]

TEMPLATES = {}

# ---- pixel_write (thiscall) ----
# SetPixel/PutPixel: params are (Point2D&, color) = (point_ptr, color)
# Point2D = { int X; int Y; } — need to dereference
TEMPLATES['pixel_write'] = L(
    *F('{name}', '{addr}', ['this_', 'point_ptr', 'color']),
    *PREAMBLE,
    'if (!point_ptr) return 0;',
    'int x = *(int*)(point_ptr + 0);',
    'int y = *(int*)(point_ptr + 4);',
    'void* buf = ((LockFn)(*(DWORD*)(vt+0x%X)))((void*)this_, x, y);' % VT_LOCK,
    'if (!buf) return 0;',
    'int bpp = ((BppFn)(*(DWORD*)(vt+0x%X)))((void*)this_);' % VT_GETBPP,
    'if (bpp == 2) *(unsigned short*)buf = (unsigned short)color;',
    'else *(unsigned char*)buf = (unsigned char)color;',
    '((UnlockFn)(*(DWORD*)(vt+0x%X)))((void*)this_);' % VT_UNLOCK,
    'return 1;',
    '}',
)

# ---- pixel_read (thiscall) ----
# GetPixel/GetPixelAtCoords: params are (Point2D&) = (point_ptr)
TEMPLATES['pixel_read'] = L(
    *F('{name}', '{addr}', ['this_', 'point_ptr']),
    *PREAMBLE,
    'if (!point_ptr) return 0;',
    'int x = *(int*)(point_ptr + 0);',
    'int y = *(int*)(point_ptr + 4);',
    'void* buf = ((LockFn)(*(DWORD*)(vt+0x%X)))((void*)this_, x, y);' % VT_LOCK,
    'if (!buf) return 0;',
    'DWORD result = 0;',
    'int bpp = ((BppFn)(*(DWORD*)(vt+0x%X)))((void*)this_);' % VT_GETBPP,
    'if (bpp == 2) result = *(unsigned short*)buf;',
    'else result = *(unsigned char*)buf;',
    '((UnlockFn)(*(DWORD*)(vt+0x%X)))((void*)this_);' % VT_UNLOCK,
    'return result;',
    '}',
)

# ---- bresenham_line (thiscall) ----
# DrawLineEx: params (RectangleStruct&, Point2D&, Point2D&, DWORD)
# template is placeholder until actual RE testing
TEMPLATES['bresenham_line'] = L(
    *F('{name}', '{addr}', ['this_', 'p1', 'p2', 'p3', 'p4']),
    '(void)this_; (void)p1; (void)p2; (void)p3; (void)p4;',
    'return 0; // TODO: update for DrawLineEx RE',
    '}',
)

# ---- fill (thiscall) ----
# params: (uint32_t color)
TEMPLATES['fill'] = L(
    *F('{name}', '{addr}', ['this_', 'color']),
    'DWORD vt = *(DWORD*)this_;',
    'struct Rct { int x,y,w,h; } r;',
    'typedef struct Rct* (__thiscall *GrFn)(void*,struct Rct*);',
    '((GrFn)(*(DWORD*)(vt+0x%X)))((void*)this_, &r);' % VT_GETRECT,
    'typedef bool (__thiscall *FrFn)(void*,struct Rct*,struct Rct*,DWORD);',
    'return ((FrFn)(*(DWORD*)(vt+0x%X)))((void*)this_, &r, &r, color);' % VT_FILLRECT_EX,
    '}',
)

# ---- rectangle (thiscall) ----
# params: (RectangleStruct& clip, RectangleStruct& draw, DWORD color)
TEMPLATES['rectangle'] = L(
    *F('{name}', '{addr}', ['this_', 'clip_ptr', 'draw_ptr', 'color']),
    '(void)this_; (void)clip_ptr; (void)draw_ptr; (void)color;',
    'return 0; // TODO: update for DrawRectEx RE',
    '}',
)

# ---- ellipse (thiscall) ----
# params: (Point2D& center, int rw, int rh, RectangleStruct& clip, uint16_t color)
TEMPLATES['ellipse'] = L(
    *F('{name}', '{addr}', ['this_', 'p1', 'p2', 'p3', 'p4', 'p5']),
    '(void)this_; (void)p1; (void)p2; (void)p3; (void)p4; (void)p5;',
    'return 0; // TODO: update for DrawEllipseOutline RE',
    '}',
)

# ---- dashed_line, callback_line, thin_wrapper, global, frame_present ----
for cat in ('dashed_line','callback_line','thin_wrapper','global','frame_present'):
    TEMPLATES[cat] = L(
        *F('{name}', '{addr}', ['p0','p1','p2','p3']),
        '(void)p0; (void)p1; (void)p2; (void)p3;',
        'return 0; // TODO',
        '}',
    )

def generate_re_impl(markers):
    out = ['// Auto-generated RE_* functions for hook DLL','// Generated by gen_re_impl.py','#include <windows.h>','']
    for m in markers:
        addr = m['addr']; name = m['fn_name']; mode = m.get('mode','None')
        if mode not in ('Inject','Replace'): continue
        cat = CATEGORY_MAP.get(addr)
        if cat is None:
            print('  WARNING: %s no category' % addr); continue
        sanitized = name.replace('::','_').replace('@','_').replace('<','_').replace('>','_')
        tmpl = TEMPLATES.get(cat)
        if tmpl is None:
            print('  WARNING: %s no template for %s' % (addr, cat)); continue
        for line in tmpl:
            out.append(line.replace('{name}', sanitized).replace('{addr}', addr))
        out.append('')
        print('  RE_%s (%s)' % (sanitized, cat))
    os.makedirs(os.path.dirname(OUT_IMPL), exist_ok=True)
    with open(OUT_IMPL, 'w') as f:
        f.write('\n'.join(out))
    print('\nGenerated %s (%d lines)' % (OUT_IMPL, len(out)))

if __name__ == '__main__':
    test = [
        dict(addr='0x7baeb0', fn_name='XSurface::SetPixel', mode='Inject'),
        dict(addr='0x7bae60', fn_name='XSurface::GetPixel', mode='Inject'),
        dict(addr='0x7baf90', fn_name='XSurface::PutPixel', mode='Inject'),
        dict(addr='0x7baf10', fn_name='XSurface::GetPixelAtCoords', mode='Inject'),
        dict(addr='0x7ba610', fn_name='XSurface::DrawLineEx', mode='Inject'),
        dict(addr='0x7badc0', fn_name='XSurface::DrawRectEx', mode='Inject'),
        dict(addr='0x7bbab0', fn_name='XSurface::Fill', mode='Inject'),
        dict(addr='0x7bb350', fn_name='XSurface::DrawEllipseOutline', mode='Inject'),
    ]
    generate_re_impl(test)
